import {createPortal} from 'react-dom';
import { type Animation, type Pose, type Keyframe, neutral } from '../lib/animation-model';
import type { LayerNode } from '../lib/psd-model';
export default function AnimationPanel({ animation, nodes, selected, select, frame, seek, playing, play, pose, setPose, easing, setEasing, add, remove, configure, undo, redo, canUndo, canRedo, exporting, exportFrames, controlsTarget }: {
 controlsTarget?:HTMLElement|null;undo:()=>void; redo:()=>void;canUndo:boolean;canRedo:boolean; animation: Animation; nodes: LayerNode[]; selected: string | null; select: (key: string) => void; frame: number; seek: (frame: number) => void; playing: boolean; play: () => void; pose: Pose; setPose: (pose: Pose) => void; easing: Keyframe['easing']; setEasing: (value: Keyframe['easing']) => void; add: () => void; remove: () => void; configure: (fps: number, duration: number) => void; exporting: boolean; exportFrames: () => void;
}) {
 const part = animation.rig.parts.find(p => p.key === selected), track = animation.tracks.find(t => t.key === selected), keyframe = track?.frames.find(k => k.frame === frame), atKey = !!keyframe;
 const number = (key: keyof Pose, label: string, min: number, max: number, step = 1) => <label>{label}<input aria-label={label} type="number" value={Number(pose[key].toFixed(3))} step={step} min={min} max={max} disabled={!part || playing || exporting} onChange={e => { const n = e.target.valueAsNumber; if (Number.isFinite(n)) setPose({ ...pose, [key]: Math.max(min,Math.min(max,n)) }); }}/></label>;
 const controls=<details className="performance-panel transform-panel" open><summary>Muunnos · liike ja avainruudut</summary><div className="pose-controls"><strong>{part ? nodes.find(n => n.key === selected)?.name : 'Valitse animoitava taso'}</strong><div className="pose-fields">{number('x','Liike X',-animation.rig.source.width*4,animation.rig.source.width*4)}{number('y','Liike Y',-animation.rig.source.height*4,animation.rig.source.height*4)}{number('rotation','Kierto °',-3600,3600)}{number('scale','Koko',.01,10,.01)}{number('opacity','Peittävyys',0,1,.01)}<label>Siirtymä<select aria-label="Avainruudun siirtymä" value={keyframe?.easing??easing} disabled={!part || playing || exporting} onChange={e => setEasing(e.target.value as Keyframe['easing'])}><option value="smooth">Pehmeä</option><option value="linear">Tasainen</option><option value="hold">Pidä asento</option></select>{keyframe?.bezierCurve&&<span className="motion-curve-note">Mukautettu Bézier · muokkaa siirtymäkäyrää</span>}</label></div><div className="pose-actions"><button className="primary" disabled={!part || playing || exporting} onClick={add}>{atKey ? 'Päivitä avainruutu' : 'Lisää avainruutu'}</button><button className="secondary" disabled={!atKey || playing || exporting} onClick={remove}>Poista avainruutu</button><button className="text-button" disabled={!part || playing || exporting} onClick={() => setPose({...neutral})}>Nollaa asento</button></div><p>Muokkaa asentoa ja lisää avainruutu. Siirrä aikajanaa ja tallenna seuraava asento. Kierron keskus määritetään Nivelet-vaiheessa.</p></div></details>;
 return <section className="timeline" aria-label="Animaation aikajana"><div className="timeline-heading"><h2>Animaatio</h2><button className="secondary" disabled={!canUndo || playing || exporting} onClick={undo}>Kumoa</button><button className="secondary" disabled={!canRedo || playing || exporting} onClick={redo}>Tee uudelleen</button><button className="primary" disabled={exporting} onClick={play}>{playing ? 'Pysäytä' : 'Toista'}</button><button className="secondary" disabled={exporting} onClick={() => seek(0)}>Alkuun</button><span>Ruutu {frame} · {(frame / animation.fps).toFixed(2)} s</span><label>Kuvaa/s<input aria-label="Kuvataajuus" type="number" min={1} max={60} value={animation.fps} disabled={playing || exporting} onChange={e => { const n=e.target.valueAsNumber; if(Number.isInteger(n)&&n>=1&&n<=60) configure(n,animation.duration); }}/></label><label>Ruudut<input aria-label="Animaation ruutumäärä" type="number" min={2} max={1800} value={animation.duration} disabled={playing || exporting} onChange={e => { const n=e.target.valueAsNumber; if(Number.isInteger(n)&&n>=2&&n<=1800) configure(animation.fps,n); }}/></label><button className="secondary" disabled={playing} onClick={exportFrames}>{exporting ? 'Peruuta vienti' : 'Vie PNG-kuvasarja'}</button></div><input className="time-slider" aria-label="Aikajanan ruutu" type="range" min={0} max={animation.duration - 1} value={frame} disabled={exporting} onChange={e => seek(Number(e.target.value))}/><div className="time-ruler"><span>AIKA / SEKUNTIA</span><div>{Array.from({length:6},(_,i)=><span key={i} style={{left:`${i*20}%`}}>{(i/5*(animation.duration-1)/animation.fps).toFixed(1)} s</span>)}</div></div><div className="timeline-body"><div className="animation-tracks">{nodes.filter(n => n.kind === 'layer').map(n => <div className={`animation-track ${n.key === selected ? 'active' : ''}`} key={n.key}><button disabled={exporting} className="track-name" onClick={() => select(n.key)}>{n.name}</button><div className="track-keys">{animation.tracks.find(t => t.key === n.key)?.frames.map(k => <button key={k.frame} title={`Ruutu ${k.frame}`} aria-label={`${n.name}: avainruutu ${k.frame}`} className={k.frame === frame ? 'current-key' : ''} disabled={exporting} style={{left:`${k.frame / (animation.duration - 1) * 100}%`}} onClick={() => { select(n.key); seek(k.frame); }}>◆</button>)}<span className="playhead" style={{left:`${frame / (animation.duration - 1) * 100}%`}}/></div></div>)}</div>{controlsTarget?createPortal(controls,controlsTarget):controls}</div></section>;
}
