import {useEffect,useRef,useState} from 'react';import {createPortal} from 'react-dom';
import type {Presentation} from '../lib/presentation-model';
import {canonicalFromPresentation} from '../lib/cloud-render/canonical-adapter';
type Json=Record<string,any>;
const api=async(method:string,path:string,body?:unknown):Promise<{status:number;body:Json}>=>{const r=await fetch(path,{method,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(()=>({}))};};
const stateFi:Record<string,string>={QUEUED:'Jonossa',VALIDATING:'Tarkistetaan',COST_CHECK:'Kustannustarkistus',AUTHORIZED:'Sallittu',SUBMITTING:'Lähetetään',RENDERING:'Renderöidään',VALIDATING_OUTPUT:'Tulosteen tarkistus',UPLOADING:'Tallennetaan Driveen',COMPLETED:'Valmis',BLOCKED:'ESTETTY',FAILED:'Epäonnistui',CANCELLED:'Peruttu'};
/** Three clearly separate stages: AI suggestion, deterministic validation, render. Policy is shown read-only; the server owns it. */
export default function CloudRenderDialog({presentation,onClose}:{presentation:Presentation|null;onClose:()=>void}){
 const [health,setHealth]=useState<Json|null>(null),[error,setError]=useState(''),[canon,setCanon]=useState<Json|null>(null),[scene,setScene]=useState(''),[suggestion,setSuggestion]=useState<Json|null>(null),[workflows,setWorkflows]=useState<Json[]>([]),[workflow,setWorkflow]=useState('text_to_image'),[job,setJob]=useState<Json|null>(null),[busy,setBusy]=useState(false),[backends,setBackends]=useState<Json[]>([]);
 const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{box.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 useEffect(()=>{void(async()=>{const h=await api('GET','/api/health');if(h.status!==200){setError('Pilvirenderöinti ei ole käytössä tällä palvelimella (käynnistä yksityinen palvelin asetuksella HAHMOSTUDIO_CLOUD_RENDER=1).');return;}setHealth(h.body);const b=await api('GET','/api/backends');setBackends(b.body.backends??[]);setWorkflows((b.body.workflows??[]).filter((w:Json)=>w.implemented));})();},[]);
 useEffect(()=>{if(!job||['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(job.state))return;const t=setTimeout(async()=>{const r=await api('GET','/api/render/'+job.job.id);if(r.status===200)setJob(r.body);},1500);return()=>clearTimeout(t);},[job]);
 const run=async(f:()=>Promise<void>)=>{setBusy(true);setError('');try{await f();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const sync=()=>run(async()=>{if(!presentation)throw new Error('Ei esitystä, josta kanoninen tila voitaisiin muodostaa.');const c=canonicalFromPresentation(presentation),r=await api('PUT','/api/projects/'+c.projectId,c);if(r.status!==200)throw new Error(r.body.error??'Synkronointi epäonnistui.');setCanon(c as unknown as Json);setScene(Object.keys(c.scenes)[0]??'');setSuggestion(null);setJob(null);});
 const direct=()=>run(async()=>{const r=await api('POST','/api/ai/direct',{projectId:canon!.projectId,sceneId:scene});if(r.status!==200)throw new Error(r.body.error??'Ehdotus epäonnistui.');setSuggestion(r.body);});
 const lock=()=>run(async()=>{const r=await api('POST',`/api/projects/${canon!.projectId}/scenes/${scene}/lock`);if(r.status!==200)throw new Error(r.body.error??'Lukitus epäonnistui.');setError('Kohtaus lukittu: renderöinti käyttää lukittua määritystä.');});
 const render=()=>run(async()=>{const r=await api('POST','/api/render',{projectId:canon!.projectId,sceneId:scene,workflowId:workflow});if(r.status>=300)throw new Error(r.body.error??'Renderöinti ei käynnistynyt.');setJob(r.body.record);});
 const policy=health?.policy,cam=suggestion?.suggestion?.camera,lit=suggestion?.suggestion?.lighting;
 return createPortal(<div className="export-backdrop studio-export"><div role="dialog" aria-modal="true" aria-labelledby="cloud-title" className="export-dialog" ref={box} tabIndex={-1}>
  <header><h2 id="cloud-title">Pilvirenderöinti (tekoäly)</h2><button className="secondary" onClick={onClose}>Sulje</button></header>
  <p>Säännöt määrittävät, mikä on totta. Tekoäly ehdottaa vain ulkoasua. Ehdotus renderöidään vasta, kun deterministinen tarkistus hyväksyy sen.</p>
  {error&&<p role="alert">{error}</p>}
  {policy&&<section aria-label="Laskennan kustannus"><h3>Kustannus</h3><p>Laskennan hinta: €{policy.maxCostEur.toFixed(2)} enintään · Maksullinen laskenta: {policy.allowPaidCompute?'PÄÄLLÄ':'POIS'} · Maksullinen varavaihtoehto: POIS</p><p>{policy.guarantee}</p><p>Käytettävissä: {backends.map(b=>`${b.id} (${b.class}${b.enabled&&b.eligibleUnderPolicy?', sallittu':', ei käytössä'})`).join(' · ')}</p></section>}
  <section aria-label="Kanoninen tila"><h3>1 · Hyväksytty kohtaus</h3><button className="secondary" disabled={busy||!health||!presentation} onClick={()=>void sync()}>Synkronoi säännöistä</button>{canon&&<><label>Kohtaus <select value={scene} onChange={e=>{setScene(e.target.value);setSuggestion(null);setJob(null);}}>{Object.keys(canon.scenes).map(id=><option key={id} value={id}>{id}</option>)}</select></label> <button className="secondary" disabled={busy} onClick={()=>void lock()}>Hyväksy ja lukitse kohtaus</button></>}</section>
  <section aria-label="Tekoälyn ehdotus"><h3>2 · TEKOÄLYN EHDOTUS</h3><button className="secondary" disabled={busy||!canon} onClick={()=>void direct()}>Pyydä ehdotus</button>
   {suggestion&&<><p>Kamera: {cam?.shot??'—'} · Liike: {cam?.movement??'—'} · Valaistus: {lit?.style??'—'}</p><p>Tila: {suggestion.status==='APPROVED'?'Odottaa renderöintiä':'Hylätty'} · Ehdottaja: {suggestion.director} (ehdotus, ei totuus)</p>
   <h4>Tarkistus</h4><ul>{suggestion.checks.map((c:Json)=><li key={c.id}>{c.ok?'✓':'✗'} {c.label}</li>)}</ul>{suggestion.issues.map((i:Json,n:number)=><p role="alert" key={n}>✗ {i.message}</p>)}<p><strong>{suggestion.status==='APPROVED'?'HYVÄKSYTTY':'HYLÄTTY — mitään ei renderöidä'}</strong></p></>}</section>
  <section aria-label="Renderöinti"><h3>3 · RENDERÖINTI</h3><label>Työnkulku <select value={workflow} onChange={e=>setWorkflow(e.target.value)}>{workflows.map(w=><option key={w.id} value={w.id}>{w.title}{w.liveVerified?'':' (ei vielä todennettu livenä)'}</option>)}</select></label> <button className="primary" disabled={busy||!canon||!!(job&&!['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(job.state))} onClick={()=>void render()}>Renderöi</button>
   {job&&<><p>Tila: <strong>{stateFi[job.state]??job.state}</strong>{job.backend&&` · Taustajärjestelmä: ${job.backend.id}`}{job.cost&&` · Hinta: €${job.cost.estimate.estimatedCostEur??'tuntematon'}`}</p>
   {job.blocked&&<pre role="alert">{job.blocked.banner}</pre>}{job.errors?.map((e:string,n:number)=><p role="alert" key={n}>{e}</p>)}{job.outputs?.length>0&&<p>Tulos tallennettu Google Driveen ({job.outputs.length} tiedostoa).</p>}
   {['QUEUED','VALIDATING','COST_CHECK','AUTHORIZED','SUBMITTING','RENDERING'].includes(job.state)&&<button className="secondary" onClick={()=>void api('POST',`/api/render/${job.job.id}/cancel`)}>Peru</button>}</>}</section>
 </div></div>,document.body);
}
