import {useEffect,useRef,useState} from 'react';import {createPortal} from 'react-dom';
import type {Presentation} from '../lib/presentation-model';
import {canonicalFromPresentation} from '../lib/cloud-render/canonical-adapter';
type Json=Record<string,any>;
const api=async(method:string,path:string,body?:unknown):Promise<{status:number;body:Json}>=>{const r=await fetch(path,{method,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(()=>({}))};};
const stateFi:Record<string,string>={QUEUED:'Jonossa',VALIDATING:'Tarkistetaan',COST_CHECK:'Kustannustarkistus',AUTHORIZED:'Sallittu',SUBMITTING:'Lähetetään',RENDERING:'Renderöidään',VALIDATING_OUTPUT:'Tulosteen tarkistus',UPLOADING:'Tallennetaan Driveen',COMPLETED:'Valmis',BLOCKED:'ESTETTY',FAILED:'Epäonnistui',CANCELLED:'Peruttu'};
/** Pure gate: the render button is enabled only for a server-AUTHORIZED card with a fingerprint and no job running. */
export function canRender(card:Json|null,job:Json|null,busy:boolean){return !busy&&card?.status==='AUTHORIZED'&&typeof card.fingerprint==='string'&&!(job&&!['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(job.state));}
export function AuthorizationCardView({card}:{card:Json}){return <div role="group" aria-label="Valtuutus ennen suoritusta"><h4>Valtuutus ennen suoritusta</h4><dl>
    <dt>Taustajärjestelmä</dt><dd>{card.backend?`${card.backend.id}`:'—'}</dd><dt>Luokka</dt><dd>{card.backend?.class??'—'}</dd>
    <dt>Arvioitu laskennan hinta</dt><dd>{card.estimate?.estimatedCostEur===null||card.estimate==null?'tuntematon (estetty)':`€${card.estimate.estimatedCostEur.toFixed(2)}`}</dd><dt>Enimmäishinta</dt><dd>€{card.maxCostEur.toFixed(2)}</dd>
    <dt>Maksullinen laskenta</dt><dd>{card.paidCompute==='ENABLED'?'PÄÄLLÄ':'POIS'}</dd><dt>Maksullinen varavaihtoehto</dt><dd>{card.paidFallback==='ENABLED'?'PÄÄLLÄ':'POIS'}</dd>
    <dt>Malli</dt><dd>{card.model?.id??'—'}</dd><dt>Mallin revisio</dt><dd>{card.model?.revision??'EI LUKITTU'}</dd><dt>Lisenssi</dt><dd>{card.model?.license??'—'}</dd><dt>Kaupallinen käyttö</dt><dd>{card.model?.commercialUse??'—'}</dd>
    <dt>Työnkulku</dt><dd>{card.workflowId}{card.workflowRevision!==undefined?` r${card.workflowRevision}`:''}</dd>{card.clips&&<><dt>Klippejä (hyväksytyt tapahtumat, ajetaan peräkkäin)</dt><dd>{card.clips.length}</dd></>}<dt>Valtuutus</dt><dd><strong>{card.status==='AUTHORIZED'?'HYVÄKSYTTY':'ESTETTY'}</strong></dd></dl>
    {card.reasons.map((x:string,n:number)=><p role="alert" key={n}>✗ {x}</p>)}<p>Palvelimen asetukset ovat ratkaisevia; tämä näkymä ei voi muuttaa niitä.</p></div>;}
/** Three clearly separate stages: AI suggestion, deterministic validation, render. Policy is shown read-only; the server owns it. */
export default function CloudRenderDialog({presentation,onClose}:{presentation:Presentation|null;onClose:()=>void}){
 const [health,setHealth]=useState<Json|null>(null),[error,setError]=useState(''),[canon,setCanon]=useState<Json|null>(null),[scene,setScene]=useState(''),[suggestion,setSuggestion]=useState<Json|null>(null),[workflows,setWorkflows]=useState<Json[]>([]),[workflow,setWorkflow]=useState('text_to_image'),[job,setJob]=useState<Json|null>(null),[busy,setBusy]=useState(false),[backends,setBackends]=useState<Json[]>([]),[card,setCard]=useState<Json|null>(null),[smoke,setSmoke]=useState<Json|null>(null),[refChar,setRefChar]=useState(''),[refMsg,setRefMsg]=useState('');
 const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{box.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 useEffect(()=>{void(async()=>{const h=await api('GET','/api/health');if(h.status!==200){setError('Pilvirenderöinti ei ole käytössä tällä palvelimella (käynnistä yksityinen palvelin asetuksella HAHMOSTUDIO_CLOUD_RENDER=1).');return;}setHealth(h.body);const b=await api('GET','/api/backends');setBackends(b.body.backends??[]);setWorkflows((b.body.workflows??[]).filter((w:Json)=>w.implemented));})();},[]);
 useEffect(()=>{if(!job||['COMPLETED','BLOCKED','FAILED','CANCELLED'].includes(job.state))return;const t=setTimeout(async()=>{const r=await api('GET','/api/render/'+job.job.id);if(r.status===200)setJob(r.body);},1500);return()=>clearTimeout(t);},[job]);
 const run=async(f:()=>Promise<void>)=>{setBusy(true);setError('');try{await f();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const sync=()=>run(async()=>{if(!presentation)throw new Error('Ei esitystä, josta kanoninen tila voitaisiin muodostaa.');const c=canonicalFromPresentation(presentation),r=await api('PUT','/api/projects/'+c.projectId,c);if(r.status!==200)throw new Error(r.body.error??'Synkronointi epäonnistui.');setCanon(c as unknown as Json);setScene(Object.keys(c.scenes)[0]??'');setSuggestion(null);setJob(null);});
 const direct=()=>run(async()=>{const r=await api('POST','/api/ai/direct',{projectId:canon!.projectId,sceneId:scene});if(r.status!==200)throw new Error(r.body.error??'Ehdotus epäonnistui.');setSuggestion(r.body);});
 const lock=()=>run(async()=>{const r=await api('POST',`/api/projects/${canon!.projectId}/scenes/${scene}/lock`);if(r.status!==200)throw new Error(r.body.error??'Lukitus epäonnistui.');setError('Kohtaus lukittu: renderöinti käyttää lukittua määritystä.');});
 const request=()=>({projectId:canon!.projectId,sceneId:scene,workflowId:workflow});
 const uploadRef=(file:File)=>run(async()=>{const char=refChar||Object.keys(canon!.characters)[0];if(file.size>8*1024*1024)throw new Error('Kuva on yli 8 MiB.');const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]??'');r.onerror=()=>no(new Error('Tiedoston luku epäonnistui.'));r.readAsDataURL(file);});const x=await api('POST',`/api/projects/${canon!.projectId}/characters/${char}/reference`,{mime:file.type,dataBase64:data,label:file.name});if(x.status!==200)throw new Error(x.body.error??'Vertailukuvan lataus epäonnistui.');setRefMsg(`Vertailukuva tallennettu hahmolle ${char}.`);setCard(null);});
 const preflight=()=>run(async()=>{const r=await api('POST','/api/render/preflight',request());if(r.status!==200)throw new Error(r.body.error??'Valtuutuksen tarkistus epäonnistui.');setCard(r.body);});
 const runSmoke=()=>run(async()=>{const r=await api('POST','/api/live-verification/smoke',{});if(r.status!==200)throw new Error(r.body.error??'Tarkistus epäonnistui.');setSmoke(r.body);});
 const render=()=>run(async()=>{if(card?.status!=='AUTHORIZED'||!card.fingerprint)throw new Error('Renderöinti vaatii palvelimen hyväksymän valtuutuksen.');const r=await api('POST','/api/render',{...request(),authorizationFingerprint:card.fingerprint});if(r.status>=300)throw new Error(r.body.error??'Renderöinti ei käynnistynyt.');setJob(r.body.record);});
 const policy=health?.policy,cam=suggestion?.suggestion?.camera,lit=suggestion?.suggestion?.lighting;
 return createPortal(<div className="export-backdrop studio-export"><div role="dialog" aria-modal="true" aria-labelledby="cloud-title" className="export-dialog" ref={box} tabIndex={-1}>
  <header><h2 id="cloud-title">Pilvirenderöinti (tekoäly)</h2><button className="secondary" onClick={onClose}>Sulje</button></header>
  <p>Säännöt määrittävät, mikä on totta. Tekoäly ehdottaa vain ulkoasua. Ehdotus renderöidään vasta, kun deterministinen tarkistus hyväksyy sen.</p>
  {error&&<p role="alert">{error}</p>}
  {policy&&<section aria-label="Laskennan kustannus"><h3>Kustannus</h3><p>Laskennan hinta: €{policy.maxCostEur.toFixed(2)} enintään · Maksullinen laskenta: {policy.allowPaidCompute?'PÄÄLLÄ':'POIS'} · Maksullinen varavaihtoehto: POIS</p><p>{policy.guarantee}</p><p>Käytettävissä: {backends.map(b=>`${b.id} (${b.class}${b.enabled&&b.eligibleUnderPolicy?', sallittu':', ei käytössä'})`).join(' · ')}</p></section>}
  <section aria-label="Kanoninen tila"><h3>1 · Hyväksytty kohtaus</h3><button className="secondary" disabled={busy||!health||!presentation} onClick={()=>void sync()}>Synkronoi säännöistä</button>{canon&&<><label>Kohtaus <select value={scene} onChange={e=>{setScene(e.target.value);setSuggestion(null);setJob(null);setCard(null);}}>{Object.keys(canon.scenes).map(id=><option key={id} value={id}>{id}</option>)}</select></label> <button className="secondary" disabled={busy} onClick={()=>void lock()}>Hyväksy ja lukitse kohtaus</button></>}</section>
  {canon&&<section aria-label="Hahmojen vertailukuvat"><h3>Hahmojen hyväksytyt vertailukuvat</h3><p>Video- ja hahmotyönkulut vaativat PNG-, JPEG- tai WebP-vertailukuvan (enintään 8 MiB) jokaiselle esiintyvälle hahmolle. Kuva tallennetaan projektin references-kansioon.</p><label>Hahmo <select value={refChar||Object.keys(canon.characters)[0]} onChange={e=>setRefChar(e.target.value)}>{Object.keys(canon.characters).map(id=><option key={id} value={id}>{canon.characters[id].name}</option>)}</select></label> <input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadRef(f);e.target.value='';}}/>{refMsg&&<p>{refMsg}</p>}</section>}
  <section aria-label="Tekoälyn ehdotus"><h3>2 · TEKOÄLYN EHDOTUS</h3><button className="secondary" disabled={busy||!canon} onClick={()=>void direct()}>Pyydä ehdotus</button>
   {suggestion&&<><p>Kamera: {cam?.shot??'—'} · Liike: {cam?.movement??'—'} · Valaistus: {lit?.style??'—'}</p><p>Tila: {suggestion.status==='APPROVED'?'Odottaa renderöintiä':'Hylätty'} · Ehdottaja: {suggestion.director} (ehdotus, ei totuus)</p>
   <h4>Tarkistus</h4><ul>{suggestion.checks.map((c:Json)=><li key={c.id}>{c.ok?'✓':'✗'} {c.label}</li>)}</ul>{suggestion.issues.map((i:Json,n:number)=><p role="alert" key={n}>✗ {i.message}</p>)}<p><strong>{suggestion.status==='APPROVED'?'HYVÄKSYTTY':'HYLÄTTY — mitään ei renderöidä'}</strong></p></>}</section>
  <section aria-label="Renderöinti"><h3>3 · RENDERÖINTI</h3><label>Työnkulku <select value={workflow} onChange={e=>{setWorkflow(e.target.value);setCard(null);}}>{workflows.map(w=><option key={w.id} value={w.id}>{w.title}{w.liveVerified?'':' (ei vielä todennettu livenä)'}</option>)}</select></label> <button className="secondary" disabled={busy||!canon} onClick={()=>void preflight()}>Tarkista valtuutus</button>
   {card&&<AuthorizationCardView card={card}/>}
   <button className="primary" disabled={!canRender(card,job,busy)} onClick={()=>void render()}>Hyväksy ja renderöi</button>
   <details><summary>Live-todennus</summary><p>Työnkulku merkitään todennetuksi vasta, kun esitarkistus on läpäisty, mallin revisio ja tarkistussummat on lukittu ja vahvistettu, lisenssi on kunnossa ja oikea renderöinti on valmistunut, ladattu ja kirjattu auditointiin.</p><button className="secondary" disabled={busy||!health} onClick={()=>void runSmoke()}>Suorita renderöinniton esitarkistus</button>{smoke&&<ul>{smoke.authorized?smoke.rows.map((x:Json)=><li key={x.workflowId+x.modelId}>{x.ok?'✓':'✗'} {x.workflowId} / {x.modelId} {x.problems.join(' ')}</li>):smoke.reasons.map((x:string,n:number)=><li key={n}>✗ {x}</li>)}</ul>}</details>
   {job&&<><p>Tila: <strong>{stateFi[job.state]??job.state}</strong>{job.backend&&` · Taustajärjestelmä: ${job.backend.id}`}{job.cost&&` · Hinta: €${job.cost.estimate.estimatedCostEur??'tuntematon'}`}</p>
   {job.blocked&&<pre role="alert">{job.blocked.banner}</pre>}{job.errors?.map((e:string,n:number)=><p role="alert" key={n}>{e}</p>)}{job.children?.length>0&&<p>Klipit: {job.children.map((c:Json)=>`${c.eventId}: ${stateFi[c.state]??c.state}`).join(' · ')}. Palvelin ei yhdistä videoita; järjestetty sekvenssimanifesti on tallennettu.</p>}{job.outputs?.length>0&&<p>Tulos tallennettu Google Driveen ({job.outputs.length} tiedostoa).</p>}{job.liveVerification&&<p>Live-todennus: {job.liveVerification.promoted?'läpäisty':'ei vielä — puuttuu: '+job.liveVerification.missing.join(', ')}</p>}
   {['QUEUED','VALIDATING','COST_CHECK','AUTHORIZED','SUBMITTING','RENDERING'].includes(job.state)&&<button className="secondary" onClick={()=>void api('POST',`/api/render/${job.job.id}/cancel`)}>Peru</button>}</>}</section>
 </div></div>,document.body);
}
