import {useEffect,useRef,useState} from 'react';import {LocalMicrophone} from '../lib/microphone';
/** A local voice performance, not synthesized speech. Recording controls stay reachable. */
export default function DialogueRecorder({disabled,recorded,busy}:{disabled:boolean;recorded:(file:File)=>Promise<void>;busy:(value:boolean)=>void}){
 const epoch=useRef(0);const mic=useRef<LocalMicrophone|null>(null),abort=useRef<AbortController|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),start=useRef(0),mounted=useRef(true);const [mode,setMode]=useState<'idle'|'loading'|'recording'|'saving'>('idle'),[elapsed,setElapsed]=useState(0),[message,setMessage]=useState('');const handlers=useRef({recorded,busy});handlers.current={recorded,busy};
 const release=()=>{epoch.current++;if(timer.current)clearInterval(timer.current);timer.current=null;mic.current?.close();mic.current=null;abort.current?.abort();abort.current=null;};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;release();handlers.current.busy(false);};},[]);
 const stop=async(cancel=false)=>{if(mode==='saving')return;if(timer.current)clearInterval(timer.current);timer.current=null;if(cancel){release();setMode('idle');busy(false);setMessage('Äänitys peruttiin. Aiempi repliikkiääni säilyi.');return;}const device=mic.current;if(!device)return;setMode('saving');try{const seconds=Math.max(.05,Math.min(60,(performance.now()-start.current)/1000)),blob=await device.finish(undefined,0,seconds);release();await handlers.current.recorded(new File([blob],'Oma repliikki.wav',{type:'audio/wav'}));if(mounted.current)setMessage('Oma äänesi liitettiin repliikkiin. Suun ajoitus perustuu tähän tallenteeseen.');}catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'Äänitys epäonnistui.');}finally{release();if(mounted.current){setMode('idle');handlers.current.busy(false);}}};
 const stopRef=useRef(stop);stopRef.current=stop;
 const record=async()=>{if(disabled||mode!=='idle')return;const session=++epoch.current,controller=new AbortController();abort.current=controller;setMode('loading');busy(true);setMessage('Salli mikrofonin käyttö.');try{const device=await LocalMicrophone.start(undefined,controller.signal);if(!mounted.current||session!==epoch.current||controller.signal.aborted){device.close();return;}mic.current=device;device.begin();start.current=performance.now();setElapsed(0);setMode('recording');setMessage('Puhu repliikki omalla äänelläsi.');timer.current=setInterval(()=>{const time=(performance.now()-start.current)/1000;setElapsed(time);if(time>=60||!device.available)void stopRef.current();},100);}catch(e){if(session!==epoch.current)return;release();if(mounted.current){setMode('idle');busy(false);setMessage(e instanceof Error?e.message:'Mikrofonia ei voitu avata.');}}};
 return <div className="dialogue-recorder"><button className="primary" disabled={mode==='saving'||mode==='idle'&&disabled} onClick={()=>mode==='idle'?void record():mode==='loading'?void stop(true):void stop()}>{mode==='loading'?'Peruuta mikrofonilupa':mode==='recording'?`Lopeta ja käytä repliikki · ${elapsed.toFixed(1)} s`:mode==='saving'?'Liitetään ääntä…':'Äänitä repliikki omalla äänellä'}</button>{mode==='recording'&&<button className="secondary" onClick={()=>void stop(true)}>Hylkää äänitys</button>}<p role="status">{message}</p></div>;
}
