import {useEffect,useRef,useState} from 'react';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import {readProject,saveProject} from '../lib/project-file';
import {flatten,releaseDocument,safeName} from '../lib/psd-model';
import type {Episode} from '../lib/mp4-export';
type Item=Episode&{id:number;name:string;blob:Blob};
const cap=128*1024*1024;
async function decode(item:Episode){try{for(const n of flatten(item.doc.layers))if(n.png){n.url=URL.createObjectURL(n.png);n.image=new Image();n.image.src=n.url;await n.image.decode();}return item;}catch(e){releaseDocument(item.doc);throw e;}}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export default function EpisodePanel({current,disabled,exporting,exportVideo}:{current:Episode|null;disabled:boolean;exporting:boolean;exportVideo:(items:Episode[])=>Promise<void>}){
 const [items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),input=useRef<HTMLInputElement>(null),resources=useRef<Item[]>([]),mounted=useRef(true),id=useRef(0);
 useEffect(()=>{resources.current=items;},[items]);useEffect(()=>()=>{mounted.current=false;resources.current.forEach(i=>releaseDocument(i.doc));},[]);
 const append=async(files:{name:string;blob:Blob}[])=>{if(busy||disabled)return;setBusy(true);setMessage('');const loaded:Item[]=[];try{if(items.length+files.length>5)throw new Error('Sarjaan mahtuu viisi jaksoa. Poista jakso ennen uusien tuontia.');if([...items,...files].reduce((n,i)=>n+i.blob.size,0)>cap)throw new Error('Sarjan projektit ylittävät 128 Mt.');let pixels=items.reduce((n,i)=>n+flatten(i.doc.layers).reduce((a,l)=>a+(l.png?l.width*l.height:0),0),0);for(const f of files){const project=await readProject(f.blob);pixels+=flatten(project.doc.layers).reduce((a,l)=>a+(l.png?l.width*l.height:0),0);if(pixels>48000000)throw new Error('Sarjan tasokuvien yhteiskoko ylittää 48 megapikseliä.');if(project.animation.duration/project.animation.fps>60)throw new Error('Yksi jakso voi kestää enintään 60 sekuntia.');await decode(project);loaded.push({...project,name:f.name.replace(/\.hahmo$/i,''),blob:f.blob,id:++id.current});}if(!mounted.current){loaded.forEach(i=>releaseDocument(i.doc));return;}const next=[...items,...loaded];resources.current=next;setItems(next);setMessage('Jaksot lisätty. Kooste käyttää näitä tallennettuja versioita.');}catch(e){loaded.forEach(i=>releaseDocument(i.doc));setMessage(e instanceof Error?e.message:'Jakson lisääminen epäonnistui.');}finally{setBusy(false);}};
 const importFiles=async(files:File[])=>{try{if(files.length===1&&/\.sarja$/i.test(files[0].name)){if(files[0].size>cap)throw new Error('Sarja ylittää 128 Mt.');let bytes=0,count=0;const zipped=unzipSync(new Uint8Array(await files[0].arrayBuffer()),{filter:e=>{bytes+=e.originalSize;if(bytes>cap||++count>6)throw new Error('Sarjan purettu koko on liian suuri.');return true;}});if(!zipped['series.json']||zipped['series.json'].length>10000)throw new Error('Sarjan tiedot puuttuvat.');const m=JSON.parse(strFromU8(zipped['series.json']));if(m.format!=='hahmostudio-series'||m.version!==1||!Array.isArray(m.episodes)||m.episodes.length>5||m.episodes.some((e:unknown)=>!e||typeof e!=='object'||typeof (e as {name:unknown}).name!=='string'||(e as {name:string}).name.length>256))throw new Error('Virheellinen sarjatiedosto.');await append(m.episodes.map((e:{name:string},i:number)=>{if(!zipped[`episodes/${i}.hahmo`])throw new Error('Jakso puuttuu sarjasta.');return {name:e.name,blob:new Blob([new Uint8Array(zipped[`episodes/${i}.hahmo`])])};}));}else{if(files.some(f=>!/\.hahmo$/i.test(f.name)))throw new Error('Valitse .hahmo-projekteja tai yksi .sarja-tiedosto.');await append(files.map(f=>({name:f.name,blob:f})));}}catch(e){setMessage(e instanceof Error?e.message:'Sarjan avaaminen epäonnistui.');}};
 const saveSeries=async()=>{setBusy(true);try{const files:Record<string,Uint8Array>={'series.json':strToU8(JSON.stringify({format:'hahmostudio-series',version:1,episodes:items.map(i=>({name:i.name}))}))};for(let i=0;i<items.length;i++)files[`episodes/${i}.hahmo`]=new Uint8Array(await items[i].blob.arrayBuffer());const data=zipSync(files,{level:0});if(data.length>cap)throw new Error('Sarjatiedosto ylittää 128 Mt.');download(new Blob([new Uint8Array(data)]),'Hahmostudio-sarja.sarja');setMessage('Sarja tallennettu. Voit avata sen myöhemmin Tuo jaksot -painikkeella.');}catch(e){setMessage(e instanceof Error?e.message:'Tallennus epäonnistui.');}finally{setBusy(false);}};
 const locked=disabled||busy,seconds=items.reduce((n,i)=>n+i.animation.duration/i.animation.fps,0);
 return <section className="episodes" aria-label="Viiden jakson sarja"><div className="panel-heading"><h2>Sarja · {items.length}/5 jaksoa</h2><span>{seconds.toFixed(1)} s</span></div><p className="panel-note">Tallenna lyhytvideo erikseen. Lisää valmis jakso tähän YouTube-koostetta varten.</p><input ref={input} type="file" hidden multiple accept=".hahmo,.sarja" onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';void importFiles(files);}}/><div className="episode-actions"><button className="secondary" disabled={locked||!current||items.length===5} onClick={async()=>{if(!current)return;setBusy(true);try{const blob=await saveProject(current.doc,current.animation,current.audio,current.scene);await append([{name:safeName(current.doc.name.replace(/\.psd$/i,'')),blob}]);}catch(e){setMessage(e instanceof Error?e.message:'Jakson tallennus epäonnistui.');setBusy(false);}}}>Lisää nykyinen jakso</button><button className="secondary" disabled={locked||items.length===5} onClick={()=>input.current?.click()}>Tuo jaksot</button></div><ol className="episode-list">{Array.from({length:5},(_,index)=>{const item=items[index];return <li key={item?.id??`empty-${index}`} className={item?'':'empty-episode'}><span className="episode-number">{index+1}</span><div><strong>{item?.name??'Tyhjä jakso'}</strong><small>{item?`${(item.animation.duration/item.animation.fps).toFixed(1)} s · ${item.scene.width} × ${item.scene.height}`:'Lisää valmis animaatio'}</small></div>{item&&<div className="episode-order"><button aria-label={`Siirrä jakso ${index+1} ylemmäs`} disabled={locked||index===0} onClick={()=>setItems(v=>{const n=[...v];[n[index-1],n[index]]=[n[index],n[index-1]];return n;})}>↑</button><button aria-label={`Siirrä jakso ${index+1} alemmas`} disabled={locked||index===items.length-1} onClick={()=>setItems(v=>{const n=[...v];[n[index],n[index+1]]=[n[index+1],n[index]];return n;})}>↓</button><button aria-label={`Poista jakso ${index+1}`} disabled={locked} onClick={()=>{releaseDocument(item.doc);setItems(v=>v.filter(i=>i.id!==item.id));}}>×</button></div>}</li>;})}</ol><div className="episode-actions"><button className="primary" disabled={!exporting&&(locked||items.length!==5)} onClick={()=>void exportVideo(items)}>{exporting?'Peruuta vienti':'Vie 5 jaksoa YouTubeen · MP4'}</button><button className="secondary" disabled={locked||!items.length} onClick={()=>void saveSeries()}>Tallenna sarja</button></div><p className="panel-note">Kooste: 1920 × 1080, 30 kuvaa/s. Pystykuva säilyy kokonaan, sivut täytetään jakson taustavärillä. Jaksot toistuvat listan järjestyksessä.</p>{message&&<p role="status" className="panel-note">{message}</p>}</section>;
}
