import {useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {flatten,type PsdDocument} from '../lib/psd-model';
import {renderLayers} from '../lib/psd-render';

export default function ImportReview({doc,close}:{doc:PsdDocument;close:()=>void}){
 const closeRef=useRef(close);closeRef.current=close;
 const original=useRef<HTMLCanvasElement>(null),layers=useRef<HTMLCanvasElement>(null),dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>{const focus=document.activeElement as HTMLElement|null;dialog.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();closeRef.current();}if(e.key==='Tab'){const items=[...dialog.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];if(e.shiftKey&&(document.activeElement===items[0]||document.activeElement===dialog.current)){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);focus?.focus();};},[]);
 useEffect(()=>{if(layers.current)renderLayers(layers.current,doc);if(original.current&&doc.compositeImage){const c=original.current,scale=Math.min(1,1024/Math.max(doc.width,doc.height));c.width=Math.round(doc.width*scale);c.height=Math.round(doc.height*scale);c.getContext('2d')?.drawImage(doc.compositeImage,0,0,c.width,c.height);}},[doc]);
 return createPortal(<div className="studio-dialog-backdrop"><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="import-review-title" className="studio-dialog import-review"><header><div><span className="eyebrow">TUONTI JA TARKISTUS</span><h2 id="import-review-title">Tarkista tuotu kuva</h2><p>{doc.name} · {doc.width} × {doc.height} · {flatten(doc.layers).filter(n=>n.kind==='layer').length} tasoa</p></div><button className="secondary" onClick={close}>Sulje tarkistus</button></header><div className="import-comparison"><figure><figcaption>Alkuperäinen yhdistelmäkuva</figcaption>{doc.compositeImage?<canvas ref={original} aria-label="Alkuperäinen yhdistelmäkuva"/>:<p>Tiedostossa ei ole tallennettua yhdistelmäkuvaa. Vertaa alkuperäistä omassa kuvaeditorissasi.</p>}</figure><figure><figcaption>Editorin tulkitsemat tasot</figcaption><canvas ref={layers} aria-label="Editorin tulkitsemat tasot"/></figure></div><section aria-label="Tuonnin todelliset huomiot"><h3>{doc.warnings.length?'Tarkistettavat ominaisuudet':'Importer ei ilmoittanut varoituksia'}</h3>{doc.warnings.length?<ul>{doc.warnings.map(w=><li key={w}>{w}</li>)}</ul>:<p>Vertaa silti kuvia. Varoitusten puuttuminen ei todista kaikkien Photoshop-ominaisuuksien täydellistä toistoa.</p>}<p>Erot voivat johtua maskeista, sekoitustiloista tai efekteistä. Korjaa tarvittaessa lähdekuvaa tai käytä alkuperäistä yhdistelmäkuvaa. Tarkistus ei yhdistä eikä poista tasoja.</p></section><footer><button className="primary" onClick={close}>Jatka nykyisen kuvan kanssa</button></footer></div></div>,document.body);
}
