import {useState,useRef} from 'react';import {createPortal} from 'react-dom';
import {readLayerEdit,appendOperation,updateLayer,reorderLayer,type EditPoint,type Stroke,type VectorShape} from '../lib/layer-edit';import {layerPixels} from '../lib/layer-pixels';import {blendModes,type LayerNode,type PsdDocument} from '../lib/psd-model';
type Tool='brush'|'erase'|'picker'|'select'|'move'|'hide'|'reveal'|'rect'|'ellipse'|'path'|'pan';
const tools: [Tool,string][]=[['brush','Sivellin'],['erase','Pyyhekumi'],['picker','Pipetti'],['select','Valitse alue'],['move','Siirrä aluetta'],['hide','Maski: piilota'],['reveal','Maski: palauta'],['rect','Suorakulmio'],['ellipse','Ellipsi'],['path','Polku'],['pan','Siirrä näkymää']];
export default function LayerEditor({doc,layer,canvas,propertiesTarget,commit,add,undo,canUndo,canRedo}:{doc:PsdDocument;layer?:LayerNode;canvas:HTMLCanvasElement|null;propertiesTarget?:HTMLElement|null;commit:(doc:PsdDocument)=>void;add:(copy?:LayerNode)=>void;undo:(redo?:boolean)=>void;canUndo:boolean;canRedo:boolean}){
 const [tool,setTool]=useState<Tool>('brush'),[size,setSize]=useState(12),[color,setColor]=useState('#1266cc'),[opacity,setOpacity]=useState(1),[fill,setFill]=useState('#1266cc'),[line,setLine]=useState('#172b42'),[lineWidth,setLineWidth]=useState(2),[outline,setOutline]=useState(true),[selection,setSelection]=useState<{x:number;y:number;width:number;height:number}|null>(null),[points,setPoints]=useState<EditPoint[]>([]),[vectorId,setVectorId]=useState(''),[error,setError]=useState('');
 const gesture=useRef<{start:EditPoint;points:EditPoint[];client:EditPoint;scroll:EditPoint}|null>(null);
 const apply=(next:PsdDocument)=>{try{commit(next);setError('');}catch(e){setError((e as Error).message);}};
 const local=(e:React.PointerEvent)=>{const b=e.currentTarget.getBoundingClientRect();const p={x:(e.clientX-b.left)/b.width*doc.width-(layer?.left??0),y:(e.clientY-b.top)/b.height*doc.height-(layer?.top??0)},t=layer?.edit?.transform;if(!t||tool==='picker')return p;const x=p.x-layer!.width/2-t.x,y=p.y-layer!.height/2-t.y,r=-t.rotation*Math.PI/180;return{x:(x*Math.cos(r)-y*Math.sin(r))/t.scaleX+layer!.width/2,y:(x*Math.sin(r)+y*Math.cos(r))/t.scaleY+layer!.height/2};};
 const overlayTransform=layer?`translate(${layer.left+layer.width/2+(layer.edit?.transform?.x??0)} ${layer.top+layer.height/2+(layer.edit?.transform?.y??0)}) rotate(${layer.edit?.transform?.rotation??0}) scale(${layer.edit?.transform?.scaleX??1} ${layer.edit?.transform?.scaleY??1}) translate(${-layer.width/2} ${-layer.height/2})`:undefined;

 const vector=layer?.edit?.operations.find(o=>'id'in o&&o.id===vectorId) as VectorShape|undefined;
 const editVector=(change:Partial<VectorShape>)=>{if(!layer||!vector||layer.locked)return;try{apply(updateLayer(doc,layer.key,n=>({...n,edit:readLayerEdit({...n.edit,version:1,operations:n.edit!.operations.map(o=>'id'in o&&o.id===vectorId?{...o,...change}:o)})})));}catch(e){setError((e as Error).message);}};
 const down=(e:React.PointerEvent<SVGSVGElement>)=>{if(!layer||layer.locked&&tool!=='pan')return;e.preventDefault();const p=local(e);if(tool==='picker'){const image=layerPixels(layer);if(!image)return;const c=document.createElement('canvas');c.width=layer.width;c.height=layer.height;const ctx=c.getContext('2d')!;ctx.drawImage(image,0,0);const pixel=ctx.getImageData(Math.max(0,Math.min(c.width-1,Math.floor(p.x))),Math.max(0,Math.min(c.height-1,Math.floor(p.y))),1,1).data;setColor('#'+[...pixel.slice(0,3)].map(x=>x.toString(16).padStart(2,'0')).join(''));c.width=c.height=0;return;}if(tool==='path'){setPoints(v=>[...v,p]);return;}const stage=canvas?.closest('.stage');gesture.current={start:p,points:[p],client:{x:e.clientX,y:e.clientY},scroll:{x:stage?.scrollLeft??0,y:stage?.scrollTop??0}};e.currentTarget.setPointerCapture(e.pointerId);};
 const move=(e:React.PointerEvent<SVGSVGElement>)=>{const g=gesture.current;if(!g)return;if(tool==='pan'){const stage=canvas?.closest('.stage');if(stage){stage.scrollLeft=g.scroll.x+g.client.x-e.clientX;stage.scrollTop=g.scroll.y+g.client.y-e.clientY;}return;}const p=local(e);if(g.points.length<20000)g.points.push(p);if(tool==='select')setSelection({x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.max(1,Math.abs(p.x-g.start.x)),height:Math.max(1,Math.abs(p.y-g.start.y))});};
 const up=(e:React.PointerEvent<SVGSVGElement>)=>{const g=gesture.current;gesture.current=null;if(!g||!layer||layer.locked)return;const p=local(e);try{if(['brush','erase','hide','reveal'].includes(tool))apply(appendOperation(doc,layer.key,{kind:tool as Stroke['kind'],points:g.points,size,color,opacity}));else if(tool==='move'&&selection){apply(appendOperation(doc,layer.key,{kind:'move',...selection,dx:p.x-g.start.x,dy:p.y-g.start.y}));setSelection({...selection,x:selection.x+p.x-g.start.x,y:selection.y+p.y-g.start.y});}else if(tool==='rect'||tool==='ellipse'){const shape:VectorShape={kind:tool,id:crypto.randomUUID(),x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.max(1,Math.abs(p.x-g.start.x)),height:Math.max(1,Math.abs(p.y-g.start.y)),rotation:0,fill,stroke:line,strokeWidth:outline?lineWidth:0};apply(appendOperation(doc,layer.key,shape));setVectorId(shape.id);}}catch(e){setError((e as Error).message);}};
 const finishPath=()=>{if(!layer||points.length<2)return;const x=Math.min(...points.map(p=>p.x)),y=Math.min(...points.map(p=>p.y)),width=Math.max(1,Math.max(...points.map(p=>p.x))-x),height=Math.max(1,Math.max(...points.map(p=>p.y))-y);const shape:VectorShape={kind:'path',id:crypto.randomUUID(),x,y,width,height,rotation:0,fill,stroke:line,strokeWidth:outline?lineWidth:0,points:points.map(p=>({x:(p.x-x)/width,y:(p.y-y)/height}))};try{apply(appendOperation(doc,layer.key,shape));setVectorId(shape.id);setPoints([]);}catch(e){setError((e as Error).message);}};
 const properties=(<details open><summary>Tason ja vektorien asetukset</summary><div className="drawing-properties"><button onClick={()=>add()}>Lisää taso</button><button disabled={!layer} onClick={()=>add(layer)}>Kopioi taso</button>{layer&&<><label>Nimi<input value={layer.name} onChange={e=>apply(updateLayer(doc,layer.key,n=>({...n,name:e.target.value,path:n.path.slice(0,n.path.lastIndexOf('/')+1)+e.target.value})))}/></label><label><input type="checkbox" checked={layer.locked??false} onChange={e=>apply(updateLayer(doc,layer.key,n=>({...n,locked:e.target.checked})))}/>Lukittu</label><label><input type="checkbox" checked={layer.visible} onChange={e=>apply(updateLayer(doc,layer.key,n=>({...n,visible:e.target.checked})))}/>Näkyvissä</label><button onClick={()=>apply(reorderLayer(doc,layer.key,1))}>Ylemmäs</button><button onClick={()=>apply(reorderLayer(doc,layer.key,-1))}>Alemmas</button>{([['x','Sisällön siirto X',-100000,100000],['y','Sisällön siirto Y',-100000,100000],['scaleX','Sisällön leveyskerroin',.01,100],['scaleY','Sisällön korkeuskerroin',.01,100],['rotation','Sisällön kierto',-3600,3600]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" disabled={layer.locked} step=".01" min={min} max={max} value={layer.edit?.transform?.[key]??(key==='scaleX'||key==='scaleY'?1:0)} onChange={e=>{try{apply(updateLayer(doc,layer.key,n=>({...n,edit:readLayerEdit({...n.edit,version:1,operations:n.edit?.operations??[],transform:{x:0,y:0,scaleX:1,scaleY:1,rotation:0,...n.edit?.transform,[key]:+e.target.value}})})));}catch(e){setError((e as Error).message);}}}/></label>)}<label>Tason peittävyys<input type="range" min="0" max="1" step=".01" value={layer.opacity} onChange={e=>apply(updateLayer(doc,layer.key,n=>({...n,opacity:+e.target.value})))}/></label><label>Sekoitustila<select value={layer.blendMode} onChange={e=>apply(updateLayer(doc,layer.key,n=>({...n,blendMode:e.target.value})))}>{Object.keys(blendModes).filter(k=>k!=='pass through').map(k=><option key={k}>{k}</option>)}</select></label></>}
 <label>Täyttö<input type="color" value={fill} onChange={e=>setFill(e.target.value)}/></label><label>Viiva<input type="color" value={line} onChange={e=>setLine(e.target.value)}/></label><label>Viivan leveys<input type="number" min="0" max="100" value={lineWidth} onChange={e=>setLineWidth(+e.target.value)}/></label>{tool==='path'&&<><button disabled={points.length<2} onClick={finishPath}>Sulje ja lisää polku</button><button onClick={()=>setPoints([])}>Tyhjennä polku</button></>}
 <label>Muokkaa vektoria<select value={vectorId} onChange={e=>setVectorId(e.target.value)}><option value="">Valitse vektori</option>{layer?.edit?.operations.filter(o=>'id'in o).map(o=>{const v=o as VectorShape;return <option value={v.id} key={v.id}>{v.kind==='rect'?'Suorakulmio':v.kind==='ellipse'?'Ellipsi':'Polku'} · {v.id.slice(0,6)}</option>;})}</select></label>{vector&&<>{([['x','X'],['y','Y'],['width','Leveys'],['height','Korkeus'],['rotation','Kierto']] as const).map(([id,label])=><label key={id}>{label}<input type="number" value={vector[id]} min={id==='width'||id==='height'?1:undefined} onChange={e=>editVector({[id]:+e.target.value})}/></label>)}<label>Täyttö<input type="color" value={vector.fill==='transparent'?'#ffffff':vector.fill} onChange={e=>editVector({fill:e.target.value})}/></label><label><input type="checkbox" checked={vector.fill==='transparent'} onChange={e=>editVector({fill:e.target.checked?'transparent':fill})}/>Ei täyttöä</label><label>Viiva<input type="color" value={vector.stroke==='transparent'?'#ffffff':vector.stroke} onChange={e=>editVector({stroke:e.target.value})}/></label><label><input type="checkbox" checked={vector.strokeWidth>0&&vector.stroke!=='transparent'} onChange={e=>editVector({stroke:e.target.checked&&vector.stroke==='transparent'?line:vector.stroke,strokeWidth:e.target.checked?Math.max(1,lineWidth):0})}/>Näytä reunaviiva</label><label>Viivan leveys<input type="number" value={vector.strokeWidth} min="0" max="1024" onChange={e=>editVector({strokeWidth:+e.target.value})}/></label>{vector.kind==='path'&&<label>Polun pisteet (x,y suhteessa kokoon)<textarea value={vector.points!.map(p=>`${p.x},${p.y}`).join('\n')} onChange={e=>{const next=e.target.value.split('\n').map(s=>{const [x,y]=s.split(',').map(Number);return {x,y};});if(next.length>=2&&next.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)))editVector({points:next});}}/></label>}</>}
 </div><p>Muokkaa valittua tasoa sen oman kuvarajauksen sisällä. Sisällön muunnos säilyttää tason kiertokeskuksen ja kuvarajauksen; näyttämön muunnokset tehdään Animointi-työtilassa. Maski säilyttää alkuperäisen kuvan. Polku lisätään napsauttamalla pisteitä ja sulkemalla polku. Siirrä aluetta valinnan jälkeen vetämällä.</p></details>);
 return <section className="drawing-tools" aria-label="Piirtäminen"><div className="drawing-toolbar"><label><input type="checkbox" checked={outline} onChange={e=>setOutline(e.target.checked)}/>Uusien muotojen reunaviiva</label><label>Työkalu<select value={tool} onChange={e=>{setTool(e.target.value as Tool);setPoints([]);}}>{tools.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Väri<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label>Koko<input type="number" min="1" max="2048" value={size} onChange={e=>setSize(Math.max(1,Math.min(2048,Number(e.target.value))))}/></label><label>Peittävyys<input type="range" min="0" max="1" step=".01" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label><button onClick={()=>undo()} disabled={!canUndo}>Kumoa</button><button onClick={()=>undo(true)} disabled={!canRedo}>Tee uudelleen</button></div>
 {propertiesTarget?createPortal(properties,propertiesTarget):properties}{!layer&&<p>Valitse taso vasemmalta tai lisää uusi taso.</p>}{error&&<p role="alert">{error}</p>}
 {canvas?.parentElement&&createPortal(<svg className="draw-overlay" viewBox={`0 0 ${doc.width} ${doc.height}`} aria-label="Piirtoalue" style={{cursor:tool==='pan'?'grab':'crosshair'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current=null;}}>{selection&&layer&&<rect transform={overlayTransform} x={selection.x} y={selection.y} width={selection.width} height={selection.height} fill="none" stroke="#1266cc" strokeWidth="2" strokeDasharray="5 4"/>}{points.length>0&&layer&&<polyline transform={overlayTransform} points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#1266cc" strokeWidth="2"/>}</svg>,canvas.parentElement)}
 </section>;
}
