import type {PresentationAssets} from '../lib/presentation-compile';
import {flatten} from '../lib/psd-model';
import {profileChains} from '../lib/studio/chain-retarget';
type Motion={mode:'fk'|'ik'|'proportional';frameStep:number;autoContacts:boolean;ikWeight:number};
export default function RelinkMappingPanel({speaker,old,incoming,mapping,change,motion,changeMotion,disabled,apply,cancel}:{speaker:string;old:PresentationAssets[string];incoming:PresentationAssets[string];mapping:Record<string,string>;change:(m:Record<string,string>)=>void;motion?:Motion;changeMotion?:(m:Motion)=>void;disabled:boolean;apply:()=>void;cancel:()=>void}){
 const nodes=flatten(incoming.doc.layers),parts=old.animation.rig.parts,sameSize=old.doc.width===incoming.doc.width&&old.doc.height===incoming.doc.height;let chainError='',covered=new Set<string>();
 try{if(motion?.mode!=='proportional'&&old.doc.quick&&incoming.doc.quick)covered=new Set(profileChains(old.animation.rig,incoming.animation.rig,old.doc.quick,incoming.doc.quick).flatMap(c=>c.source));}catch(e){chainError=(e as Error).message;}
 const required=incoming.doc.quick&&motion?.mode!=='proportional'?parts.filter(p=>old.animation.tracks.some(t=>t.key===p.key)&&!covered.has(p.key)):parts;
 const values=Object.values(mapping).filter(Boolean),complete=!chainError&&required.every(p=>nodes.some(n=>n.key===mapping[p.key]))&&new Set(values).size===values.length;
 return <section className="studio-validation" aria-label="Hahmon tasojen uudelleenkytkentä"><h3>Uudelleenkytkentä · {speaker}</h3><p>{old.doc.name} → {incoming.doc.name}. Vanha resurssi ja liikkeet säilyvät. Tarkista osavastaavuudet; nivelketjut voivat sisältää eri määrän luita.</p>{!sameSize&&<p>Piirtoalue muuttui. Raaka-PSD:n nivelpisteet ja siirtymät skaalataan. Valmis hahmo käyttää omia niveliään.</p>}{incoming.doc.quick&&motion&&changeMotion&&<fieldset disabled={disabled}><legend>Liikesovitus</legend><label>Menetelmä<select value={motion.mode} onChange={e=>changeMotion({...motion,mode:e.target.value as Motion['mode'],autoContacts:e.target.value==='fk'?false:motion.autoContacts})}><option value="ik">IK · sovita käsien ja jalkojen kohteet</option><option value="fk">FK · sovita nivelten suunnat</option><option value="proportional">Vastaavat luut · suhteellinen sovitus</option></select></label><label>IK-osuus {Math.round(motion.ikWeight*100)} %<input type="range" min="0" max="100" disabled={motion.mode!=='ik'} value={motion.ikWeight*100} onChange={e=>changeMotion({...motion,ikWeight:Number(e.target.value)/100,autoContacts:Number(e.target.value)===0?false:motion.autoContacts})}/></label><label>Ruutuaskel<input type="number" min="1" max="24" value={motion.frameStep} onChange={e=>changeMotion({...motion,frameStep:Number(e.target.value)})}/></label><label><input type="checkbox" disabled={motion.mode!=='ik'||motion.ikWeight===0} checked={motion.autoContacts} onChange={e=>changeMotion({...motion,autoContacts:e.target.checked})}/>Lukitse lähdeliikkeessä paikallaan pysyvät kädet ja jalat</label><p>Suurempi ruutuaskel vähentää avainruutuja. Sovitettu liike jää käsin muokattavaksi.</p></fieldset>}{chainError&&<p role="alert">{chainError}</p>}<div>{parts.map(p=><label key={p.key}>{p.path}{covered.has(p.key)?' · sovitetaan ketjussa':''}<select value={mapping[p.key]??''} disabled={disabled} onChange={e=>change({...mapping,[p.key]:e.target.value})}><option value="">{covered.has(p.key)?'Sovita nivelketjussa':'Ei vastaavuutta'}</option>{nodes.map(n=><option key={n.key} value={n.key}>{n.path} · {n.key}</option>)}</select></label>)}</div><p>Ulottumattomat kohteet ilmoitetaan. Tarkista nivelpisteet ja liike ennen hyväksyntää.</p><button disabled={disabled||!complete} onClick={apply}>Tarkista ja vaihda resurssi</button><button disabled={disabled} onClick={cancel}>Peruuta uudelleenkytkentä</button></section>;
}
