import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {desktop,studioPortalHost,type ProjectRevision} from '../lib/platform';
export default function RevisionPanel({projectId,disabled,capture,restore}:{projectId?:string;disabled:boolean;capture:()=>Promise<{name:string;bytes:Uint8Array}>;restore:(bytes:Uint8Array,name:string)=>Promise<boolean>}){
 const bridge=desktop(),[open,setOpen]=useState(false),[items,setItems]=useState<ProjectRevision[]>([]),[label,setLabel]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[deleting,setDeleting]=useState(''),dialog=useRef<HTMLDialogElement>(null),active=useRef(projectId);active.current=projectId;
 const refresh=async()=>{if(!projectId||!bridge)return;const id=projectId,next=await bridge.revisionsList(id);if(active.current===id)setItems(next);};
 useEffect(()=>{if(!open)return;const focus=document.activeElement as HTMLElement|null;dialog.current?.showModal();void refresh().catch(e=>setMessage(e.message));return()=>{dialog.current?.close();(focus?.closest('details')?.querySelector('summary') as HTMLElement|null??focus)?.focus();};},[open,projectId]);
 const run=async(work:()=>Promise<void>)=>{setWorking(true);setMessage('');try{await work();}catch(e){setMessage((e as Error).message);}finally{setWorking(false);}};
 return <><button disabled={disabled||!projectId||!bridge} title={!bridge?'Revisiohistoria on käytettävissä KILSAT Studion Mac-versiossa.':undefined} onClick={()=>setOpen(true)}>Projektin versiot{!bridge?' (Mac-versio)':''}</button>{open&&createPortal(<dialog ref={dialog} className="revision-dialog studio-dialog" aria-labelledby="revision-title" onKeyDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onBlur={e=>e.stopPropagation()} onCancel={e=>{if(working)e.preventDefault();else setOpen(false);}}><header><h2 id="revision-title">Projektin versiot</h2><button disabled={working} onClick={()=>setOpen(false)}>Sulje</button></header><p>Nimetty versio sisältää koko projektin ja äänet. Palautus avaa version editoriin; alkuperäistä projektitiedostoa ei korvata. Nämä versiot säilyvät kahden automaattipalautuspisteen rinnalla.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{const id=projectId;if(!id||!bridge)return;const snapshot=await capture();await bridge.revisionsSave({projectId:id,label,...snapshot});setLabel('');await refresh();setMessage('Nimetty versio tallennettu paikalliseen arkistoon.');});}}><label>Version nimi<input autoFocus value={label} maxLength={120} disabled={working} placeholder="Esim. kohtaus ennen ajoitusmuutoksia" onChange={e=>setLabel(e.target.value)}/></label><button disabled={working||disabled||!label.trim()} type="submit">Tallenna nimetty versio</button></form><p role="status">{message}</p>{!items.length&&<p>Tällä projektilla ei ole vielä nimettyjä versioita.</p>}<ol className="revision-list">{items.map(item=><li key={item.id}><strong>{item.label}</strong><span>{new Date(item.createdAt).toLocaleString('fi-FI')} · {item.name}</span><code title={item.hash}>SHA-256: {item.hash.slice(0,12)}…</code><div><button disabled={working||disabled} onClick={()=>void run(async()=>{if(!projectId||!bridge)return;const stored=await bridge.revisionsRead(projectId,item.id);if(await restore(stored.bytes,stored.name))setOpen(false);})}>Avaa tämä versio</button><button disabled={working} onClick={()=>setDeleting(item.id)}>Poista versio…</button></div>{deleting===item.id&&<div role="group" aria-label="Vahvista version poisto"><p>Poistetaan vain arkiston versio. Alkuperäinen projekti ja muut versiot säilyvät.</p><button disabled={working} onClick={()=>void run(async()=>{if(!projectId||!bridge)return;await bridge.revisionsRemove(projectId,item.id);setDeleting('');await refresh();})}>Poista tämä versio pysyvästi</button><button disabled={working} onClick={()=>setDeleting('')}>Peruuta</button></div>}</li>)}</ol><p>Arkiston raja on 2 GiB / 1000 nimettyä versiota. Vanhoja nimettyjä versioita ei poisteta automaattisesti.</p></dialog>,studioPortalHost())}</>;
}
