import type {ShotSort} from '../lib/studio/shot-sort';
import {useState} from 'react';
import {addShotView,readShotViews,removeShotView,storeShotViews,shotViewKey,type SavedShotView,type ShotViews} from '../lib/studio/saved-shot-views';
import type {ShotFilter} from '../lib/studio/production-overview';
export default function SavedShotViews({filter,query,sort,descending,apply}:{filter:ShotFilter;query:string;sort:ShotSort;descending:boolean;apply:(v:SavedShotView)=>void}){
 const [loaded]=useState(()=>{try{return{data:readShotViews(typeof localStorage==='undefined'?null:localStorage.getItem(shotViewKey)),error:''};}catch{return{data:{schemaVersion:1,views:[]} as ShotViews,error:'Hakunäkymiä ei voitu lukea. Vanhat asetukset säilytetään; uusia näkymiä ei kirjoiteta niiden päälle.'};}});
 const [data,setData]=useState(loaded.data),[name,setName]=useState(''),[message,setMessage]=useState('');
 const save=(next:ShotViews)=>{try{const saved=storeShotViews(localStorage,next);setData(saved);return true;}catch{setMessage('Asetusten tallennus epäonnistui. Nykyiset näkymät säilyvät.');return false;}};
 return <details className="studio-task-editor"><summary>Tallennetut hakunäkymät · {data.views.length} / 20</summary><p>Näkymä tallentaa nykyisen haun, suodatuksen ja lajittelun paikallisiin asetuksiin. Se sovelletaan aina avoinna olevaan valmisteluun, eikä se sisällä kuvia tai muuta projektia.</p>{loaded.error&&<p role="alert">{loaded.error}</p>}<form onSubmit={e=>{e.preventDefault();try{const next=addShotView(data,{id:crypto.randomUUID(),name,filter,query,sort,descending});if(save(next)){setName('');setMessage('Hakunäkymä tallennettu paikallisiin asetuksiin.');}}catch{setMessage('Anna yksilöllinen nimi (1–80 merkkiä). Enintään 20 näkymää ja 500 merkin haku.');}}}><label>Uuden hakunäkymän nimi<input value={name} maxLength={80} required disabled={!!loaded.error} onChange={e=>setName(e.target.value)}/></label><button disabled={!!loaded.error||data.views.length>=20||!name.trim()}>Tallenna nykyinen haku ja suodatus</button></form><ul>{data.views.map(v=><li key={v.id}><button onClick={()=>{apply(v);setMessage('Hakunäkymä avattu: '+v.name);}}>{v.name}</button><button aria-label={'Poista hakunäkymä '+v.name} onClick={()=>{if(window.confirm('Poista tallennettu hakunäkymä '+v.name+'? Projektin sisältö säilyy.')&&save(removeShotView(data,v.id)))setMessage('Hakunäkymä poistettu.');}}>Poista</button></li>)}</ul><p role="status">{message}</p></details>;
}
