import {useRef,useState} from 'react';import {clampToStage,clientToStage,dragPosition,snapToStage,stageLimits,type StageGeometry} from '../lib/stage-bounds';import type {Scene} from '../lib/scene-model';
export default function StagePosition({scene,geometry,disabled,preview,commit}:{scene:Scene;geometry:StageGeometry;disabled:boolean;preview:(scene?:Scene)=>void;commit:(scene:Scene)=>Promise<unknown>}){
 const gesture=useRef<{id:number;point:{x:number;y:number};scene:Scene}|null>(null),latest=useRef(scene),pending=useRef<number|null>(null);const [moving,setMoving]=useState(false),[guides,setGuides]=useState<{axis:'x'|'y';value:number}[]>([]);const g={...geometry,scale:scene.scale,safeArea:scene.safeArea},box=g.box??{left:0,top:0,width:g.docWidth,height:g.docHeight},safe=scene.safeArea??{left:40,right:40,top:120,bottom:220};
 const flush=()=>{if(pending.current!==null){cancelAnimationFrame(pending.current);pending.current=null;}preview(latest.current);};const finish=async()=>{const changed=gesture.current;gesture.current=null;setMoving(false);setGuides([]);if(!changed)return;flush();try{if(latest.current.x!==changed.scene.x||latest.current.y!==changed.scene.y)await commit(latest.current);}finally{preview(undefined);}};
 const cancel=()=>{gesture.current=null;if(pending.current!==null)cancelAnimationFrame(pending.current);pending.current=null;setMoving(false);setGuides([]);preview(undefined);};
 return <svg className={'stage-position '+(moving?'grabbing':'')} viewBox={`0 0 ${scene.width} ${scene.height}`} tabIndex={disabled?-1:0} role="application" aria-label="Hahmon sijainti näyttämöllä: raahaa tai siirrä nuolinäppäimillä" onKeyDown={e=>{if(disabled||e.target!==e.currentTarget)return;if(e.key==='Escape'){cancel();return;}const direction:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},d=direction[e.key];if(!d)return;e.preventDefault();e.stopPropagation();const step=e.shiftKey?10:1;void commit({...scene,...clampToStage(scene.x+d[0]*step,scene.y+d[1]*step,g)});}} onPointerDown={e=>{if(disabled||e.button!==0||(e.target as Element).getAttribute('data-drag-character')!=='true')return;e.preventDefault();e.currentTarget.focus();const p=clientToStage({x:e.clientX,y:e.clientY},e.currentTarget.getBoundingClientRect(),scene);gesture.current={id:e.pointerId,point:p,scene};latest.current=scene;setMoving(true);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const drag=gesture.current;if(!drag||e.pointerId!==drag.id)return;const p=clientToStage({x:e.clientX,y:e.clientY},e.currentTarget.getBoundingClientRect(),scene),position=dragPosition(drag.scene,{x:p.x-drag.point.x,y:p.y-drag.point.y},e.shiftKey),next=snapToStage(position.x,position.y,g);latest.current={...drag.scene,x:next.x,y:next.y,scale:next.scale};setGuides(next.guides);if(pending.current===null)pending.current=requestAnimationFrame(()=>{pending.current=null;preview(latest.current);});}} onPointerUp={e=>{if(!gesture.current)return;void finish();if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current)cancel();}}>
 {scene.guides&&<rect className="stage-safe-area" x={safe.left} y={safe.top} width={Math.max(0,scene.width-safe.left-safe.right)} height={Math.max(0,scene.height-safe.top-safe.bottom)}/>}
 {!disabled&&<rect data-drag-character="true" className="character-drag-hit" x={scene.x+(box.left-g.docWidth/2)*scene.scale} y={scene.y+(box.top-g.docHeight/2)*scene.scale} width={box.width*scene.scale} height={box.height*scene.scale}/>}
 {guides.map((l,i)=><line key={i} className="stage-snap-line" x1={l.axis==='x'?l.value:0} x2={l.axis==='x'?l.value:scene.width} y1={l.axis==='y'?l.value:0} y2={l.axis==='y'?l.value:scene.height}/>)}
 </svg>;
}
