import {useState} from 'react';
import {addState,addTransition,type StateMachine,type StateId} from '../lib/state-machine-model';
interface StateEditorProps {machine:StateMachine; onChange:(machine:StateMachine)=>void|Promise<unknown>; selectedStateId?:StateId; onSelectState?:(id:StateId|undefined)=>void; tracks?:{key:string;name:string}[]; disabled?:boolean}
export default function StateEditor({machine,onChange,selectedStateId,onSelectState,tracks=[],disabled=false}:StateEditorProps){
 const [from,setFrom]=useState(''),[to,setTo]=useState('');
 const selected=machine.states.find(s=>s.id===selectedStateId);
 const position=(index:number)=>({x:100+(index%2)*200,y:70+Math.floor(index/2)*120});
 return <section className="state-editor" aria-label="Tilakoneen solmukaavio"><p>Tilakone tallennetaan projektiin. Kaavio kuvaa liikelogiikkaa; se ei vielä ohjaa aikajanan toistoa.</p>
 <div className="row"><button className="button" disabled={disabled||!tracks.length||machine.states.length>=256} onClick={()=>void onChange(addState(machine,`Tila ${machine.states.length+1}`,tracks[0].key))}>Lisää tila</button></div>
 <svg className="state-graph" viewBox={`0 0 400 ${Math.max(180,Math.ceil(machine.states.length/2)*120)}`} aria-label="Tilat ja siirtymät">
 {machine.transitions.map(t=>{const a=position(machine.states.findIndex(s=>s.id===t.fromState)),b=position(machine.states.findIndex(s=>s.id===t.toState));return <g key={t.id}><path className="curve-handle" d={`M${a.x} ${a.y}L${b.x} ${b.y}`}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2}>{t.duration.toFixed(2)} s →</text></g>;})}
 {machine.states.map((s,i)=>{const p=position(i);return <g key={s.id} role="button" tabIndex={0} aria-label={`${s.name}${s.id===machine.entryState?', aloitustila':''}`} aria-pressed={s.id===selectedStateId} onClick={()=>onSelectState?.(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();onSelectState?.(s.id);}}}><rect className={s.id===selectedStateId?'state-shape selected':'state-shape'} x={p.x-80} y={p.y-30} width="160" height="60" rx="8"/><text x={p.x} y={p.y}>{s.name}</text><text x={p.x} y={p.y+18}>{s.id===machine.entryState?'Aloitus':''}</text></g>;})}
 </svg><div className="state-inspector"><fieldset disabled={disabled}><legend>Tilan asetukset</legend>{selected?<><label>Nimi<input value={selected.name} maxLength={256} onChange={e=>void onChange({...machine,states:machine.states.map(s=>s.id===selected.id?{...s,name:e.target.value}:s)})}/></label><label>Animaatiorata<select value={selected.trackKey} onChange={e=>void onChange({...machine,states:machine.states.map(s=>s.id===selected.id?{...s,trackKey:e.target.value}:s)})}><option value={selected.trackKey}>{tracks.find(t=>t.key===selected.trackKey)?.name??selected.trackKey}</option>{tracks.filter(t=>t.key!==selected.trackKey).map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></label><label>Nopeus<input type="number" min=".1" max="10" step=".1" value={selected.speed} onChange={e=>{const speed=e.target.valueAsNumber;if(Number.isFinite(speed)&&speed>0&&speed<=10)void onChange({...machine,states:machine.states.map(s=>s.id===selected.id?{...s,speed}:s)});}}/></label><button className="button" onClick={()=>void onChange({...machine,entryState:selected.id})}>Aseta aloitustilaksi</button><button className="button" disabled={machine.states.length===1} onClick={()=>{const states=machine.states.filter(s=>s.id!==selected.id);void onChange({...machine,states,entryState:machine.entryState===selected.id?states[0].id:machine.entryState,transitions:machine.transitions.filter(t=>t.fromState!==selected.id&&t.toState!==selected.id)});onSelectState?.(undefined);}}>Poista tila</button></>:<p>Valitse tila kaaviosta.</p>}</fieldset>
 <fieldset disabled={disabled}><legend>Siirtymät</legend><label>Mistä<select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Valitse</option>{machine.states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mihin<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Valitse</option>{machine.states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="button" disabled={!from||!to||from===to||machine.transitions.length>=1024} onClick={()=>{const a=machine.states.find(s=>s.id===from),b=machine.states.find(s=>s.id===to);if(a&&b)void onChange(addTransition(machine,a.id,b.id));}}>Lisää siirtymä</button>{machine.transitions.map(t=><div className="row" key={t.id}><span>{machine.states.find(s=>s.id===t.fromState)?.name} → {machine.states.find(s=>s.id===t.toState)?.name}</span><label>Kesto (s)<input type="number" min="0" max="60" step=".05" value={t.duration} onChange={e=>{const duration=e.target.valueAsNumber;if(Number.isFinite(duration)&&duration>=0&&duration<=60)void onChange({...machine,transitions:machine.transitions.map(v=>v.id===t.id?{...v,duration}:v)});}}/></label><button className="button" onClick={()=>void onChange({...machine,transitions:machine.transitions.filter(v=>v.id!==t.id)})}>Poista siirtymä</button></div>)}</fieldset></div></section>;
}
