// React markup and event contracts tested in Node, without a browser or device access.
import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {readFileSync,existsSync} from 'node:fs';import {fileURLToPath} from 'node:url';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
const root=new URL('../',import.meta.url);
registerHooks({
 resolve(specifier,context,next){
  const resolveFile=(url)=>{for(const suffix of ['', '.ts','.tsx']){const candidate=url+suffix;if(existsSync(fileURLToPath(candidate)))return {url:candidate,shortCircuit:true};}};
  if(specifier.startsWith('@/')){const file=resolveFile(new URL(specifier.slice(2),root).href);if(file)return file;}
  if(specifier.startsWith('.')&&context.parentURL?.startsWith(root.href)&&!context.parentURL.includes('/node_modules/')){const file=resolveFile(new URL(specifier,context.parentURL).href);if(file)return file;}
  return next(specifier,context);
 },
 load(url,context,next){if(url.startsWith(root.href)&&!url.includes('/node_modules/')&&/\.tsx?$/.test(url)){
  const source=readFileSync(fileURLToPath(url),'utf8').replaceAll('import.meta.env',"({BASE_URL:'/',VITE_PRIVATE_SERVER:'true'})");
  return {format:'module',source:ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText,shortCircuit:true};
 }return next(url,context);}
});
const {default:Editor}=await import('../components/editor.tsx');const {default:WorkspaceTabs}=await import('../components/workspace-tabs.tsx');const {default:QuickPanel}=await import('../components/quick-panel.tsx');const {default:CameraPanel}=await import('../components/camera-panel.tsx');const {readProject}=await import('../lib/project-file.ts');
test('editor exposes five flow tabs in topbar, device status and file actions',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Tuotantovaiheet"/);assert.ok(html.includes('studio-flow-tabs'));for(const label of ['Käsikirjoitus','Hahmot','Storyboard','Kuva','Aikajana','Tallenna','Vie…','Ohje','Mikrofoni:','Kamera:'])assert.ok(html.includes(label),label);
assert.ok(html.includes('kilsat-top'));assert.ok(html.includes('kilsat-app'));assert.equal((html.match(/aria-pressed="true"/g)??[]).length>=1,true);assert.match(html,/class="[^"]*studio[^"]*workspace-performance[^"]*"/);});
test('workspace navigation stays operable with recording active and only invokes a view transition',()=>{for(const workspace of ['character','performance','animation']){const chosen=[];const nav=WorkspaceTabs({workspace,change:v=>chosen.push(v)});const buttons=nav.props.children;assert.equal(buttons.length,3);assert.equal(buttons.filter(b=>b.props['aria-pressed']).length,1);for(const b of buttons){assert.equal(b.props.disabled,undefined);b.props.onClick();}assert.deepEqual(chosen,['character','performance','animation']);}});
test('ready character controls expose independent microphone and keyboard toggles; busy transport blocks recording',async()=>{const p=await readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));const noop=()=>{};const html=renderToStaticMarkup(React.createElement(QuickPanel,{profile:p.doc.quick,animation:p.animation,scene:p.scene,active:true,enabled:false,stopRequest:0,status:noop,live:noop,apply:noop,update:noop,activity:noop,setScene:noop,play:noop,save:noop,video:noop}));assert.match(html,/type="checkbox"[^>]*checked/);assert.match(html,/Käynnistä mikrofoni/);assert.match(html,/<button class="primary full" disabled="">Tallenna ääni ja esitys/);assert.ok(html.includes('Kamera ja näppäimet voivat toimia samanaikaisesti'));});
test('camera ready-template defaults include head and pupils, combined recording uses one main take',async()=>{const p=await readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));const {flatten}=await import('../lib/psd-model.ts');const noop=()=>{};const html=renderToStaticMarkup(React.createElement(CameraPanel,{defaults:p.doc.quick.roles,rig:p.animation.rig,combined:true,nodes:flatten(p.doc.layers),width:p.doc.width,height:p.doc.height,fps:24,duration:24,frame:0,disabled:false,live:noop,record:noop,active:noop}));assert.ok(html.includes('Tallenna yhteinen otto yllä'));assert.ok(html.includes('playsInline=""'));assert.equal((html.match(/selected=""/g)??[]).length,4);});

const {default:AssetLibrary}=await import('../components/asset-library.tsx');const {default:ScriptPanel}=await import('../components/script-panel.tsx');
test('library has real character, angle and download actions with accessible selected states',()=>{const calls=[],view=AssetLibrary({disabled:false,current:'Aino.psd',design:'car-driver-v1',open:v=>calls.push(['character',v]),background:v=>calls.push(['background',v]),script:()=>calls.push(['script']),download:v=>calls.push(['download',v])});const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(typeof node!=='object')return;if(node.type==='button'&&!node.props.disabled)node.props.onClick();visit(node.props?.children);};visit(view);assert.ok(calls.some(c=>c[0]==='character'&&c[1]==='Leo'));assert.ok(calls.some(c=>c[0]==='character'&&c[1]==='Mr.Kille'));assert.ok(calls.some(c=>c[0]==='character'&&c[1]==='Mr.Handu'));assert.ok(calls.some(c=>c[0]==='background'&&c[1]==='cutout-street-v1'));assert.equal(calls.filter(c=>c[0]==='background').length,35);assert.ok(calls.some(c=>c[0]==='download'&&c[1]==='Hahmopohja.psd'));assert.ok(calls.some(c=>c[0]==='script'));const html=renderToStaticMarkup(view);assert.equal((html.match(/aria-pressed="true"/g)??[]).length,2);assert.ok(html.includes('Valmiina animoitavaksi'));});
test('script panel exposes labelled input, honest speech limitations, plan and protected append action',()=>{const html=renderToStaticMarkup(React.createElement(ScriptPanel,{animation:null,scene:{},disabled:false,apply:()=>{}}));assert.match(html,/<label for="screenplay">/);assert.match(html,/<textarea id="screenplay"/);assert.ok(html.includes('Lisää animaatio aikajanan loppuun'));assert.match(html,/<button class="primary full" disabled="">/);assert.ok(html.includes('ei tuota puheääntä tekstistä'));assert.ok(html.includes('Vilkutus'));});
test('actual light and dark theme text and selected controls meet WCAG AA contrast',()=>{const css=readFileSync(new URL('../style.css',import.meta.url),'utf8'),blocks=[...css.matchAll(/:root(?:\[data-theme=light\])?\{([^}]*--field:[^}]*)\}/g)].map(m=>m[1]);const luminance=hex=>{hex=hex.slice(1);if(hex.length===3)hex=[...hex].map(c=>c+c).join('');const c=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};assert.equal(blocks.length,2);for(const b of blocks){const vars=Object.fromEntries([...b.matchAll(/--([a-z-]+):(#[a-f0-9]+)/g)].map(m=>[m[1],m[2]]));for(const [fg,bg] of [['text','panel'],['text','surface'],['muted','panel'],['muted','surface'],['green','green-bg'],['panel','green']]){const a=luminance(vars[fg]),c=luminance(vars[bg]),ratio=(Math.max(a,c)+.05)/(Math.min(a,c)+.05);assert.ok(ratio>=4.5,`${fg}/${bg}: ${ratio}`);}}});

const {default:ViewMenu}=await import('../components/view-menu.tsx');const {default:PhonePanel}=await import('../components/phone-panel.tsx');
test('view menu offers three keyboard-accessible persistent toggles and always-visible device status and reset without file or device actions',()=>{const states=[],layout={library:true,inspector:true,timeline:false,status:true},view=ViewMenu({layout,update:v=>states.push(v)}),group=view.props.children[1],labels=group.props.children[0];assert.equal(labels.length,3);labels[0].props.children[0].props.onChange({target:{checked:false}});assert.deepEqual(states[0],{...layout,library:false});group.props.children[1].props.onClick();assert.deepEqual(states[1],layout);const html=renderToStaticMarkup(view);assert.ok(html.includes('Näytä'));assert.equal((html.match(/type="checkbox"/g)??[]).length,3);});
test('phone panel provides three original views and exposes placement independently from backgrounds',()=>{const html=renderToStaticMarkup(React.createElement(PhonePanel,{scene:{phone:{view:'back',x:0,y:0,scale:1,rotation:0,anchor:'leftHand'}},disabled:false,update:()=>{}}));for(const label of ['Puhelin edestä','Puhelin takaa','Puhelin sivulta','Hahmon vasen käsi','Näyttämö','Poista puhelin'])assert.ok(html.includes(label));assert.equal((html.match(/aria-pressed="true"/g)??[]).length,1);});

const {default:MovementBar}=await import('../components/movement-bar.tsx');
test('top movement controls expose walk/run, all three directions without duplicate play transport',()=>{const html=renderToStaticMarkup(React.createElement(MovementBar,{disabled:false,playing:false,create:()=>{},play:()=>{}}));for(const label of ['Kävely','Juoksu','Vasemmalle','Kohti katsojaa','Oikealle'])assert.ok(html.includes(label));const busy=renderToStaticMarkup(React.createElement(MovementBar,{disabled:true,playing:true,create:()=>{},play:()=>{}}));assert.ok(!html.includes('>Toista<'));assert.equal((busy.match(/<button[^>]*disabled[^>]*>/g)??[]).length,3);});

test('library selection exposes named character/environment/object categories and hides object editor initially',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Kirjaston sisältö"/);for(const label of ['Hahmot ja esineet','Kuvausympäristöt','Esineet'])assert.ok(html.includes(label));assert.match(html,/<div hidden=""><section class="phone-panel"/);});

const {default:PanelResizer}=await import('../components/panel-resizer.tsx');const {default:AppMenu}=await import('../components/app-menu.tsx');
test('application navigation groups file edit view help actions; source panes remain mounted behind visibility flags',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Sovelluksen valikot"/);for(const label of ['Tiedosto','Muokkaa','Näytä','Ohje','Näytä tuotantokierros uudelleen','Rajaa paneelit valitun työvaiheen mukaan','Nollaa työvaihe ja poista rajat','Keskity näyttämöön','Palauta paneelien koot','Sovita koko näyttämö'])assert.ok(html.includes(label));assert.equal((html.match(/role="separator"/g)??[]).length,3);assert.match(html,/aria-label="Kirjaston leveys"/);assert.match(html,/aria-label="Ominaisuuspaneelin leveys"/);assert.match(html,/aria-label="Aikajanan korkeus"/);assert.ok(!html.includes('class="projectbar"'));const lib=html.indexOf('class="layers-panel'),menuEnd=html.indexOf('</header>');assert.ok(lib>menuEnd);});
test('all three pane dividers expose real dimensions, focus and orientation even before a project is open',()=>{for(const [vertical,label] of [[false,'Kirjaston leveys'],[true,'Aikajanan korkeus']]){const html=renderToStaticMarkup(React.createElement(PanelResizer,{label,value:260,min:120,max:480,vertical,change:()=>{}}));assert.match(html,/role="separator" tabindex="0"/);assert.ok(html.includes('aria-orientation="'+(vertical?'horizontal':'vertical')+'"'));assert.match(html,/aria-valuenow="260"/);assert.match(html,/aria-valuemin="120"/);assert.match(html,/aria-valuemax="480"/);}});
test('disclosure app menus preserve disabled actions and ordinary semantic keyboard controls',()=>{const html=renderToStaticMarkup(React.createElement(AppMenu,{label:'Tiedosto'},React.createElement('button',{disabled:true},'Tallenna')));assert.match(html,/<summary>Tiedosto<\/summary>/);assert.match(html,/role="group" aria-label="Tiedosto"/);assert.match(html,/<button disabled="">Tallenna/);});

const {default:PresentationPanel}=await import('../components/presentation-panel.tsx');
test('dialogue import is integrated with the existing movement script without fake synthesis or enabled missing-resource creation',()=>{const html=renderToStaticMarkup(React.createElement(Editor));for(const label of ['Dialogi ja leikkaukset','Yhden hahmon liikkeet','Dialogikäsikirjoitus','Tuo UTF-8-teksti','Lataa KILSAT-esimerkki','Uusi kohtaus'])assert.ok(html.includes(label));const empty=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920},disabled:false,apply:()=>{}}));assert.ok(empty.includes('Jaa kohtauksiin'));assert.match(empty,/class="primary full"[^>]*disabled=""[^>]*>Jaa kohtauksiin/);});

test('general episode review exposes requirement categories and blocks creation without resources',async()=>{const {parsePresentation}=await import('../lib/presentation-parser.ts');const p=parsePresentation('Title: Tervehdys\nPituus: 5–10 s\nHahmo VERA: rauhallinen.\nMiljöö: metsä\nVERA: “Hei.”\nVera vilkuttaa 2 s.');const html=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920,presentationDraft:p},disabled:false,apply:()=>{}}));for(const label of ['Jakson ohjaussuunnitelma','Tarkoitus','Hahmojen luonne ja suhteet','Miljöö','Rekvisiitta','Sijoittelu','Dialogi ja ääni','Toiminta','Katseet','Ilmeet','Kesto ja tauot','Kiellot ja rajoitukset','Rajaukset ja leikkaukset','Lopetus','Hyväksyn tämän arvion','Lataa toinen esimerkki'])assert.ok(html.includes(label),label);assert.match(html,/<button class="primary full" disabled="">Rakenna muokattava jakso/);assert.ok(html.includes('metsä'));assert.ok(html.includes('puuttuu'));});

test('voice acting, mouth source choice, richer cast and depth camera controls are real accessible markup',async()=>{
 const p=await readProject(new Blob([readFileSync(new URL('../public/library/Roni-Studio.hahmo',import.meta.url))]));const noop=()=>{},quick=renderToStaticMarkup(React.createElement(QuickPanel,{profile:p.doc.quick,animation:p.animation,scene:p.scene,active:true,enabled:true,stopRequest:0,status:noop,live:noop,apply:noop,update:noop,activity:noop,setScene:noop,play:noop,save:noop,video:noop}));assert.ok(quick.includes('Suun ohjaus'));assert.ok(quick.includes('Tallenna ääni ja esitys'));const {default:ScenePanel}=await import('../components/scene-panel.tsx');const scene=renderToStaticMarkup(React.createElement(ScenePanel,{scene:p.scene,doc:p.doc,disabled:false,update:noop}));assert.ok(scene.includes('Käytä 3D-paperihahmoa'));assert.ok(scene.includes('Kamera vasemmalle / oikealle'));const {default:PresentationPanel}=await import('../components/presentation-panel.tsx'),{parsePresentation}=await import('../lib/presentation-parser.ts');const model=parsePresentation('Title: Testi\nHahmo MIRA: rauhallinen.\nMIRA: Hei!');const html=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:p.doc,animation:p.animation,scene:{...p.scene,presentationDraft:model},disabled:false,apply:noop}));assert.ok(html.includes('Ääninäyttelijän työpiste'));assert.ok(html.includes('Äänitä repliikki omalla äänellä'));assert.ok(html.includes('Valitse Studio-hahmot kaikille puhujille'));
});

test('production validation exposes accessible search and next target navigation without browser testing',async()=>{const {default:Panel}=await import('../components/production-validation-panel.tsx');const {parsePresentation}=await import('../lib/presentation-parser.ts');const p=parsePresentation('KILLE:\n“Hello.”');p.diagnostics=[{code:'global',severity:'error',message:'Tarkista projekti'}];const html=renderToStaticMarkup(React.createElement(Panel,{presentation:p,disabled:true,navigate:()=>{}}));assert.ok(html.includes('Hae tarkistusilmoitus'));assert.ok(html.includes('Avaa seuraava ongelman tapahtuma'));assert.match(html,/<button disabled="">Avaa seuraava/);assert.ok(html.includes('Koskee koko valmistelua'));assert.ok(html.includes('role="status"'));});

test('studio flow nav exposes tour targets and Finnish tour copy is defined',async()=>{const {default:StudioFlowNav}=await import('../components/studio-flow-nav.tsx');const {default:StudioFlowTabs}=await import('../components/studio-flow-tabs.tsx');const {flowTourSteps}=await import('../lib/studio-flow-tour.ts');const nav=renderToStaticMarkup(React.createElement(StudioFlowNav,{active:'script',onSelect:()=>{}}));const tabs=renderToStaticMarkup(React.createElement(StudioFlowTabs,{active:'script',onSelect:()=>{}}));assert.ok(nav.includes('data-studio-flow-step="characters"'));assert.ok(tabs.includes('studio-flow-tabs'));assert.ok(tabs.includes('>01</span'));assert.ok(tabs.includes('>05</span'));assert.equal(flowTourSteps[1].title,'Tästä luot hahmon');assert.ok(flowTourSteps.every(s=>s.title&&s.body));});
test('presentation panel shows script lock notice when source is locked',async()=>{const {default:PresentationPanel}=await import('../components/presentation-panel.tsx');const html=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920},disabled:false,scriptSourceLocked:true,apply:()=>{}}));assert.ok(html.includes('flow-script-lock'));assert.ok(html.includes('Käsikirjoitusteksti on lukittu'));});

test('speaker binding table renders Finnish column headers',async()=>{const {default:SpeakerBindingTable}=await import('../components/speaker-binding-table.tsx');const {parsePresentation}=await import('../lib/presentation-parser.ts');const {initProduction}=await import('../lib/production-model.ts');const {studioMetadata}=await import('../lib/studio/domain.ts');const model=parsePresentation('Hahmo MIRA: x.\nMIRA: "Hei."');model.production=initProduction(model);model.production.studio={...studioMetadata(model),speakerHandles:{mira:'MIRA'}};model.bindings=[{speaker:'MIRA',asset:'pack-a',voice:'v',side:'left',functions:{}}];const html=renderToStaticMarkup(React.createElement(SpeakerBindingTable,{model,assets:{'pack-a':{doc:{name:'Roni.psd'},animation:{}}}}));assert.ok(html.includes('speaker-binding-table'));assert.ok(html.includes('@mira'));assert.ok(html.includes('Puhuja'));});

test('speaker binding table shows pack select when handler is provided',async()=>{const {default:SpeakerBindingTable}=await import('../components/speaker-binding-table.tsx');const {parsePresentation}=await import('../lib/presentation-parser.ts');const {initProduction}=await import('../lib/production-model.ts');const model=parsePresentation('Hahmo KILLE: x.\nKILLE: "Hei."');model.production=initProduction(model);model.bindings=[];const html=renderToStaticMarkup(React.createElement(SpeakerBindingTable,{model,assets:{},onSelectPack:()=>{}}));assert.ok(html.includes('Valitse .hahmo'));assert.ok(html.includes('Kille-Oma'));});

test('presentation panel focus layout hides step nav in markup class',async()=>{const React=await import('react');const {default:PresentationPanel}=await import('../components/presentation-panel.tsx');const html=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920},disabled:false,scriptLayout:'focus',apply:()=>{}}));assert.ok(html.includes('script-panel--focus'));});

test('script reparse confirm dialog component renders Finnish actions',async()=>{const React=await import('react');const {default:ScriptReparseConfirm}=await import('../components/script-reparse-confirm.tsx');const html=renderToStaticMarkup(React.createElement(ScriptReparseConfirm,{open:true,message:'1 hyväksyttyä kuvaa palautuu luonnokseksi.',onCancel:()=>{},onConfirm:()=>{}}));assert.ok(html.includes('Jaetaanko kohtauksiin uudelleen'));assert.ok(html.includes('Jaa kohtauksiin uudelleen'));});

test('studio component layer defines canonical button tab and focus tokens',()=>{const css=readFileSync(new URL('../styles/studio-components.css',import.meta.url),'utf8');assert.match(css,/\.studio \.primary[\s\S]*border:\s*none/);assert.match(css,/\.studio \.ghost-btn/);assert.match(css,/\.studio \.library-tabs button/);assert.match(css,/\.studio \.inspector-tabs button/);assert.match(css,/--focus-ring/);assert.match(css,/selection-inspector/);});
test('studio component layer defines timeline token overrides',()=>{const css=readFileSync(new URL('../styles/studio-components.css',import.meta.url),'utf8');const tokens=readFileSync(new URL('../styles/tokens.css',import.meta.url),'utf8');assert.match(tokens,/--timeline-bg/);assert.match(css,/\.studio \.timeline input:not\(\[type='range'\]\)/);assert.match(css,/var\(--timeline-track-active-bg\)/);});
test('legacy style.css omits trimmed studio primary and tab overrides',()=>{const css=readFileSync(new URL('../style.css',import.meta.url),'utf8');assert.ok(!css.includes('.studio .primary{background:var(--green)'));assert.ok(!css.includes('.studio .inspector-tabs button[aria-pressed=true]{font-weight:700;border-bottom:3px solid var(--green)}'));assert.ok(css.includes('studio-components.css (0.47)'));});
test('editor exposes selection-inspector layout class on Valinta pane',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.ok(html.includes('selection-inspector'));assert.ok(html.includes('Valitun tason tiedot')||html.includes('Valinta ja nivelet'));});
test('script compose editor is shared markup with dialogue field and parse action',async()=>{const React=await import('react');const {default:ScriptComposeEditor}=await import('../components/script-compose-editor.tsx');const html=renderToStaticMarkup(React.createElement(ScriptComposeEditor,{text:'',scriptLocked:false,scriptLayout:'panel',message:'',error:'',working:false,parseDisabled:true,onTextChange:()=>{},onAbort:()=>{},onRequestParse:()=>{},onInsertGuide:()=>{}}));assert.ok(html.includes('script-compose-editor'));assert.ok(html.includes('id="dialogue-script"'));assert.ok(html.includes('Jaa kohtauksiin'));});
test('script compose hero writes one line per row while keeping a single source string',async()=>{const React=await import('react');const {default:ScriptComposeEditor}=await import('../components/script-compose-editor.tsx');const html=renderToStaticMarkup(React.createElement(ScriptComposeEditor,{text:'Kohtaus: Keittiö\nMikko: "Hei"',scriptLocked:false,scriptLayout:'focus',variant:'hero',toolsHidden:true,message:'',error:'',working:false,parseDisabled:false,onTextChange:()=>{},onAbort:()=>{},onRequestParse:()=>{},onInsertGuide:()=>{}}));assert.ok(html.includes('script-line-sheet'));assert.ok(html.includes('script-line-row'));assert.ok(html.includes('Jaa kohtauksiin'));assert.equal((html.match(/script-line-field/g)||[]).length,2);});
test('script compose hero empty state exposes primary example action',async()=>{const React=await import('react');const {default:ScriptComposeEditor}=await import('../components/script-compose-editor.tsx');const html=renderToStaticMarkup(React.createElement(ScriptComposeEditor,{text:'',scriptLocked:false,scriptLayout:'panel',variant:'hero',toolsHidden:true,message:'',error:'',working:false,parseDisabled:true,onTextChange:()=>{},onAbort:()=>{},onRequestParse:()=>{},onInsertGuide:()=>{},onTryExample:()=>{}}));assert.ok(html.includes('Kokeile esimerkkiä'));assert.ok(html.includes('Vedä käsikirjoitus tähän'));assert.ok(html.includes('script-empty-drop'));});
test('editor exposes script hero center host when flow is script step',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.ok(html.includes('script-center-host'));});
test('shot timeline strip renders domain shots on a horizontal rail',async()=>{const {default:ShotTimelineStrip}=await import('../components/shot-timeline-strip.tsx');const {buildStudioExample}=await import('../lib/studio-example.ts');const {createScene}=await import('../lib/scene-model.ts');const {readProject}=await import('../lib/project-file.ts');const kille=await readProject(new Blob([readFileSync(new URL('../public/library/Kille-Oma.hahmo',import.meta.url))]));const handu=await readProject(new Blob([readFileSync(new URL('../public/library/Handu-Oma.hahmo',import.meta.url))]));const built=buildStudioExample({kille:{doc:kille.doc,animation:kille.animation},handu:{doc:handu.doc,animation:handu.animation}},createScene({width:1080,height:1920}));const compiled=built.scene.presentations[0];const html=renderToStaticMarkup(React.createElement(ShotTimelineStrip,{presentation:compiled,fps:24,frame:48,disabled:false,onChoose:()=>{}}));assert.ok(html.includes('aria-label="Jakson kuvat aikajanalla"'));assert.ok(html.includes('shot-timeline-strip'));assert.ok((html.match(/class="active"/g)??[]).length<=1);});
