// React markup and event contracts tested in Node, without a browser or device access.
import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {readFileSync,existsSync} from 'node:fs';import {fileURLToPath} from 'node:url';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
const root=new URL('../',import.meta.url);
registerHooks({
 resolve(specifier,context,next){
  const resolveFile=(url)=>{for(const suffix of ['', '.ts','.tsx']){const candidate=url+suffix;if(existsSync(fileURLToPath(candidate)))return {url:candidate,shortCircuit:true};}};
  if(specifier.startsWith('@/')){const file=resolveFile(new URL(specifier.slice(2),root).href);if(file)return file;}
  if(specifier.startsWith('.')&&context.parentURL?.startsWith(root.href)&&!context.parentURL.includes('/node_modules/')){const file=resolveFile(new URL(specifier,context.parentURL).href);if(file)return file;}
  return next(specifier,context);
 },
 load(url,context,next){if(url.startsWith(root.href)&&!url.includes('/node_modules/')&&/\.tsx?$/.test(url)){
  const source=readFileSync(fileURLToPath(url),'utf8').replaceAll('import.meta.env',"({BASE_URL:'/',VITE_PRIVATE_SERVER:'true'})");
  return {format:'module',source:ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText,shortCircuit:true};
 }return next(url,context);}
});
const {default:Editor}=await import('../components/editor.tsx');const {default:WorkspaceTabs}=await import('../components/workspace-tabs.tsx');const {default:QuickPanel}=await import('../components/quick-panel.tsx');const {default:CameraPanel}=await import('../components/camera-panel.tsx');const {readProject}=await import('../lib/project-file.ts');
test('editor starts with three accessible workspaces, independent device status and distinct file actions',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Työtila"/);for(const label of ['Hahmo','Esitys','Animointi','Tallenna projekti','Vie MP4','Avaa tallennettu projekti','Ulkoasu','Mikrofoni:','Kamera:'])assert.ok(html.includes(label),label);assert.equal((html.match(/aria-pressed="true"/g)??[]).length>=1,true);assert.match(html,/class="studio workspace-performance"/);});
test('workspace navigation stays operable with recording active and only invokes a view transition',()=>{for(const workspace of ['character','performance','animation']){const chosen=[];const nav=WorkspaceTabs({workspace,change:v=>chosen.push(v)});const buttons=nav.props.children;assert.equal(buttons.length,3);assert.equal(buttons.filter(b=>b.props['aria-pressed']).length,1);for(const b of buttons){assert.equal(b.props.disabled,undefined);b.props.onClick();}assert.deepEqual(chosen,['character','performance','animation']);}});
test('ready character controls expose independent microphone and keyboard toggles; busy transport blocks recording',async()=>{const p=await readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));const noop=()=>{};const html=renderToStaticMarkup(React.createElement(QuickPanel,{profile:p.doc.quick,animation:p.animation,scene:p.scene,active:true,enabled:false,stopRequest:0,status:noop,live:noop,apply:noop,update:noop,activity:noop,setScene:noop,play:noop,save:noop,video:noop}));assert.match(html,/type="checkbox"[^>]*checked/);assert.match(html,/Käynnistä mikrofoni/);assert.match(html,/<button class="primary full" disabled="">Tallenna uusi otto/);assert.ok(html.includes('Kamera ja näppäimet voivat toimia samanaikaisesti'));});
test('camera ready-template defaults include head and pupils, combined recording uses one main take',async()=>{const p=await readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));const {flatten}=await import('../lib/psd-model.ts');const noop=()=>{};const html=renderToStaticMarkup(React.createElement(CameraPanel,{defaults:p.doc.quick.roles,rig:p.animation.rig,combined:true,nodes:flatten(p.doc.layers),width:p.doc.width,height:p.doc.height,fps:24,duration:24,frame:0,disabled:false,live:noop,record:noop,active:noop}));assert.ok(html.includes('Tallenna yhteinen otto yllä'));assert.ok(html.includes('playsInline=""'));assert.equal((html.match(/selected=""/g)??[]).length,4);});

const {default:AssetLibrary}=await import('../components/asset-library.tsx');const {default:ScriptPanel}=await import('../components/script-panel.tsx');
test('library has real character, angle and download actions with accessible selected states',()=>{const calls=[],view=AssetLibrary({disabled:false,current:'Aino.psd',design:'car-driver-v1',open:v=>calls.push(['character',v]),background:v=>calls.push(['background',v]),script:()=>calls.push(['script']),download:v=>calls.push(['download',v])});const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return;}if(typeof node!=='object')return;if(node.type==='button'&&!node.props.disabled)node.props.onClick();visit(node.props?.children);};visit(view);assert.ok(calls.some(c=>c[0]==='character'&&c[1]==='Leo'));assert.equal(calls.filter(c=>c[0]==='background').length,6);assert.ok(calls.some(c=>c[0]==='download'&&c[1]==='Hahmopohja.psd'));assert.ok(calls.some(c=>c[0]==='script'));const html=renderToStaticMarkup(view);assert.equal((html.match(/aria-pressed="true"/g)??[]).length,2);assert.ok(html.includes('Valmiina animoitavaksi'));});
test('script panel exposes labelled input, honest speech limitations, plan and protected append action',()=>{const html=renderToStaticMarkup(React.createElement(ScriptPanel,{animation:null,scene:{},disabled:false,apply:()=>{}}));assert.match(html,/<label for="screenplay">/);assert.match(html,/<textarea id="screenplay"/);assert.ok(html.includes('Lisää animaatio aikajanan loppuun'));assert.match(html,/<button class="primary full" disabled="">/);assert.ok(html.includes('ei tuota puheääntä tekstistä'));assert.ok(html.includes('Vilkutus'));});
test('actual light and dark theme text and selected controls meet WCAG AA contrast',()=>{const css=readFileSync(new URL('../style.css',import.meta.url),'utf8'),blocks=[...css.matchAll(/:root(?:\[data-theme=light\])?\{([^}]*--field:[^}]*)\}/g)].map(m=>m[1]);const luminance=hex=>{hex=hex.slice(1);if(hex.length===3)hex=[...hex].map(c=>c+c).join('');const c=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};assert.equal(blocks.length,2);for(const b of blocks){const vars=Object.fromEntries([...b.matchAll(/--([a-z-]+):(#[a-f0-9]+)/g)].map(m=>[m[1],m[2]]));for(const [fg,bg] of [['text','panel'],['text','surface'],['muted','panel'],['muted','surface'],['green','green-bg'],['panel','green']]){const a=luminance(vars[fg]),c=luminance(vars[bg]),ratio=(Math.max(a,c)+.05)/(Math.min(a,c)+.05);assert.ok(ratio>=4.5,`${fg}/${bg}: ${ratio}`);}}});

const {default:ViewMenu}=await import('../components/view-menu.tsx');const {default:PhonePanel}=await import('../components/phone-panel.tsx');
test('view menu offers four keyboard-accessible persistent toggles and reset without file or device actions',()=>{const states=[],layout={library:true,inspector:true,timeline:false,status:true},view=ViewMenu({layout,update:v=>states.push(v)}),group=view.props.children[1],labels=group.props.children[0];assert.equal(labels.length,4);labels[0].props.children[0].props.onChange({target:{checked:false}});assert.deepEqual(states[0],{...layout,library:false});group.props.children[1].props.onClick();assert.deepEqual(states[1],layout);const html=renderToStaticMarkup(view);assert.ok(html.includes('Näytä'));assert.equal((html.match(/type="checkbox"/g)??[]).length,4);});
test('phone panel provides three original views and exposes placement independently from backgrounds',()=>{const html=renderToStaticMarkup(React.createElement(PhonePanel,{scene:{phone:{view:'back',x:0,y:0,scale:1,rotation:0,anchor:'leftHand'}},disabled:false,update:()=>{}}));for(const label of ['Puhelin edestä','Puhelin takaa','Puhelin sivulta','Hahmon vasen käsi','Näyttämö','Poista puhelin'])assert.ok(html.includes(label));assert.equal((html.match(/aria-pressed="true"/g)??[]).length,1);});

const {default:MovementBar}=await import('../components/movement-bar.tsx');
test('top movement controls expose walk/run, all three directions and independent play transport',()=>{const html=renderToStaticMarkup(React.createElement(MovementBar,{disabled:false,playing:false,create:()=>{},play:()=>{}}));for(const label of ['Kävely','Juoksu','Vasemmalle','Kohti katsojaa','Oikealle','Toista'])assert.ok(html.includes(label));const busy=renderToStaticMarkup(React.createElement(MovementBar,{disabled:true,playing:true,create:()=>{},play:()=>{}}));assert.match(busy,/<button class="primary">Pysäytä/);assert.equal((busy.match(/class="secondary" disabled/g)??[]).length,3);});

test('library selection exposes named character/environment/object categories and hides object editor initially',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Kirjaston sisältö"/);for(const label of ['Hahmot ja esineet','Kuvausympäristöt','Esineet'])assert.ok(html.includes(label));assert.match(html,/<div hidden=""><section class="phone-panel"/);});

const {default:PanelResizer}=await import('../components/panel-resizer.tsx');const {default:AppMenu}=await import('../components/app-menu.tsx');
test('application navigation groups file edit view help actions; source panes remain mounted behind visibility flags',()=>{const html=renderToStaticMarkup(React.createElement(Editor));assert.match(html,/aria-label="Sovelluksen valikot"/);for(const label of ['Tiedosto','Muokkaa','Näytä','Ohje','Keskity näyttämöön','Palauta paneelien koot','Sovita koko näyttämö'])assert.ok(html.includes(label));assert.equal((html.match(/role="separator"/g)??[]).length,3);assert.match(html,/aria-label="Kirjaston leveys"/);assert.match(html,/aria-label="Ominaisuuspaneelin leveys"/);assert.match(html,/aria-label="Aikajanan korkeus"/);assert.ok(!html.includes('class="projectbar"'));const lib=html.indexOf('class="layers-panel"'),menuEnd=html.indexOf('</header>');assert.ok(lib>menuEnd);});
test('all three pane dividers expose real dimensions, focus and orientation even before a project is open',()=>{for(const [vertical,label] of [[false,'Kirjaston leveys'],[true,'Aikajanan korkeus']]){const html=renderToStaticMarkup(React.createElement(PanelResizer,{label,value:260,min:120,max:480,vertical,change:()=>{}}));assert.match(html,/role="separator" tabindex="0"/);assert.ok(html.includes('aria-orientation="'+(vertical?'horizontal':'vertical')+'"'));assert.match(html,/aria-valuenow="260"/);assert.match(html,/aria-valuemin="120"/);assert.match(html,/aria-valuemax="480"/);}});
test('disclosure app menus preserve disabled actions and ordinary semantic keyboard controls',()=>{const html=renderToStaticMarkup(React.createElement(AppMenu,{label:'Tiedosto'},React.createElement('button',{disabled:true},'Tallenna')));assert.match(html,/<summary>Tiedosto<\/summary>/);assert.match(html,/role="group" aria-label="Tiedosto"/);assert.match(html,/<button disabled="">Tallenna/);});

const {default:PresentationPanel}=await import('../components/presentation-panel.tsx');
test('dialogue import is integrated with the existing movement script without fake synthesis or enabled missing-resource creation',()=>{const html=renderToStaticMarkup(React.createElement(Editor));for(const label of ['Dialogi ja leikkaukset','Yhden hahmon liikkeet','Dialogikäsikirjoitus','Tuo UTF-8-teksti','Lataa KILSAT-esimerkki','Uusi kohtaus'])assert.ok(html.includes(label));const empty=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920},disabled:false,apply:()=>{}}));assert.ok(empty.includes('Tunnista ja tarkista käsikirjoitus'));assert.match(empty,/<button class="primary full" disabled="">Tunnista/);});

test('general episode review exposes requirement categories and blocks creation without resources',async()=>{const {parsePresentation}=await import('../lib/presentation-parser.ts');const p=parsePresentation('Title: Tervehdys\nPituus: 5–10 s\nHahmo VERA: rauhallinen.\nMiljöö: metsä\nVERA: “Hei.”\nVera vilkuttaa 2 s.');const html=renderToStaticMarkup(React.createElement(PresentationPanel,{doc:null,animation:null,scene:{width:1080,height:1920,presentationDraft:p},disabled:false,apply:()=>{}}));for(const label of ['Jakson ohjaussuunnitelma','Tarkoitus','Hahmojen luonne ja suhteet','Miljöö','Rekvisiitta','Sijoittelu','Dialogi ja ääni','Toiminta','Katseet','Ilmeet','Kesto ja tauot','Kiellot ja rajoitukset','Rajaukset ja leikkaukset','Lopetus','Hyväksyn tämän arvion','Lataa toinen esimerkki'])assert.ok(html.includes(label),label);assert.match(html,/<button class="primary full" disabled="">Rakenna muokattava jakso/);assert.ok(html.includes('metsä'));assert.ok(html.includes('puuttuu'));});
