import test from 'node:test';import assert from 'node:assert/strict';
import {retargetChains,solveChain,type RetargetChain} from './studio/chain-retarget.ts';
import {createAnimation,putKeyframe,neutral} from './animation-model.ts';import {createRig,type Rig} from './rig-model.ts';import type {PsdDocument} from './psd-model.ts';import {animationTransforms} from './animation-transform.ts';
function rig(name:string,positions:number[]){const keys=['root',...positions.map((_,i)=>name+i),'end'];const doc:PsdDocument={name,width:500,height:500,size:0,warnings:[],layers:keys.map(key=>({key,name:key,path:key,kind:'layer',left:0,top:0,width:5,height:5,opacity:1,visible:true,blendMode:'normal',children:[],warnings:[]}))};const rig=createRig(doc);rig.parts[0].role='body';rig.parts[0].pivot={x:0,y:0};positions.forEach((x,i)=>{const p=rig.parts[i+1];p.pivot={x,y:100};p.role='arm';p.parentKey=i?name+(i-1):'root';});rig.parts.at(-1)!.pivot={x:200,y:100};rig.parts.at(-1)!.role='hand';rig.parts.at(-1)!.parentKey=name+(positions.length-1);return{rig,doc};}
function endpoint(a:ReturnType<typeof createAnimation>,frame:number){const p=a.rig.parts.at(-1)!.pivot,t=animationTransforms(a,frame).get('end')!;return{x:t.a*p.x+t.c*p.y+t.e,y:t.b*p.x+t.d*p.y+t.f};}
test('unequal two-to-three bone IK reaches same endpoint without changing source or target anatomy',()=>{const a=rig('source',[100,150]),b=rig('target',[100,130,170]);let source=createAnimation(a.rig);source={...source,duration:12};source=putKeyframe(source,'source0',{...neutral,rotation:30,frame:0,easing:'hold'});source=putKeyframe(source,'source1',{...neutral,rotation:-50,frame:0,easing:'hold'});const chain:RetargetChain={id:'arm',source:['source0','source1'],target:['target0','target1','target2'],sourceEnd:a.rig.parts.at(-1)!.pivot,targetEnd:b.rig.parts.at(-1)!.pivot,sourceEndKey:'end',targetEndKey:'end'};const out=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'ik',chains:[chain]});const x=endpoint(source,0),y=endpoint(out.animation,0);assert.ok(Math.hypot(x.x-y.x,x.y-y.y)<.01,JSON.stringify({x,y}));assert.deepEqual(out.animation.rig.parts.map(p=>p.pivot),b.rig.parts.map(p=>p.pivot));assert.equal(source.tracks.length,2);assert.equal(out.animation.tracks.find(t=>t.key==='target2')!.frames.length,12);});
test('moving root is compensated for a locked hand contact and orientation',()=>{const a=rig('source',[100,150]),b=rig('target',[100,130,170]);let source={...createAnimation(a.rig),duration:12};source=putKeyframe(source,'root',{...neutral,x:0,frame:0,easing:'linear'});source=putKeyframe(source,'root',{...neutral,x:12,frame:11,easing:'linear'});const chain:RetargetChain={id:'hand',source:['source0','source1'],target:['target0','target1','target2'],sourceEnd:{x:200,y:100},targetEnd:{x:200,y:100},sourceEndKey:'end',targetEndKey:'end'};const out=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'ik',chains:[chain],contacts:[{chainId:'hand',start:0,end:11,point:{x:175,y:120},rotation:0}]});for(let f=0;f<12;f++){const p=endpoint(out.animation,f);assert.ok(Math.hypot(p.x-175,p.y-120)<.02,JSON.stringify({f,p}));const t=animationTransforms(out.animation,f).get('end')!;assert.ok(Math.abs(Math.atan2(t.b,t.a))<1e-6);}assert.equal(out.diagnostics.length,0);});
test('FK split/merge and partial IK blend are deterministic and unreachable contacts are diagnosed',()=>{const a=rig('source',[100,150]),b=rig('target',[100,130,170]),source={...createAnimation(a.rig),duration:4},chain:RetargetChain={id:'arm',source:['source0','source1'],target:['target0','target1','target2'],sourceEnd:{x:200,y:100},targetEnd:{x:200,y:100},sourceEndKey:'end',targetEndKey:'end'};const opts={mode:'ik' as const,chains:[chain],ikWeight:.5,contacts:[{chainId:'arm',start:0,end:3,point:{x:490,y:490}}]};const a1=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},opts),a2=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},opts);assert.deepEqual(a1,a2);assert.ok(a1.diagnostics.some(d=>d.kind==='contact'));assert.ok(retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'fk',chains:[chain]}).animation.tracks.length>=3);assert.throws(()=>retargetChains({...source,duration:72000},b.rig,b.doc,{root:'root',end:'end'},{mode:'ik',chains:[chain]}),/10 000/);});
test('FABRIK preserves bone lengths and finite results for pole directions and unreachable target',()=>{for(const bend of [1,-1] as const){const r=solveChain({x:0,y:0},{x:70,y:20},[30,30,30],[{x:0,y:0},{x:30,y:0},{x:60,y:0},{x:90,y:0}],bend);r.points.slice(1).forEach((p,i)=>assert.ok(Math.abs(Math.hypot(p.x-r.points[i].x,p.y-r.points[i].y)-30)<1e-5));assert.ok(r.error<.01);}assert.ok(solveChain({x:0,y:0},{x:300,y:0},[30,30,30],[{x:0,y:0},{x:30,y:0},{x:60,y:0},{x:90,y:0}]).error>200);});

test('FK respects rotation limits and cannot silently promise IK-only contacts',()=>{const a=rig('source',[100,150]),b=rig('target',[100,130,170]);let source={...createAnimation(a.rig),duration:4};source=putKeyframe(source,'source0',{...neutral,rotation:30,frame:0,easing:'hold'});const chain:RetargetChain={id:'arm',source:['source0','source1'],target:['target0','target1','target2'],sourceEnd:{x:200,y:100},targetEnd:{x:200,y:100},sourceEndKey:'end',targetEndKey:'end'},out=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'fk',chains:[chain],limits:{target0:{min:0,max:0}}});assert.equal(out.animation.tracks.find(t=>t.key==='target0')!.frames[0].rotation,0);assert.ok(out.diagnostics.some(d=>d.kind==='constraint'));assert.throws(()=>retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'fk',chains:[chain],autoContacts:true}),/IK-osuuden/);});

test('root scale and rotation are applied once during unequal-chain IK retarget',()=>{const a=rig('source',[100,150]),b=rig('target',[100,130,170]);let source={...createAnimation(a.rig),duration:4};source=putKeyframe(source,'root',{...neutral,scale:1.5,rotation:15,frame:0,easing:'hold'});source=putKeyframe(source,'source0',{...neutral,rotation:30,frame:0,easing:'hold'});source=putKeyframe(source,'source1',{...neutral,rotation:-50,frame:0,easing:'hold'});const chain:RetargetChain={id:'arm',source:['source0','source1'],target:['target0','target1','target2'],sourceEnd:{x:200,y:100},targetEnd:{x:200,y:100},sourceEndKey:'end',targetEndKey:'end'},out=retargetChains(source,b.rig,b.doc,{root:'root',end:'end'},{mode:'ik',chains:[chain]}),expected=endpoint(source,0),actual=endpoint(out.animation,0);assert.ok(Math.hypot(expected.x-actual.x,expected.y-actual.y)<.02,JSON.stringify({expected,actual}));assert.equal(out.diagnostics.length,0);});
