import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {exampleScreenplay} from './example-screenplay.ts';import {parseScreenplay,buildScreenplay} from './screenplay.ts';import {readProject,saveProject} from './project-file.ts';import {resizeSceneContent} from './scene-resize.ts';import {sampleTrack} from './animation-model.ts';
test('one-click example builds real animated tracks from the bundled Aino pack and survives saving',async()=>{
 const p=await readProject(new Blob([readFileSync(new URL('../public/library/Aino-Monikulma.hahmo',import.meta.url))]));const base={...p.animation,duration:2,tracks:[]};const out=buildScreenplay(base,p.doc.quick!,p.scene,parseScreenplay(exampleScreenplay));assert.equal(out.start,2);assert.ok(out.animation.duration>200);assert.equal(out.scene.cuts?.length,3);assert.ok(out.animation.tracks.some(t=>t.frames.some(f=>sampleTrack(t,f.frame).rotation!==0)));assert.deepEqual(base.tracks,[]);const restored=await readProject(await saveProject(p.doc,out.animation,undefined,out.scene));assert.deepEqual(restored.animation,out.animation);assert.equal(restored.scene.screenplay,exampleScreenplay);
});
test('stage resizing changes output content, preserves placement, cues and source data, and clamps safely',async()=>{
 const p=await readProject(new Blob([readFileSync(new URL('../public/library/Aino.hahmo',import.meta.url))]));const original=structuredClone(p.scene),larger=resizeSceneContent(p.scene,1.1),restored=resizeSceneContent(larger,1/1.1);assert.equal(larger.scale,p.scene.scale*1.1);assert.equal(larger.x,p.scene.x);assert.equal(larger.y,p.scene.y);assert.deepEqual(p.scene,original);assert.ok(Math.abs(restored.scale-p.scene.scale)<1e-9);assert.equal(resizeSceneContent({...p.scene,scale:99},2).scale,100);for(const factor of [0,-1,NaN,Infinity])assert.throws(()=>resizeSceneContent(p.scene,factor));const saved=await readProject(await saveProject(p.doc,p.animation,undefined,larger));assert.equal(saved.scene.scale,larger.scale);
});

test('resizing dialogue actors preserves direction and timing and persists explicit sizes',async()=>{
 const {parsePresentation}=await import('./presentation-parser.ts');const {functions}=await import('./presentation-model.ts');const {stageActor}=await import('./presentation-stage.ts');
 const p=await readProject(new Blob([readFileSync(new URL('../public/library/Aino.hahmo',import.meta.url))]));const model=parsePresentation('Title: Testi\nHahmo MIRA: rauhallinen.\nMira vilkuttaa 2 s.');model.bindings=[{speaker:'MIRA',asset:'Aino',voice:'Oma ääni',side:'left',functions:Object.fromEntries(functions.map(f=>[f,'supported']))}];const scene={...p.scene,presentations:[model],presentationDraft:model};const before=structuredClone(scene),next=resizeSceneContent(scene,1.2);assert.ok(Math.abs(stageActor(next.presentations![0],next.presentations![0].bindings[0],0).scale/stageActor(model,model.bindings[0],0).scale-1.2)<1e-9);assert.deepEqual(next.presentations![0].events,model.events);assert.deepEqual(scene,before);assert.equal(next.presentationDraft!.bindings[0].scale,next.presentations![0].bindings[0].scale);const roundtrip=await readProject(await saveProject({...p.doc,presentationAssets:{Aino:{doc:p.doc,animation:p.animation}}},p.animation,undefined,next));assert.equal(roundtrip.scene.presentations![0].bindings[0].scale,next.presentations![0].bindings[0].scale);
});
