import {test} from 'node:test';import assert from 'node:assert/strict';import {faceSample,headPose,attachedHeadPose} from './face-motion.ts';
test('face pose calibration handles mirrored translation, roll, scale and invalid detections',()=>{assert.equal(faceSample([],[]),undefined);const b={x:.5,y:.5,width:.2,roll:0,blinkLeft:0,blinkRight:0,jaw:0};const p=headPose({...b,x:.6,y:.6,width:.3,roll:Math.PI/6},b,400,300);assert.ok(Math.abs(p.x+60)<1e-6);assert.ok(Math.abs(p.y-45)<1e-6);assert.ok(Math.abs(p.rotation+30)<1e-6);assert.ok(Math.abs(p.scale-1.5)<1e-6);});

test('attached camera head cannot translate or scale away from neck; independent head remains compatible',()=>{const p={x:400,y:600,rotation:60,scale:2,opacity:1};assert.deepEqual(attachedHeadPose(p,true),{x:0,y:0,rotation:25,scale:1,opacity:1});assert.deepEqual(attachedHeadPose(p,false),p);assert.equal(p.x,400);});

test('body translation and attached live head rotation keep the world-space neck together',async()=>{const {animationTransforms}=await import('./animation-transform.ts'),{readProject}=await import('./project-file.ts'),{readFileSync}=await import('node:fs');const p=await readProject(new Blob([readFileSync(new URL('../public/library/Ukko.hahmo',import.meta.url))])),q=p.doc.quick!,head=p.animation.rig.parts.find(p=>p.key===q.roles.head)!,headPose=attachedHeadPose({x:450,y:600,rotation:60,scale:2,opacity:1},true),poses={[q.roles.head]:headPose,[q.roles.root]:{x:125,y:-72,rotation:9,scale:1.2,opacity:1}},transforms=animationTransforms(p.animation,0,{key:q.roles.head,pose:headPose,poses}),point=(t:import('./animation-transform.ts').Transform)=>({x:t.a*head.pivot.x+t.c*head.pivot.y+t.e,y:t.b*head.pivot.x+t.d*head.pivot.y+t.f}),neck=point(transforms.get(q.roles.head)!),body=point(transforms.get(q.roles.root)!);assert.ok(Math.abs(neck.x-body.x)<1e-9);assert.ok(Math.abs(neck.y-body.y)<1e-9);});

test('sustained camera jaw and closed eyes stay active for seconds; reopening restores lids, mouth and expression',async()=>{
 const {facePoses,initialFaceFilter}=await import('./face-motion.ts'),{readProject}=await import('./project-file.ts'),{readFileSync}=await import('node:fs');const p=await readProject(new Blob([readFileSync(new URL('../public/library/Pipsa.hahmo',import.meta.url))])),q=p.doc.quick!,filter=initialFaceFilter(),base={x:.5,y:.5,width:.2,roll:0,blinkLeft:0,blinkRight:0,jaw:0};let poses={};for(let frame=0;frame<180;frame++)poses=facePoses({...base,blinkLeft:.9,blinkRight:.9,jaw:.5,browUp:.7,lookX:.4},base,q.roles,p.animation.rig,filter,frame/30);const r=poses as Record<string,import('./animation-model.ts').Pose>;assert.equal(r[q.roles.leftBlink].opacity,1);assert.equal(r[q.roles.rightBlink].opacity,1);assert.equal(r[q.roles.leftPupil].opacity,0);assert.equal(r[q.roles.mouthNeutral].opacity,0);assert.equal(r[q.roles.mouthOpen].opacity,1);assert.ok(r[q.roles.leftBrow].y<0);assert.ok(r[q.roles.leftPupil].x>0);for(let frame=180;frame<210;frame++)poses=facePoses({...base,smile:.9},base,q.roles,p.animation.rig,filter,frame/30);const smile=poses as typeof r;assert.equal(smile[q.roles.leftBlink].opacity,0);assert.equal(smile[q.roles.leftPupil].opacity,1);assert.equal(smile[q.roles.mouthOpen].opacity,0);assert.equal(smile[q.roles.mouthSmile].opacity,1);assert.equal(smile[q.roles.mouthNeutral].opacity,0);
});
