import {flatten,type LayerNode,type PsdDocument} from './psd-model.ts';
export type EditPoint={x:number;y:number};
export type Stroke={kind:'brush'|'erase'|'hide'|'reveal';points:EditPoint[];size:number;color:string;opacity:number};
export type VectorShape={kind:'rect'|'ellipse'|'path';id:string;x:number;y:number;width:number;height:number;rotation:number;fill:string;stroke:string;strokeWidth:number;points?:EditPoint[]};
export type RegionMove={kind:'move';x:number;y:number;width:number;height:number;dx:number;dy:number};
export type LayerEdit={version:1;transform?:{x:number;y:number;scaleX:number;scaleY:number;rotation:number};operations:(Stroke|VectorShape|RegionMove)[]};
const number=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
const color=(v:unknown)=>typeof v==='string'&&/^(#[0-9a-fA-F]{6}|transparent)$/.test(v);
/** Reject unbounded coordinates and operation counts before allocating raster surfaces. */
export function readLayerEdit(v:unknown):LayerEdit|undefined{if(v===undefined)return;const e=v as LayerEdit;if(!e||e.version!==1||!Array.isArray(e.operations)||e.operations.length>2000)throw Error('Tason muokkaustiedot ovat virheelliset.');if(e.transform){const t=e.transform;if(!number(t.x,-100000,100000)||!number(t.y,-100000,100000)||!number(t.scaleX,.01,100)||!number(t.scaleY,.01,100)||!number(t.rotation,-3600,3600))throw Error('Kuvasisällön muunnos on virheellinen.');}let points=0;for(const o of e.operations){if(!o||typeof o!=='object')throw Error('Tason muokkaus puuttuu.');if(['brush','erase','hide','reveal'].includes(o.kind)){const s=o as Stroke;if(!number(s.size,.1,2048)||!number(s.opacity,0,1)||!color(s.color)||!Array.isArray(s.points)||s.points.length<1||s.points.length>20000)throw Error('Siveltimen tiedot ovat virheelliset.');points+=s.points.length;if(!s.points.every(p=>p&&number(p.x,-100000,100000)&&number(p.y,-100000,100000)))throw Error('Siveltimen piste on virheellinen.');}else if(o.kind==='move'){if(!['x','y','dx','dy'].every(k=>number(o[k as keyof RegionMove],-100000,100000))||!number(o.width,.1,16000)||!number(o.height,.1,16000))throw Error('Alueen siirto on virheellinen.');}else{const s=o as VectorShape;if(!['rect','ellipse','path'].includes(s.kind)||typeof s.id!=='string'||s.id.length>100||!number(s.x,-100000,100000)||!number(s.y,-100000,100000)||!number(s.width,.1,16000)||!number(s.height,.1,16000)||!number(s.rotation,-3600,3600)||!color(s.fill)||!color(s.stroke)||!number(s.strokeWidth,0,1024))throw Error('Vektorin tiedot ovat virheelliset.');if(s.kind==='path'){if(!Array.isArray(s.points)||s.points.length<2||s.points.length>1000||!s.points.every(p=>number(p.x,-100000,100000)&&number(p.y,-100000,100000)))throw Error('Vektoripolku on virheellinen.');points+=s.points.length;}}}if(points>100000)throw Error('Tasossa on liikaa piirtopisteitä.');return structuredClone(e);}
export function updateLayer(doc:PsdDocument,key:string,change:(n:LayerNode)=>LayerNode):PsdDocument{let found=false;const visit=(nodes:LayerNode[]):LayerNode[]=>nodes.map(n=>{if(n.key===key){found=true;return change(n);}const children=visit(n.children);return children.some((c,i)=>c!==n.children[i])?{...n,children}:n;});const layers=visit(doc.layers);if(!found)throw Error('Muokattavaa tasoa ei löydy.');return {...doc,layers};}
export function appendOperation(doc:PsdDocument,key:string,operation:LayerEdit['operations'][number]):PsdDocument{return updateLayer(doc,key,n=>{if(n.locked||n.kind!=='layer')throw Error('Avaa tason lukitus ennen piirtämistä.');return {...n,edit:readLayerEdit({...n.edit,version:1,operations:[...(n.edit?.operations??[]),operation]})};});}
/** Stable keys and PSD geometry are deliberately left intact. Only local pixels change. */
export function reorderLayer(doc:PsdDocument,key:string,delta:1|-1):PsdDocument{const visit=(nodes:LayerNode[]):LayerNode[]=>{const i=nodes.findIndex(n=>n.key===key);if(i>=0){const a=[...nodes],j=Math.max(0,Math.min(a.length-1,i+delta));[a[i],a[j]]=[a[j],a[i]];return a;}return nodes.map(n=>({...n,children:visit(n.children)}));};return {...doc,layers:visit(doc.layers)};}
export function addEditableLayer(doc:PsdDocument,copy?:LayerNode):{doc:PsdDocument;layer:LayerNode}{if(flatten(doc.layers).length>=1000)throw Error('Projektissa on jo 1000 tasoa.');const key='edit-'+crypto.randomUUID();const layer:LayerNode=copy?{...copy,key,psdId:undefined,name:copy.name+' kopio',path:copy.path+' kopio',locked:false,children:[],edit:copy.edit?structuredClone(copy.edit):undefined}:{key,name:'Uusi taso',path:'Uusi taso',kind:'layer',left:0,top:0,width:doc.width,height:doc.height,opacity:1,visible:true,blendMode:'normal',children:[],warnings:[],edit:{version:1,operations:[]}};return {doc:{...doc,layers:[...doc.layers,layer]},layer};}
