import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {mixPerformance,cameraCaptureTimes} from './performance-mixer.ts';import {readProject,saveProject} from './project-file.ts';import {neutral} from './animation-model.ts';import {initialQuick,dispatchQuick,quickPoses} from './quick-animation.ts';import {workspaceView,readTheme} from './workspace.ts';
const fixture=()=>readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));
test('camera head, two keyboard arms, microphone mouth and timeline legs coexist in recorded project',async()=>{
 const p=await fixture(),q=p.doc.quick!,state=initialQuick();dispatchQuick(state,'left',true,0);dispatchQuick(state,'right',true,0);const quick=quickPoses(state,q,p.animation.rig,.1,.08),head={...neutral,x:31,y:14,rotation:12,scale:1.15},eye={...neutral,opacity:0};
 const animation={...p.animation,tracks:[...p.animation.tracks,{key:q.roles.leftForearm,frames:[{...neutral,rotation:21,frame:0,easing:'hold' as const}]}]};const camera={[q.roles.head]:head,[q.roles.leftPupil]:eye,[q.roles.mouthOpen]:{...neutral,scale:1.6}};
 const out=mixPerformance(animation,0,q,quick,camera,true);assert.equal(out[q.roles.head].rotation,12);assert.equal(out[q.roles.head].x,31);assert.equal(out[q.roles.head].scale,1.15);assert.equal(out[q.roles.leftBlink].opacity,1);assert.ok(out[q.roles.leftArm].rotation<0&&out[q.roles.rightArm].rotation>0);assert.equal(out[q.roles.leftPupil].opacity,0);assert.equal(out[q.roles.mouthOpen].scale,1);assert.equal(out[q.roles.leftForearm].rotation,21);assert.equal(['mouthNeutral','mouthOpen','mouthRound'].reduce((n,k)=>n+out[q.roles[k]].opacity,0),1);
 const recorded={...animation,tracks:Object.entries(out).map(([key,pose])=>({key,frames:[{...pose,frame:0,easing:'hold' as const}]}))};const restored=await readProject(await saveProject(p.doc,recorded,undefined,p.scene));assert.deepEqual(restored.animation.tracks,recorded.tracks);assert.deepEqual(p.doc.quick,q);
});
test('removing a source restores fallback, unknown camera keys are ignored and inputs stay immutable',async()=>{const p=await fixture(),q=p.doc.quick!,quick=quickPoses(initialQuick(),q,p.animation.rig,.2),before=structuredClone(quick);const cam={[q.roles.head]:{...neutral,rotation:40},missing:{...neutral}};assert.equal(mixPerformance(p.animation,0,q,quick,cam,false)[q.roles.head].rotation,40);assert.equal(mixPerformance(p.animation,0,q,quick,undefined,false)[q.roles.head].rotation,quick[q.roles.head].rotation);assert.equal(mixPerformance(p.animation,0,q,quick,cam,false).missing,undefined);assert.deepEqual(quick,before);});
test('workspace changes contain only view state, leave portable document and playhead untouched',async()=>{const p=await fixture(),state={doc:p.doc,animation:p.animation,frame:1,selected:p.doc.quick!.roles.leftArm,camera:true,microphone:true,zoom:1.7};const original={...state};for(const workspace of ['character','animation','performance'] as const){const next={...state,...workspaceView(workspace)};for(const key of Object.keys(state) as (keyof typeof state)[])assert.equal(next[key],original[key]);}assert.deepEqual(Object.keys(workspaceView('performance')).sort(),['inspector','libraryTab','workspace']);assert.equal(readTheme('unexpected'),'system');assert.equal(readTheme('light'),'light');});

test('silent enabled microphone cannot erase sustained camera mouth; speech can take ownership and explicit camera mode wins',async()=>{
 const p=await fixture(),q=p.doc.quick!,quick=quickPoses(initialQuick(),q,p.animation.rig,1),camera={[q.roles.mouthNeutral]:{...neutral,opacity:0},[q.roles.mouthOpen]:{...neutral,opacity:1,scale:1.2},[q.roles.mouthRound]:{...neutral,opacity:0}};const silent=mixPerformance(p.animation,0,q,quick,camera,true,false);assert.equal(silent[q.roles.mouthOpen].opacity,1);assert.equal(silent[q.roles.mouthOpen].scale,1.2);const talking=quickPoses(initialQuick(),q,p.animation.rig,1,.06),speech=mixPerformance(p.animation,0,q,talking,camera,true,true);assert.equal(speech[q.roles.mouthOpen].opacity,talking[q.roles.mouthOpen].opacity);const cameraOnly=mixPerformance(p.animation,0,{...q,mouthSource:'camera'},talking,camera,true,true);assert.equal(cameraOnly[q.roles.mouthOpen].scale,1.2);
});

test('recording timestamps follow camera-owned face channels and microphone mouth ownership',async()=>{const p=await fixture(),q=p.doc.quick!,camera={[q.roles.head]:{...neutral},[q.roles.leftArm]:{...neutral},[q.roles.mouthOpen]:{...neutral}};const cameraOnly=cameraCaptureTimes(q,camera,1100,false,false);assert.equal(cameraOnly[q.roles.head],1100);assert.equal(cameraOnly[q.roles.mouthOpen],1100);assert.equal(cameraOnly[q.roles.leftArm],undefined);const speaking=cameraCaptureTimes(q,camera,1100,true,true);assert.equal(speaking[q.roles.head],1100);assert.equal(speaking[q.roles.mouthOpen],undefined);assert.deepEqual(cameraCaptureTimes(q,camera,undefined,false,false),{});});
test('manual camera offset is portable, bounded and changes captured channel time only',async()=>{const {readQuick}=await import('./quick-animation.ts');const p=await fixture(),q={...p.doc.quick!,cameraOffsetMs:-80},camera={[q.roles.head]:{...neutral}};assert.equal(cameraCaptureTimes(q,camera,1100,false,false)[q.roles.head],1020);const restored=await readProject(await saveProject({...p.doc,quick:q},p.animation,undefined,p.scene));assert.equal(restored.doc.quick?.cameraOffsetMs,-80);for(const cameraOffsetMs of [NaN,501,-501,.5])assert.throws(()=>readQuick({...q,cameraOffsetMs},p.animation.rig));});
