import {keyframeLimb} from './inverse-kinematics.ts';import {neutral,sampleTrack,putKeyframe,type Animation}from'./animation-model.ts';import type{QuickProfile}from'./quick-animation.ts';import type{Event}from'./presentation-model.ts';
export const phoneActions=['phone_hold','phone_look','phone_tap','show_phone','phone_camera','phone_ear','phone_down','phone_transfer'] as const;
export const phoneActionNames:Record<typeof phoneActions[number],string>={phone_hold:'Pidä puhelinta',phone_look:'Katso puhelinta',phone_tap:'Napauta näyttöä',show_phone:'Näytä toiselle',phone_camera:'Näytä kameralle',phone_ear:'Nosta korvalle',phone_down:'Laske pöydälle',phone_transfer:'Siirrä toiseen käteen'};
export function phoneInstruction(text:string):typeof phoneActions[number]|undefined{if(!/puheli|phone/i.test(text))return;return /siir.*kä|transfer|switch.*hand/i.test(text)?'phone_transfer':/korva|ear/i.test(text)?'phone_ear':/napau|tap.*screen|tap.*phone/i.test(text)?'phone_tap':/pöyd|laske|put.*down|on.*table|lower.*phone/i.test(text)?'phone_down':/näyt.*kamera|show.*camera/i.test(text)?'phone_camera':/näyt|show/i.test(text)?'show_phone':/katso|look/i.test(text)?'phone_look':/pidä|pitää|hold/i.test(text)?'phone_hold':undefined;}
/** IK emits ordinary editable tracks; source speech and face tracks are never replaced. */
export function compilePhoneAction(a:Animation,q:QuickProfile,e:Event,hand:'leftHand'|'rightHand',tableTarget?:{x:number;y:number}):Animation{const r=q.roles,side=hand==='leftHand'?'left':'right',other=side==='left'?'right':'left',start=Math.round((e.at??0)*a.fps),end=Math.min(a.duration-1,start+Math.max(1,Math.round((e.seconds??.8)*a.fps))),sign=side==='left'?1:-1,upper=a.rig.parts.find(p=>p.key===r[side+'Arm']);if(!upper)throw Error('Puhelintoiminto tarvitsee käsivarren sidokset.');let next=a;const holdAt=(role:string,frame:number)=>{const key=r[role];if(key)next=putKeyframe(next,key,{...sampleTrack(next.tracks.find(t=>t.key===key),frame),frame,easing:'smooth'});};const aim=(s:string,point:{x:number;y:number},frame:number)=>{holdAt(s+'Arm',start);holdAt(s+'Forearm',start);const solved=keyframeLimb(next,r[s+'Arm'],r[s+'Forearm'],frame,point,s==='left'?-1:1,'smooth');if(solved.clamped)throw Error('Puhelimen kohde on käden ulottumattomissa. Siirrä pöytää tai muuta asentoa.');next=solved.animation;holdAt(s+'Hand',start);const u=sampleTrack(next.tracks.find(t=>t.key===r[s+'Arm']),frame),l=sampleTrack(next.tracks.find(t=>t.key===r[s+'Forearm']),frame);if(r[s+'Hand'])next=putKeyframe(next,r[s+'Hand'],{...neutral,rotation:-u.rotation-l.rotation,frame,easing:'smooth'});};
 if(e.value==='phone_down')aim(side,tableTarget??{x:300+sign*125,y:552},end);
 else if(e.value==='phone_ear')aim(side,{x:300+sign*113,y:326},end);
 else if(e.value==='phone_transfer'){aim(side,{x:300,y:506},end);aim(other,{x:300,y:506},end);}
 else if(e.value==='phone_hold')aim(side,{x:300+sign*96,y:580},end);
 else{aim(side,{x:300+sign*(e.value==='phone_tap'?25:72),y:497},end);if(e.value==='phone_tap'){aim(other,{x:300+sign*25,y:482},end);aim(other,{x:300+sign*25,y:490},Math.min(a.duration-1,end+Math.round(.15*a.fps)));}}
 if(['phone_down','phone_transfer','phone_tap'].includes(e.value)){const finish=Math.min(a.duration-1,end+Math.round(.35*a.fps));const sides=e.value==='phone_down'?[side,other]:[e.value==='phone_tap'?other:side];for(const s of sides)for(const role of [s+'Arm',s+'Forearm',s+'Hand'])if(r[role])next=putKeyframe(next,r[role],{...neutral,frame:finish,easing:'smooth'});}
 return next;
}
