import {sampleTrack,type Animation,type Pose} from './animation-model.ts';import {animationTransforms} from './animation-transform.ts';import {handGrip} from './held-props.ts';import type {PsdDocument} from './psd-model.ts';import type {Scene} from './scene-model.ts';
export const phoneViews={front:'Puhelin edestä',back:'Puhelin takaa',side:'Puhelin sivulta'} as const;
export type PhoneView=keyof typeof phoneViews;
export type PhoneProp={view:PhoneView;x:number;y:number;scale:number;rotation:number;anchor:'scene'|'leftHand'|'rightHand'};
export function defaultPhone():PhoneProp{return {view:'front',x:0,y:0,scale:.7,rotation:0,anchor:'leftHand'};}
export function readPhone(p:unknown):PhoneProp|undefined{if(p===undefined)return;const v=p as PhoneProp;if(!v||!Object.hasOwn(phoneViews,v.view)||!['scene','leftHand','rightHand'].includes(v.anchor)||![v.x,v.y,v.scale,v.rotation].every(Number.isFinite)||Math.abs(v.x)>10000||Math.abs(v.y)>10000||v.scale<.1||v.scale>10||Math.abs(v.rotation)>360)throw new Error('Puhelimen asetukset ovat virheelliset.');return {...v};}
export function phoneSvg(view:PhoneView){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 240"><rect x="${view==='side'?48:4}" y="4" width="${view==='side'?24:112}" height="232" rx="18" fill="#24364b"/>${view==='front'?'<rect x="12" y="22" width="96" height="190" rx="10" fill="#76b5d1"/><rect x="43" y="12" width="34" height="5" rx="2" fill="#bfd7e2"/>':view==='back'?'<rect x="14" y="18" width="42" height="50" rx="10" fill="#546782"/><circle cx="26" cy="32" r="7" fill="#111c2b"/><circle cx="43" cy="51" r="7" fill="#111c2b"/><circle cx="60" cy="130" r="14" fill="#8192a8"/>':'<rect x="66" y="60" width="6" height="35" rx="2" fill="#9dafbf"/>'}</svg>`;}
export function phonePlacement(scene:Scene,doc:PsdDocument,a:Animation,frame:number,draft?:{key:string;pose:Pose;poses?:Record<string,Pose>}){const phone=scene.phone;if(!phone)return;const cue=scene.phoneCues?.filter(c=>c.frame<=frame).at(-1);if(cue?.view==='hidden')return;let x=phone.x,y=phone.y;
 let rotation=phone.rotation;
 if(phone.anchor!=='scene'){let roles=doc.quick?.roles;for(const map of Object.values(doc.quick?.views??{}))if(map&&(draft?.poses?.[map.root]?.opacity??sampleTrack(a.tracks.find(t=>t.key===map.root),frame).opacity)>.5)roles=map;const key=roles?.[phone.anchor],part=a.rig.parts.find(p=>p.key===key);if(!part)return;const transform=animationTransforms(a,frame,draft).get(part.key)!;if(transform.opacity<.01)return;
  // Tartuntapiste: kämmenen keskikohta (handGrip) ja puhelimen alaosa; puhelin kiertyy käden mukana.
  const view=(Object.entries(doc.quick?.views??{}).find(([,m])=>m===roles)?.[0]??'front') as import('./character-view.ts').CharacterView,grip=handGrip(doc,view,phone.anchor)??{x:part.pivot.x,y:part.pivot.y,angle:0};
  const p={x:scene.x-doc.width*scene.scale/2,y:scene.y-doc.height*scene.scale/2},gx=p.x+(transform.a*grip.x+transform.c*grip.y+transform.e)*scene.scale,gy=p.y+(transform.b*grip.x+transform.d*grip.y+transform.f)*scene.scale;
  rotation+=Math.atan2(transform.b,transform.a)*180/Math.PI+grip.angle;const rad=rotation*Math.PI/180,dy=-(phoneGrip.y-.5)*240*phone.scale,dx=-(phoneGrip.x-.5)*120*phone.scale;
  x+=gx+dx*Math.cos(rad)-dy*Math.sin(rad);y+=gy+dx*Math.sin(rad)+dy*Math.cos(rad);}
 return {x,y,width:120*phone.scale,height:240*phone.scale,rotation,view:cue?.view??phone.view};}
const phoneGrip={x:.5,y:.7};
export function drawPhone(ctx:CanvasRenderingContext2D,p:NonNullable<ReturnType<typeof phonePlacement>>){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation*Math.PI/180);ctx.scale(p.width/120,p.height/240);ctx.translate(-60,-120);ctx.fillStyle='#24364b';ctx.beginPath();ctx.roundRect(p.view==='side'?48:4,4,p.view==='side'?24:112,232,18);ctx.fill();if(p.view==='front'){ctx.fillStyle='#76b5d1';ctx.fillRect(12,22,96,190);ctx.fillStyle='#bfd7e2';ctx.fillRect(43,12,34,5);}else if(p.view==='back'){ctx.fillStyle='#546782';ctx.fillRect(14,18,42,50);for(const [x,y] of [[26,32],[43,51]]){ctx.fillStyle='#111c2b';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#8192a8';ctx.beginPath();ctx.arc(60,130,14,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle='#9dafbf';ctx.fillRect(66,60,6,35);}ctx.restore();}
