import type {Direction} from './presentation-direction.ts';
import {backgrounds} from './backgrounds.ts';
import type {Animation} from './animation-model.ts';
export type Ref={line:number;text:string};
export type Basis='rule'|'user'|'estimate'|'audio';
export type Event={id:string;kind:'dialogue'|'shot'|'action'|'expression'|'gaze'|'hold'|'title'|'note'|'environment'|'placement'|'prop'|'constraint';target:string;value:string;text?:string;seconds?:number;protected?:boolean;locked?:boolean;at?:number;duration?:number;sourceRef:Ref;basis:Basis;section:string;after?:string};
export type Binding={speaker:string;asset:string;voice:string;side:'left'|'right';functions:Record<string,string>;x?:number;y?:number;scale?:number};
export type AudioClip={id:string;dialogue:string;asset:string;start:number;end:number;duration:number;mouth:{time:number;shape:'rest'|'open'|'round'}[];source:'volume'|'viseme';pauseInside?:boolean;trailingSilence?:number;locked?:boolean};
export type Diagnostic={code:string;severity:'error'|'warning';message:string;event?:string};
export type Presentation={schemaVersion:1;id:string;original:string;metadata:{series:string;season:number;episode:number;title:string;target:number;purpose:string;environment:string};characters:string[];assets:{id:string;kind:'character'|'audio'|'prop'}[];direction?:Direction;world:{width:number;height:number;background:string;design?:typeof backgrounds[number]['id'];phone:{enabled:boolean;model:'phone-v1';carrier:string;hand:'leftHand'|'rightHand';view:'front'|'back'|'side'}};sections:{id:string;name:string;start:number;end:number;sourceRef:Ref;locked?:boolean}[];events:Event[];comments:Ref[];bindings:Binding[];audioClips:AudioClip[];diagnostics:Diagnostic[];seconds:number;startFrame?:number;actorAnimations?:Record<string,Animation>;natural:boolean;source:'script'|'recorded'|'live'};
export const functions=['neutral_talk','worried','confused','mildly_hurt','look_at_phone','look_at_other_character','show_phone','eyebrow_raise','dead_stare'] as const;
export function stableId(text:string){let h=2166136261;for(const c of text){h=Math.imul(h^c.charCodeAt(0),16777619);}return (h>>>0).toString(16);}
export function bytesId(bytes:Uint8Array){let h=2166136261;for(const b of bytes)h=Math.imul(h^b,16777619);return (h>>>0).toString(16);}
export function normalizeSpeaker(s:string){return s.trim().replace(/\.$/,'').toLocaleUpperCase('fi-FI');}
export function validatePresentation(value:unknown):Presentation{
 const p=value as Presentation;
 if(!p||p.schemaVersion!==1||typeof p.id!=='string'||typeof p.original!=='string'||p.original.length>60000||!p.metadata||typeof p.metadata.series!=='string'||typeof p.metadata.title!=='string'||!Number.isFinite(p.metadata.target)||p.metadata.target<0||p.metadata.target>600||!Array.isArray(p.characters)||p.characters.length>4||p.characters.some(c=>typeof c!=='string'||c.length>100||['__proto__','constructor','prototype'].includes(c))||!Array.isArray(p.events)||p.events.length>500||!Array.isArray(p.sections)||p.sections.length>100||!Array.isArray(p.comments)||p.comments.length>500||!Array.isArray(p.bindings)||p.bindings.length>4||!Array.isArray(p.audioClips)||p.audioClips.length>100||!['script','recorded','live'].includes(p.source)||typeof p.natural!=='boolean'||!Number.isFinite(p.seconds)||p.seconds<0||p.seconds>600)throw Error('Käsikirjoituskohtaus on virheellinen.');
 if(!p.world||![p.world.width,p.world.height].every(v=>Number.isFinite(v)&&v>0&&v<=4096)||typeof p.world.phone?.enabled!=='boolean'||!/^#[a-fA-F0-9]{6}$/.test(p.world.background)||(p.world.design!==undefined&&!backgrounds.some(b=>b.id===p.world.design))||p.world.phone?.model!=='phone-v1'||(!p.characters.includes(p.world.phone.carrier)&&!(p.characters.length===0&&!p.world.phone.enabled&&p.world.phone.carrier===''))||!['leftHand','rightHand'].includes(p.world.phone.hand)||!['front','back','side'].includes(p.world.phone.view)||!Array.isArray(p.assets)||p.assets.length>110)throw Error('Kohtauksen jatkuva näyttämö tai rekvisiitta on virheellinen.');
 if(!['purpose','environment'].every(k=>typeof p.metadata[k as 'purpose']==='string'&&p.metadata[k as 'purpose'].length<=5000)||![p.metadata.season,p.metadata.episode].every(n=>Number.isInteger(n)&&n>=1&&n<=999)||!Array.isArray(p.diagnostics)||p.diagnostics.length>1000||p.diagnostics.some(d=>!d||!['error','warning'].includes(d.severity)||typeof d.code!=='string'||typeof d.message!=='string'||d.message.length>12000))throw Error('Kohtauksen metadata tai tarkistus on virheellinen.');
 const ids=new Set<string>();for(const e of p.events){if(!e||typeof e.id!=='string'||ids.has(e.id)||!['dialogue','shot','action','expression','gaze','hold','title','note','environment','placement','prop','constraint'].includes(e.kind)||typeof e.target!=='string'||typeof e.value!=='string'||!e.sourceRef||!Number.isInteger(e.sourceRef.line)||e.sourceRef.line<1||typeof e.sourceRef.text!=='string'||!['rule','user','estimate','audio'].includes(e.basis)||typeof e.section!=='string'||(e.locked!==undefined&&typeof e.locked!=='boolean')||(e.protected!==undefined&&typeof e.protected!=='boolean')||(e.at!==undefined&&(!Number.isFinite(e.at)||e.at<0||e.at>600))||(e.duration!==undefined&&(!Number.isFinite(e.duration)||e.duration<0||e.duration>600))||(e.seconds!==undefined&&(!Number.isFinite(e.seconds)||e.seconds<0||e.seconds>60))||(e.text!==undefined&&(typeof e.text!=='string'||e.text.length>5000)))throw Error('Kohtauksen tapahtuma on virheellinen.');ids.add(e.id);}
 for(const e of p.events)if((e.kind==='dialogue'&&!p.characters.includes(e.target))||(e.after!==undefined&&!p.events.some(x=>x.id===e.after&&x.kind==='dialogue')))throw Error('Tapahtuman puhuja tai repliikkiviittaus puuttuu.');
 for(const b of p.bindings){if(['__proto__','prototype','constructor'].includes(b.asset)||!p.characters.includes(b.speaker)||typeof b.asset!=='string'||!/^[-a-zA-Z0-9_.]{1,100}$/.test(b.asset)||typeof b.voice!=='string'||!['left','right'].includes(b.side)||(b.scale!==undefined&&b.scale<=0)||!b.functions||functions.some(k=>!['supported','none'].includes(b.functions[k]))||['x','y','scale'].some(k=>b[k as 'x']!==undefined&&(!Number.isFinite(b[k as 'x'])||Math.abs(b[k as 'x']!)>10000)))throw Error('Puhujan hahmomääritys on virheellinen.');}
 if(new Set(p.bindings.map(b=>b.speaker)).size!==p.bindings.length)throw Error('Puhujan määritys on kahteen kertaan.');
 for(const a of p.audioClips){if(!a||!p.events.some(e=>e.id===a.dialogue&&e.kind==='dialogue')||typeof a.asset!=='string'||(a.locked!==undefined&&typeof a.locked!=='boolean')||(a.pauseInside!==undefined&&typeof a.pauseInside!=='boolean')||(a.trailingSilence!==undefined&&(!Number.isFinite(a.trailingSilence)||a.trailingSilence<0||a.trailingSilence>a.duration))||!/^[-a-zA-Z0-9_.]{1,100}$/.test(a.asset)||![a.start,a.end,a.duration].every(Number.isFinite)||a.start<0||a.end<=a.start||a.end>600||Math.abs(a.duration-(a.end-a.start))>.001||!['volume','viseme'].includes(a.source)||!Array.isArray(a.mouth)||a.mouth.length>4000||a.mouth.some((m,i)=>!Number.isFinite(m.time)||m.time<0||m.time>a.duration+.001||!['rest','open','round'].includes(m.shape)||(i>0&&m.time<a.mouth[i-1].time)))throw Error('Repliikkiäänen rajat tai suuajoitus ovat virheelliset.');}
 if(new Set(p.audioClips.map(a=>a.dialogue)).size!==p.audioClips.length)throw Error('Repliikillä on kaksi äänileikettä.');
 if(p.startFrame!==undefined&&(!Number.isInteger(p.startFrame)||p.startFrame<0||p.startFrame>=1800))throw Error('Kohtauksen aloitusruutu on virheellinen.');
 for(const s of p.sections)if(!s||!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end<=s.start||s.end>600||(s.locked!==undefined&&typeof s.locked!=='boolean'))throw Error('Osion aikaväli on virheellinen.');
 if(p.direction){const d=p.direction;if(![d.targetMin,d.targetMax].every(n=>Number.isFinite(n)&&n>=0&&n<=600)||d.targetMin>d.targetMax||typeof d.noLargeGestures!=='boolean'||typeof d.noExtraProps!=='boolean'||!Array.isArray(d.profiles)||d.profiles.length>4||!Array.isArray(d.requirements)||d.requirements.length>1500)throw Error('Jakson ohjaussuunnitelma on virheellinen.');for(const r of d.requirements)if(!r||typeof r.id!=='string'||typeof r.detail!=='string'||r.detail.length>60000||!['purpose','character','environment','prop','placement','dialogue','action','gaze','expression','timing','restriction','camera','ending'].includes(r.category)||!['implemented','estimated','missing'].includes(r.status)||!r.sourceRef||!Number.isInteger(r.sourceRef.line)||!Array.isArray(r.events)||r.events.some(id=>typeof id!=='string')||(r.accepted!==undefined&&typeof r.accepted!=='boolean'))throw Error('Käsikirjoituksen vaatimus on virheellinen.');for(const c of d.profiles)if(!p.characters.includes(c.speaker)||![c.personality,c.relationship,c.delivery].every(t=>typeof t==='string'&&t.length<=60000)||!Number.isFinite(c.intensity)||c.intensity<0||c.intensity>1||typeof c.still!=='boolean'||!Array.isArray(c.sourceRefs))throw Error('Hahmon ohjaus on virheellinen.');}
 return structuredClone(p);
}
