import {visemeRoles} from './cutout/mouth-roles.ts';
import {cameraInstruction} from './production-model.ts';
import {phoneActions,compilePhoneAction} from './phone-actions.ts';
import {stageState,stageActor} from './presentation-stage.ts';
import {compileBodyMotion} from './presentation-motion.ts';
import {applyIdleLife} from './motion-library.ts';
import {viewAtFrame} from './character-view.ts';
import {environmentId} from './presentation-direction.ts';
import {animationTransforms} from './animation-transform.ts';
import {neutral,putKeyframe,sampleTrack,type Animation} from './animation-model.ts';
import type {PsdDocument} from './psd-model.ts';
import {timePresentation} from './presentation-timing.ts';
import type {Presentation,Binding} from './presentation-model.ts';
export type PresentationAsset={doc:PsdDocument;animation:Animation};
export type PresentationAssets=Record<string,PresentationAsset>;
export function compilePresentation(input:Presentation,assets:PresentationAssets,fps:number):Presentation{
 const p=timePresentation(input,fps);p.actorAnimations={};p.assets=[...new Map([...(p.world.phone.enabled?[{id:'phone-v1',kind:'prop' as const}]:[]),...p.bindings.map(b=>({id:b.asset,kind:'character' as const})),...p.audioClips.map(c=>({id:c.asset,kind:'audio' as const}))].map(a=>[a.id,a])).values()];
 const phoneTarget=(binding:Binding,e:typeof p.events[number])=>{if(e.value!=='phone_down')return;const table=p.production?.props?.filter(v=>v.asset==='table-prop-v1'&&v.start<=(e.at??0)&&v.end>(e.at??0)).sort((a,b)=>Math.abs(a.x*p.world.width-stageActor(p,binding,e.at??0).x)-Math.abs(b.x*p.world.width-stageActor(p,binding,e.at??0).x))[0];if(!table)return;const r=stageActor(p,binding,e.at??0),doc=assets[binding.asset]?.doc,size=Math.min(p.world.width,p.world.height)*table.scale;return doc?{x:doc.width/2+(table.x*p.world.width-r.x)/r.scale,y:doc.height/2+(table.y*p.world.height-size*.25-20*r.scale-r.y)/r.scale}:undefined;};
 const bodies:Record<string,Animation>={};const bodyFor=(binding:Binding)=>{if(bodies[binding.speaker])return bodies[binding.speaker];const asset=assets[binding.asset],q=asset?.doc.quick;if(!q)return;let a:Animation={...asset.animation,fps,duration:Math.max(2,Math.ceil(p.seconds*fps)),tracks:[]};for(const map of Object.values(q.views??{front:q.roles}))if(map)a=putKeyframe(a,map.root,{...neutral,frame:0,easing:'hold',opacity:map.root===q.roles.root?1:0});try{a=compileBodyMotion(a,q,p,binding.speaker);}catch{}bodies[binding.speaker]=a;return a;};
 for(const b of p.bindings){const asset=assets[b.asset];if(!asset?.doc.quick){p.diagnostics.push({code:'missing-character',severity:'error',message:b.speaker+': valitse .hahmo, jossa on pikaanimoinnin sidokset.'});continue;}
  const q=asset.doc.quick,r=q.roles,missing=(keys:string[])=>keys.some(k=>!r[k]);
  for(const [fn,keys] of Object.entries({neutral_talk:['mouthNeutral','mouthOpen'],worried:['leftBrow','rightBrow'],confused:['leftBrow','rightBrow'],mildly_hurt:['leftBrow','rightBrow'],angry:['leftBrow','rightBrow'],look_at_phone:['leftPupil','rightPupil'],look_at_other_character:['leftPupil','rightPupil'],show_phone:[p.world.phone.hand==='leftHand'?'leftArm':'rightArm',p.world.phone.hand==='leftHand'?'leftForearm':'rightForearm',p.world.phone.hand],eyebrow_raise:['leftBrow'],dead_stare:['root','head']}))if(b.functions[fn]==='supported'&&missing(keys))p.diagnostics.push({code:'missing-function',severity:'error',message:b.speaker+': hahmosta puuttuu toiminnon '+fn+' tarvitsema osa.'});
  let a:Animation={...asset.animation,fps,duration:Math.max(2,Math.ceil(p.seconds*fps)),tracks:[]};
  const rolesAt=(time:number)=>q.views?.[viewAtFrame(q,a,Math.round(time*fps))]??r;
  const key=(role:string,time:number,pose:Partial<typeof neutral>,easing:'hold'|'smooth'='hold')=>{const roles=rolesAt(time);if(roles[role])a=putKeyframe(a,roles[role],{...neutral,...Object.fromEntries(Object.entries(pose).map(([k,v])=>[k,v===0?0:v])),frame:Math.min(a.duration-1,Math.max(0,Math.round(time*fps))),easing});};
  for(const [keyName,opacity] of Object.entries(q.switchDefaults??{}))a=putKeyframe(a,keyName,{...neutral,frame:0,easing:'hold',opacity});
  // No idle/bounce/random blink: the dead stare remains motionless between intentional events.
  for(const [view,map] of Object.entries(q.views??{front:r})){a=putKeyframe(a,map!.root,{...neutral,frame:0,easing:'hold',opacity:map!.root===r.root?1:0});for(const role of ['leftBlink','rightBlink','mouthOpen','mouthRound','mouthSmile','mouthSad'])if(map![role])a=putKeyframe(a,map![role],{...neutral,frame:0,easing:'hold',opacity:0});}
  // Ilo pitää hymy-suun lepoasentona seuraavaan ilmeeseen asti; repliikin ajan suu seuraa puhetta.
  const expressionAt=(time:number)=>p.events.filter(x=>x.kind==='expression'&&x.target===b.speaker&&(x.at??0)<=time).sort((x,y)=>(x.at??0)-(y.at??0)).at(-1)?.value;
  const expressionMouth:Record<string,string>={happy:'mouthSmile',sad:'mouthSad',scared:'mouthRound'};
  const restMouth=(time:number,roles:Record<string,string>)=>{const m=expressionMouth[expressionAt(time)??''];return m&&roles[m]?m:'mouthNeutral';};
  const restMouths=['mouthNeutral','mouthSmile','mouthSad','mouthRound'];
  // Avainruutu, joka säilyttää radan nykyisen asennon (esim. katseen pupillisiirtymän) ja muuttaa vain annetut arvot.
  const keep=(role:string,time:number,pose:Partial<typeof neutral>)=>{const roles=rolesAt(time),k=roles[role];if(!k)return;const frame=Math.min(a.duration-1,Math.max(0,Math.round(time*fps)));a=putKeyframe(a,k,{...sampleTrack(a.tracks.find(x=>x.key===k),frame),...pose,frame,easing:'hold'});};
  try{a=compileBodyMotion(a,q,p,b.speaker);}catch(error){for(const e of p.events.filter(e=>e.kind==='action'&&e.target===b.speaker&&e.value!=='show_phone'))p.diagnostics.push({code:'motion-conflict',severity:'error',event:e.id,message:b.speaker+': '+(error as Error).message});}
  for(const e of p.events.filter(e=>e.kind==='action'&&e.target===b.speaker&&phoneActions.includes(e.value as any))){try{const t=e.at??0,roles=q.views?.[viewAtFrame(q,a,Math.round(t*fps))]??q.roles;a=compilePhoneAction(a,{...q,roles},e,stageState(p,t).phone.hand,phoneTarget(b,e));}catch{}}
  bodies[b.speaker]=a;
  const profile=p.direction?.profiles.find(v=>v.speaker===b.speaker);if(profile){const text=profile.personality.toLowerCase();const brow=/huolest|worried/.test(text)?8*profile.intensity:/confused|hämment/.test(text)?4*profile.intensity:0;key('leftBrow',0,{y:-brow});key('rightBrow',0,{y:-brow});}
  for(const e of p.events.filter(e=>e.target===b.speaker)){
   const t=e.at??0,r=rolesAt(t),intensity=p.direction?.profiles.find(v=>v.speaker===b.speaker)?.intensity??1;
   if(e.kind==='expression'){
    // Kulmat: ilo kevyesti ylös, suru sisäreunat ylös, pelko korkealle; muut ilmeet kuten ennen.
    if(e.value==='happy'){key('leftBrow',t,{y:-4*intensity});key('rightBrow',t,{y:-4*intensity});}
    else if(e.value==='sad'){key('leftBrow',t,{y:-3*intensity,rotation:-12*intensity});key('rightBrow',t,{y:-3*intensity,rotation:12*intensity});}
    else if(e.value==='scared'){key('leftBrow',t,{y:-12*intensity,rotation:-6*intensity});key('rightBrow',t,{y:-12*intensity,rotation:6*intensity});}
    else{const v=e.value==='angry'?12:e.value==='worried'?8:e.value==='mildly_hurt'?4:e.value==='confused'?6:e.value==='eyebrow_raise'?10:0;
     key('leftBrow',t,{y:-v*intensity,rotation:v?5*intensity:0});key('rightBrow',t,{y:(e.value==='confused'?2:-v)*intensity,rotation:v?-5*intensity:0});}
    // Silmät: suru laskee katsetta, pelko laajentaa silmät ja pienentää pupillit; katseen vaakasiirtymä säilyy.
    const scared=e.value==='scared',wasScared=expressionAt(t-1/fps)==='scared';
    if(scared||wasScared){keep('leftEye',t,{scale:scared?1.14:1});keep('rightEye',t,{scale:scared?1.14:1});keep('leftPupil',t,{scale:scared?.78:1});keep('rightPupil',t,{scale:scared?.78:1});}
    if(e.value==='sad'){keep('leftPupil',t,{y:4});keep('rightPupil',t,{y:4});}
    // Suu: ilmeen lepoasento (hymy / surusuu / pyöreä) pysyy seuraavaan ilmeeseen; repliikki ohittaa sen.
    if(e.value==='happy'&&!r.mouthSmile)p.diagnostics.push({code:'smile-missing',severity:'warning',event:e.id,message:b.speaker+': hahmopaketissa ei ole hymy-suuta. Ilo näkyy vain kulmakarvoissa; valitse hahmo, jossa on Suu hymy -taso.'});
    const now=restMouth(t,r),before=restMouth(t-1/fps,r);
    if(now!==before||expressionMouth[e.value])for(const role of restMouths.filter(x=>r[x]))key(role,t,{opacity:role===now?1:0});
    if(e.value==='dead_stare'){key('head',t,{});key('leftBlink',t,{opacity:0});key('rightBlink',t,{opacity:0});}
   }
   if(e.kind==='gaze'&&e.value==='camera'){
    // Katse kameraan: pupillit keskelle ja pää suoraan. Profiilissa katse ei voi osua katsojaan.
    key('leftPupil',t,{});key('rightPupil',t,{});key('head',t,{});
    if(q.views&&viewAtFrame(q,a,Math.round(t*fps))!=='front')p.diagnostics.push({code:'camera-gaze-profile',severity:'warning',event:e.id,message:b.speaker+': katse kameraan näkyy vain etunäkymässä. Käännä hahmo edestä kuvattavaksi tai poista ohje.'});
   }
   else if(e.kind==='gaze'){let x=0,y=0;const first=a.rig.parts.find(part=>part.key===r.leftPupil),second=a.rig.parts.find(part=>part.key===r.rightPupil);if(!first||!second)continue;const eye1=first.pivot,eye2=second.pivot,eye={x:(eye1.x+eye2.x)/2,y:(eye1.y+eye2.y)/2};if(e.value==='phone'){const world=stageState(p,t),carrier=p.bindings.find(n=>n.speaker===world.phone.carrier),resource=carrier?assets[carrier.asset]:undefined,body=carrier?bodyFor(carrier):undefined;if(!world.phone.enabled||!carrier||!resource?.doc.quick||!body)p.diagnostics.push({code:'phone-missing',severity:'error',event:e.id,message:'Katse puhelimeen tarvitsee näkyvän puhelimen ja haltijan.'});else{const roles=resource.doc.quick.views?.[viewAtFrame(resource.doc.quick,body,Math.round(t*fps))]??resource.doc.quick.roles,hand=body.rig.parts.find(part=>part.key===roles[world.phone.hand]);if(hand){const matrix=animationTransforms(body,Math.round(t*fps)).get(hand.key)!,placement=stageActor(p,carrier,t),self=stageActor(p,b,t),tx=placement.x-resource.doc.width*placement.scale/2+(matrix.a*hand.pivot.x+matrix.c*hand.pivot.y+matrix.e)*placement.scale,ty=placement.y-resource.doc.height*placement.scale/2+(matrix.b*hand.pivot.x+matrix.d*hand.pivot.y+matrix.f)*placement.scale;const eyeMatrix=animationTransforms(a,Math.round(t*fps)).get(r.leftPupil)!,ex=self.x-asset.doc.width*self.scale/2+(eyeMatrix.a*eye.x+eyeMatrix.c*eye.y+eyeMatrix.e)*self.scale,ey=self.y-asset.doc.height*self.scale/2+(eyeMatrix.b*eye.x+eyeMatrix.d*eye.y+eyeMatrix.f)*self.scale;x=Math.max(-9,Math.min(9,(tx-ex)*.025));y=Math.max(-6,Math.min(6,(ty-ey)*.018));}}}else{const other=p.bindings.find(n=>n.speaker===e.value),self=stageActor(p,b,t);if(other){const target=stageActor(p,other,t);x=Math.sign(target.x-self.x)*6;y=Math.max(-5,Math.min(5,(target.y-self.y)*.01));}else p.diagnostics.push({code:'missing-gaze-target',severity:'error',event:e.id,message:'Katsekohde '+e.value+' puuttuu kohtauksesta.'});}key('leftPupil',t,{x,y});key('rightPupil',t,{x,y});}
   if(e.kind==='action'&&e.value==='phone_down'&&!phoneTarget(b,e))p.diagnostics.push({code:'phone-table-missing',severity:'error',event:e.id,message:'Puhelimen laskeminen pöydälle tarvitsee näkyvän pöydän kirjastosta ja paikan käden ulottuvilla.'});
   if(e.kind==='action'&&phoneActions.includes(e.value as any)){try{a=compilePhoneAction(a,{...q,roles:r},e,stageState(p,t).phone.hand,phoneTarget(b,e));}catch(error){p.diagnostics.push({code:'phone-rig',severity:'error',event:e.id,message:(error as Error).message});}}
   if(e.kind==='action'&&e.value==='show_phone'){const world=stageState(p,t);if(!world.phone.enabled)p.diagnostics.push({code:'phone-missing',severity:'error',event:e.id,message:'Puhelimen näyttäminen tarvitsee näkyvän puhelimen.'});if(b.speaker!==world.phone.carrier)p.diagnostics.push({code:'phone-carrier',severity:'error',event:e.id,message:'Puhelimen näyttäminen on osoitettu eri hahmolle kuin puhelimen haltija.'});const hand=world.phone.hand==='leftHand'?'left':'right';}
   if(e.kind==='hold'&&e.value==='dead_stare'){key('head',t,{});key('leftBlink',t,{opacity:0});key('rightBlink',t,{opacity:0});}
   if(e.kind==='dialogue'){
    const clip=p.audioClips.find(c=>c.dialogue===e.id);if(clip){for(const extra of ['mouthSmile','mouthSad'])if(r[extra])key(extra,t,{opacity:0});for(const m of clip.mouth){const wanted=m.viseme&&r[visemeRoles[m.viseme]]?visemeRoles[m.viseme]:m.shape==='rest'?'mouthNeutral':m.shape==='round'?'mouthRound':'mouthOpen';for(const role of Object.values(visemeRoles))key(role,t+m.time,{opacity:role===wanted?1:0});}const rest=restMouth(t+clip.duration,r);for(const role of Object.values(visemeRoles))key(role,t+clip.duration,{opacity:role===rest?1:0});for(const extra of ['mouthSmile','mouthSad'])if(r[extra])key(extra,t+clip.duration,{opacity:rest===extra?1:0});}
   }
  }
  if(p.source==='recorded'){const face=new Set(['head','leftPupil','rightPupil','leftBrow','rightBrow','leftBlink','rightBlink'].map(k=>r[k]).filter(Boolean)),recorded=asset.animation.tracks.filter(t=>face.has(t.key)&&t.frames.length>1);if(recorded.length)a={...a,tracks:[...a.tracks.filter(t=>!recorded.some(old=>old.key===t.key)),...recorded.map(t=>({...t,frames:t.frames.map(k=>({...k,frame:Math.round(k.frame/asset.animation.fps*fps)})).filter(k=>k.frame<a.duration)}))]};else p.diagnostics.push({code:'recorded-missing',severity:'warning',message:b.speaker+': hahmopaketissa ei ole tallennettua kasvoesitystä, käytetään käsikirjoituksen ja repliikkiäänen ajoitusta.'});}
  for(const h of p.events.filter(e=>e.kind==='hold'&&e.protected&&e.value==='dead_stare'&&e.target===b.speaker)){const start=Math.round(h.at!*fps),end=Math.round((h.at!+h.duration!)*fps);for(const role of ['head','leftPupil','rightPupil','leftBrow','rightBrow','leftBlink','rightBlink',...Object.values(visemeRoles)]){const key=rolesAt(h.at!)[role],track=a.tracks.find(t=>t.key===key);if(!key)continue;const pose=sampleTrack(track,start),resume=sampleTrack(track,end);a={...a,tracks:a.tracks.map(t=>t.key===key?{...t,frames:t.frames.filter(f=>f.frame<start||f.frame>=end)}:t)};a=putKeyframe(a,key,{...pose,opacity:role==='mouthNeutral'?1:[...Object.values(visemeRoles).filter(r=>r!=='mouthNeutral'),'leftBlink','rightBlink'].includes(role)?0:pose.opacity,frame:start,easing:'hold'});if(end<a.duration)a=putKeyframe(a,key,{...resume,frame:end,easing:'hold'});}}
  for(const c of p.events.filter(e=>e.kind==='constraint'&&e.value==='still'&&[b.speaker,'scene'].includes(e.target))){const end=p.events.find(e=>e.kind==='constraint'&&e.value==='release-still'&&[b.speaker,'scene'].includes(e.target)&&e.at!>c.at!)?.at??p.seconds,start=Math.round(c.at!*fps);for(const role of ['head','leftPupil','rightPupil','leftBrow','rightBrow','leftBlink','rightBlink']){const part=rolesAt(c.at!)[role];if(!part)continue;const old=a.tracks.find(t=>t.key===part),pose=sampleTrack(old,start),resume=sampleTrack(old,Math.round(end*fps));a={...a,tracks:a.tracks.map(t=>t.key===part?{...t,frames:t.frames.filter(k=>k.frame<start||k.frame>=Math.round(end*fps))}:t)};a=putKeyframe(a,part,{...pose,frame:start,easing:'hold'});if(end<p.seconds)a=putKeyframe(a,part,{...resume,frame:Math.round(end*fps),easing:'hold'});}}
  if(p.source==='script')a=applyIdleLife(a,{speaker:b.speaker,rolesAt:frame=>q.views?.[viewAtFrame(q,a,frame)]??r,quiet:frame=>{const t=frame/fps;return p.events.some(e=>(e.kind==='constraint'&&e.value==='still'&&[b.speaker,'scene'].includes(e.target)&&(e.at??0)<=t&&!p.events.some(x=>x.kind==='constraint'&&x.value==='release-still'&&[b.speaker,'scene'].includes(x.target)&&(x.at??0)>(e.at??0)&&(x.at??0)<=t))||(e.kind==='hold'&&e.value==='dead_stare'&&e.target===b.speaker&&t>=(e.at??0)-.2&&t<=(e.at??0)+(e.duration??0)+.2));}});
  p.actorAnimations[b.speaker]=a;
 }
 for(const e of p.events.filter(e=>e.kind==='environment'))if(!environmentId(e.value))p.diagnostics.push({code:'environment-missing',severity:'error',event:e.id,message:'Miljöötä ei ole kirjastossa: '+e.value+'. Valitse tuettu tausta tarkistuksesta.'});
 for(const e of p.events.filter(e=>e.kind==='shot')){const c=p.production?.cameras[e.id];if(!c)continue;const direct=cameraInstruction(e.sourceRef.text);if(direct&&direct.motion!=='still'&&p.events.some(rule=>rule.value==='camera-still'&&(rule.section===e.section||rule.section==='intro')))p.diagnostics.push({code:'camera-motion-conflict',severity:'warning',event:e.id,message:'Suora kameraliike ja kamera paikallaan -ohje koskevat samaa kuvaa. Tarkista ohjauspöydässä, kumpaa noudatetaan.'});const angled=c.view!=='front'||c.angle!=='eye';if(angled&&p.bindings.some(b=>p.production?.representations[b.speaker]!=='toon3d'))p.diagnostics.push({code:'camera-2d-view',severity:'error',event:e.id,message:'Kamerakulma '+c.view+' / '+c.angle+' tarvitsee tässä esityksessä kaikkien hahmojen 3D-versiot. Alkuperäiset 2D-kuvakulmat säilyvät liikeohjauksessa.'});if(angled&&stageState(p,e.at??0).design&&stageState(p,e.at??0).design!=='white')p.diagnostics.push({code:'flat-environment',severity:'warning',event:e.id,message:'Tausta on litteä 2D-kuva. Kulma kiertää hahmoja; ympäristön perspektiivi ei kierry mukana.'});}
 return p;
}
export function actorPlacement(b:Binding,width:number,height:number){return {x:b.x??width*(b.side==='left'?.28:.72),y:b.y??height*.60,scale:b.scale??Math.min(width/1400,height/1100)};}
