import {backgrounds,type BackgroundId} from './backgrounds.ts';
import {stableId,normalizeSpeaker,type Presentation,type Event,type Ref} from './presentation-model.ts';
export const productionMotions=['walk-left','walk-right','walk-front','run-left','run-right','run-front','wave','jump','crouch','nod','stop'] as const;
export const requirementCategories=['purpose','character','environment','prop','placement','dialogue','action','gaze','expression','timing','restriction','camera','ending'] as const;
export type Category=typeof requirementCategories[number];
export type Requirement={id:string;category:Category;detail:string;sourceRef:Ref;events:string[];status:'implemented'|'estimated'|'missing';accepted?:boolean};
export type CharacterDirection={speaker:string;personality:string;relationship:string;delivery:string;intensity:number;still:boolean;sourceRefs:Ref[]};
export type Direction={targetMin:number;targetMax:number;profiles:CharacterDirection[];requirements:Requirement[];noLargeGestures:boolean;noExtraProps:boolean};
export const categoryNames:Record<Category,string>={purpose:'Tarkoitus',character:'Hahmojen luonne ja suhteet',environment:'Miljöö',prop:'Rekvisiitta',placement:'Sijoittelu',dialogue:'Dialogi ja ääni',action:'Toiminta',gaze:'Katseet',expression:'Ilmeet',timing:'Kesto ja tauot',restriction:'Kiellot ja rajoitukset',camera:'Rajaukset ja leikkaukset',ending:'Lopetus'};
export function environmentId(text:string):BackgroundId|'white'|undefined{const t=text.toLowerCase();if(t==='white')return 'white';if(/valkoi|white/.test(t)&&/studio|tausta|background/.test(t))return 'white';if(/auto|car/.test(t))return /matkust|passenger/.test(t)?'car-passenger-v1':/taka|back/.test(t)?'car-back-v1':/kuljett|driver/.test(t)?'car-driver-v1':undefined;if(/puhelin|phone/.test(t))return /sivu|angle/.test(t)?'phone-angle-v1':/edestä|front/.test(t)?'phone-front-v1':undefined;if(/studio/.test(t))return 'studio-v1';return backgrounds.find(b=>b.id===text.trim())?.id;}
const clean=(s:string)=>s.trim().replace(/^#{1,6}\s*/,'').replace(/\*\*/g,'').replace(/\\$/,'').trim();
export function enrichDirection(p:Presentation):Presentation{
 const raw=p.original.replace(/\r\n?/g,'\n').split('\n'),requirements:Requirement[]=[],profiles:CharacterDirection[]=p.characters.map(speaker=>({speaker,personality:'',relationship:'',delivery:'',intensity:1,still:false,sourceRefs:[]}));
 const add=(category:Category,ref:Ref,status:Requirement['status'],events:string[]=[])=>{const id='r-'+stableId(category+'|'+ref.line+'|'+ref.text),old=requirements.find(r=>r.id===id);if(old){old.events=[...new Set([...old.events,...events])];if(status==='missing'||(status==='estimated'&&old.status==='implemented'))old.status=status;}else requirements.push({id,category,detail:ref.text,sourceRef:ref,events,status});};
 const duration=(line:string)=>{const m=line.match(/(\d+(?:[.,]\d+)?)\s*(?:s\b|sek|sec(?:onds)?)/i);return m?+m[1].replace(',','.'):undefined;};
 const named=(line:string)=>p.characters.find(c=>normalizeSpeaker(line).includes(c));
 const make=(kind:Event['kind'],target:string,value:string,ref:Ref,extra:Partial<Event>={}):Event=>({id:'e-'+stableId(kind+'|'+ref.line+'|'+value),kind,target,value,sourceRef:ref,basis:'rule',section:p.events.find(e=>e.sourceRef.line===ref.line)?.section??p.sections.filter(s=>s.sourceRef.line<=ref.line).at(-1)?.id??'intro',...extra});
 const noLargeGestures=raw.some(line=>!named(line)&&/ei iso(?:a|ja) ele|ei paljon animaatiota|ei tarvita paljon animaatiota|vähäele|no (?:big|large) gestures|minimal motion/i.test(line)),noExtraProps=/ei ylimääräistä taustakamaa|ei ylimääräis(?:iä|tä).*esine|no extra props/i.test(p.original);
 if(!raw.some(line=>/^(?:Miljöö|Environment|Tausta|Background):/i.test(clean(line))))add('environment',{line:1,text:'Miljöötä ei määritelty: arvioitu neutraali valkoinen tausta.'},'estimated');
 if(!raw.some(line=>/^(?:Pituus|Duration|Tavoitepituus):/i.test(clean(line))))add('timing',{line:1,text:'Pituutta ei määritelty: nykyisen jakson enimmäisraja 60 s.'},'estimated');
 let targetMin=0,targetMax=p.metadata.target;
 for(const [i,lineRaw] of raw.entries()){
  const line=clean(lineRaw),ref={line:i+1,text:lineRaw};if(!line)continue;const low=line.toLowerCase();
  if(/^(?:Pituus|Duration|Tavoitepituus):/i.test(line)){const pair=line.match(/(\d+(?:[.,]\d+)?)\s*[–—-]\s*(\d+(?:[.,]\d+)?)/);targetMin=pair?+pair[1].replace(',','.'):/(noin|about)/i.test(line)?0:duration(line)??0;targetMax=pair?+pair[2].replace(',','.'):duration(line)??p.metadata.target;p.metadata.target=targetMax;add('timing',ref,'implemented');}
  if(/^(?:Tarkoitus|Purpose):/i.test(line)){p.metadata.purpose=line.slice(line.indexOf(':')+1).trim();add('purpose',ref,'estimated');}
  if(/^(?:Hahmo|Character|Luonne|Personality|Suhde|Relationship|Ääni|Voice)\s+[^:]+:/i.test(line)){
   const who=named(line),profile=profiles.find(v=>v.speaker===who);if(profile){const text=line.slice(line.indexOf(':')+1).trim();profile.sourceRefs.push(ref);if(/^(Suhde|Relationship)/i.test(line))profile.relationship=text;else if(/^(Ääni|Voice)/i.test(line))profile.delivery=text;else profile.personality=text;add('character',ref,'estimated');p.events=p.events.filter(e=>e.sourceRef.line!==ref.line);}else add('character',ref,'missing');
  }
  if(/^(?:Miljöö|Environment|Tausta|Background):/i.test(line)){const text=line.slice(line.indexOf(':')+1).trim();if(!p.metadata.environment)p.metadata.environment=text;for(const c of p.characters){const normalized=normalizeSpeaker(text);if([c+'LLÄ PUHELIN',c+'LLA PUHELIN',c+' PUHELIN',c+' ON PUHELIN',c+' HAS A PHONE'].some(part=>normalized.includes(part)))p.world.phone.carrier=c;}const design=environmentId(text),initial=!p.events.some(e=>e.kind==='environment');p.events=p.events.filter(e=>!(e.kind==='note'&&e.sourceRef.line===ref.line));const e=make('environment','scene',design??text,ref);p.events.push(e);if(initial&&design&&design!=='white')p.world.design=design;add('environment',ref,design?'implemented':'missing',[e.id]);
   for(const c of p.characters){const term=c.toLowerCase(),part=low.slice(low.indexOf(term));if(low.includes(term)&&/^(?:.{0,45})?(vasemm|left|oikeall|right)/.test(part)){const value=/^(?:.{0,25})?(vasemm|left)/.test(part)?'left':'right';p.events.push(make('placement',c,value,ref));}}
  }
  // Global comments shape presets without being spoken or becoming unrelated actions.
  if(/Tarkoitus:|Hahmo |Character |Luonne |Personality |sanoo.*pokerinaam|dead stare|kuivasti|dry|vähäele|huolest|puolust|worried/i.test(line))for(const profile of profiles){if(!normalizeSpeaker(line).includes(profile.speaker))continue;const fragments=line.split(/[.!]/).filter(s=>normalizeSpeaker(s).includes(profile.speaker));const text=fragments.join('. ')||line;if(!profile.personality)profile.personality=text;if(/kuiv|dry|pokerinaam|dead stare|rauhalli|calm|vähäele/.test(text.toLowerCase())){profile.intensity=.45;profile.still=true;}else if(/huolest|worried|puolust/.test(text.toLowerCase()))profile.intensity=.7;if(!profile.delivery)profile.delivery=profile.still?'Rauhallinen ja vähäeleinen':'Käsikirjoituksen mukainen';if(!profile.sourceRefs.some(r=>r.line===ref.line))profile.sourceRefs.push(ref);}
 }
 // Transform only known safe directions; unsupported requirements remain visible and block readiness.
 const next:Event[]=[];
 for(const e of p.events){if(e.kind!=='note'){next.push(e);continue;}const line=clean(e.value),low=line.toLowerCase(),ref=e.sourceRef,target=named(line)??e.target;
  if(/^(Hahmo|Character|Luonne|Personality|Suhde|Relationship|Ääni|Voice)\s+/i.test(line))continue;
  if(/liikkumiskielto pois|saa liikkua|allow motion/i.test(line)){next.push({...e,kind:'constraint',target,value:'release-still'});add('restriction',ref,'implemented',[e.id]);continue;}
  const restriction=/^(?:ei|älä|do not|don't)(?=\s|[.!:]|$)/i.test(line)||/ei isoa elettä/i.test(line);
  if(restriction){const known=/ei (isoa|isoja) ele|ei ylimäär|ei dialogia|älä (?:liikuta|käytä dissolve)|no extra props|no (?:big|large) gestures|do not move|don't move/i.test(line);next.push({...e,kind:'constraint',target,value:/liikuta|move/.test(low)?'still':/dissolve/.test(low)?'hard-cuts':/ylimäär|extra props/.test(low)?'no-extra-props':'small-gestures'});add('restriction',ref,known?'implemented':'missing',[e.id]);continue;}
  if(/odota|wait|tauko|pause|silence/i.test(line)){const seconds=duration(line);next.push({...e,kind:'hold',target,value:/silence|hiljaisuus|dead stare/.test(low)?'dead_stare':'pause',seconds:seconds??.25,protected:seconds!==undefined,basis:seconds!==undefined?'rule':'estimate'});add('timing',ref,seconds!==undefined?'implemented':'estimated',[e.id]);continue;}
  const motion=/juok|run/.test(low)?(/vasem|left/.test(low)?'run-left':/suoraan|front|forward|kohti/.test(low)?'run-front':'run-right'):/kävel|kävele|walk/.test(low)?(/vasem|left/.test(low)?'walk-left':/suoraan|front|forward|kohti/.test(low)?'walk-front':'walk-right'):/vilkut|vilkuta|heilut|wave/.test(low)?'wave':/hypp|jump/.test(low)?'jump':/kyyk|crouch/.test(low)?'crouch':/nyökk|nyökä|nod/.test(low)?'nod':/pysäht|pysähdy|stop/.test(low)?'stop':undefined;
  if(motion){next.push({...e,kind:'action',target,value:motion,seconds:duration(line)??(motion==='stop'?0:2),basis:duration(line)!==undefined||motion==='stop'?'rule':'estimate',after:/samalla|puhuessaan|while speaking|during dialogue/i.test(line)?p.events.filter(d=>d.kind==='dialogue'&&d.sourceRef.line<ref.line).at(-1)?.id:undefined});add('action',ref,duration(line)!==undefined||motion==='stop'?'implemented':'estimated',[e.id]);continue;}
  if(/^(?:Rekvisiitta|Prop|Puhelin|Phone):?/i.test(line)){const enabled=!/pois|hidden|off/i.test(low),phone=/puhelin|phone/i.test(low);if(phone){next.push({...e,kind:'prop',target,value:enabled?'phone-on':'phone-off',text:/takaa|back/i.test(line)?'back':/sivul|side/i.test(line)?'side':'front'});p.world.phone.enabled ||=enabled;add('prop',ref,'implemented',[e.id]);}else{next.push(e);add('prop',ref,'missing',[e.id]);}continue;}
  if(/^(?:Sijainti|Position):/i.test(line)){const m=line.match(/(vasen|left|oikea|right|keskellä|center)/i);if(m){next.push({...e,kind:'placement',target,value:/vasen|left/i.test(m[0])?'left':/oikea|right/i.test(m[0])?'right':'center'});add('placement',ref,'implemented',[e.id]);}else{next.push(e);add('placement',ref,'missing',[e.id]);}continue;}
  if(/^(?:Otsikkokortti|Title card|Lopetus|Ending):/i.test(line)){next.push({...e,kind:'title',target:'scene',value:line.slice(line.indexOf(':')+1).trim().replace(/\s+\d+(?:[.,]\d+)?\s*s$/i,''),seconds:duration(line)??1,basis:duration(line)!==undefined?'rule':'estimate'});add('ending',ref,duration(line)!==undefined?'implemented':'estimated',[e.id]);continue;}
  next.push(e);add('action',ref,'missing',[e.id]);
 }
 p.events=next.sort((a,b)=>a.sourceRef.line-b.sourceRef.line);p.diagnostics=p.diagnostics.filter(d=>!['review-instruction','unclear-shot'].includes(d.code));
 for(const e of p.events)if(!requirements.some(r=>r.events.includes(e.id))){const category:Category=e.kind==='dialogue'?'dialogue':e.kind==='shot'?'camera':e.kind==='expression'?'expression':e.kind==='gaze'?'gaze':e.kind==='hold'?'timing':e.kind==='title'?'ending':e.kind==='action'?'action':e.kind==='placement'?'placement':e.kind==='environment'?'environment':e.kind==='prop'?'prop':'restriction';add(category,e.sourceRef,e.basis==='estimate'?'estimated':'implemented',[e.id]);}
 // A conservative estimate is explicit; production prose is retained for review, never spoken.
 for(const ref of p.comments){const t=ref.text.toLowerCase();if(/älä|ei iso|no |do not/.test(t)){if(/liikuta/.test(t)){const subject=t.match(/älä liikuta ([\p{L}.]+)/u)?.[1],who=subject?p.characters.find(c=>normalizeSpeaker(subject).startsWith(c)):undefined,hold=p.events.find(e=>e.kind==='hold'&&e.protected&&e.value==='dead_stare'&&e.target===who);add('restriction',ref,hold?'implemented':'missing',hold?[hold.id]:[]);}else add('restriction',ref,/dissolve|transition|ei paljon|ele/.test(t)?'implemented':'missing');}else if(/tarvitsee|needs|suh|luon|tietää|kuiv|tavaramerk|komedia|comedy|rytmi|rythm/.test(t))add(/rytmi|komedia|comedy/.test(t)?'purpose':'character',ref,'estimated');}
 p.direction={targetMin,targetMax,profiles,requirements,noLargeGestures,noExtraProps};return p;
}
export function requirementStatus(p:Presentation,r:Requirement):Requirement['status']{
 if(r.events.length){const es=r.events.map(id=>p.events.find(e=>e.id===id));if(es.some(e=>!e||e.kind==='note'))return 'missing';if(es.some(e=>e?.kind==='environment'&&!environmentId(e.value)))return 'missing';if(es.some(e=>p.diagnostics.some(d=>d.severity==='error'&&d.event===e!.id)))return 'missing';}
 if(r.events.length&&r.events.every(id=>p.events.some(e=>e.id===id&&e.kind==='dialogue')&&p.audioClips.some(a=>a.dialogue===id)))return 'implemented';
 if(r.status==='missing'&&r.events.length){const es=r.events.map(id=>p.events.find(e=>e.id===id));if(es.every(e=>e?.kind==='environment'&&environmentId(e.value)))return 'implemented';if(es.every(e=>e&&e.kind!=='note'&&e.basis==='user'))return 'estimated';}
 return r.status;
}
