import type {Cutout3D} from './cutout-3d';
import {sampleTrack} from './animation-model.ts';
import {drawBackground} from './backgrounds.ts';
import {stageState,stageActor} from './presentation-stage.ts';
import {viewAtFrame} from './character-view.ts';
import {paintAnimatedLayers} from './psd-render.ts';import {drawPhone,phonePlacement,defaultPhone} from './phone-prop.ts';import {actorPlacement,type PresentationAssets} from './presentation-compile.ts';import type {Pose} from './animation-model.ts';import type {Presentation} from './presentation-model.ts';
export function presentationState(p:Presentation,time:number){const active=(kind:string)=>p.events.filter(e=>e.kind===kind&&(e.at??0)<=time).sort((a,b)=>(a.at??0)-(b.at??0)).at(-1);return {shot:active('shot'),title:p.events.filter(e=>e.kind==='title'&&(e.at??0)<=time&&time<(e.at??0)+(e.duration??.7)).at(-1)};}
export function renderPresentation(canvas:HTMLCanvasElement,scratch:HTMLCanvasElement,p:Presentation,assets:PresentationAssets,time:number,width:number,height:number,live?:{roles:Record<string,string>;poses:Record<string,Pose>},depth?:Cutout3D,transparent=false){
 canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;if(!transparent){ctx.fillStyle=p.world.background;ctx.fillRect(0,0,width,height);}const state=presentationState(p,time),world=stageState(p,time);if(!transparent&&world.design&&world.design!=='white')drawBackground(ctx,world.design,width,height);
 if(state.title){ctx.fillStyle='#242a31';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`700 ${Math.round(width*.11)}px -apple-system, sans-serif`;ctx.fillText(state.title.value,width/2,height/2,width*.9);return;}
 const target=p.bindings.find(b=>b.speaker===state.shot?.target),asset=target?assets[target.asset]:undefined;
 if(target&&asset&&state.shot?.value!=='wide'){const r=stageActor(p,target,time,width,height),zoom=state.shot?.value==='close'?2.4:1.5;ctx.translate(width/2,height*.46);ctx.scale(zoom,zoom);const a=p.actorAnimations?.[target.speaker],q=asset.doc.quick,root=a&&q?(q.views?.[viewAtFrame(q,a,Math.round(time*a.fps))]??q.roles).root:undefined,pose=a?sampleTrack(a.tracks.find(t=>t.key===root),Math.round(time*a.fps)):undefined;ctx.translate(-(r.x+(pose?.x??0)*r.scale),-(r.y+(pose?.y??0)*r.scale-asset.doc.height*r.scale*.22));}
 for(const b of p.bindings){const resource=assets[b.asset],animation=p.actorAnimations?.[b.speaker];if(!resource||!animation)continue;const frame=Math.max(0,Math.min(animation.duration-1,Math.round(time*animation.fps))),r=stageActor(p,b,time,width,height);ctx.save();ctx.translate(r.x-resource.doc.width*r.scale/2,r.y-resource.doc.height*r.scale/2);ctx.scale(r.scale,r.scale);const poses:Record<string,Pose>={};const constraint=p.events.filter(e=>e.kind==='constraint'&&['still','release-still'].includes(e.value)&&[b.speaker,'scene'].includes(e.target)&&(e.at??0)<=time).at(-1);if(live&&p.source==='live'&&constraint?.value!=='still'&&b===p.bindings[0]&&!p.events.some(e=>e.kind==='hold'&&e.protected&&e.value==='dead_stare'&&e.target===b.speaker&&time>=e.at!&&time<e.at!+e.duration!))for(const role of ['head','leftPupil','rightPupil','leftBrow','rightBrow','leftBlink','rightBlink']){const src=live.poses[live.roles[role]],key=(resource.doc.quick?.views?.[viewAtFrame(resource.doc.quick,animation,frame)]??resource.doc.quick?.roles)?.[role];if(src&&key)poses[key]=src;}paintAnimatedLayers(ctx,resource.doc,animation,frame,Object.keys(poses).length?{key:resource.doc.quick!.roles.head,pose:poses[resource.doc.quick!.roles.head]??{x:0,y:0,rotation:0,scale:1,opacity:1},poses}:undefined,depth);ctx.restore();
  if(world.phone.enabled&&b.speaker===world.phone.carrier){const phone=phonePlacement({width,height,background:'#ffffff',guides:false,...r,phone:{...defaultPhone(),scale:.5,anchor:world.phone.hand,view:world.phone.view}},resource.doc,animation,frame);if(phone)drawPhone(ctx,phone);}
 }
}
