import {toonProfiles,type ToonProfile} from './toon3d.ts';
import {propLibrary,type PropInstance} from './prop-library.ts';
import type {Event,Presentation} from './presentation-model.ts';
export type CameraSpec={size:'wide'|'medium'|'close';view:'front'|'profile-left'|'profile-right'|'rear'|'quarter-left'|'quarter-right';angle:'eye'|'high'|'low';foreground?:string;motion:'still'|'zoom'|'pan'|'tracking';duration?:number;zoom?:number;panX?:number;panY?:number;offsetX?:number;offsetY?:number};
export type SourceSpan={revision:number;start:number;end:number;origin:'direct'|'user'|'rule'|'semantic'|'unresolved'};
export type EventLocks={content?:boolean;duration?:boolean;start?:boolean;relative?:boolean};
export type Production={eventOrder?:string[];characterProfiles?:Record<string,ToonProfile>;props?:PropInstance[];schemaVersion:1;scriptRevision:number;longForm:boolean;sourceRefs:Record<string,SourceSpan>;generatedBase:Event[];manualOverrides:Record<string,Partial<Event>>;locks:Record<string,EventLocks>;cameras:Record<string,CameraSpec>;representations:Record<string,'2d'|'toon3d'>;assetVersions:Record<string,string>;semantic:{backend:'unavailable';status:'explicit-rules-only'};diff:{kept:string[];changed:string[];added:string[];removed:string[]};seriesProfile:{id:string;name:string;notes:string;noCameraMotion:boolean};alternatives:{id:string;name:string;cameras:Record<string,CameraSpec>}[]};
const safeKey=(s:string)=>s.length<=160&&!['__proto__','constructor','prototype'].includes(s);
export function cameraInstruction(text:string):CameraSpec|undefined{if(!/wide|medium|close[- ]?up|laaja|puolikuva|lähikuva|olkapään yli|over.*shoulder|zoom|panor|tracking|seuranta/i.test(text))return;return{size:/close[- ]?up|lähikuva/i.test(text)?'close':/medium|puolikuva/i.test(text)?'medium':'wide',view:/rear|takakuva/i.test(text)?'rear':/three.quarter|viisto/i.test(text)?(/left|vasem/i.test(text)?'quarter-left':'quarter-right'):/profile|sivukuva/i.test(text)?(/left|vasem/i.test(text)?'profile-left':'profile-right'):'front',angle:/high.angle|yläkulm/i.test(text)?'high':/low.angle|alakulm/i.test(text)?'low':'eye',motion:/no camera|ei kameraliik|keep.*camera.*still/i.test(text)?'still':/zoom/i.test(text)?'zoom':/panor|\bpan\b/i.test(text)?'pan':/tracking|seuranta/i.test(text)?'tracking':'still',...(/(\d+(?:[.,]\d+)?)\s*(?:s\b|seconds|sek)/i.test(text)?{duration:Number(text.match(/(\d+(?:[.,]\d+)?)\s*(?:s\b|seconds|sek)/i)![1].replace(',','.'))}:{})};}
export function initProduction(p:Presentation):Production{const offsets:number[]=[];let at=0;for(const line of p.original.split('\n')){offsets.push(at);at+=line.length+1;}return{schemaVersion:1,scriptRevision:1,longForm:p.metadata.target>60||p.original.split(/\s+/).length>=1000,sourceRefs:Object.fromEntries(p.events.map(e=>[e.id,{revision:1,start:offsets[e.sourceRef.line-1]??0,end:(offsets[e.sourceRef.line-1]??0)+e.sourceRef.text.length,origin:e.kind==='note'?'unresolved':e.basis==='estimate'?'rule':'direct'}])),generatedBase:structuredClone(p.events),manualOverrides:{},locks:{},cameras:Object.fromEntries(p.events.filter(e=>e.kind==='shot').map(e=>[e.id,{...(cameraInstruction(e.sourceRef.text)??{size:e.value,view:'front',angle:'eye',motion:'still'}),...(p.events.some(c=>c.value==='camera-still'&&(c.section===e.section||c.section==='intro'))?{motion:'still' as const}:{}),size:e.value==='close'?'close':e.value==='medium'?'medium':'wide',...(/olkapään yli|over.*shoulder/i.test(e.sourceRef.text)?{foreground:p.characters.find(c=>c!==e.target&&e.sourceRef.text.toUpperCase().includes(c))}:{} )}])),representations:{},assetVersions:{},semantic:{backend:'unavailable',status:'explicit-rules-only'},diff:{kept:[],changed:[],added:p.events.map(e=>e.id),removed:[]},seriesProfile:{id:'series-'+p.metadata.series,name:p.metadata.series,notes:p.metadata.purpose,noCameraMotion:p.events.some(e=>e.value==='camera-still'&&e.section==='intro')},alternatives:[]};}
export function validateProduction(v:unknown,events:Event[],original:string):Production{const p=v as Production;if(!p||p.schemaVersion!==1||!Number.isInteger(p.scriptRevision)||p.scriptRevision<1||typeof p.longForm!=='boolean'||!p.sourceRefs||!Array.isArray(p.generatedBase)||p.generatedBase.length>2500||!p.manualOverrides||!p.locks||!p.cameras||!p.representations||!p.assetVersions||!p.diff||!p.seriesProfile||typeof p.seriesProfile.name!=='string'||typeof p.seriesProfile.notes!=='string'||p.seriesProfile.notes.length>60000||typeof p.seriesProfile.noCameraMotion!=='boolean'||!Array.isArray(p.alternatives)||p.alternatives.length>20||p.semantic?.backend!=='unavailable'||p.semantic?.status!=='explicit-rules-only')throw Error('Tuotantomalli on virheellinen.');for(const [key,s]of Object.entries(p.sourceRefs)){if(!safeKey(key)||!s||!Number.isInteger(s.revision)||s.revision<1||s.revision!==p.scriptRevision||!Number.isInteger(s.start)||!Number.isInteger(s.end)||s.start<0||s.end<s.start||s.end>original.length||!['direct','user','rule','semantic','unresolved'].includes(s.origin))throw Error('Käsikirjoituksen lähdeviittaus on virheellinen.');}for(const camera of [p.cameras,...p.alternatives.map(a=>a.cameras)])for(const [key,c]of Object.entries(camera)){if(!safeKey(key)||!c||!['wide','medium','close'].includes(c.size)||!['front','profile-left','profile-right','rear','quarter-left','quarter-right'].includes(c.view)||!['eye','high','low'].includes(c.angle)||!['still','zoom','pan','tracking'].includes(c.motion)||['duration','zoom','panX','panY','offsetX','offsetY'].some(k=>c[k as 'duration']!==undefined&&(!Number.isFinite(c[k as 'duration'])||Math.abs(c[k as 'duration']!)>1200))||c.duration!==undefined&&c.duration<=0||c.zoom!==undefined&&(c.zoom<-.9||c.zoom>5)||c.foreground!==undefined&&(typeof c.foreground!=='string'||c.foreground.length>100))throw Error('Kameramääritys on virheellinen.');}for(const [k,r]of Object.entries(p.representations))if(!safeKey(k)||!['2d','toon3d'].includes(r))throw Error('Hahmon esitystapa on virheellinen.');for(const [k,l]of Object.entries(p.locks))if(!safeKey(k)||!l||Object.entries(l).some(([n,v])=>!['content','duration','start','relative'].includes(n)||typeof v!=='boolean'))throw Error('Tapahtuman lukitus on virheellinen.');for(const field of ['kept','changed','added','removed']as const)if(!Array.isArray(p.diff[field])||p.diff[field].length>2500||p.diff[field].some(x=>typeof x!=='string'||!safeKey(x)))throw Error('Päivityksen muutokset ovat virheelliset.');if(Object.keys(p.manualOverrides).length>2500||Object.keys(p.sourceRefs).length>2500||Object.keys(p.cameras).length>2500)throw Error('Tuotantomalli on liian suuri.');validateProductionDetails(p,events);for(const e of events)if(!p.sourceRefs[e.id])throw Error('Tapahtuman lähdeviittaus puuttuu.');return structuredClone(p);}
const signature=(e:Event)=>[e.kind,e.target,e.text??e.value].join('|');
/** Preserve identity by ordered exact anchors, then align edited events within each gap. */
export function reconcileProduction(parsed:Presentation,old:Presentation){const previous=old.production??initProduction(old),fresh=parsed.production??initProduction(parsed),used=new Set<string>(),mapping=new Map<string,string>(),pairs=new Map<string,Event>();let floor=0;for(const e of parsed.events){const i=old.events.findIndex((o,j)=>j>=floor&&!used.has(o.id)&&signature(o)===signature(e));if(i>=0){const o=old.events[i];mapping.set(e.id,o.id);pairs.set(e.id,o);used.add(o.id);floor=i+1;}}for(let i=0;i<parsed.events.length;i++){const e=parsed.events[i];if(pairs.has(e.id))continue;const prev=parsed.events.slice(0,i).reverse().find(e=>pairs.has(e.id)),next=parsed.events.slice(i+1).find(e=>pairs.has(e.id)),left=prev?old.events.findIndex(o=>o.id===mapping.get(prev.id)):-1,right=next?old.events.findIndex(o=>o.id===mapping.get(next.id)):old.events.length;const candidates=old.events.slice(left+1,right).filter(o=>!used.has(o.id)&&o.kind===e.kind&&o.target===e.target);if(candidates.length===1){const o=candidates[0];mapping.set(e.id,o.id);pairs.set(e.id,o);used.add(o.id);}}
 for(const e of parsed.events)if(!mapping.has(e.id))mapping.set(e.id,crypto.randomUUID());
 const baseCameras=initProduction({...old,events:previous.generatedBase}).cameras;const revision=previous.scriptRevision+1,kept:string[]=[],changed:string[]=[],added:string[]=[],sourceRefs:Production['sourceRefs']={},cameras:Production['cameras']={};const events=parsed.events.map(e=>{const o=pairs.get(e.id),id=mapping.get(e.id)!,manual=o&&(o.basis==='user'||previous.locks[o.id]?.content||o.locked)?o:undefined;if(o)(signature(o)===signature(e)?kept:changed).push(id);else added.push(id);sourceRefs[id]={...fresh.sourceRefs[e.id],revision};if(fresh.cameras[e.id]){const prior=o&&previous.cameras[o.id],base=o&&baseCameras[o.id],overrides=prior?Object.fromEntries(Object.entries(prior).filter(([key,value])=>!base||JSON.stringify(value)!==JSON.stringify(base[key as keyof CameraSpec]))):{};cameras[id]={...fresh.cameras[e.id],...overrides};}const override=o?previous.manualOverrides[o.id]:undefined;return{...e,...(manual?{value:manual.value,target:manual.target,seconds:manual.seconds,protected:manual.protected,locked:manual.locked,basis:manual.basis}:{}),...override,id,after:e.after?mapping.get(e.after)??e.after:undefined};});for(const o of old.events.filter(e=>previous.sourceRefs[e.id]?.origin==='user'&&!events.some(n=>n.id===e.id))){const anchor=old.events.slice(0,old.events.indexOf(o)).reverse().find(e=>events.some(n=>n.id===e.id)),at=anchor?events.findIndex(e=>e.id===anchor.id)+1:events.length,ref=anchor?sourceRefs[anchor.id]:{revision,start:0,end:0,origin:'user' as const};const copy={...o,sourceRef:anchor?events.find(e=>e.id===anchor.id)!.sourceRef:{line:1,text:''},after:o.after&&events.some(e=>e.id===o.after)?o.after:undefined};events.splice(at,0,copy);sourceRefs[o.id]={...ref,revision,origin:'user'};used.add(o.id);kept.push(o.id);}
 if(previous.eventOrder){const order=previous.eventOrder.filter(id=>events.some(e=>e.id===id));for(let i=0;i<events.length;i++)if(!order.includes(events[i].id)){const before=events.slice(0,i).reverse().find(e=>order.includes(e.id));order.splice(before?order.indexOf(before.id)+1:0,0,events[i].id);}events.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));}
 const removed=old.events.filter(e=>!used.has(e.id)).map(e=>e.id);return{...parsed,id:old.id,events,direction:parsed.direction?{...parsed.direction,requirements:parsed.direction.requirements.map(r=>({...r,events:r.events.map(id=>mapping.get(id)??id),accepted:old.direction?.requirements.find(o=>o.category===r.category&&o.detail===r.detail)?.accepted}))}:undefined,production:{...previous,scriptRevision:revision,eventOrder:previous.eventOrder?events.map(e=>e.id):undefined,sourceRefs,generatedBase:[...parsed.events.map(e=>({...e,id:mapping.get(e.id)!,after:e.after?mapping.get(e.after):undefined})),...events.filter(e=>sourceRefs[e.id]?.origin==='user')],cameras,diff:{kept,changed,added,removed}},audioClips:old.audioClips.filter(a=>{const e=events.find(e=>e.id===a.dialogue),before=old.events.find(e=>e.id===a.dialogue);return !!e&&e.text===before?.text;}),diagnostics:[...parsed.diagnostics,...removed.filter(id=>old.events.find(e=>e.id===id)?.locked||Object.values(previous.locks[id]??{}).some(Boolean)).map(id=>({code:'removed-locked',severity:'error' as const,event:id,message:'Lukittu lähdetapahtuma poistui. Päivitys vaatii tarkistuksen: '+id}))]};}

const overrideKeys=['value','target','text','seconds','protected','locked','at','duration','basis','after'] as const;
export function manualEvent(e:Event):Partial<Event>{return Object.fromEntries(overrideKeys.filter(k=>e[k]!==undefined).map(k=>[k,e[k]]));}
function validateProductionDetails(p:Production,events:Event[]){
 const fail=()=>{throw Error('Tuotannon ohitus tai resurssiprofiili on virheellinen.');};
 const validOverride=(v:Partial<Event>)=>{if(!v||Array.isArray(v)||typeof v!=='object')return false;return Object.entries(v).every(([k,value])=>{
 if(!overrideKeys.includes(k as typeof overrideKeys[number]))return false;
 if(['seconds','at','duration'].includes(k))return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=(k==='seconds'?60:1200);
 if(['protected','locked'].includes(k))return typeof value==='boolean';
 if(k==='basis')return ['rule','user','estimate','audio'].includes(value as string);
 return typeof value==='string'&&value.length<=(k==='value'?60000:k==='text'?5000:160)&&!['__proto__','constructor','prototype'].includes(value);
 });};
 if(Object.entries(p.manualOverrides).some(([k,v])=>!safeKey(k)||!validOverride(v)))fail();
 if(Object.entries(p.assetVersions).length>100||Object.entries(p.assetVersions).some(([k,v])=>!safeKey(k)||typeof v!=='string'||v.length>100))fail();
 if(Object.keys(p.representations).length>4||Object.keys(p.locks).length>2500||typeof p.seriesProfile.id!=='string'||p.seriesProfile.id.length>200||p.seriesProfile.name.length>5000)fail();
 if(p.alternatives.some(a=>!a||typeof a.id!=='string'||!safeKey(a.id)||typeof a.name!=='string'||a.name.length>200||!a.cameras||Object.keys(a.cameras).length>2500))fail();
 if(p.eventOrder&&(!Array.isArray(p.eventOrder)||p.eventOrder.length>2500||new Set(p.eventOrder).size!==p.eventOrder.length||p.eventOrder.some(k=>typeof k!=='string'||!safeKey(k))))fail();
 if(p.characterProfiles&&(typeof p.characterProfiles!=='object'||Array.isArray(p.characterProfiles)||Object.entries(p.characterProfiles).length>4||Object.entries(p.characterProfiles).some(([k,v])=>!safeKey(k)||!v||v.schemaVersion!==1||!toonProfiles.some(a=>a.id===v.id&&a.reference===v.reference)||typeof v.version!=='string'||v.version.length>100||typeof v.name!=='string'||v.name.length>100||v.status!=='review'||!['short','bob'].includes(v.hairStyle)||!Number.isFinite(v.outline)||v.outline<.5||v.outline>5||['skin','coat','hair','trousers','shoes'].some(c=>!/^#[0-9a-f]{6}$/i.test(v[c as 'skin'])))))fail();
 if(p.props&&(!Array.isArray(p.props)||p.props.length>100||new Set(p.props.map(v=>v?.id)).size!==p.props.length||p.props.some(v=>!v||!safeKey(v.id)||!propLibrary.some(a=>a.id===v.asset)||!['x','y','scale','start','end'].every(k=>Number.isFinite(v[k as 'x']))||v.x<0||v.x>1||v.y<0||v.y>1||v.scale<=0||v.scale>2||v.start<0||v.end<=v.start||v.end>1200)))fail();
 const ids=new Set<string>();for(const e of p.generatedBase){if(!e||typeof e.id!=='string'||!safeKey(e.id)||ids.has(e.id)||!['dialogue','shot','action','expression','gaze','hold','title','note','environment','placement','prop','constraint'].includes(e.kind)||typeof e.target!=='string'||typeof e.value!=='string'||typeof e.section!=='string'||!e.sourceRef||typeof e.sourceRef.text!=='string'||!Number.isInteger(e.sourceRef.line)||e.sourceRef.line<1||!validOverride(manualEvent(e)))fail();ids.add(e.id);}
}
