import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {readProject,saveProject} from './project-file.ts';import {appendTake,dispatchQuick,initialQuick,keyAction,quickPoses,readQuick} from './quick-animation.ts';import {sampleTrack,neutral} from './animation-model.ts';import {wav} from './microphone.ts';
const fixture=()=>readProject(new Blob([readFileSync(new URL('../public/library/Otto.hahmo',import.meta.url))]));
test('original robot package preserves real PSD, stable roles and scene through save/reopen',async()=>{const p=await fixture();assert.equal(p.animation.rig.parts.length,25);assert.equal(p.doc.quick?.roles.leftArm,'/0/9');assert.equal(p.scene.design,'studio-v1');assert.equal(await p.doc.sourcePsd!.slice(0,4).text(),'8BPS');const next=await readProject(await saveProject(p.doc,p.animation,undefined,p.scene));assert.deepEqual(next.doc.quick,p.doc.quick);assert.deepEqual(next.animation,p.animation);assert.deepEqual(next.scene,p.scene);assert.deepEqual(new Uint8Array(await next.doc.sourcePsd!.arrayBuffer()),new Uint8Array(await p.doc.sourcePsd!.arrayBuffer()));});
test('Mac keys ignore Command, Control, Alt and unrelated Shift combinations; physical Caps Lock codes stay usable',async()=>{const q=(await fixture()).doc.quick!;const event={code:'KeyW',metaKey:false,altKey:false,ctrlKey:false,shiftKey:false};assert.equal(keyAction(event,q),'jump');for(const k of ['metaKey','altKey','ctrlKey','shiftKey'])assert.equal(keyAction({...event,[k]:true},q),undefined);});
test('both arms blend independently; jump repeats are ignored and time is independent of FPS',async()=>{const p=await fixture(),q=p.doc.quick!,s=initialQuick();dispatchQuick(s,'left',true,0);dispatchQuick(s,'right',true,0);dispatchQuick(s,'jump',true,0);dispatchQuick(s,'jump',true,.4,true);assert.equal(s.jumpAt,0);let poses=quickPoses(s,q,p.animation.rig,.425,.06);assert.ok(poses[q.roles.leftArm].rotation<0&&poses[q.roles.rightArm].rotation>0);assert.ok(poses[q.roles.root].y<-100);assert.equal(poses[q.roles.mouthOpen].opacity+poses[q.roles.mouthNeutral].opacity+poses[q.roles.mouthRound].opacity,1);dispatchQuick(s,'left',false,.425);dispatchQuick(s,'right',false,.425);for(let i=1;i<=60;i++)poses=quickPoses(s,q,p.animation.rig,.425+i/60,0);assert.ok(Math.abs(poses[q.roles.leftArm].rotation)<.01);assert.equal(poses[q.roles.root].y,0);assert.equal(poses[q.roles.mouthNeutral].opacity,1);assert.ok(Math.abs(poses[q.roles.leftPupil].x)<=3);for(const fps of [30,60,120]){const t=initialQuick();dispatchQuick(t,'jump',true,0);for(let i=1;i<=fps;i++)quickPoses(t,q,p.animation.rig,i/fps,0);assert.equal(quickPoses(t,q,p.animation.rig,1)[q.roles.root].y,0);}});
test('recorded take appends without replacing old keys and keeps audio after reopen',async()=>{const p=await fixture(),q=p.doc.quick!,s=initialQuick();dispatchQuick(s,'jump',true,0);const captured=Object.entries(quickPoses(s,q,p.animation.rig,.4)).map(([key,pose])=>({key,frames:[{...pose,frame:0,easing:'hold' as const},{...pose,frame:24,easing:'hold' as const}]}));const result=appendTake(p.animation,captured);assert.equal(result.start,p.animation.duration);for(const old of p.animation.tracks)assert.deepEqual(result.animation.tracks.find(t=>t.key===old.key)!.frames[0],old.frames[0]);const audio={name:'test.wav',blob:wav(new Float32Array(48000),48000)};const next=await readProject(await saveProject(p.doc,result.animation,audio,p.scene));assert.deepEqual(next.animation,result.animation);assert.equal(next.audio?.blob.type,'audio/wav');assert.equal(next.audio?.blob.size,audio.blob.size);const again=appendTake(result.animation,captured);assert.equal(again.start,result.animation.duration);});
test('quick profile rejects conflicting keys and missing semantic roles',async()=>{const p=await fixture(),q=p.doc.quick!;assert.throws(()=>readQuick({...q,bindings:{...q.bindings,jump:'KeyA'}},p.animation.rig));assert.throws(()=>readQuick({...q,roles:{...q.roles,head:'missing'}},p.animation.rig));});
test('original robot has real two-segment IK pivots; solving keeps mouth keys',async()=>{const {keyframeLimb}=await import('./inverse-kinematics.ts');const p=await fixture(),q=p.doc.quick!;const result=keyframeLimb(p.animation,q.roles.leftArm,q.roles.leftForearm,24,{x:470,y:450},1,'smooth');assert.ok(result.animation.tracks.find(t=>t.key===q.roles.leftArm)!.frames.some(k=>k.frame===24));assert.deepEqual(result.animation.tracks.find(t=>t.key===q.roles.mouthOpen),p.animation.tracks.find(t=>t.key===q.roles.mouthOpen));});

test('appending a take preserves the complete previous playback, including unkeyed tracks and trailing holds',async()=>{const p=await fixture(),q=p.doc.quick!;const old={...p.animation,duration:120,tracks:[...p.animation.tracks,{key:q.roles.root,frames:[{...neutral,x:17,frame:0,easing:'linear' as const},{...neutral,x:42,frame:24,easing:'smooth' as const}]}]};const addition=[{key:q.roles.root,frames:[{...neutral,y:-108,frame:0,easing:'linear' as const},{...neutral,frame:24,easing:'hold' as const}]},{key:q.roles.leftArm,frames:[{...neutral,rotation:-135,frame:0,easing:'linear' as const},{...neutral,frame:24,easing:'hold' as const}]}];const result=appendTake(old,addition);assert.equal(result.start,120);for(const key of [q.roles.root,q.roles.leftArm])for(let frame=0;frame<=119;frame+=.5)for(const field of ['x','y','rotation','scale','opacity'] as const)assert.equal(sampleTrack(result.animation.tracks.find(t=>t.key===key),frame)[field],sampleTrack(old.tracks.find(t=>t.key===key),frame)[field]);});

test('live modifier gestures release independently and keep old binding archives readable',async()=>{const q=(await fixture()).doc.quick!,e={code:q.bindings.left,metaKey:false,altKey:false,ctrlKey:false,shiftKey:true};assert.equal(keyAction(e,q),'leftBend');assert.equal(keyAction({...e,metaKey:true},q),undefined);const s=initialQuick();dispatchQuick(s,'leftBend',true,1);dispatchQuick(s,'headLeft',true,1);assert.equal(s.leftBend,true);dispatchQuick(s,'leftBend',false,2);assert.equal(s.leftBend,false);assert.equal(s.headLeft,true);assert.ok(readQuick(q,(await fixture()).animation.rig));});
