import {readCutout3D,type Cutout3D} from './cutout-3d.ts';
import {validatePresentation,type Presentation} from './presentation-model.ts';
import {readPhone,type PhoneProp,type PhoneView} from './phone-prop.ts';
import {backgrounds,type BackgroundId} from './backgrounds.ts';
export type Scene={cutout3d?:Cutout3D;presentationDraft?:Presentation;presentations?:Presentation[];phone?:PhoneProp;phoneCues?:{frame:number;view:PhoneView|'hidden'}[];design?:BackgroundId;cuts?:{frame:number;design:BackgroundId}[];screenplay?:string;width:number;height:number;background:string;x:number;y:number;scale:number;guides:boolean};
export const formats=[{name:'Pystyvideo · Instagram / TikTok',width:1080,height:1920},{name:'Laajakuva · YouTube',width:1920,height:1080},{name:'Neliö',width:1080,height:1080}] as const;
export function createScene(doc:{width:number;height:number},width=1080,height=1920):Scene{return {width,height,background:'#253341',x:width/2,y:height/2,scale:Math.min(width/doc.width,height/doc.height)*.8,guides:true};}
export function readScene(value:unknown,doc:{width:number;height:number}):Scene{if(value===undefined)return createScene(doc);const s=value as Scene;if(!s||(s.design!==undefined&&!backgrounds.some(b=>b.id===s.design))||!formats.some(f=>f.width===s.width&&f.height===s.height)||!/^#[0-9a-f]{6}$/i.test(s.background)||typeof s.guides!=='boolean'||![s.x,s.y,s.scale].every(Number.isFinite)||Math.abs(s.x)>10000||Math.abs(s.y)>10000||s.scale<=0||s.scale>100)throw new Error('Näyttämön asetukset ovat virheelliset.');if(s.screenplay!==undefined&&(typeof s.screenplay!=='string'||s.screenplay.length>12000))throw new Error('Käsikirjoitus on liian pitkä.');if(s.cuts!==undefined&&(!Array.isArray(s.cuts)||s.cuts.length>100||s.cuts.some((c,i)=>!c||!Number.isInteger(c.frame)||c.frame<0||c.frame>=1800||!backgrounds.some(b=>b.id===c.design)||(i>0&&s.cuts![i-1].frame>=c.frame))))throw new Error('Kuvakulmien aikajana on virheellinen.');if(s.phoneCues!==undefined&&(!Array.isArray(s.phoneCues)||s.phoneCues.length>100||s.phoneCues.some((c,i)=>!c||!Number.isInteger(c.frame)||c.frame<0||c.frame>=1800||!['front','back','side','hidden'].includes(c.view)||(i>0&&s.phoneCues![i-1].frame>=c.frame))))throw new Error('Puhelimen kuvakulmien aikajana on virheellinen.');if(s.presentations!==undefined&&(!Array.isArray(s.presentations)||s.presentations.length>10))throw Error('Käsikirjoituskohtauksia on liikaa.');const result={...s};if(s.cutout3d!==undefined)result.cutout3d=readCutout3D(s.cutout3d);if(s.presentationDraft)result.presentationDraft=validatePresentation(s.presentationDraft);if(s.presentations)result.presentations=s.presentations.map(validatePresentation);if(s.phone===undefined)delete result.phone;else result.phone=readPhone(s.phone);return result;}
export function placement(scene:Scene,doc:{width:number;height:number}){return {x:scene.x-doc.width*scene.scale/2,y:scene.y-doc.height*scene.scale/2,width:doc.width*scene.scale,height:doc.height*scene.scale};}
export function scenePoint(scene:Scene,doc:{width:number;height:number},p:{x:number;y:number}){const r=placement(scene,doc);return {x:(p.x-r.x)/scene.scale,y:(p.y-r.y)/scene.scale};}
export function contain(width:number,height:number,targetWidth:number,targetHeight:number){const scale=Math.min(targetWidth/width,targetHeight/height);return {x:(targetWidth-width*scale)/2,y:(targetHeight-height*scale)/2,width:width*scale,height:height*scale};}
export function episodeTiming(durations:{duration:number;fps:number}[],fps=30){let start=0;return durations.map(a=>{if(!Number.isFinite(a.duration)||!Number.isFinite(a.fps)||a.duration<2||a.fps<1||a.duration/a.fps>60)throw new Error('Yksi jakso voi kestää enintään 60 sekuntia.');const frames=Math.ceil(a.duration/a.fps*fps),clip={start,frames,seconds:frames/fps};start+=frames;return clip;});}

export function sceneDesign(scene:Scene,frame:number){return scene.cuts?.filter(c=>c.frame<=frame).at(-1)?.design??scene.design;}
