import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {parseScreenplay,buildScreenplay} from './screenplay.ts';import {readProject,saveProject} from './project-file.ts';import {neutral,sampleTrack} from './animation-model.ts';import {sceneDesign,readScene} from './scene-model.ts';
const load=(name='Taru')=>readProject(new Blob([readFileSync(new URL(`../public/library/${name}.hahmo`,import.meta.url))]));
test('Finnish and English scripts recognize motions, durations and actual camera-angle cuts',()=>{const p=parseScreenplay('[tausta auto kuljettaja]\nHei! [vilkuta 2s]\nKävelen vasemmalle. [kävele vasemmalle 3s]\n[background phone angle]\nYes! [nod 1,5s]');assert.deepEqual(p.beats.map(b=>b.motion),['wave','walk-left','nod']);assert.equal(p.seconds,6.5);assert.equal(p.beats[0].design,'car-driver-v1');assert.equal(p.beats[2].design,'phone-angle-v1');assert.equal(parseScreenplay('En kävele nyt.').beats[0].motion,'wait');});
test('unknown explicit instructions and invalid durations are explained before generating',()=>{for(const text of ['', '[lennä 2s]','[tausta mars]\n[odota 1s]','[tausta studio]','[vilkuta 0s]','[hyppää 999s]','[vilkuta][hyppää]','x'.repeat(12001)])assert.throws(()=>parseScreenplay(text));assert.equal(parseScreenplay('Puhun nyt.').warnings.length,1);assert.throws(()=>parseScreenplay(Array(4).fill('[odota 20s]').join('\n')));});
test('script creates segmented editable walking/waving, keeps neck attachment, preserves existing playback and mouth tracks',async()=>{
 const p=await load('Taru'),q=p.doc.quick!,head=q.roles.head;const a={...p.animation,duration:24,tracks:[...p.animation.tracks,{key:head,frames:[{...neutral,rotation:7,frame:0,easing:'hold' as const}]}]},before=structuredClone(a),plan=parseScreenplay('[tausta auto kuljettaja]\n[vilkuta 2s]\n[kävele oikealle 2s]\n[tausta puhelin edestä]\n[nyökkää 1s]');
 const out=buildScreenplay(a,q,p.scene,plan);assert.equal(out.start,24);assert.deepEqual(a,before);for(const old of a.tracks)for(let f=0;f<a.duration;f++){const prev=sampleTrack(old,f),next=sampleTrack(out.animation.tracks.find(t=>t.key===old.key),f);for(const k of ['x','y','rotation','scale','opacity'] as const)assert.equal(next[k],prev[k]);}
 assert.ok(out.animation.tracks.find(t=>t.key===q.roles.leftForearm)!.frames.some(f=>f.rotation<-20));assert.ok(out.animation.tracks.find(t=>t.key===q.roles.leftShin)!.frames.some(f=>f.rotation>10));assert.ok(out.animation.tracks.find(t=>t.key===q.roles.root)!.frames.some(f=>f.x>0));assert.equal(out.animation.rig.parts.find(p=>p.key===head)!.parentKey,q.roles.root);
 assert.deepEqual(out.animation.tracks.find(t=>t.key===q.roles.mouthOpen),a.tracks.find(t=>t.key===q.roles.mouthOpen));assert.equal(sceneDesign(out.scene,0),p.scene.design);assert.equal(sceneDesign(out.scene,24),'car-driver-v1');assert.equal(sceneDesign(out.scene,24+96),'phone-front-v1');
 const restored=await readProject(await saveProject(p.doc,out.animation,undefined,out.scene));assert.deepEqual(restored.animation,out.animation);assert.deepEqual(restored.scene,out.scene);
});
test('portrait rejects unsupported leg movement and full timelines cannot exceed export limits',async()=>{const p=await load('Pipsa'),base=p.doc.quick!,q={...base,roles:Object.fromEntries(Object.entries(base.roles).filter(([k])=>!/Thigh|Shin|Foot/.test(k)))};assert.throws(()=>buildScreenplay(p.animation,q,p.scene,parseScreenplay('[kävele 2s]')),/kokovartalo/);assert.throws(()=>buildScreenplay(p.animation,q,p.scene,parseScreenplay('[kyykisty 2s]')),/kokovartalo/);assert.ok(buildScreenplay(p.animation,q,p.scene,parseScreenplay('[vilkuta 2s]')).animation.tracks.length>4);const long={...p.animation,duration:1400};assert.throws(()=>buildScreenplay(long,q,p.scene,parseScreenplay('[nyökkää 4s]')),/60 sekuntia/);});
test('scene reader rejects malformed cuts and oversized script while older scenes still load',async()=>{const p=await load();for(const cuts of [[{frame:-1,design:'studio-v1'}],[{frame:1,design:'invalid'}],[{frame:2,design:'studio-v1'},{frame:1,design:'studio-v1'}]])assert.throws(()=>readScene({...p.scene,cuts},p.doc));assert.throws(()=>readScene({...p.scene,screenplay:'x'.repeat(12001)},p.doc));assert.equal(readScene(p.scene,p.doc).design,'studio-v1');});
