import {sampleTrack} from './animation-model.ts';
import type {PsdDocument} from './psd-model.ts';
export type SafeArea={left:number;right:number;top:number;bottom:number};
export type EdgeBehavior='stop'|'turn'|'shorten';
export const defaultSafeArea:SafeArea={left:40,right:40,top:120,bottom:220};
export type CharacterBox={left:number;top:number;width:number;height:number};
export type StageGeometry={width:number;height:number;scale:number;safeArea?:SafeArea;box?:CharacterBox;docWidth:number;docHeight:number};
export function readSafeArea(value:unknown):SafeArea{if(value===undefined)return {...defaultSafeArea};const s=value as SafeArea;if(!s||!['left','right','top','bottom'].every(k=>Number.isFinite(s[k as keyof SafeArea])&&s[k as keyof SafeArea]>=0&&s[k as keyof SafeArea]<=10000))throw Error('Turva-alueen reunat ovat virheelliset.');return {...s};}
/** Bounds come from trimmed visible layer geometry, not transparent PSD margins. */
export function characterBox(doc:{width:number;height:number;layers?:PsdDocument['layers']}):CharacterBox{const boxes:CharacterBox[]=[];const visit=(nodes:NonNullable<typeof doc.layers>,visible:boolean)=>{for(const n of nodes){const show=visible&&n.visible;if(show&&n.kind==='layer'&&(n.png||n.image||n.edit?.operations.length))boxes.push({left:n.left,top:n.top,width:n.width,height:n.height});visit(n.children,show);}};if(doc.layers)visit(doc.layers,true);if(!boxes.length)return {left:0,top:0,width:doc.width,height:doc.height};const left=Math.min(...boxes.map(b=>b.left)),top=Math.min(...boxes.map(b=>b.top));return {left,top,width:Math.max(...boxes.map(b=>b.left+b.width))-left,height:Math.max(...boxes.map(b=>b.top+b.height))-top};}
export function stageLimits(g:StageGeometry){const safe=readSafeArea(g.safeArea),b=g.box??{left:0,top:0,width:g.docWidth,height:g.docHeight};if(![g.width,g.height,g.scale,g.docWidth,g.docHeight,b.width,b.height].every(n=>Number.isFinite(n)&&n>0)||safe.left+safe.right>=g.width||safe.top+safe.bottom>=g.height)throw Error('Turva-alueelle ei jää tilaa.');const scale=Math.min(g.scale,(g.width-safe.left-safe.right)/b.width,(g.height-safe.top-safe.bottom)/b.height);return {scale,left:safe.left-(b.left-g.docWidth/2)*scale,right:g.width-safe.right-(b.left+b.width-g.docWidth/2)*scale,top:safe.top-(b.top-g.docHeight/2)*scale,bottom:g.height-safe.bottom-(b.top+b.height-g.docHeight/2)*scale};}
/** One shared limiter for pointer, numeric inputs, keys, walking and loading. */
export function clampToStage(x:number,y:number,g:StageGeometry){if(!Number.isFinite(x)||!Number.isFinite(y))throw Error('Hahmon sijainti on virheellinen.');const r=stageLimits(g);return {x:Math.max(r.left,Math.min(r.right,x)),y:Math.max(r.top,Math.min(r.bottom,y)),scale:r.scale};}
export function clientToStage(client:{x:number;y:number},rect:{left:number;top:number;width:number;height:number},size:{width:number;height:number}){if(rect.width<=0||rect.height<=0)throw Error('Näyttämö ei ole näkyvissä.');return {x:(client.x-rect.left)*size.width/rect.width,y:(client.y-rect.top)*size.height/rect.height};}
export function dragPosition(start:{x:number;y:number},delta:{x:number;y:number},shift:boolean){if(shift){if(Math.abs(delta.x)>=Math.abs(delta.y))delta={x:delta.x,y:0};else delta={x:0,y:delta.y};}return {x:start.x+delta.x,y:start.y+delta.y};}
export function snapToStage(x:number,y:number,g:StageGeometry){const r=stageLimits(g),safe=readSafeArea(g.safeArea),b=g.box??{left:0,top:0,width:g.docWidth,height:g.docHeight},guides:{axis:'x'|'y';value:number}[]=[];const cx=g.width/2-(b.left+b.width/2-g.docWidth/2)*r.scale,cy=g.height/2-(b.top+b.height/2-g.docHeight/2)*r.scale;const find=(n:number,targets:{position:number;line:number}[],axis:'x'|'y')=>{const v=targets.reduce((a,b)=>Math.abs(b.position-n)<Math.abs(a.position-n)?b:a);if(Math.abs(v.position-n)<8){guides.push({axis,value:v.line});return v.position;}return n;};return {...clampToStage(find(x,[{position:r.left,line:safe.left},...(cx>=r.left&&cx<=r.right?[{position:cx,line:g.width/2}]:[]),{position:r.right,line:g.width-safe.right}],'x'),find(y,[{position:r.top,line:safe.top},...(cy>=r.top&&cy<=r.bottom?[{position:cy,line:g.height/2}]:[]),{position:r.bottom,line:g.height-safe.bottom}],'y'),g),guides};}

export function boundedWalk(start:number,distance:number,min:number,max:number,behavior:EdgeBehavior){const crossed=start+distance<min||start+distance>max,finish=Math.max(min,Math.min(max,start+distance)),fraction=distance?Math.max(0,Math.min(1,(finish-start)/distance)):1,span=max-min;return {crossed,fraction:behavior==='shorten'&&crossed?fraction:1,position:(t:number)=>{const v=start+distance*t;if(behavior!=='turn'||span<.000001)return Math.max(min,Math.min(max,v));const p=((v-min)%(span*2)+span*2)%(span*2);return min+(p<=span?p:span*2-p);},moving:(t:number)=>behavior==='turn'||!crossed||t<fraction};}

export function animationRoot(doc:PsdDocument,animation:import('./animation-model').Animation,frame:number){const roots=Object.values(doc.quick?.views??{}).flatMap(v=>v?[v.root]:[]);return roots.sort((a,b)=>sampleTrack(animation.tracks.find(t=>t.key===b),frame).opacity-sampleTrack(animation.tracks.find(t=>t.key===a),frame).opacity)[0]??doc.quick?.roles.root;}
export function animatedCharacterBox(doc:PsdDocument,animation:import('./animation-model').Animation,frame:number,pose=sampleTrack(animation.tracks.find(t=>t.key===animationRoot(doc,animation,frame)),frame)){const base=characterBox(doc),root=animation.rig.parts.find(p=>p.key===animationRoot(doc,animation,frame)),pivot=root?.pivot??{x:doc.width/2,y:doc.height/2};const r=pose.rotation*Math.PI/180,c=Math.cos(r)*pose.scale,s=Math.sin(r)*pose.scale,points=[[base.left,base.top],[base.left+base.width,base.top],[base.left,base.top+base.height],[base.left+base.width,base.top+base.height]].map(([x,y])=>({x:pivot.x+pose.x+(x-pivot.x)*c-(y-pivot.y)*s,y:pivot.y+pose.y+(x-pivot.x)*s+(y-pivot.y)*c}));const left=Math.min(...points.map(p=>p.x)),top=Math.min(...points.map(p=>p.y)),box={left,top,width:Math.max(...points.map(p=>p.x))-left,height:Math.max(...points.map(p=>p.y))-top};return box;}
export function clampAnimatedPlacement(scene:import('./scene-model').Scene,doc:PsdDocument,animation:import('./animation-model').Animation,frame:number,pose:import('./animation-model').Pose){return {...scene,...clampToStage(scene.x,scene.y,{...scene,docWidth:doc.width,docHeight:doc.height,box:animatedCharacterBox(doc,animation,frame,pose)})};}

