import {strFromU8} from 'fflate';
import {suggestMotionMapping} from './studio/motion-retarget.ts';
import {incrementalZip} from './studio/incremental-zip.ts';
import {unzipSync} from 'fflate';
import test from 'node:test';import assert from 'node:assert/strict';
import {semanticDelta,applySemanticDelta} from './studio/semantic-delta.ts';
import {serializedResource,readProject,saveProject} from './project-file.ts';
import {attachHistory,extractHistory} from './studio/portable-history.ts';
import {sha256} from './studio/hash.ts';
import {readFile} from 'node:fs/promises';
import {retargetMotion} from './studio/motion-retarget.ts';
test('semantic edits replay exactly, reject stale base and unsafe paths, preserve input',()=>{const a={scene:{text:'old',flag:true},tracks:[1,2]},b={scene:{text:'new'},tracks:[1,3]};const d=semanticDelta(a,b);assert.deepEqual(applySemanticDelta(a,d),b);assert.equal(a.scene.text,'old');assert.throws(()=>applySemanticDelta(b,d),/lähtötila/);assert.throws(()=>applySemanticDelta(a,{version:1,changes:[{path:['__proto__','x'],after:1}]}),/estetty/);});
test('incremental resource serialization reuses immutable blob bytes',async()=>{const b=new Blob(['original']);const a=await serializedResource(b);assert.equal(await serializedResource(b),a);assert.equal(new TextDecoder().decode(a),'original');});
test('portable undo and redo roundtrip with real project and checksum validation',async()=>{const bytes=new Uint8Array(await readFile('public/library/Mr.Kille.hahmo')),p=await readProject(new Blob([bytes]));const blob=await saveProject(p.doc,p.animation,p.audio,p.scene);const hash=await sha256(bytes),ref={file:'snapshot-00000000-0000-4000-8000-000000000000.hahmo',hash,size:bytes.length};const portable=await attachHistory(blob,{past:[ref],future:[ref]},async()=>({bytes}));const history=await extractHistory(portable);assert.deepEqual(history?.past[0],bytes);assert.deepEqual(history?.future[0],bytes);assert.equal((await readProject(portable)).doc.width,p.doc.width);assert.equal(await extractHistory(blob),null);await assert.rejects(attachHistory(blob,{past:[{...ref,hash:'0'.repeat(64)}],future:[]},async()=>({bytes})),/tarkistussumma/);});
test('different-size skeleton retarget preserves target pivots, timing and source',async()=>{const p=await readProject(new Blob([new Uint8Array(await readFile('public/library/Mr.Kille.hahmo'))]));const source=structuredClone(p.animation),key=source.rig.parts.find(p=>!p.parentKey)!.key;source.tracks=[{key,frames:[{frame:0,x:4,y:6,rotation:20,scale:1,opacity:1,easing:'hold'}]}];const target=structuredClone(source.rig);target.source.width*=2;target.source.height*=2;for(const part of target.parts){part.pivot.x*=2;part.pivot.y*=2;for(const j of part.joints){j.x*=2;j.y*=2;}}const doc={...p.doc,width:p.doc.width*2,height:p.doc.height*2},mapping=Object.fromEntries(target.parts.map(p=>[p.key,p.key]));const out=retargetMotion(source,target,doc,mapping);assert.equal(out.tracks[0].frames[0].x,8);assert.equal(out.tracks[0].frames[0].rotation,20);assert.equal(source.tracks[0].frames[0].x,4);assert.deepEqual(out.rig.parts[0].pivot,target.parts[0].pivot);assert.throws(()=>retargetMotion(source,target,doc,{}),/vastaavuus/);});

test('incremental ZIP is deterministic, valid and preserves unicode resources',async()=>{const files={'ääni/test':new Uint8Array([1,2,3]),'empty':new Uint8Array()};const a=new Uint8Array(await incrementalZip(files).arrayBuffer()),b=new Uint8Array(await incrementalZip(files).arrayBuffer());assert.deepEqual(a,b);assert.deepEqual(unzipSync(a),files);});

test('serialized command delta reconstructs project metadata from its exact baseline',async()=>{const p=await readProject(new Blob([new Uint8Array(await readFile('public/library/Mr.Kille.hahmo'))]));const base=await saveProject(p.doc,p.animation,p.audio,p.scene),next=await saveProject(p.doc,p.animation,p.audio,{...p.scene,presentationSource:'Muutos'},base),a=unzipSync(new Uint8Array(await base.arrayBuffer())),b=unzipSync(new Uint8Array(await next.arrayBuffer())),command=JSON.parse(strFromU8(b['command-delta.json']));assert.equal(command.base,await sha256(a['project.json']));assert.equal(command.result,await sha256(b['project.json']));assert.deepEqual(applySemanticDelta(JSON.parse(strFromU8(a['project.json'])),command.delta),JSON.parse(strFromU8(b['project.json'])));});
test('semantic rig role suggestions do not guess left/right from broad arm role',()=>{const source={format:'hahmostudio-rig' as const,version:1 as const,source:{name:'a',width:100,height:100},parts:[{key:'a',path:'a',role:'arm' as const,pivot:{x:1,y:1},joints:[]},{key:'b',path:'b',role:'arm' as const,pivot:{x:2,y:2},joints:[]}]},target={...source,parts:source.parts.map(p=>({...p,key:'new'+p.key,path:'new'+p.path}))};assert.deepEqual(suggestMotionMapping(source,target,{leftArm:'a',rightArm:'b'},{leftArm:'newa',rightArm:'newb'}),{a:'newa',b:'newb'});assert.deepEqual(suggestMotionMapping(source,target,{},{}),{});});

test('portable history v2 shares chunks and preserves original archive bytes',async()=>{const bytes=new Uint8Array(await readFile('public/library/Mr.Kille.hahmo')),hash=await sha256(bytes),ref={file:'snapshot-00000000-0000-4000-8000-000000000000.hahmo',hash,size:bytes.length},portable=await attachHistory(new Blob([bytes]),{past:Array.from({length:8},()=>ref),future:[]},async()=>({bytes})),files=unzipSync(new Uint8Array(await portable.arrayBuffer()));assert.equal(JSON.parse(strFromU8(files['history.json'])).version,2);assert.ok(portable.size<bytes.length*4);const extracted=await extractHistory(portable);assert.equal(extracted!.past.length,8);for(const state of extracted!.past)assert.deepEqual(state,bytes);});
