import {flatten} from './psd-model.ts';
import {relinkCharacter} from './studio/character-relink.ts';
import {prepareEditorEdit} from './studio/editor-command.ts';
import {executeProductionCommand,journalProductionCommand} from './studio/production-command.ts';
import {productionResources,verifyAudioRelink} from './studio/resources.ts';
import {validateCommandJournal} from './studio/command-journal.ts';
import {sortProductionShots} from './studio/shot-sort.ts';
import {readShotViews,addShotView,removeShotView,storeShotViews,shotViewKey} from './studio/saved-shot-views.ts';
import {shotChecklist} from './studio/shot-checklist.ts';
import {filterProductionIssues,nextProductionIssue,productionIssues,issueNavigation} from './studio/validation-navigation.ts';
import {exportProductionCsv,csvText,productionCsvFilename} from './studio/production-csv.ts';
import {assignShotTasks,assignShotTask,validateShotTasks,validCalendarDate} from './studio/shot-tasks.ts';
import {productionOverview,filterProductionShots,nextUnfinishedShot} from './studio/production-overview.ts';
import {commentProduction,commentNavigation,validateReviewComments} from './studio/review.ts';
import {unzipSync,zipSync} from 'fflate';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readProject,saveProject} from './project-file.ts';
import {parsePresentation} from './presentation-parser.ts';
import {compilePresentation} from './presentation-compile.ts';
import type {Presentation} from './presentation-model.ts';
import {functions} from './presentation-model.ts';
import {initProduction} from './production-model.ts';
import {adaptPresentation,studioMetadata,TIMEBASE,ticks,seconds,readStudio,revise,selectShot} from './studio/domain.ts';
import {editProduction,reviewShot,replaceDialogueVoice,TransactionHistory,type ProductionState} from './studio/commands.ts';
import {affectedShots} from './studio/shot-impact.ts';
import {inspectRenderSnapshot} from './studio/render-contract.ts';
import {canonicalJson,sha256} from './studio/hash.ts';
const pack=()=>readProject(new Blob([readFileSync(new URL('../public/library/Mr.Kille.hahmo',import.meta.url))]));
async function fixture(){const r=await pack(),assets={kille:{doc:r.doc,animation:r.animation}},voice={name:'voice.wav',blob:new Blob([new Uint8Array(44)],{type:'audio/wav'})};let p=parsePresentation('Kohtaus: cutout-studio-v1\nLAAJA KUVA\nKILLE:\n“Hello.”\nPidä 0,5 sekuntia hiljaisuutta.\nPUOLIKUVA\nKILLE:\n“Goodbye.”');p.natural=true;p.bindings=[{speaker:'KILLE',asset:'kille',voice:'own',side:'left',functions:Object.fromEntries(functions.map(f=>[f,f==='show_phone'?'none':'supported']))}];p.audioClips=p.events.filter(e=>e.kind==='dialogue').map((e,i)=>({id:'voice-'+i,dialogue:e.id,asset:'audio-'+i,start:0,end:1,duration:1,source:'viseme',mouth:[{time:0,shape:'open',viseme:'AI'},{time:1,shape:'rest',viseme:'REST'}]}));p=compilePresentation(p,assets,24);return{r,assets,state:{model:p,voices:{'audio-0':voice,'audio-1':voice}} as ProductionState,voice};}
test('episode/scene/shot identity survives timing and presentation metadata edits',async()=>{const {state}=await fixture(),a=adaptPresentation(state.model),b=adaptPresentation({...state.model,metadata:{...state.model.metadata,title:'Changed'},seconds:4});assert.equal(a.id,b.id);assert.deepEqual(a.shots.map(s=>s.id),b.shots.map(s=>s.id));assert.equal(a.timebase,TIMEBASE);assert.ok(a.scenes.every(s=>s.episodeId===a.id));assert.equal(seconds(ticks(1001/30000)),1001/30000);assert.throws(()=>ticks(-1));assert.throws(()=>readStudio({schemaVersion:1,episodeId:'x',revision:0}));});
test('audio replacement is atomic, retimes following shots, regenerates mouths and invalidates approval; undo restores voices and timing',async()=>{const {state,voice,assets}=await fixture(),before=state.model,episode=adaptPresentation(before);before.production??=initProduction(before);before.production.studio={...studioMetadata(before),shots:{[episode.shots[0].id]:{status:'approved',approvedRevision:1}}};const clip={...before.audioClips[0],asset:'new-audio',duration:2,end:2,mouth:[{time:0,shape:'round' as const,viseme:'O' as const},{time:2,shape:'rest' as const,viseme:'REST' as const}]};const history=new TransactionHistory<typeof state>();const next=replaceDialogueVoice(state,clip,voice,assets,24,1);history.commit(state);assert.equal(next.model.seconds,before.seconds+1);assert.equal(next.model.production!.studio!.shots[episode.shots[0].id].status,'draft');assert.ok(adaptPresentation(next.model).shots[0].duration>episode.shots[0].duration);assert.ok(next.model.actorAnimations!.KILLE.tracks.some(t=>t.key==='MOUTH_O'&&t.frames[0]?.opacity===1));assert.equal(before.audioClips[0].duration,1);const restored=history.undo(next)!;assert.equal(restored.model.seconds,before.seconds);assert.equal(restored.voices['new-audio'],undefined);assert.equal(history.redo(restored)!.model.audioClips.find(c=>c.dialogue===clip.dialogue)!.asset,'new-audio');});
test('locked timing and stale revisions reject the whole dialogue transaction',async()=>{const {state,voice,assets}=await fixture();const before=canonicalJson(state.model),clip={...state.model.audioClips[0],duration:3,end:3,mouth:[{time:0,shape:'rest' as const}]};assert.throws(()=>replaceDialogueVoice(state,clip,voice,assets,24,2),/muuttui/);state.model.events.find(e=>e.id===clip.dialogue)!.locked=true;assert.throws(()=>replaceDialogueVoice(state,clip,voice,assets,24,1),/Lukittu/);assert.equal(state.voices['new-audio'],undefined);delete state.model.events.find(e=>e.id===clip.dialogue)!.locked;assert.equal(canonicalJson(state.model),before);});
test('studio metadata, identity and original voice resources roundtrip in existing hahmo v5',async()=>{const {r,state,assets}=await fixture();state.model.production??=initProduction(state.model);state.model.production.studio=studioMetadata(state.model);state.model.production.studio.rawScript='Unparsed draft';const bytes=await saveProject({...r.doc,presentationAssets:assets,presentationAudio:state.voices},{...r.animation,duration:Math.ceil(state.model.seconds*24)},undefined,{...r.scene,presentationDraft:state.model});const loaded=await readProject(bytes);assert.equal(loaded.scene.presentationDraft!.production!.studio!.rawScript,'Unparsed draft');assert.equal(adaptPresentation(loaded.scene.presentationDraft!).id,adaptPresentation(state.model).id);assert.equal(Object.keys(loaded.doc.presentationAudio!).length,2);});
test('render manifest hashes resources and produces the same revision for repeated identical renders',async()=>{const r=await pack(),preset={id:'test',name:'test',format:'png' as const,width:1080,height:1920,fps:24,start:0,end:2/24,quality:8,transparent:true,audio:false,loop:0},a=new Uint8Array(await(await saveProject(r.doc,r.animation,undefined,r.scene)).arrayBuffer()),first=await inspectRenderSnapshot(a,preset),second=await inspectRenderSnapshot(a,preset);assert.deepEqual(first,second);assert.equal(first.expectedFrames,2);assert.ok(first.assets.every(a=>/^[a-f0-9]{64}$/.test(a.sha256)));assert.equal(first.snapshotHash,await sha256(a));const repacked=new Uint8Array(zipSync(unzipSync(a),{level:0,mtime:new Date('2020-01-01T00:00:00Z')}));const repeated=await inspectRenderSnapshot(repacked,preset);assert.equal(repeated.revisionId,first.revisionId);assert.notEqual(repeated.snapshotHash,first.snapshotHash);await assert.rejects(inspectRenderSnapshot(a,{...preset,end:10}),/keston/);assert.equal(canonicalJson({z:1,a:2}),canonicalJson({a:2,z:1}));});
test('render preflight rejects missing dialogue even if a previous mixed master exists',async()=>{const {r,state,assets,voice}=await fixture();state.model.audioClips=[];const scene={...r.scene,presentations:[state.model]},blob=await saveProject({...r.doc,presentationAssets:assets},{...r.animation,duration:120},voice,scene),preset={id:'test',name:'test',format:'mp4' as const,width:1080,height:1920,fps:24,start:0,end:5,quality:8,transparent:false,audio:true,loop:0};await assert.rejects(inspectRenderSnapshot(new Uint8Array(await blob.arrayBuffer()),preset),/repliikkiääni puuttuu/);});

test('resource manifest detects corrupted bytes before decoding and keeps legacy archives readable',async()=>{const r=await pack(),bytes=new Uint8Array(await(await saveProject(r.doc,r.animation,undefined,r.scene)).arrayBuffer()),files=unzipSync(bytes);assert.ok(files['resource-manifest.json']);const path=Object.keys(files).find(p=>p.startsWith('images/'))!;files[path][files[path].length-1]^=1;await assert.rejects(readProject(new Blob([new Uint8Array(zipSync(files))])),/resurssi.*muuttunut/);delete files['resource-manifest.json'];await readProject(new Blob([new Uint8Array(zipSync(files))]));});
test('scene renaming preserves identity through surviving event IDs',async()=>{const {state}=await fixture(),before=state.model;before.production??=initProduction(before);before.production.studio=studioMetadata(before);const after=structuredClone(before);after.sections=after.sections.map(s=>({...s,id:'renamed-'+s.id,name:'Renamed'}));after.events=after.events.map(e=>({...e,section:'renamed-'+e.section}));after.production!.studio=revise(before,after,'rename');assert.deepEqual(adaptPresentation(after).scenes.map(s=>s.id),adaptPresentation(before).scenes.map(s=>s.id));assert.deepEqual(adaptPresentation(after).shots.map(s=>s.id),adaptPresentation(before).shots.map(s=>s.id));});

test('autosave roundtrips unfinished and lengthened drafts without relaxing committed scene validation',async()=>{const {r,state}=await fixture(),draft=structuredClone(state.model);draft.startFrame=0;const doc=r.doc,animation={...r.animation,duration:2},blob=await saveProject(doc,animation,undefined,{...r.scene,presentationDraft:draft,presentationSource:'Not parsed yet'});const restored=await readProject(blob);assert.equal(restored.scene.presentationDraft!.audioClips.length,2);assert.equal(restored.scene.presentationSource,'Not parsed yet');assert.equal(restored.doc.presentationAssets,undefined);const committed=await saveProject(doc,animation,undefined,{...r.scene,presentations:[draft]});await assert.rejects(readProject(committed),/hahmo puuttuu/);});

test('board and validation navigation resolve a shared event selection and scene-local playhead',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;assert.ok(shots.every(s=>s.duration>0));const shot=shots[1],nav=selectShot(p,shot.id,24);assert.equal(nav.frame,Math.round(seconds(shot.at)*24));assert.equal(nav.eventId,shot.sourceEventId);const line=shot.eventIds.find(id=>p.events.find(e=>e.id===id)?.kind==='dialogue')!;assert.equal(selectShot(p,shot.id,24,line).eventId,line);assert.throws(()=>selectShot(p,shot.id,24,'not-a-member'),/kuulu/);assert.throws(()=>selectShot(p,'missing',24),/löydy/);});

test('reusing a renamed scene key creates a new identity rather than colliding with the preserved scene',async()=>{const {state}=await fixture(),before=state.model;before.production??=initProduction(before);before.production.studio=studioMetadata(before);const after=structuredClone(before),original=before.events[0].section;after.events=after.events.map(e=>({...e,section:'renamed'}));after.events.push({...before.events[0],id:'new-event',section:original,at:before.seconds,duration:1});after.seconds+=1;after.production!.studio=revise(before,after,'rename and append');const scenes=adaptPresentation(after).scenes;assert.equal(scenes.length,2);assert.equal(new Set(scenes.map(s=>s.id)).size,2);assert.equal(scenes[0].id,adaptPresentation(before).scenes[0].id);});

test('a newly inserted scene cannot steal the identity of a renamed existing scene',async()=>{const {state}=await fixture(),before=state.model;before.production??=initProduction(before);before.production.studio=studioMetadata(before);const after=structuredClone(before),original=before.events[0].section;after.events=[{...before.events[0],id:'new-first-event',section:original,at:0,duration:1},...after.events.map(e=>({...e,section:'renamed',at:(e.at??0)+1}))];after.seconds+=1;after.production!.studio=revise(before,after,'insert and rename');const old=adaptPresentation(before).scenes[0].id,scenes=adaptPresentation(after).scenes;assert.notEqual(scenes[0].id,old);assert.equal(scenes[1].id,old);});


test('review approval and lock are transactional, unlocking invalidates approval and content edits invalidate approved shots',async()=>{const {state,assets}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0];const approved=reviewShot(p,shot.id,'approve',1);assert.equal(adaptPresentation(approved).shots[0].status,'approved');assert.equal(studioMetadata(approved).revision,1);const locked=reviewShot(approved,shot.id,'lock',1);assert.equal(adaptPresentation(locked).shots[0].status,'locked');assert.throws(()=>editProduction(locked,{...locked,metadata:{...locked.metadata,title:'Changed'}},assets,24,1),/lukittu/);const unlocked=reviewShot(locked,shot.id,'unlock',1);assert.equal(adaptPresentation(unlocked).shots[0].status,'draft');const next=editProduction(approved,{...approved,metadata:{...approved.metadata,title:'Edited'}},assets,24,1);assert.equal(studioMetadata(next).revision,2);assert.equal(adaptPresentation(next).shots[0].status,'draft');const history=new TransactionHistory<Presentation>();history.commit(approved);assert.deepEqual(history.undo(next),approved);assert.equal(adaptPresentation(p).shots[0].status,'draft');});
test('approval rejects missing audio, failed validation, stale revision and illegal review transitions',async()=>{const {state}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0];assert.throws(()=>reviewShot(p,shot.id,'lock',1),/Hyväksy/);assert.throws(()=>reviewShot(p,shot.id,'approve',2),/muuttui/);assert.throws(()=>reviewShot({...p,audioClips:[]},shot.id,'approve',1),/äänet/);assert.throws(()=>reviewShot({...p,diagnostics:[{code:'missing',severity:'error',message:'Broken'}]},shot.id,'approve',1),/virheet/);});


test('a later camera edit preserves an earlier locked shot and only invalidates dependent approvals',async()=>{const {state,assets}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;let approved=reviewShot(p,shots[0].id,'approve',1);approved=reviewShot(approved,shots[1].id,'approve',1);const locked=reviewShot(approved,shots[0].id,'lock',1),proposal=structuredClone(locked),id=shots[1].sourceEventId;proposal.production!.cameras[id]={...proposal.production!.cameras[id],zoom:.2};const next=editProduction(locked,proposal,assets,24,1),result=adaptPresentation(next).shots;assert.equal(result[0].status,'locked');assert.equal(result[1].status,'draft');assert.equal(next.production!.studio!.shots[shots[0].id].approvedRevision,2);assert.equal(studioMetadata(locked).revision,1);assert.equal(adaptPresentation(locked).shots[1].status,'approved');});
test('earlier dialogue retiming cannot shift a later locked shot and rejection preserves audio and approval',async()=>{const {state,assets,voice}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,locked=reviewShot(reviewShot(p,shots[1].id,'approve',1),shots[1].id,'lock',1),before=canonicalJson(locked),clip={...locked.audioClips[0],asset:'longer',duration:2,end:2};assert.throws(()=>replaceDialogueVoice({...state,model:locked},clip,voice,assets,24,1),/lukittu/);assert.equal(canonicalJson(locked),before);assert.equal(state.voices.longer,undefined);});
test('global framing and deletion remain blocked when they affect a locked shot',async()=>{const {state,assets}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0],locked=reviewShot(reviewShot(p,shot.id,'approve',1),shot.id,'lock',1);assert.throws(()=>editProduction(locked,{...locked,world:{...locked.world,width:1920}},assets,24,1),/lukittu/);const proposal=structuredClone(locked);proposal.events=proposal.events.filter(e=>e.id!==shot.sourceEventId);assert.throws(()=>editProduction(locked,proposal,assets,24,1),/lukittu/);});


test('interpolation beyond a shot boundary and animation truncation remain protected dependencies',async()=>{const {state}=await fixture(),p=structuredClone(state.model),shots=adaptPresentation(p).shots,a=p.actorAnimations!.KILLE,boundary=seconds(shots[0].at+shots[0].duration)*a.fps;const pose={x:0,y:0,rotation:0,scale:1,opacity:1,easing:'linear' as const};a.tracks=[{key:'controlled',frames:[{...pose,frame:0},{...pose,frame:Math.ceil(boundary)+10,x:10}]}];const changed=structuredClone(p);changed.actorAnimations!.KILLE.tracks[0].frames[1].x=20;assert.ok(affectedShots(p,changed).has(shots[0].id));const truncated=structuredClone(p);truncated.actorAnimations!.KILLE.duration=1;assert.ok(affectedShots(p,truncated).has(shots[0].id));});


test('review comments persist in hahmo, block approval while open, resolve and reopen in one undo transaction',async()=>{const {state,r,assets}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0],withComment=commentProduction(p,{kind:'add',shotId:shot.id,offset:0,body:'  Tarkista käden liike.  '},1),comment=studioMetadata(withComment).reviewComments![0];assert.equal(comment.body,'Tarkista käden liike.');assert.equal(studioMetadata(withComment).revision,1);assert.equal(studioMetadata(p).reviewComments,undefined);assert.throws(()=>reviewShot(withComment,shot.id,'approve',1),/kommentit/);const resolved=commentProduction(withComment,{kind:'resolve',id:comment.id},1),approved=reviewShot(resolved,shot.id,'approve',1),reopened=commentProduction(approved,{kind:'reopen',id:comment.id},1);assert.equal(adaptPresentation(reopened).shots[0].status,'draft');assert.equal(studioMetadata(reopened).reviewComments![0].resolvedAt,undefined);const history=new TransactionHistory<Presentation>();history.commit(approved);assert.deepEqual(history.undo(reopened),approved);const bytes=await saveProject({...r.doc,presentationAssets:assets,presentationAudio:state.voices},{...r.animation,duration:Math.ceil(p.seconds*24)},undefined,{...r.scene,presentationDraft:resolved});const loaded=await readProject(bytes);assert.deepEqual(studioMetadata(loaded.scene.presentationDraft!).reviewComments,studioMetadata(resolved).reviewComments);});
test('comment navigation follows shot retiming, clamps shortened shots and preserves orphan feedback',async()=>{const {state}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[1],annotated=commentProduction(p,{kind:'add',shotId:shot.id,offset:Math.floor(shot.duration*.9),body:'Tarkista tämä kohta.'},1),comment=studioMetadata(annotated).reviewComments![0],before=commentNavigation(annotated,comment,24)!;const retimed=structuredClone(annotated);retimed.events=retimed.events.map(e=>({...e,at:(e.at??0)+1}));retimed.seconds+=1;assert.equal(commentNavigation(retimed,comment,24)!.frame,before.frame+24);const shorter=structuredClone(annotated);shorter.seconds=seconds(shot.at)+.1;shorter.events=shorter.events.map(e=>({...e,duration:Math.min(e.duration??0,.1)}));assert.equal(commentNavigation(shorter,comment,24)!.clamped,true);assert.ok(commentNavigation(shorter,comment,24)!.frame<Math.ceil(shorter.seconds*24));const removed=structuredClone(annotated);removed.events=removed.events.filter(e=>e.id!==shot.sourceEventId);assert.equal(commentNavigation(removed,comment,24),null);assert.equal(studioMetadata(removed).reviewComments![0].body,comment.body);});
test('comments on approved shots invalidate only their approval; locked content remains locked while feedback is handled',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,approved=reviewShot(reviewShot(p,shots[0].id,'approve',1),shots[1].id,'approve',1),annotated=commentProduction(approved,{kind:'add',shotId:shots[0].id,offset:0,body:'Korjauspyyntö'},1);assert.equal(adaptPresentation(annotated).shots[0].status,'draft');assert.equal(adaptPresentation(annotated).shots[1].status,'approved');const locked=reviewShot(approved,shots[0].id,'lock',1),lockedNote=commentProduction(locked,{kind:'add',shotId:shots[0].id,offset:0,body:'Huomio lukittuun kuvaan'},1);assert.equal(adaptPresentation(lockedNote).shots[0].status,'locked');const fixed=commentProduction(lockedNote,{kind:'resolve',id:studioMetadata(lockedNote).reviewComments![0].id},1);assert.equal(adaptPresentation(fixed).shots[0].status,'locked');});
test('malformed, oversized, stale and out-of-shot review data is rejected without mutating the model',async()=>{const {state}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0],before=canonicalJson(p);assert.throws(()=>commentProduction(p,{kind:'add',shotId:shot.id,offset:shot.duration,body:'Outside'},1),/sisällä/);assert.throws(()=>commentProduction(p,{kind:'add',shotId:shot.id,offset:0,body:'x'.repeat(4001)},1),/4000/);assert.throws(()=>commentProduction(p,{kind:'add',shotId:shot.id,offset:0,body:'stale'},2),/muuttui/);const note=studioMetadata(commentProduction(p,{kind:'add',shotId:shot.id,offset:0,body:'valid'},1)).reviewComments![0];assert.throws(()=>validateReviewComments([note,note],1));assert.throws(()=>validateReviewComments([{...note,status:'resolved'}],1));assert.throws(()=>readStudio({...studioMetadata(p),reviewComments:[{...note,offset:-1}]}));assert.throws(()=>validateReviewComments(Array(1001).fill(note),1));assert.equal(canonicalJson(p),before);});


test('production overview counts distinct shots, keeps review readiness separate from approval and never mutates data',async()=>{const {state}=await fixture(),p=state.model,before=canonicalJson(p),overview=productionOverview(p);assert.equal(overview.counts.all,2);assert.equal(overview.counts.ready,2);assert.equal(overview.counts.approved,0);assert.equal(overview.counts.attention,0);const shots=overview.episode.shots,approved=reviewShot(p,shots[0].id,'approve',1),locked=reviewShot(approved,shots[0].id,'lock',1),annotated=commentProduction(locked,{kind:'add',shotId:shots[0].id,offset:0,body:'Palautetta'},1),result=productionOverview(annotated);assert.equal(result.counts.locked,1);assert.equal(result.counts.attention,1);assert.equal(result.counts.comments,1);assert.equal(result.counts.ready,1);assert.equal(result.counts.draft+result.counts.approved+result.counts.locked,result.counts.all);assert.equal(canonicalJson(p),before);});
test('production filters combine status, comments, missing voice references and Finnish character/scene search',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,missing={...p,audioClips:p.audioClips.filter(c=>c.dialogue!==p.events.find(e=>shots[1].eventIds.includes(e.id)&&e.kind==='dialogue')!.id)},overview=productionOverview(missing);assert.equal(filterProductionShots(overview,'missingAudio').length,1);assert.equal(filterProductionShots(overview,'attention').length,1);assert.equal(filterProductionShots(overview,'ready').length,1);assert.equal(filterProductionShots(overview,'all',' kille ').length,2);assert.equal(filterProductionShots(overview,'all',overview.episode.scenes[0].name.toLocaleUpperCase('fi-FI')).length,2);assert.equal(filterProductionShots(overview,'approved').length,0);assert.equal(filterProductionShots(overview,'all','does-not-exist').length,0);});
test('next unfinished navigation wraps, includes feedback on locked shots and returns none when all have no outstanding work',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,approved=reviewShot(reviewShot(p,shots[0].id,'approve',1),shots[1].id,'approve',1);assert.equal(nextUnfinishedShot(productionOverview(approved)),undefined);assert.equal(nextUnfinishedShot(productionOverview(p),shots[0].id)!.id,shots[1].id);assert.equal(nextUnfinishedShot(productionOverview(p),shots[1].id)!.id,shots[0].id);const locked=reviewShot(approved,shots[0].id,'lock',1),noted=commentProduction(locked,{kind:'add',shotId:shots[0].id,offset:0,body:'Huomio'},1);assert.equal(nextUnfinishedShot(productionOverview(noted),shots[1].id)!.id,shots[0].id);});
test('overview reports orphan feedback and empty drafts without inventing production-ready shots',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,noted=commentProduction(p,{kind:'add',shotId:shots[1].id,offset:0,body:'Säilytä tämä palaute'},1),removed={...noted,events:noted.events.filter(e=>e.id!==shots[1].sourceEventId)},overview=productionOverview(removed);assert.equal(overview.orphanComments,1);assert.equal(overview.openComments,1);assert.equal(overview.counts.comments,0);const empty=productionOverview({...noted,events:[]});assert.equal(empty.counts.all,0);assert.equal(empty.counts.ready,0);assert.equal(empty.orphanComments,1);assert.equal(nextUnfinishedShot(empty),undefined);});


test('shot assignments roundtrip in hahmo, preserve approval and locks, and undo removes the entire scheduling transaction',async()=>{const {state,r,assets}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0],locked=reviewShot(reviewShot(p,shot.id,'approve',1),shot.id,'lock',1),assigned=assignShotTask(locked,{shotId:shot.id,owner:'  Aleksi  ',dueDate:'2026-10-05'},1);assert.equal(studioMetadata(assigned).shotTasks![shot.id].owner,'Aleksi');assert.equal(adaptPresentation(assigned).shots[0].status,'locked');assert.equal(studioMetadata(assigned).revision,1);assert.equal(studioMetadata(locked).shotTasks,undefined);const history=new TransactionHistory<Presentation>();history.commit(locked);assert.deepEqual(history.undo(assigned),locked);const bytes=await saveProject({...r.doc,presentationAssets:assets,presentationAudio:state.voices},{...r.animation,duration:Math.ceil(p.seconds*24)},undefined,{...r.scene,presentationDraft:assigned});const restored=await readProject(bytes);assert.deepEqual(studioMetadata(restored.scene.presentationDraft!).shotTasks,studioMetadata(assigned).shotTasks);const cleared=assignShotTask(assigned,{shotId:shot.id,owner:'',dueDate:''},1);assert.deepEqual(studioMetadata(cleared).shotTasks,{});});
test('deadline filters use a supplied calendar date, exclude finished shots and include unresolved feedback',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;let assigned=assignShotTask(p,{shotId:shots[0].id,owner:'Aleksi',dueDate:'2026-10-04'},1);assert.equal(productionOverview(assigned,'2026-10-04').counts.overdue,0);assert.equal(productionOverview(assigned,'2026-10-05').counts.overdue,1);assert.equal(productionOverview(assigned,'2026-10-05').counts.unassigned,1);assert.equal(filterProductionShots(productionOverview(assigned,'2026-10-05'),'overdue')[0].id,shots[0].id);assert.equal(filterProductionShots(productionOverview(assigned,'2026-10-05'),'all',' aleksi ').length,1);assigned=reviewShot(assigned,shots[0].id,'approve',1);assert.equal(productionOverview(assigned,'2026-10-05').counts.overdue,0);const noted=commentProduction(assigned,{kind:'add',shotId:shots[0].id,offset:0,body:'Palautetta'},1);assert.equal(productionOverview(noted,'2026-10-05').counts.overdue,1);assert.equal(filterProductionShots(productionOverview(noted,'2026-10-05'),'unassigned').length,1);});
test('invalid calendar dates, oversized owners, stale revisions and invalid assignment schema reject atomically',async()=>{const {state}=await fixture(),p=state.model,shot=adaptPresentation(p).shots[0],before=canonicalJson(p);assert.equal(validCalendarDate('2028-02-29'),true);for(const date of ['2026-02-29','2026-13-01','2026-01-32','10/05/2026']){assert.equal(validCalendarDate(date),false);assert.throws(()=>assignShotTask(p,{shotId:shot.id,owner:'Aleksi',dueDate:date},1));}assert.throws(()=>assignShotTask(p,{shotId:shot.id,owner:'x'.repeat(121),dueDate:''},1));assert.throws(()=>assignShotTask(p,{shotId:shot.id,owner:'Aleksi',dueDate:''},2),/muuttui/);assert.throws(()=>validateShotTasks({bad:{owner:'Aleksi',updatedAt:'invalid'}}));assert.throws(()=>readStudio({...studioMetadata(p),shotTasks:{bad:{dueDate:'2026-02-29',updatedAt:new Date().toISOString()}}}));assert.equal(canonicalJson(p),before);});
test('assignment follows stable shot identity through retiming and preserves orphan scheduling data without counting it as active work',async()=>{const {state,assets}=await fixture(),p=state.model,shots=adaptPresentation(p).shots,assigned=assignShotTask(p,{shotId:shots[1].id,owner:'Salla',dueDate:'2026-10-03'},1),proposal=structuredClone(assigned);proposal.production!.cameras[shots[1].sourceEventId].zoom=.2;const next=editProduction(assigned,proposal,assets,24,1);assert.deepEqual(studioMetadata(next).shotTasks,studioMetadata(assigned).shotTasks);const deleted={...next,events:next.events.filter(e=>e.id!==shots[1].sourceEventId)};assert.ok(studioMetadata(deleted).shotTasks![shots[1].id]);assert.equal(productionOverview(deleted,'2026-10-04').counts.overdue,0);});


test('production CSV preserves exact IDs/ticks, revision and calendar date without mutating the project',async()=>{const {state}=await fixture(),p=state.model,before=canonicalJson(p),overview=productionOverview(p,'2026-10-04'),csv=exportProductionCsv(overview);assert.ok(csv.startsWith('\uFEFF'));const lines=csv.slice(1).trimEnd().split('\r\n');assert.equal(lines.length,3);assert.ok(lines[0].includes('"Alku (tick)"'));assert.ok(lines[1].includes(csvText(overview.episode.shots[0].id)));assert.ok(lines[1].includes('"2026-10-04"'));assert.ok(lines[2].includes(csvText(String(overview.episode.shots[1].at))));assert.equal(csv,exportProductionCsv(productionOverview(p,'2026-10-04')));assert.equal(canonicalJson(p),before);});
test('filtered production CSV includes every matched shot and resolves supplied IDs against the authoritative overview',async()=>{const {state}=await fixture(),overview=productionOverview(state.model,'2026-10-04'),selected=overview.episode.shots[1],csv=exportProductionCsv(overview,[{...selected,name:'stale fake name'}]);assert.ok(csv.includes(csvText(selected.name)));assert.ok(!csv.includes('stale fake name'));assert.ok(!csv.includes(csvText(overview.episode.shots[0].id)));assert.throws(()=>exportProductionCsv(overview,[selected,selected]),/kahdesti/);assert.throws(()=>exportProductionCsv(overview,[{...selected,id:'unknown'}]),/valmisteluun/);assert.equal(exportProductionCsv(overview,[]).split('\r\n').length,2);});
test('CSV quotes separators/newlines and neutralizes formula prefixes; filenames stay within a single safe leaf',()=>{assert.equal(csvText('Hei; "Aleksi"\nToinen rivi'),'"Hei; ""Aleksi""\nToinen rivi"');for(const text of ['=1+1','+SUM(A1)','-1','@command',' \t=1+1'])assert.ok(csvText(text).startsWith('"\''));assert.equal(csvText('Tavallinen teksti'),'"Tavallinen teksti"');assert.equal(productionCsvFilename('../A:B/C\\D?'),'A-B-C-D-tyojono.csv');assert.equal(productionCsvFilename('...'),'Jakso-tyojono.csv');assert.ok(!/[\\/\u0000-\u001f]/.test(productionCsvFilename('Kuva\n../Nimi')));});

test('batch scheduling preserves independent fields and locked shots, undo restores all targets',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;let base=assignShotTask(p,{shotId:shots[0].id,owner:'Original',dueDate:'2026-10-10'},1);base=reviewShot(reviewShot(base,shots[0].id,'approve',1),shots[0].id,'lock',1);const before=canonicalJson(base),next=assignShotTasks(base,{shotIds:shots.map(s=>s.id),owner:'  Aleksi  '},1);assert.equal(studioMetadata(next).shotTasks![shots[0].id].dueDate,'2026-10-10');assert.ok(shots.every(s=>studioMetadata(next).shotTasks![s.id].owner==='Aleksi'));assert.equal(adaptPresentation(next).shots[0].status,'locked');assert.equal(studioMetadata(next).revision,1);assert.deepEqual(next.events,base.events);assert.equal(canonicalJson(base),before);const history=new TransactionHistory<Presentation>();history.commit(base);assert.deepEqual(history.undo(next),base);const clear=assignShotTasks(next,{shotIds:[shots[0].id],owner:''},1);assert.equal(studioMetadata(clear).shotTasks![shots[0].id].owner,undefined);assert.equal(studioMetadata(clear).shotTasks![shots[0].id].dueDate,'2026-10-10');assert.equal(studioMetadata(clear).shotTasks![shots[1].id].owner,'Aleksi');const cleared=assignShotTasks(clear,{shotIds:[shots[0].id],dueDate:''},1);assert.equal(studioMetadata(cleared).shotTasks![shots[0].id],undefined);});
test('batch scheduling validates all targets before atomic commit',async()=>{const {state}=await fixture(),p=state.model,id=adaptPresentation(p).shots[0].id,before=canonicalJson(p);for(const command of [{shotIds:[],owner:'A'},{shotIds:[id,id],owner:'A'},{shotIds:[id,'unknown'],owner:'A'},{shotIds:[id]},{shotIds:[id],dueDate:'2026-02-29'},{shotIds:[id],owner:'x'.repeat(121)}])assert.throws(()=>assignShotTasks(p,command,1));assert.throws(()=>assignShotTasks(p,{shotIds:[id],owner:'A'},2),/muuttui/);assert.equal(canonicalJson(p),before);});

test('validation navigation uses actual event, shot and playhead without changing the project',async()=>{const {state}=await fixture(),p=structuredClone(state.model),shot=adaptPresentation(p).shots[1],event=p.events.find(e=>shot.eventIds.includes(e.id))!;p.diagnostics=[{code:'camera-2d-view',severity:'error',message:'Test',event:event.id}];const before=canonicalJson(p),issues=productionIssues(p),nav=issueNavigation(p,issues[0].id,24)!;assert.equal(nav.shot.id,shot.id);assert.equal(nav.eventId,event.id);assert.equal(nav.frame,Math.round((event.at??0)*24));assert.match(issues[0].recommendation,/kamera/);assert.equal(canonicalJson(p),before);});
test('global and orphan diagnostics never navigate to an arbitrary shot; missing dialogue is explicit',async()=>{const {state}=await fixture(),p=structuredClone(state.model);p.diagnostics=[{code:'global',severity:'warning',message:'Global'},{code:'rig',severity:'error',message:'Gone',event:'deleted'}];p.audioClips=[];const issues=productionIssues(p);assert.equal(issues[0].scope,'project');assert.equal(issues[1].scope,'orphan');assert.equal(issueNavigation(p,issues[0].id,24),undefined);assert.equal(issueNavigation(p,issues[1].id,24),undefined);assert.equal(issueNavigation(p,'unknown',24),undefined);const audio=issues.find(i=>i.code==='missing-audio-reference')!;assert.ok(audio);assert.ok(issueNavigation(p,audio.id,24));assert.match(audio.recommendation,/äänitiedosto/);assert.equal(productionIssues({...p,events:[],diagnostics:[]}).length,0);});

test('shot checklist separates approval from audio references, global errors and open feedback',async()=>{const {state}=await fixture(),p=state.model,id=adaptPresentation(p).shots[0].id,before=canonicalJson(p),list=shotChecklist(p,id)!;assert.equal(list.checks.find(c=>c.id==='approval')!.ok,false);assert.equal(shotChecklist(p,'unknown'),undefined);const approved=reviewShot(p,id,'approve',1);assert.equal(shotChecklist(approved,id)!.checks.find(c=>c.id==='approval')!.ok,true);const bad={...approved,diagnostics:[{code:'global',severity:'error' as const,message:'Error'}],audioClips:[]};const checks=shotChecklist(bad,id)!.checks;assert.equal(checks.find(c=>c.id==='approval')!.ok,true);assert.equal(checks.find(c=>c.id==='diagnostics')!.ok,false);assert.equal(checks.find(c=>c.id==='audio')!.ok,false);const noted=commentProduction(p,{kind:'add',shotId:id,offset:0,body:'Fix'},1);assert.equal(shotChecklist(noted,id)!.checks.find(c=>c.id==='comments')!.ok,false);assert.equal(canonicalJson(p),before);});

test('saved work queue views roundtrip only local search criteria and preserve their source',()=>{const empty=readShotViews(null),view={id:'view-1',name:'  Omat  ',filter:'overdue' as const,query:'Aleksi'},next=addShotView(empty,view);assert.deepEqual(empty.views,[]);assert.equal(next.views[0].name,'Omat');let stored='';storeShotViews({setItem:(key,value)=>{assert.equal(key,shotViewKey);stored=value;}},next);assert.deepEqual(readShotViews(stored),next);assert.deepEqual(removeShotView(next,'view-1'),empty);assert.equal(next.views.length,1);assert.throws(()=>storeShotViews({setItem:()=>{throw Error('quota');}},next));assert.equal(next.views.length,1);});
test('saved work queue views reject unsupported schemas, duplicate names/IDs and unbounded data',()=>{const v={id:'id',name:'Omat',filter:'all' as const,query:''},data=addShotView(readShotViews(null),v);for(const raw of ['{',JSON.stringify({schemaVersion:2,views:[]}),JSON.stringify({schemaVersion:1,views:[{...v,filter:'unknown'}]}),JSON.stringify({schemaVersion:1,views:[{...v,query:'x'.repeat(501)}]}),JSON.stringify({schemaVersion:1,views:[{...v,name:' '}]}),'x'.repeat(40001)])assert.throws(()=>readShotViews(raw));assert.throws(()=>addShotView(data,{...v,id:'other',name:' OMAT '}));assert.throws(()=>addShotView(data,{...v,name:'Other'}));const full=readShotViews(JSON.stringify({schemaVersion:1,views:Array.from({length:20},(_,i)=>({...v,id:'v'+i,name:'N'+i}))}));assert.throws(()=>addShotView(full,{...v,id:'last',name:'Last'}));});

test('work queue sorting is stable, read-only and missing fields are last',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;const assigned=assignShotTasks(p,{shotIds:[shots[1].id],owner:'Aleksi',dueDate:'2026-10-05'},1),overview=productionOverview(assigned),before=canonicalJson(assigned),input=[...overview.episode.shots];for(const mode of ['deadline','owner'] as const)assert.equal(sortProductionShots(overview,input,mode)[0].id,shots[1].id);assert.deepEqual(sortProductionShots(overview,[...input].reverse(),'timeline'),input);assert.deepEqual(sortProductionShots(overview,input,'status'),input);assert.equal(canonicalJson(assigned),before);assert.deepEqual(input,overview.episode.shots);const approved=reviewShot(p,shots[0].id,'approve',1),ordered=sortProductionShots(productionOverview(approved),adaptPresentation(approved).shots,'status');assert.equal(ordered[0].id,shots[1].id);});
test('saved views retain optional sorting and legacy views use episode order',()=>{const old=readShotViews(JSON.stringify({schemaVersion:1,views:[{id:'old',name:'Old',filter:'all',query:''}]}));assert.equal(old.views[0].sort??'timeline','timeline');const next=addShotView(old,{id:'new',name:'New',filter:'draft',query:'A',sort:'deadline'});assert.equal(readShotViews(JSON.stringify(next)).views[1].sort,'deadline');assert.throws(()=>readShotViews(JSON.stringify({schemaVersion:1,views:[{...old.views[0],sort:'unknown'}]})));});

test('production workflow integrates assignments, feedback, approval, archive, views, CSV and render preflight',async()=>{
 const {r,state,assets,voice}=await fixture(),original=canonicalJson(state.model),ids=adaptPresentation(state.model).shots.map(s=>s.id);
 const assigned=assignShotTasks(state.model,{shotIds:ids,owner:'Aleksi',dueDate:'2026-10-05'},1),history=new TransactionHistory<Presentation>();history.commit(state.model);assert.deepEqual(history.undo(assigned),state.model);assert.deepEqual(history.redo(state.model),assigned);
 const commented=commentProduction(assigned,{kind:'add',shotId:ids[0],offset:0,body:'Tarkista ajoitus'},1);assert.throws(()=>reviewShot(commented,ids[0],'approve',1));
 const comment=studioMetadata(commented).reviewComments![0];
 const resolved=commentProduction(commented,{kind:'resolve',id:comment.id},1),approved=reviewShot(resolved,ids[0],'approve',1),locked=reviewShot(approved,ids[0],'lock',1);
 const blob=await saveProject({...r.doc,presentationAssets:assets,presentationAudio:state.voices},{...r.animation,duration:Math.ceil(locked.seconds*24)},voice,{...r.scene,presentations:[locked],presentationDraft:locked});
 const restored=await readProject(blob),model=restored.scene.presentationDraft!,overview=productionOverview(model,'2026-10-06');
 assert.deepEqual(overview.episode.shots.map(s=>s.id),ids);assert.equal(overview.episode.shots[0].status,'locked');assert.equal(overview.openComments,0);assert.equal(overview.counts.overdue,1);
 const view=readShotViews(JSON.stringify(addShotView(readShotViews(null),{id:'integration',name:'Aleksin jono',query:'Aleksi',filter:'overdue',sort:'deadline',descending:true}))).views[0];
 const result=sortProductionShots(overview,filterProductionShots(overview,view.filter,view.query),view.sort!,view.descending);assert.equal(result.length,1);assert.equal(result[0].id,ids[1]);
 const csv=exportProductionCsv(overview,result);assert.ok(csv.includes(ids[1]));assert.ok(!csv.includes(ids[0]));assert.ok(shotChecklist(model,ids[0])!.checks.every(c=>c.ok));
 const preset={id:'integration',name:'Integration',format:'mp4' as const,width:1080,height:1920,fps:24,start:0,end:locked.seconds,quality:8,transparent:false,audio:true,loop:0},bytes=new Uint8Array(await blob.arrayBuffer()),manifest=await inspectRenderSnapshot(bytes,preset);assert.equal(manifest.expectedFrames,Math.ceil(locked.seconds*24));assert.deepEqual(await inspectRenderSnapshot(bytes,preset),manifest);assert.ok(manifest.assets.length>0);assert.equal(canonicalJson(state.model),original);
});
test('validation search and next issue skip non-actionable targets and wrap within results',async()=>{const {state}=await fixture(),p=state.model,e=p.events[0];const issues=productionIssues({...p,diagnostics:[{code:'global',severity:'error',message:'Camera global'},{code:'camera-one',severity:'warning',message:'Kamera',event:e.id},{code:'camera-gone',severity:'error',message:'Kamera',event:'gone'}]});const filtered=filterProductionIssues(issues,'all',' KAMERA ');assert.equal(filtered.length,2);const next=nextProductionIssue(filtered)!;assert.equal(next.code,'camera-one');assert.equal(nextProductionIssue(filtered,next.id)!.id,next.id);assert.equal(nextProductionIssue(filterProductionIssues(issues,'error','Kamera')),undefined);assert.equal(filterProductionIssues(issues,'all','nonexistent').length,0);});
test('descending scheduling keeps missing values last and ties in episode order; saved view roundtrip retains direction',async()=>{const {state}=await fixture(),p=state.model,shots=adaptPresentation(p).shots;let assigned=assignShotTask(p,{shotId:shots[0].id,owner:'A',dueDate:'2026-10-05'},1);assigned=assignShotTask(assigned,{shotId:shots[1].id,owner:'Z',dueDate:'2026-10-06'},1);const overview=productionOverview(assigned),list=overview.episode.shots;assert.equal(sortProductionShots(overview,list,'deadline',true)[0].id,shots[1].id);assert.equal(sortProductionShots(overview,list,'owner',true)[0].id,shots[1].id);assert.deepEqual(sortProductionShots(overview,list,'status',true),list);assert.deepEqual(sortProductionShots(overview,list,'timeline',true),[...list].reverse());const missing=productionOverview(assignShotTask(assigned,{shotId:shots[1].id,owner:'',dueDate:''},1));assert.equal(sortProductionShots(missing,missing.episode.shots,'deadline',true)[0].id,shots[0].id);const data=addShotView(readShotViews(null),{id:'desc',name:'Desc',filter:'all',query:'',sort:'owner',descending:true});assert.equal(readShotViews(JSON.stringify(data)).views[0].descending,true);assert.throws(()=>readShotViews(JSON.stringify({...data,views:[{...data.views[0],descending:'yes'}]})));});

test('500-shot work queue sorting and CSV include the entire result without mutating production order',async()=>{const {state}=await fixture(),base=productionOverview(state.model),template=base.episode.shots[0],shots=Array.from({length:500},(_,i)=>({...template,id:'bulk-'+i,name:'Bulk '+i,status:'draft' as const})),tasks=Object.fromEntries(shots.filter((_,i)=>i%2===0).map(s=>[s.id,{owner:'Aleksi',dueDate:'2026-10-05',updatedAt:'2026-10-04T00:00:00Z'}])),overview={...base,episode:{...base.episode,shots},tasks};const before=canonicalJson(shots);for(const descending of [false,true]){const result=sortProductionShots(overview,shots,'deadline',descending);assert.equal(result.length,500);assert.equal(new Set(result.map(s=>s.id)).size,500);assert.ok(result.slice(0,250).every(s=>tasks[s.id]));assert.ok(result.slice(250).every(s=>!tasks[s.id]));assert.deepEqual(result.slice(0,250).map(s=>s.id),shots.filter((_,i)=>i%2===0).map(s=>s.id));const csv=exportProductionCsv(overview,result);assert.equal(csv.split('\r\n').length,502);assert.ok(csv.includes('bulk-499'));}assert.equal(canonicalJson(shots),before);});

test('command boundary journals transactions, persists history and rejects missing resources before approval',async()=>{const {state,assets,r}=await fixture(),id=adaptPresentation(state.model).shots[0].id,next=executeProductionCommand(state,{kind:'tasks',command:{shotIds:[id],owner:'Aleksi'}},assets,24,1);assert.equal(studioMetadata(next.model).commandJournal!.length,1);assert.equal(studioMetadata(state.model).commandJournal,undefined);assert.equal(studioMetadata(next.model).commandJournal![0].kind,'tasks');assert.throws(()=>executeProductionCommand({...next,voices:{}},{kind:'review',shotId:id,action:'approve'},assets,24,1),/Resurssi puuttuu/);const approved=executeProductionCommand(next,{kind:'review',shotId:id,action:'approve'},assets,24,1);assert.equal(studioMetadata(approved.model).commandJournal!.length,2);const blob=await saveProject({...r.doc,presentationAssets:assets,presentationAudio:approved.voices},{...r.animation,duration:Math.ceil(approved.model.seconds*24)},undefined,{...r.scene,presentationDraft:approved.model});const restored=await readProject(blob);assert.deepEqual(studioMetadata(restored.scene.presentationDraft!).commandJournal,studioMetadata(approved.model).commandJournal);assert.throws(()=>executeProductionCommand(next,{kind:'review',shotId:id,action:'lock'},assets,24,2),/muuttui/);});
test('content-addressed audio restoration checks SHA-256, preserves approval and is atomic with undo',async()=>{const {state,assets,voice}=await fixture(),digest='audio-'+await sha256(new Uint8Array(await voice.blob.arrayBuffer())),model=structuredClone(state.model);model.audioClips[0].asset=digest;const id=adaptPresentation(model).shots[0].id,approved=reviewShot(model,id,'approve',1),missing={model:approved,voices:{'audio-1':voice}};assert.ok(productionResources(missing,assets).some(r=>!r.available));assert.equal(await verifyAudioRelink(digest,voice),voice);await assert.rejects(verifyAudioRelink(digest,{name:'same.wav',blob:new Blob([new Uint8Array([9])])}),/ei ole alkuperäinen/);await assert.rejects(verifyAudioRelink('legacy-id',voice),/SHA-256/);const next=journalProductionCommand(missing,{...missing,voices:{...missing.voices,[digest]:voice}},'relink-audio');assert.equal(adaptPresentation(next.model).shots[0].status,'approved');assert.deepEqual(next.model.audioClips,approved.audioClips);assert.equal(studioMetadata(next.model).revision,1);assert.ok(productionResources(next,assets).every(r=>r.available));const history=new TransactionHistory<ProductionState>();history.commit(missing);const undo=history.undo(next)!;assert.equal(undo.voices[digest],undefined);assert.ok(history.redo(undo)!.voices[digest]);});
test('transaction history owns snapshots and journal validation rejects invalid records',()=>{const history=new TransactionHistory<{values:number[]}>(2),original={values:[1]};history.commit(original);original.values[0]=9;const current={values:[2]},undo=history.undo(current)!;assert.deepEqual(undo.values,[1]);current.values[0]=8;assert.deepEqual(history.redo(undo)!.values,[2]);assert.throws(()=>validateCommandJournal([{id:'bad'}]));assert.throws(()=>validateCommandJournal(Array.from({length:101},()=>({}))));});

test('bind-cast command journals speaker hahmo attachment',async()=>{const {state,assets}=await fixture(),speaker=state.model.characters[0]!,before=studioMetadata(state.model).revision,next=executeProductionCommand(state,{kind:'bind-cast',speaker,assetId:'kille'},assets,24,before);assert.equal(studioMetadata(next.model).commandJournal!.at(-1)!.kind,'bind-cast');assert.equal(next.model.bindings.find(b=>b.speaker===speaker)?.asset,'kille');assert.equal(studioMetadata(next.model).revision,before+1);});

test('central production commands cover edit, voice, scheduling, comments and review with bounded validated history',async()=>{const {state,assets,voice}=await fixture();let next=executeProductionCommand(state,{kind:'edit',proposal:{...state.model,metadata:{...state.model.metadata,title:'Command edited'}}},assets,24,1);const revision=studioMetadata(next.model).revision,id=adaptPresentation(next.model).shots[0].id;assert.equal(revision,2);next=executeProductionCommand(next,{kind:'task',command:{shotId:id,owner:'Aleksi',dueDate:''}},assets,24,revision);next=executeProductionCommand(next,{kind:'comment',command:{kind:'add',shotId:id,offset:0,body:'Check'}},assets,24,revision);const comment=studioMetadata(next.model).reviewComments![0];next=executeProductionCommand(next,{kind:'comment',command:{kind:'resolve',id:comment.id}},assets,24,revision);next=executeProductionCommand(next,{kind:'voice',clip:next.model.audioClips[0],voice},assets,24,revision);assert.deepEqual(studioMetadata(next.model).commandJournal!.map(e=>e.kind),['edit','task','comment','comment','voice']);for(let i=0;i<105;i++)next=journalProductionCommand(next,next,'relink-audio');assert.equal(studioMetadata(next.model).commandJournal!.length,100);const meta=studioMetadata(next.model);assert.throws(()=>readStudio({...meta,commandJournal:[{...meta.commandJournal![0],revisionAfter:meta.revision+1}]}));});

test('character package relink preserves layer-bound animation, retains old asset and undo restores entire resource state',async()=>{const {state,assets,r}=await fixture(),id=adaptPresentation(state.model).shots[0].id,approved={...state,model:reviewShot(state.model,id,'approve',1),assets},key='cast-sha256-'+'a'.repeat(64),before=canonicalJson(approved.model),next=relinkCharacter(approved,assets,'KILLE',key,{doc:{...r.doc,name:'Updated art'},animation:r.animation},24);assert.equal(next.model.bindings[0].asset,key);assert.ok(next.assets!.kille);assert.deepEqual(next.assets![key].animation.tracks,r.animation.tracks);assert.equal(adaptPresentation(next.model).shots[0].status,'draft');assert.equal(canonicalJson(approved.model),before);const history=new TransactionHistory<ProductionState>(30,s=>({...s,model:structuredClone(s.model),voices:{...s.voices}}));history.commit(approved);const undo=history.undo(next)!;assert.equal(undo.model.bindings[0].asset,'kille');assert.equal(undo.assets![key],undefined);assert.equal(history.redo(undo)!.model.bindings[0].asset,key);});
test('incompatible character rig and locked resource replacement fail without overwriting old resources',async()=>{const {state,assets,r}=await fixture(),id=adaptPresentation(state.model).shots[0].id,locked={...state,model:reviewShot(reviewShot(state.model,id,'approve',1),id,'lock',1)},key='cast-sha256-'+'b'.repeat(64),before=canonicalJson(locked.model);assert.throws(()=>relinkCharacter(locked,assets,'KILLE',key,{doc:r.doc,animation:r.animation},24),/lukittu/);assert.throws(()=>relinkCharacter(state,assets,'KILLE',key,{doc:{...r.doc,width:r.doc.width+1},animation:r.animation},24));assert.equal(canonicalJson(locked.model),before);assert.equal(Object.hasOwn(assets,key),false);});
test('editor edit boundary validates rig and animation together before any commit',async()=>{const {r}=await fixture(),before=canonicalJson(r.animation),next=prepareEditorEdit(r.doc,r.animation.rig,r.animation);assert.deepEqual(next.animation.tracks,r.animation.tracks);assert.equal(canonicalJson(r.animation),before);const rig=structuredClone(r.animation.rig);rig.parts[0].parentKey=rig.parts[0].key;assert.throws(()=>prepareEditorEdit(r.doc,rig,r.animation),/kehä/);assert.throws(()=>prepareEditorEdit(r.doc,r.animation.rig,{...r.animation,tracks:[{key:'orphan',frames:[]}]}));});

test('explicit PSD layer mapping preserves parent links, pivots, tracks and quick roles without guessing names',async()=>{const {r,state,assets}=await fixture();r.animation.tracks=[{key:r.doc.quick!.roles.root,frames:[{frame:0,x:3,y:4,rotation:5,scale:1,opacity:1,easing:'hold'}]}];const doc=structuredClone(r.doc),mapping:Record<string,string>={};for(const n of flatten(doc.layers)){mapping[n.key]='new'+n.key;n.key='new'+n.key;n.path='Revision/'+n.path;delete n.psdId;}delete doc.quick;const id='cast-sha256-'+'d'.repeat(64),incoming={doc,animation:r.animation};assert.throws(()=>relinkCharacter(state,assets,'KILLE',id,incoming,24));const next=relinkCharacter(state,assets,'KILLE',id,incoming,24,mapping),pack=next.assets[id];for(const p of r.animation.rig.parts){const mapped=pack.animation.rig.parts.find(n=>n.key===mapping[p.key])!;assert.deepEqual(mapped.pivot,p.pivot);if(p.parentKey)assert.equal(mapped.parentKey,mapping[p.parentKey]);}for(const t of r.animation.tracks)assert.deepEqual(pack.animation.tracks.find(n=>n.key===mapping[t.key])?.frames,t.frames);assert.equal(pack.doc.quick!.roles.root,mapping[r.doc.quick!.roles.root]);assert.equal(Object.hasOwn(assets,id),false);assert.equal(next.assets.kille,assets.kille);});
test('manual mapping rejects missing or duplicate targets and supports resized raw PSD',async()=>{const {r,state,assets}=await fixture(),doc=structuredClone(r.doc),mapping=Object.fromEntries(r.animation.rig.parts.map(p=>[p.key,p.key])),id='cast-sha256-'+'e'.repeat(64),before=canonicalJson(state.model);const [a,b]=Object.keys(mapping);const missing={...mapping};delete missing[a];assert.throws(()=>relinkCharacter(state,assets,'KILLE',id,{doc,animation:r.animation},24,missing));assert.throws(()=>relinkCharacter(state,assets,'KILLE',id,{doc,animation:r.animation},24,{...mapping,[a]:mapping[b]}));const resized=relinkCharacter(state,assets,'KILLE',id,{doc:{...doc,quick:undefined,width:doc.width+1},animation:r.animation},24,mapping);assert.equal(resized.assets[id].animation.rig.source.width,doc.width+1);assert.equal(canonicalJson(state.model),before);assert.equal(Object.hasOwn(assets,id),false);});
