import {viewAtFrame} from './character-view.ts';
import {buildToonAsset,toonPoses,toonProfileFor,deformVertex,skinPoint,rotate3,ellipsoid,type V3,type ToonProfile,type ToonAsset} from './toon3d.ts';import {stageActor,stageState} from './presentation-stage.ts';import type {Presentation} from './presentation-model.ts';import type {PresentationAssets} from './presentation-compile.ts';import {presentationState,heldItems} from './presentation-render.ts';import {toonHeldPropMeshes} from './toon-props.ts';import {sceneryFaces} from './toon-scenery.ts';
const cache=new Map<string,ToonAsset>();const assetFor=(p:ToonProfile)=>{const key=JSON.stringify(p);let asset=cache.get(key);if(!asset){asset=buildToonAsset(p);if(cache.size>20)cache.clear();cache.set(key,asset);}return asset;};
const tone=(color:string,shade:number)=>'#'+[1,3,5].map(i=>Math.round(parseInt(color.slice(i,i+2),16)*shade).toString(16).padStart(2,'0')).join('');
export function toonCamera(p:Presentation,time:number){const e=presentationState(p,time).shot,s=e?p.production?.cameras[e.id]:undefined;const size=s?.size??e?.value??'wide',yaw=s?.foreground&&s.view==='front'?(p.bindings.find(b=>b.speaker===s.foreground)?.side==='left'?35:-35):s?.view==='rear'?180:s?.view==='profile-left'?-90:s?.view==='profile-right'?90:s?.view==='quarter-left'?-35:s?.view==='quarter-right'?35:0,pitch=s?.angle==='high'?25:s?.angle==='low'?-20:0;const duration=s?.duration??p.events.find(d=>d.kind==='dialogue'&&(d.at??0)>=(e?.at??0))?.duration??3,t=Math.max(0,Math.min(1,(time-(e?.at??0))/duration)),u=t*t*(3-2*t),zoom=(size==='close'?2.4:size==='medium'?1.5:1)*(s?.motion==='zoom'?1+u*(s.zoom??.2):1+(s?.zoom??0));return{yaw,pitch,zoom,target:size==='wide'?'scene':e?.target??'scene',foreground:s?.foreground,pan:s?.motion==='pan'?u:0,panX:s?.panX??.15,panY:s?.panY??0,offsetX:s?.offsetX??0,offsetY:s?.offsetY??0};}
/** Shared CPU triangle renderer: solid skinned geometry, orthographic camera, explicit flat or legacy cel colors. */
export function renderToonCast(ctx:CanvasRenderingContext2D,p:Presentation,assets:PresentationAssets,time:number,width:number,height:number){const camera=toonCamera(p,time),target=p.bindings.find(b=>b.speaker===camera.target),targetAsset=target?assets[target.asset]:undefined,targetPosition=target?stageActor(p,target,time,width,height):undefined,rootPose=target&&targetAsset&&p.actorAnimations?.[target.speaker]?toonPoses(targetAsset.doc,p.actorAnimations[target.speaker],time*p.actorAnimations[target.speaker].fps).root:undefined,center:V3=[targetPosition?(targetPosition.x+(rootPose?.x??0)*targetPosition.scale+(camera.foreground?(p.bindings.find(b=>b.speaker===camera.foreground)?.side==='left'?-1:1)*width*.2/camera.zoom:0)):width/2,targetPosition&&targetAsset?targetPosition.y+(rootPose?.y??0)*targetPosition.scale-targetAsset.doc.height*targetPosition.scale*.22:height*.46,0],yaw=camera.yaw*Math.PI/180,pitch=camera.pitch*Math.PI/180,world=stageState(p,time);const faces:{points:V3[];color:string;depth:number;outline:boolean[];outlineWidth:number}[]=[];
 const project=(point:V3)=>{const q=rotate3([point[0]-center[0],point[1]-center[1],point[2]],0,yaw,pitch);return[width/2+(q[0]-(camera.offsetX+camera.pan*camera.panX)*width)*camera.zoom,height*.46+(q[1]-(camera.offsetY+camera.pan*camera.panY)*height)*camera.zoom,q[2]]as V3;};
 for(const binding of p.bindings){const source=assets[binding.asset],a=p.actorAnimations?.[binding.speaker],profile=source&&(p.production?.characterProfiles?.[binding.speaker]??toonProfileFor(source.doc));if(!source||!a||!profile||p.production?.representations[binding.speaker]!=='toon3d')continue;const asset=assetFor(profile),poses=toonPoses(source.doc,a,time*a.fps),r=stageActor(p,binding,time,width,height),root=poses.root,view=source.doc.quick?viewAtFrame(source.doc.quick,a,time*a.fps):'front',heading=view==='left'?-Math.PI/2:view==='right'?Math.PI/2:0,worldPoint=(v:V3)=>{const q=rotate3([v[0]-300-(root?.x??0),v[1]-450-(root?.y??0),v[2]],0,heading);return[r.x+(q[0]+(root?.x??0))*r.scale,r.y+(q[1]+(root?.y??0))*r.scale,q[2]*r.scale]as V3;};
 if(world.phone.enabled&&world.phone.carrier===binding.speaker&&world.phone.anchor==='hand'){for(const side of ['left','right'])for(const [part,z] of [['Arm',20],['Forearm',35]]as const){const key=side+part;poses[key]={...{x:0,y:0,rotation:0,scale:1,opacity:1},...poses[key],z}as typeof poses[string];}}
 // Katse kameraan 3D:ssä: pupilli siirretään projisoidun silmänvalkuaisen keskelle, jolloin katse osuu katsojaan kamerakulmasta riippumatta.
 const cameraGaze=toonCameraGaze(p,binding.speaker,time);
 const append=(mesh:ToonAsset['meshes'][number],points?:V3[])=>{const vertices=(points??mesh.vertices.map(v=>{let point=v.position;if(mesh.id.endsWith('Pupil')){const pose=poses[mesh.id];if(pose)point=[point[0]+pose.x,point[1]+pose.y,point[2]];}if(mesh.id.endsWith('Brow')){const pose=poses[mesh.id];if(pose)point=[point[0],point[1]+pose.y,point[2]];}if(mesh.id==='mouth'){const opening=poses.mouthOpen?.opacity??0,round=poses.mouthRound?.opacity??0;point=[300+(point[0]-300)*(round>.5?.6:1),338+(point[1]-338)*(opening>.5?7:round>.5?6:1),point[2]];}if(mesh.id.endsWith('eye-white')||mesh.id.endsWith('Pupil')){const blink=poses[mesh.id.startsWith('left')?'leftBlink':'rightBlink']?.opacity??0;if(blink>.5)point=[point[0],277+(point[1]-277)*.06,point[2]];}return deformVertex({...v,position:point},asset.bones,poses);})).map(v=>project(worldPoint(v)));if(cameraGaze&&!points&&mesh.id.endsWith('Pupil'))centerOnEyeWhite(vertices,asset.meshes.find(m=>m.id===mesh.id.replace('Pupil','eye-white')),v=>project(worldPoint(deformVertex(v,asset.bones,poses))));const areas=mesh.faces.map(f=>{const[a,b,c]=f.map(i=>vertices[i]);return(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}),edges=new Map<string,number[]>();mesh.faces.forEach((f,i)=>f.forEach((v,j)=>{const u=f[(j+1)%3],key=v<u?v+':'+u:u+':'+v;edges.set(key,[...(edges.get(key)??[]),i]);}));mesh.faces.forEach((f,i)=>{if(areas[i]<.001)return;const points=f.map(v=>vertices[v]),[v,b,c]=points,ab=[b[0]-v[0],b[1]-v[1],b[2]-v[2]],ac=[c[0]-v[0],c[1]-v[1],c[2]-v[2]],normal=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]],length=Math.hypot(...normal)||1,light=Math.abs((normal[0]*-.3+normal[1]*-.5+normal[2]*.81)/length),shade=profile.renderStyle==='flat'||mesh.id==='face'||mesh.id==='neck'||mesh.id.includes('palm')?1:light>.22?1:.94;faces.push({points,color:profile.renderStyle==='flat'?mesh.color:tone(mesh.color,shade),outlineWidth:profile.renderStyle==='flat'?0:profile.renderStyle===undefined?1.3:profile.outline,depth:points.reduce((n,v)=>n+v[2],0)/3,outline:f.map((v,j)=>{const u=f[(j+1)%3],key=v<u?v+':'+u:u+':'+v,adj=edges.get(key)!;return adj.length===1||adj.some(other=>areas[other]*areas[i]<0);})});});};
 for(const mesh of asset.meshes)append(mesh);
 if(world.phone.enabled&&world.phone.carrier===binding.speaker){const hand=world.phone.hand==='leftHand'?'left':'right',grip=asset.grips[hand],phone=buildPhoneMesh(grip),releaseTime=world.phone.releasedAt,phonePoses=releaseTime===undefined?poses:toonPoses(source.doc,a,releaseTime*a.fps),pr=releaseTime===undefined?r:stageActor(p,binding,releaseTime,width,height);if(releaseTime!==undefined)for(const side of ['left','right'])for(const [part,z]of[['Arm',20],['Forearm',35]]as const){const key=side+part;phonePoses[key]={...{x:0,y:0,rotation:0,scale:1,opacity:1},...phonePoses[key],z}as typeof phonePoses[string];}const phonePoint=(v:V3)=>{const q=skinPoint(v,hand+'Hand',asset.bones,phonePoses);return [300+(pr.x-r.x+(q[0]-300)*pr.scale)/r.scale,450+(pr.y-r.y+(q[1]-450)*pr.scale)/r.scale,q[2]*pr.scale/r.scale]as V3;};append(phone,phone.vertices.map(v=>phonePoint(v.position)));const screen=buildPhoneMesh([grip[0],grip[1],grip[2]+5]);screen.id='phone-screen';screen.color='#86adb8';screen.vertices=screen.vertices.map(v=>({...v,position:[grip[0]+(v.position[0]-grip[0])*.82,grip[1]-22+(v.position[1]-(grip[1]-22))*.83,v.position[2]]as V3}));screen.faces=[[4,5,6],[4,6,7]];append(screen,screen.vertices.map(v=>phonePoint(v.position)));if(world.phone.anchor==='hand')for(let i=0;i<3;i++){const finger=ellipsoid('grip-finger-'+i,profile.skin,[grip[0]-14,grip[1]-12-i*9,grip[2]+10],[6,4,5],hand+'Hand',4,8);append(finger);}}
  // Kirjaston esineet (kahvikuppi, kirja, laukku, sateenvarjo) skinnataan käsiluuhun; vapautettu esine jää vapautushetken paikkaan.
  for(const item of heldItems(p,world,binding.speaker)){if(item.spec.id==='phone-v1')continue;const grip=asset.grips[item.hand==='leftHand'?'left':'right'],meshes=toonHeldPropMeshes(item.spec.id,grip,item.hand,grip[0]>300?1:-1);if(!meshes)continue;const releaseTime=item.releasedAt,propPoses=releaseTime===undefined?poses:toonPoses(source.doc,a,releaseTime*a.fps),pr=releaseTime===undefined?r:stageActor(p,binding,releaseTime,width,height),point=(v:V3)=>{const q=skinPoint(v,item.hand,asset.bones,propPoses);return [300+(pr.x-r.x+(q[0]-300)*pr.scale)/r.scale,450+(pr.y-r.y+(q[1]-450)*pr.scale)/r.scale,q[2]*pr.scale/r.scale]as V3;};for(const m of meshes)append(m,m.vertices.map(v=>point(v.position)));}
 }
 faces.push(...sceneryFaces(p.production?.props??[],time,width,height,project).map(f=>({...f,outlineWidth:0})));
 faces.sort((a,b)=>a.depth-b.depth);ctx.lineJoin='round';for(const f of faces){ctx.beginPath();f.points.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=f.color;ctx.strokeStyle=f.color;ctx.lineWidth=.5;ctx.fill();ctx.stroke();if(f.outlineWidth===0)continue;ctx.strokeStyle='#222a30';ctx.lineWidth=Math.max(1,width/1080*f.outlineWidth);f.outline.forEach((draw,i)=>{if(draw){ctx.beginPath();ctx.moveTo(f.points[i][0],f.points[i][1]);const end=f.points[(i+1)%3];ctx.lineTo(end[0],end[1]);ctx.stroke();}});}
}
export function buildPhoneMesh(grip:V3){const vertices:ToonAsset['meshes'][number]['vertices']=[];for(const z of [-4,4])for(const[x,y]of[[-18,-35],[18,-35],[18,35],[-18,35]])vertices.push({position:[grip[0]+x,grip[1]+y-22,grip[2]+z],weights:[{bone:'rightHand',weight:1}]});return{id:'phone-v1',color:'#233642',vertices,faces:[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]]as[number,number,number][]};}

/** Viimeisin katse ennen hetkeä `time`: onko kohde kamera. */
export function toonCameraGaze(p:Presentation,speaker:string,time:number){return p.events.filter(e=>e.kind==='gaze'&&e.target===speaker&&(e.at??0)<=time).sort((a,b)=>(a.at??0)-(b.at??0)).at(-1)?.value==='camera';}
/** Siirtää projisoidut pupillipisteet silmänvalkuaisen projisoituun keskipisteeseen (syvyys säilyy). */
export function centerOnEyeWhite(pupil:V3[],white:ToonAsset['meshes'][number]|undefined,projectVertex:(v:ToonAsset['meshes'][number]['vertices'][number])=>V3){
 if(!white||!pupil.length)return;const w=white.vertices.map(projectVertex),mean=(list:V3[],i:0|1)=>list.reduce((sum,v)=>sum+v[i],0)/list.length;
 const dx=mean(w,0)-mean(pupil,0),dy=mean(w,1)-mean(pupil,1);for(const v of pupil){v[0]+=dx;v[1]+=dy;}
}
