/** Reproducible editable preparation, explicitly pending original dialogue audio. */
import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{readProject,saveProject}from'../lib/project-file.ts';import{parsePresentation}from'../lib/presentation-parser.ts';import{compilePresentation}from'../lib/presentation-compile.ts';import{functions,type Presentation}from'../lib/presentation-model.ts';import{toonProfiles}from'../lib/toon3d.ts';
const out=process.argv[2]??'/private/tmp/hahmostudio-010-demo';mkdirSync(out,{recursive:true});const r=await readProject(new Blob([readFileSync('public/library/Roni-Studio.hahmo')])),s=await readProject(new Blob([readFileSync('public/library/Salla-Studio.hahmo')])),assets={roni:{doc:r.doc,animation:r.animation},salla:{doc:s.doc,animation:s.animation}},fps=24;let frame=0;const plans:Presentation[]=[],storyboard:{name:string;start:number;end:number;status:string}[]=[];
function add(text:string,name:string,cast=false,edit?:(p:Presentation)=>void){let p=parsePresentation(text);p.id='demo-'+plans.length;p.world.width=1920;p.world.height=1080;p.production!.longForm=true;if(cast){p.bindings=p.characters.map((speaker,i)=>({speaker,asset:i?'salla':'roni',voice:'Oma repliikkiääni',side:i?'right':'left',functions:Object.fromEntries(functions.map(f=>[f,'supported']))}));p.production!.representations=Object.fromEntries(p.characters.map(c=>[c,'toon3d']));p.production!.characterProfiles=Object.fromEntries(p.characters.map((c,i)=>[c,structuredClone(toonProfiles[i])]));}edit?.(p);p=compilePresentation(p,assets,fps);p.startFrame=frame;frame+=Math.ceil(p.seconds*fps);plans.push(p);storyboard.push({name,start:p.startFrame/fps,end:frame/fps,status:p.audioClips.length<p.events.filter(e=>e.kind==='dialogue').length?'Alkuperäiset puheäänet puuttuvat':'Kuva tarkistettava'});return p;}
add('Pituus: noin 4 s\nOtsikkokortti: Hahmostudio 4 s','Avaus');const k=add(readFileSync('public/library/KILSAT-S01E01.md','utf8'),'KILSAT · alkuperäiset 18 repliikkiä',true,p=>{p.production!.locks=Object.fromEntries(p.events.filter(e=>e.kind==='hold'&&e.protected).map(e=>[e.id,{duration:true,relative:true}]));});
const voiceDraft={...k,startFrame:undefined};const voiceFile=await saveProject({...r.doc,presentationAssets:assets},{...r.animation,fps,tracks:[],duration:Math.ceil(k.seconds*fps)},undefined,{...r.scene,width:1920,height:1080,presentations:[],presentationDraft:voiceDraft});writeFileSync(out+'/KILSAT-oma-aanitys.hahmo',new Uint8Array(await voiceFile.arrayBuffer()));
add('Pituus: noin 12 s\nHahmo Roni: Roni.\nHahmo Salla: Salla.\nKohtaus: valkoinen studio.\nRONI MEDIUM, viistonäkymä oikealta.\nPidä 3 sekuntia hiljaisuutta.\nSALLA MEDIUM, sivukuva oikealta.\nPidä 3 sekuntia hiljaisuutta.\nRONI MEDIUM, takakuva.\nPidä 3 sekuntia hiljaisuutta.\nSALLA MEDIUM, viistonäkymä vasemmalta.\nPidä 3 sekuntia hiljaisuutta.','Samat 3D-mallit eri kulmista',true,p=>p.world.phone.enabled=false);
add('Pituus: noin 12 s\nHahmo Roni: Roni.\nHahmo Salla: Salla.\nKohtaus: toimisto.\nLAAJA KUVA\nSalla nyökkää 1 s.\nPidä 3 sekuntia hiljaisuutta.\nKohtaus: kahvila.\nLAAJA KUVA\nPidä 4 sekuntia hiljaisuutta.\nKohtaus: puisto.\nLAAJA KUVA\nRoni vilkuttaa 2 s.\nPidä 2 sekuntia hiljaisuutta.','Erillinen miljöönäyte',true,p=>{p.world.phone.enabled=false;p.production!.props=[{id:'book',asset:'book-prop-v1',x:.5,y:.75,scale:.1,start:0,end:4},{id:'mug',asset:'mug-prop-v1',x:.5,y:.75,scale:.08,start:4,end:8}];});
add('Pituus: noin 8 s\nOtsikkokortti: Ohjauspöytä · käyttöliittymätallenne puuttuu 8 s','Todellinen UI-tallenne · vielä korvattava');add('Pituus: noin 4 s\nOtsikkokortti: Hahmostudio · paikallinen animaatiotyökalu 4 s','Loppukortti');
const animation={...r.animation,tracks:[],fps,duration:frame},scene={...r.scene,width:1920,height:1080,presentations:plans},doc={...r.doc,presentationAssets:assets};const file=await saveProject(doc,animation,undefined,scene);writeFileSync(out+'/Hahmostudio-demo-valmistelu.hahmo',new Uint8Array(await file.arrayBuffer()));writeFileSync(out+'/demo-kuvakasikirjoitus.json',JSON.stringify({status:'Ei valmis esittelyvideo: alkuperäiset repliikkiäänet ja oikea UI-tallenne puuttuvat.',duration:frame/fps,originalDialogue:k.events.filter(e=>e.kind==='dialogue').map(e=>e.text),storyboard,diagnostics:plans.flatMap(p=>p.diagnostics)},null,2));console.log(JSON.stringify({seconds:frame/fps,segments:plans.length,dialogue:k.events.filter(e=>e.kind==='dialogue').length,pendingAudio:true}));
