import fs from 'node:fs';import {writePsdBuffer,readPsd,getLayerImageData,initializeCanvas} from 'ag-psd';import {zipSync,strToU8} from 'fflate';
initializeCanvas(()=>{throw Error('Canvas not used')},(width,height)=>({width,height,data:new Uint8ClampedArray(width*height*4)}));
const out=new URL('../public/library/',import.meta.url);let id=5000;
for(const name of ['Aino','Leo','Hahmopohja']){
 const a=new URL(`../.character-build/${name}/`,import.meta.url).pathname,c=JSON.parse(fs.readFileSync(a+'character.json')),meta=JSON.parse(fs.readFileSync(a+'layers.json'));
 const psd={width:c.width,height:c.height,imageData:{width:c.width,height:c.height,data:new Uint8ClampedArray(fs.readFileSync(a+'composite.rgba'))},children:['Vartalo','Pää','Suut'].map(name=>({name,blendMode:'pass through',children:meta.filter(n=>n.group===name).map(n=>({id:++id,name:n.name,left:n.left,top:n.top,right:n.left+n.width,bottom:n.top+n.height,hidden:n.hidden,imageData:{width:n.width,height:n.height,data:new Uint8ClampedArray(fs.readFileSync(a+n.key+'.rgba'))}}))}))};
 const bytes=writePsdBuffer(psd,{generateThumbnail:false});fs.writeFileSync(new URL(name+'.psd',out),bytes);const parsed=readPsd(bytes,{useRawData:true,skipThumbnail:true}),files={},parts=[],roles={};
 const groups=parsed.children.map((g,gi)=>({key:`/${gi}`,name:g.name,path:g.name,kind:'group',left:0,top:0,width:0,height:0,opacity:1,visible:true,blendMode:'pass through',warnings:[],children:g.children.map((l,li)=>{const n=meta.find(n=>n.name===l.name),p=getLayerImageData(l),key=`/${gi}/${li}`,path=`${g.name}/${l.name}`;if(!p||p.width!==n.width||p.height!==n.height)throw Error('PSD validation failed');roles[n.key]=key;files['images/'+n.key+'.png']=fs.readFileSync(a+n.key+'.png');parts.push({key,psdId:l.id,path,role:n.role,pivot:n.pivot,joints:n.joints,parentKey:n.parentKey});return {key,psdId:l.id,name:l.name,path,kind:'layer',left:l.left,top:l.top,width:p.width,height:p.height,opacity:1,visible:true,blendMode:'normal',warnings:[],image:'images/'+n.key+'.png',children:[]};})}));
 for(const p of parts)if(p.parentKey)p.parentKey=roles[p.parentKey];else delete p.parentKey;
 const quick={version:1,asset:c.asset,roles,bindings:{left:'KeyA',right:'KeyD',jump:'KeyW',neutral:'Digit1',happy:'Digit2',surprise:'Digit3',blink:'KeyB',record:'KeyR',play:'Space'},strength:1,speed:1,gate:.015,sensitivity:10,smoothing:.6,idle:true},rig={format:'hahmostudio-rig',version:1,source:{name:name+'.psd',width:c.width,height:c.height},parts},neutral={frame:0,x:0,y:0,rotation:0,scale:1,opacity:1,easing:'hold'},tracks=['leftBlink','rightBlink','mouthOpen','mouthRound'].map(r=>({key:roles[r],frames:[{...neutral,opacity:0}]}));
 files['images/original.png']=fs.readFileSync(a+'preview.png');files['source/character.psd']=bytes;files['preview.png']=fs.readFileSync(a+'preview.png');
 files['KAYTTOOHJE.txt']=strToU8(`${name}: Hahmostudion alkuperäistä grafiikkaa, CC0-1.0. Valmis .hahmo sisältää tasot, liitokset ja lähde-PSD:n. Käytä valmista .hahmo-pakettia animointiin. Muokkaa PSD:tä Photoshopissa yhdistämättä tasoja; palauta muokatun PSD:n liitokset erikseen editorissa. Kädet A/D, hyppy W, ilmeet 1/2/3, räpäytys B. Käsikirjoitus luo vilkutuksen, nyökkäyksen ja hypyn${c.portrait?' (muotokuvassa ei jalkoja).':', kävelyn ja kyykistyksen.'} Pää seuraa vartaloa ja kääntyy kaulan kiertokeskuksesta. Suu reagoi äänenvoimakkuuteen; äänteiden tunnistus toimii erillisellä äänityökalulla. Ei puheäänen synteesiä.`);
 files['provenance.json']=strToU8(JSON.stringify({asset:c.asset,version:2,author:'Hahmostudio',license:'CC0-1.0',origin:'studio-library',externalAssets:[],graphics:'Original procedural raster art',capabilities:c.portrait?['portrait','wave','nod','volume-mouth']:['full-body','wave','walk','crouch','jump','volume-mouth']}));
 files['project.json']=strToU8(JSON.stringify({format:'hahmostudio-project',version:2,document:{name:name+'.psd',width:c.width,height:c.height,size:bytes.length,warnings:[],composite:'images/original.png',layers:groups,quick,sourcePsd:'source/character.psd'},animation:{format:'hahmostudio-animation',version:1,fps:24,duration:2,rig,tracks},scene:{width:1080,height:1920,background:'#253341',design:'studio-v1',x:540,y:c.portrait?1180:1050,scale:c.portrait?1.9:1.65,guides:true}}));
 fs.writeFileSync(new URL(name+'.hahmo',out),zipSync(files));fs.copyFileSync(a+'preview.png',new URL(name+'.png',out));console.log(name,meta.length,'layers',bytes.length,'PSD bytes');
}
