import {packager} from '@electron/packager';import {mkdtemp,mkdir,cp,writeFile,rm,readFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
if(process.platform!=='darwin')throw new Error('Paketoi Mac-versio Macilla.');
const binary=resolve('.private-runtime/rhubarb/rhubarb'),arch=spawnSync('/usr/bin/lipo',['-archs',binary],{encoding:'utf8'});if(arch.status!==0||!arch.stdout.trim().split(/\s+/).includes(process.arch))throw new Error('Rhubarb ei vastaa tämän Macin arkkitehtuuria: '+process.arch);
for(const file of ['native/bin/ffmpeg','native/bin/ffprobe','native/bin/whisper-cli','native/models/ggml-base.bin']){await readFile(resolve('.private-runtime',file));}
const root=process.cwd(),stage=await mkdtemp(join(tmpdir(),'hahmostudio-package-')),meta=JSON.parse(await readFile('package.json','utf8'));
try{
 for(const directory of ['desktop','server','dist-desktop','licenses'])await cp(resolve(directory),join(stage,directory),{recursive:true,filter:path=>!path.endsWith('.test.mjs')&&!path.includes('test-fixtures')});
 await writeFile(join(stage,'package.json'),JSON.stringify({name:meta.name,version:meta.version,main:meta.main,type:'module',private:true}));
 for(const name of ['THIRD_PARTY_NOTICES.md','README.md','DEVELOPMENT-0.9.md','DEVELOPMENT-0.10.md','DEVELOPMENT-0.11.md','DEVELOPMENT-0.12.md','DEVELOPMENT-0.13.md','DEVELOPMENT-0.14.md','DEVELOPMENT-0.15.md','DEVELOPMENT-0.16.md','DEVELOPMENT-0.17.md','DEVELOPMENT-0.18.md','DEVELOPMENT-0.19.md','DEVELOPMENT-0.20.md','DEVELOPMENT-0.21.md','DEVELOPMENT-0.22.md','DEVELOPMENT-0.23.md','DEVELOPMENT-0.24.md','DEVELOPMENT-0.25.md','DEVELOPMENT-0.26.md','DEVELOPMENT-0.27.md','DEVELOPMENT-0.28.md','DEVELOPMENT-0.29.md','DEVELOPMENT-0.30.md','DEVELOPMENT-0.31.md','DEVELOPMENT-0.32.md','DEVELOPMENT-0.33.md','DEVELOPMENT-0.34.md','DEVELOPMENT-0.35.md','DEVELOPMENT-0.36.md','DEVELOPMENT-0.37.md','CHANGELOG.md','docs']){try{await cp(resolve(name),join(stage,name),{recursive:true});}catch(error){if(error.code!=='ENOENT')throw error;}}
 const paths=await packager({dir:stage,name:'KILSAT Studio',appBundleId:'fi.hahmostudio.desktop',appCategoryType:'public.app-category.graphics-design',appVersion:meta.version,platform:'darwin',arch:process.arch,electronVersion:meta.devDependencies.electron,out:resolve('release'),overwrite:true,asar:true,prune:false,download:{cacheRoot:process.env.electron_config_cache??join(tmpdir(),'hahmostudio-electron-cache')},icon:resolve('desktop/assets/Hahmostudio.icns'),extraResource:[resolve('.private-runtime/rhubarb'),resolve('.private-runtime/native')],usageDescription:{Camera:'Hahmostudio käyttää kameraa hahmon kasvojen ja pään liikkeiden ohjaamiseen vain, kun käynnistät kameran.',Microphone:'Hahmostudio käyttää mikrofonia hahmon suun ohjaamiseen ja puheen tallentamiseen vain, kun käynnistät mikrofonin.'},extendInfo:{NSCameraUsageDescription:'Käynnistämäsi kameraseuranta ohjaa hahmon kasvoja paikallisesti.',NSMicrophoneUsageDescription:'Käynnistämäsi mikrofoniohjaus käsittelee puheen paikallisesti.'},osxSign:{identity:'-',identityValidation:false,hardenedRuntime:false,preAutoEntitlements:false,gatekeeperAssess:false,continueOnError:false,optionsForFile:()=>({entitlements:resolve('desktop/entitlements.plist'),hardenedRuntime:false,signatureFlags:'0',timestamp:'none'})}});
 for(const path of paths){const app=join(path,'KILSAT Studio.app'),zip=resolve('release',`Hahmostudio-Mac-${process.arch}.zip`);const result=spawnSync('/usr/bin/ditto',['-c','-k','--sequesterRsrc','--keepParent',app,zip],{stdio:'inherit'});if(result.status!==0)throw new Error('Sovelluspaketin ZIP ei valmistunut.');console.log(app+'\n'+zip);}
}finally{await rm(stage,{recursive:true,force:true});}
