export const visemes=['REST','AI','E','O','U','MBP','FV','CDGKNRSThYZ','L_WQ'] as const;
export type Viseme=typeof visemes[number];
export type Matrix=[number,number,number,number,number,number];
export type Layer={id:string;parent?:string;pivot:[number,number];bounds:[number,number,number,number];pivotFrame?:[number,number,number,number];z:number;switch?:string;state?:string;default?:boolean};
export type Rig={version:1;width:number;height:number;layers:Layer[]};
export type Event={id:string;kind:'scene'|'dialogue'|'action'|'emotion'|'camera'|'hold';actor?:string;value:string;line:number;seconds?:number};
export type TimedEvent=Event&{start:number;end:number};
export type Actor={id:string;asset:'Kille'|'Mr.Kille'|'Mr.Handu';x:number;y:number;scale:number;rig:Rig};
export type CutoutHeld={id:string;actor:string;hand:'leftHand'|'rightHand';start:number;end?:number};
export type Timeline={format:'kilsat-cutout';version:1;fps:24;source:string;events:TimedEvent[];actors:Actor[];held?:CutoutHeld[];duration:number;width:number;height:number;cadence:'twos'|'threes'|'three-two'};
export function validateRig(r:Rig){if(!r||r.version!==1||![r.width,r.height].every(n=>Number.isFinite(n)&&n>0&&n<=4096)||!Array.isArray(r.layers)||r.layers.length>200)throw Error('Virheellinen kartonkiluusto.');const ids=new Set(r.layers.map(l=>l?.id));if(ids.size!==r.layers.length||!ids.has('ROOT'))throw Error('Luuston ID:t ovat virheelliset.');for(const l of r.layers){if(!l||!Array.isArray(l.pivot)||l.pivot.length!==2||!Array.isArray(l.bounds)||(l.id==='ROOT'&&!!l.parent)||!/^[A-Za-z0-9_]{1,100}$/.test(l.id)||!l.pivot.every(n=>Number.isFinite(n)&&n>=0&&n<=1)||l.bounds.length!==4||!l.bounds.every(Number.isFinite)||l.bounds[2]<0||l.bounds[3]<0||!Number.isFinite(l.z))throw Error('Virheellinen nivelpiste tai kerros.');if(l.pivotFrame&&(!Array.isArray(l.pivotFrame)||l.pivotFrame.length!==4||!l.pivotFrame.every(Number.isFinite)||l.pivotFrame[2]<=0||l.pivotFrame[3]<=0))throw Error('Nivelpisteen koordinaatisto on virheellinen.');if(l.id!=='ROOT'&&!l.parent)throw Error('Kerros tarvitsee vanhemman.');if((l.switch!==undefined||l.state!==undefined)&&(!l.switch||!l.state||typeof l.switch!=='string'||typeof l.state!=='string'))throw Error('Kytkinryhmä on virheellinen.');let p=l,seen=new Set([l.id]);while(p.parent){if(!ids.has(p.parent)||seen.has(p.parent))throw Error('Luustossa on puuttuva vanhempi tai kierto.');seen.add(p.parent);p=r.layers.find(x=>x.id===p.parent)!;}}return r;}
