import {validateRig,visemes,type Timeline,type Viseme} from './model.ts';
const kinds=['scene','dialogue','action','emotion','camera','hold'];
const identifier=(s:unknown):s is string=>typeof s==='string'&&/^[-\p{L}\d_. ]{1,100}$/u.test(s)&&!['__proto__','prototype','constructor'].includes(s);
const frame=(v:unknown)=>typeof v==='number'&&Number.isInteger(v)&&v>=0&&v<=28800;
/** Strict file boundary; reading never evaluates script or shape markup. */
export function readTimeline(value:unknown):Timeline{
 const t=value as Timeline;
 if(!t||t.format!=='kilsat-cutout'||t.version!==1||t.fps!==24||typeof t.source!=='string'||t.source.length>60000||!['twos','threes','three-two'].includes(t.cadence)||!frame(t.duration)||t.duration===0||![t.width,t.height].every(v=>Number.isInteger(v)&&v>0&&v<=4096)||t.width*t.height>16000000||!Array.isArray(t.actors)||!t.actors.length||t.actors.length>4||!Array.isArray(t.events)||t.events.length>2500)throw Error('Kartonkianimaation JSON on virheellinen.');
 const actors=new Set<string>();for(const a of t.actors){if(!a||!identifier(a.id)||actors.has(a.id)||!['Kille','Mr.Kille','Mr.Handu'].includes(a.asset)||![a.x,a.y,a.scale].every(Number.isFinite)||Math.abs(a.x)>10000||Math.abs(a.y)>10000||a.scale<=0||a.scale>10)throw Error('Kartonkianimaation hahmo on virheellinen.');actors.add(a.id);validateRig(a.rig);}
 const events=new Set<string>();for(const e of t.events){if(!e||!identifier(e.id)||events.has(e.id)||!kinds.includes(e.kind)||typeof e.value!=='string'||e.value.length>5000||!Number.isInteger(e.line)||e.line<1||!frame(e.start)||!frame(e.end)||e.start>e.end||e.end>t.duration||(e.actor!==undefined&&!actors.has(e.actor))||(e.seconds!==undefined&&(!Number.isFinite(e.seconds)||e.seconds<=0||e.seconds>60)))throw Error('Kartonkianimaation tapahtuma on virheellinen.');if(['dialogue','action','emotion'].includes(e.kind)&&!e.actor)throw Error('Tapahtuman hahmo puuttuu.');if(e.kind==='camera'&&!['CLOSE_UP','MEDIUM_TWO_SHOT','WIDE_SHOT'].includes(e.value))throw Error('Tuntematon kuvakoko.');if(e.kind==='scene'&&!['WHITE_STUDIO','STUDIO','STREET','CAR'].includes(e.value))throw Error('Tuntematon lavastus.');if(e.kind==='emotion'&&!['NORMAL','HAPPY','ANGRY','SQUINT'].includes(e.value))throw Error('Tuntematon ilme.');if(e.kind==='action'&&!['POINT','HAND_WAVE','WALK_LEFT','WALK_RIGHT','RUN_LEFT','RUN_RIGHT','IDLE'].includes(e.value))throw Error('Tuntematon ele.');events.add(e.id);}
 return t;
}
export function readAnimationPackage(text:string):{timeline:Timeline;voices:Record<string,Viseme[]>}{if(text.length>20*1024*1024)throw Error('Animaation JSON on yli 20 Mt.');const p=JSON.parse(text);const timeline=readTimeline(p?.timeline);if(!p.voices||typeof p.voices!=='object'||Array.isArray(p.voices))throw Error('Suuajoitukset puuttuvat.');for(const [id,frames] of Object.entries(p.voices)){const e=timeline.events.find(e=>e.id===id&&e.kind==='dialogue');if(!e||!Array.isArray(frames)||frames.length>e.end-e.start||frames.some(v=>!visemes.includes(v)))throw Error('Repliikin suuajoitus on virheellinen.');}return {timeline,voices:p.voices};}
export function readRenderedFrames(text:string){if(text.length>64*1024*1024)throw Error('Ruututilan JSON on yli 64 Mt.');const p=JSON.parse(text),timeline=readTimeline(p?.timeline);if(!Array.isArray(p.frames)||p.frames.length!==timeline.duration||timeline.duration>7200)throw Error('Ruututilojen lukumäärä on virheellinen.');for(const [i,f] of p.frames.entries()){if(!f||f.format!=='kilsat-cutout-frame'||f.version!==1||f.frame!==i||f.fps!==24||f.width!==timeline.width||f.height!==timeline.height||!Array.isArray(f.camera)||f.camera.length!==6||!f.camera.every(Number.isFinite)||!Array.isArray(f.actors)||f.actors.length!==timeline.actors.length)throw Error('Ruututila on virheellinen.');for(const [j,a] of f.actors.entries()){const rig=timeline.actors[j].rig;if(a.id!==timeline.actors[j].id||a.asset!==timeline.actors[j].asset||!a.switches||!visemes.includes(a.switches.MOUTH_SWITCH)||!['NORMAL','BLINK','SQUINT','ANGRY'].includes(a.switches.EYES_GROUP)||!Array.isArray(a.layers)||a.layers.length!==rig.layers.length||new Set(a.layers.map((l:any)=>l.id)).size!==rig.layers.length)throw Error('Ruututilan hahmo on virheellinen.');for(const l of a.layers)if(!rig.layers.some(r=>r.id===l.id)||![0,1].includes(l.opacity)||!Array.isArray(l.matrix)||l.matrix.length!==6||!l.matrix.every(Number.isFinite))throw Error('Ruututilan kerros on virheellinen.');}}
 return {timeline,frames:p.frames};}
