import {animationTransforms,type Transform} from '../animation-transform.ts';
import {neutral,sampleTrack,readAnimation,type Animation,type Keyframe} from '../animation-model.ts';
import {rigChain,type Point,type Rig} from '../rig-model.ts';
import {solveTwoBone} from '../inverse-kinematics.ts';
import type {PsdDocument} from '../psd-model.ts';
export type RetargetChain={id:string;source:string[];target:string[];sourceEnd:Point;targetEnd:Point;sourceEndKey?:string;targetEndKey?:string;pole?:Point};
export type RetargetContact={chainId:string;start:number;end:number;point?:Point;rotation?:number};
export type RetargetOptions={mode:'fk'|'ik';chains:RetargetChain[];contacts?:RetargetContact[];autoContacts?:boolean;ikWeight?:number;frameStep?:number;limits?:Record<string,{min:number;max:number}>};
export type RetargetDiagnostic={chainId:string;frame:number;error:number;kind:'unreachable'|'constraint'|'contact'};
const distance=(a:Point,b:Point)=>Math.hypot(b.x-a.x,b.y-a.y),point=(t:Transform,p:Point)=>({x:t.a*p.x+t.c*p.y+t.e,y:t.b*p.x+t.d*p.y+t.f}),degrees=(r:number)=>r*180/Math.PI,wrap=(x:number)=>((x+180)%360+360)%360-180;
export function solveChain(root:Point,goal:Point,lengths:number[],rest:Point[],bend:1|-1=1,pole?:Point):{points:Point[];error:number}{
 if(!lengths.length||lengths.length>32||lengths.some(l=>!Number.isFinite(l)||l<=1e-6))throw Error('Liikesovituksen luupituus on virheellinen.');
 if(lengths.length===2){const sign=pole?((goal.x-root.x)*(pole.y-root.y)-(goal.y-root.y)*(pole.x-root.x)>=0?1:-1):bend,s=solveTwoBone(root,goal,lengths[0],lengths[1],sign as 1|-1);return{points:[root,s.elbow,s.reached],error:distance(goal,s.reached)};}
 const total=lengths.reduce((a,b)=>a+b,0);let positions=rest.map(p=>({...p}));positions[0]={...root};
 if(distance(root,goal)>=total-1e-8){const d=distance(root,goal)||1;positions=[{...root}];for(const l of lengths){const p=positions.at(-1)!;positions.push({x:p.x+(goal.x-root.x)*l/d,y:p.y+(goal.y-root.y)*l/d});}}
 else{const d=distance(root,goal)||1,normal={x:-(goal.y-root.y)/d,y:(goal.x-root.x)/d},sign=pole?((goal.x-root.x)*(pole.y-root.y)-(goal.y-root.y)*(pole.x-root.x)>=0?1:-1):bend;for(let i=1;i<positions.length-1;i++){positions[i].x+=normal.x*sign*total*.05*Math.sin(Math.PI*i/lengths.length);positions[i].y+=normal.y*sign*total*.05*Math.sin(Math.PI*i/lengths.length);}for(let iteration=0;iteration<64;iteration++){positions[positions.length-1]={...goal};for(let i=lengths.length-1;i>=0;i--){const b=positions[i+1],a=positions[i],d=distance(a,b)||1;positions[i]={x:b.x+(a.x-b.x)*lengths[i]/d,y:b.y+(a.y-b.y)*lengths[i]/d};}positions[0]={...root};for(let i=0;i<lengths.length;i++){const a=positions[i],b=positions[i+1],d=distance(a,b)||1;positions[i+1]={x:a.x+(b.x-a.x)*lengths[i]/d,y:a.y+(b.y-a.y)*lengths[i]/d};}if(distance(positions.at(-1)!,goal)<1e-5)break;}}
 return{points:positions,error:distance(positions.at(-1)!,goal)};
}
function validateChain(rig:Rig,keys:string[],end:Point){if(!keys.length||keys.length>32||new Set(keys).size!==keys.length||!Number.isFinite(end.x)||!Number.isFinite(end.y))throw Error('Liikesovituksen nivelketju on virheellinen.');for(const [i,key] of keys.entries()){const p=rig.parts.find(p=>p.key===key);if(!p||i>0&&p.parentKey!==keys[i-1])throw Error('Nivelketjun osat eivät ole peräkkäin.');}const parts=keys.map(k=>rig.parts.find(p=>p.key===k)!);const points=[...parts.map(p=>p.pivot),end];if(points.slice(1).some((p,i)=>distance(p,points[i])<1e-6))throw Error('Nivelketjussa on nollapituinen luu.');return points;}
/** Bakes ordinary editor keyframes; source/target rigs are immutable and manual overrides remain possible. */
export function retargetChains(source:Animation,target:Rig,doc:PsdDocument,mapping:Record<string,string>,options:RetargetOptions):{animation:Animation;diagnostics:RetargetDiagnostic[]}{
 const step=options.frameStep??1,weight=options.mode==='fk'?0:options.ikWeight??1;if(!Number.isInteger(step)||step<1||step>24||!Number.isFinite(weight)||weight<0||weight>1||options.chains.length>32)throw Error('Liikesovituksen asetukset ovat virheelliset.');
 if(weight===0&&((options.contacts?.length??0)>0||options.autoContacts))throw Error('Kontaktin lukitus vaatii positiivisen IK-osuuden.');
 const from=new Map(source.rig.parts.map(p=>[p.key,p])),to=new Map(target.parts.map(p=>[p.key,p])),covered=new Set(options.chains.flatMap(c=>c.source)),targetKeys=options.chains.flatMap(c=>c.target);
 if(new Set(targetKeys).size!==targetKeys.length||new Set(options.chains.map(c=>c.id)).size!==options.chains.length)throw Error('Kohteen nivelketjut menevät päällekkäin.');
 for(const [a,b] of Object.entries(mapping))if(!from.has(a)||!to.has(b)||from.get(a)!.role!==to.get(b)!.role)throw Error('Liikesovituksen osan rooli ei täsmää.');
 if(new Set(Object.values(mapping)).size!==Object.keys(mapping).length)throw Error('Liikesovituksen kohteet eivät ole yksilöllisiä.');
 for(const t of source.tracks)if(!mapping[t.key]&&!covered.has(t.key))throw Error('Animoidun osan vastaavuus puuttuu: '+t.key);
 const chains=options.chains.map(c=>({c,source:validateChain(source.rig,c.source,c.sourceEnd),target:validateChain(target,c.target,c.targetEnd)}));
 for(const c of options.contacts??[]){if(!chains.some(v=>v.c.id===c.chainId)||!Number.isInteger(c.start)||!Number.isInteger(c.end)||c.start<0||c.end<c.start||c.end>=source.duration||c.point&&(!Number.isFinite(c.point.x)||!Number.isFinite(c.point.y))||c.rotation!==undefined&&!Number.isFinite(c.rotation))throw Error('Liikesovituksen kontaktijakso on virheellinen.');if((options.contacts??[]).some(d=>d!==c&&d.chainId===c.chainId&&d.start<=c.end&&c.start<=d.end))throw Error('Kontaktijaksot menevät päällekkäin.');}
 const ratio=Math.sqrt(target.source.width*target.source.height/(source.rig.source.width*source.rig.source.height));let animation:Animation={...source,rig:target,tracks:source.tracks.filter(t=>mapping[t.key]).map(t=>({key:mapping[t.key],frames:t.frames.map(k=>({...k,x:k.x*ratio,y:k.y*ratio}))}))};
 const frames=Array.from({length:Math.ceil(source.duration/step)},(_,i)=>Math.min(source.duration-1,i*step));if(frames.at(-1)!==source.duration-1)frames.push(source.duration-1);for(const c of options.contacts??[]){frames.push(c.start,c.end);}const bakeFrames=[...new Set(frames)].sort((a,b)=>a-b),output=new Map<string,Keyframe[]>(targetKeys.map(k=>[k,[]]));for(const c of chains)if(c.c.targetEndKey)output.set(c.c.targetEndKey,[]);
 const unrelated=animation.tracks.filter(t=>!output.has(t.key));if(output.size*bakeFrames.length+unrelated.reduce((n,t)=>n+t.frames.length,0)>10000)throw Error('Liikesovitus ylittää 10 000 avainruutua. Lyhennä liikettä tai suurenna ruutuaskelta.');
 const diagnostics:RetargetDiagnostic[]=[],contacts=new Map<string,Point>(),previousSourceEnd=new Map<string,Point>();
 for(const frame of bakeFrames){const sourceWorld=animationTransforms(source,frame),poses:Record<string,ReturnType<typeof sampleTrack>>=Object.fromEntries(animation.rig.parts.map(p=>[p.key,sampleTrack(animation.tracks.find(t=>t.key===p.key),frame)]));
  for(const {c,source:sourceRest,target:targetRest} of chains){const sourcePoints=sourceRest.map((p,i)=>point(sourceWorld.get(c.source[Math.min(i,c.source.length-1)])!,p));if(c.sourceEndKey)sourcePoints[sourcePoints.length-1]=point(sourceWorld.get(c.sourceEndKey)!,c.sourceEnd);
   let targetWorld=animationTransforms(animation,frame,{key:c.target[0],pose:poses[c.target[0]],poses});const root=point(targetWorld.get(c.target[0])!,targetRest[0]),sourceRoot=sourcePoints[0],sourceEnd=sourcePoints.at(-1)!,sourceLength=sourceRest.slice(1).reduce((n,p,i)=>n+distance(sourceRest[i],p),0),targetLength=targetRest.slice(1).reduce((n,p,i)=>n+distance(targetRest[i],p),0),ancestorScale=Math.hypot(targetWorld.get(c.target[0])!.a,targetWorld.get(c.target[0])!.b),sourceScale=Math.hypot(sourceWorld.get(c.source[0])!.a,sourceWorld.get(c.source[0])!.b),scale=targetLength/sourceLength*ancestorScale/sourceScale;
   let goal={x:root.x+(sourceEnd.x-sourceRoot.x)*scale,y:root.y+(sourceEnd.y-sourceRoot.y)*scale};const explicit=(options.contacts??[]).find(v=>v.chainId===c.id&&frame>=v.start&&frame<=v.end),previous=previousSourceEnd.get(c.id),automatic=options.autoContacts&&previous&&distance(previous,sourceEnd)<.25*step;const contactId=explicit?c.id+':'+explicit.start:c.id+':auto';if(explicit||automatic){if(!contacts.has(contactId))contacts.set(contactId,explicit?.point??goal);goal=contacts.get(contactId)!;}else contacts.delete(c.id+':auto');previousSourceEnd.set(c.id,sourceEnd);
   // FK distributes source world orientations by cumulative chain length, allowing split/merged bones.
   let walked=0;const sourceDistances=sourceRest.slice(1).map((p,i)=>distance(sourceRest[i],p));for(let i=0;i<c.target.length;i++){const fraction=walked/targetLength;let sourceIndex=0,sum=0;while(sourceIndex<sourceDistances.length-1&&(sum+sourceDistances[sourceIndex])/sourceLength<=fraction){sum+=sourceDistances[sourceIndex++];}const a=sourcePoints[sourceIndex],b=sourcePoints[sourceIndex+1],desired=Math.atan2(b.y-a.y,b.x-a.x),part=to.get(c.target[i])!,parent=part.parentKey?targetWorld.get(part.parentKey):undefined,parentRotation=parent?Math.atan2(parent.b,parent.a):0,rest=Math.atan2(targetRest[i+1].y-targetRest[i].y,targetRest[i+1].x-targetRest[i].x);poses[part.key]={...poses[part.key],...(i?{x:0,y:0}:{}),rotation:wrap(degrees(desired-parentRotation-rest))};targetWorld=animationTransforms(animation,frame,{key:part.key,pose:poses[part.key],poses});walked+=distance(targetRest[i],targetRest[i+1]);}
   const fk=Object.fromEntries(c.target.map(k=>[k,poses[k].rotation]));if(weight>0){const restWorld=targetRest.map((p,i)=>point(targetWorld.get(c.target[Math.min(i,c.target.length-1)])!,p)),lengths=targetRest.slice(1).map((p,i)=>distance(targetRest[i],p)*Math.hypot(targetWorld.get(c.target[i])!.a,targetWorld.get(c.target[i])!.b)),cross=sourcePoints.length>2?(sourceEnd.x-sourceRoot.x)*(sourcePoints[1].y-sourceRoot.y)-(sourceEnd.y-sourceRoot.y)*(sourcePoints[1].x-sourceRoot.x):1,solved=solveChain(root,goal,lengths,restWorld,cross>=0?1:-1,c.pole);
    if(solved.error>.5)diagnostics.push({chainId:c.id,frame,error:solved.error,kind:explicit||automatic?'contact':'unreachable'});
    for(let i=0;i<c.target.length;i++){const key=c.target[i],part=to.get(key)!,parent=part.parentKey?targetWorld.get(part.parentKey):undefined,parentRotation=parent?Math.atan2(parent.b,parent.a):0,rest=Math.atan2(targetRest[i+1].y-targetRest[i].y,targetRest[i+1].x-targetRest[i].x),a=solved.points[i],b=solved.points[i+1],ik=wrap(degrees(Math.atan2(b.y-a.y,b.x-a.x)-parentRotation-rest));let rotation=fk[key]+wrap(ik-fk[key])*weight;const limit=options.limits?.[key];if(limit){if(!Number.isFinite(limit.min)||!Number.isFinite(limit.max)||limit.min>limit.max)throw Error('Nivelraja on virheellinen.');const clipped=Math.max(limit.min,Math.min(limit.max,rotation));if(clipped!==rotation)diagnostics.push({chainId:c.id,frame,error:Math.abs(rotation-clipped),kind:'constraint'});rotation=clipped;}poses[key]={...poses[key],rotation};targetWorld=animationTransforms(animation,frame,{key,pose:poses[key],poses});}}
   if(weight===0)for(const key of c.target){const limit=options.limits?.[key];if(!limit)continue;if(!Number.isFinite(limit.min)||!Number.isFinite(limit.max)||limit.min>limit.max)throw Error('Nivelraja on virheellinen.');const rotation=poses[key].rotation,clipped=Math.max(limit.min,Math.min(limit.max,rotation));if(clipped!==rotation)diagnostics.push({chainId:c.id,frame,error:Math.abs(rotation-clipped),kind:'constraint'});poses[key]={...poses[key],rotation:clipped};}
   if(weight>0&&(explicit||automatic)){const lastKey=c.targetEndKey??c.target.at(-1)!,world=animationTransforms(animation,frame,{key:c.target[0],pose:poses[c.target[0]],poses}),actual=point(world.get(lastKey)!,c.targetEnd),error=distance(actual,goal);if(error>.5&&!diagnostics.some(d=>d.chainId===c.id&&d.frame===frame&&d.kind==='contact'))diagnostics.push({chainId:c.id,frame,error,kind:'contact'});}
   if(c.targetEndKey&&explicit?.rotation!==undefined){const end=to.get(c.targetEndKey);if(!end||end.parentKey!==c.target.at(-1))throw Error('Kontaktin pääteosa ei liity nivelketjuun.');const parent=targetWorld.get(end.parentKey!)!;poses[end.key]={...poses[end.key],rotation:explicit.rotation-degrees(Math.atan2(parent.b,parent.a))};}
  }
  for(const [key,keys] of output)keys.push({...poses[key]??neutral,frame,easing:'linear'});
 }
 animation={...animation,tracks:[...unrelated,...[...output].map(([key,frames])=>({key,frames}))]};return{animation:readAnimation(JSON.stringify(animation),doc),diagnostics};
}
export function semanticChains(source:Rig,target:Rig,sourceRoles:Record<string,string>,targetRoles:Record<string,string>):RetargetChain[]{
 const chains:RetargetChain[]=[];for(const side of ['left','right'])for(const [startRole,endRole] of [['Arm','Hand'],['Thigh','Foot']]){const a=sourceRoles[side+startRole],b=sourceRoles[side+endRole],c=targetRoles[side+startRole],d=targetRoles[side+endRole];if(!a||!b||!c||!d)continue;const sourcePath=rigChain(source,b).map(p=>p.key),targetPath=rigChain(target,d).map(p=>p.key),i=sourcePath.indexOf(a),j=targetPath.indexOf(c);if(i<0||j<0)throw Error('Hahmon semanttinen raaja ei muodosta liitettyä ketjua.');chains.push({id:side+startRole,source:sourcePath.slice(i,-1),target:targetPath.slice(j,-1),sourceEnd:source.parts.find(p=>p.key===b)!.pivot,targetEnd:target.parts.find(p=>p.key===d)!.pivot,sourceEndKey:b,targetEndKey:d});}return chains;
}
export function profileChains(source:Rig,target:Rig,a:{roles:Record<string,string>;views?:Partial<Record<string,Record<string,string>>>},b:{roles:Record<string,string>;views?:Partial<Record<string,Record<string,string>>>}):RetargetChain[]{
 if(a.views&&b.views){const chains:RetargetChain[]=[];for(const [view,roles] of Object.entries(a.views)){const targetRoles=b.views[view];if(!roles||!targetRoles)continue;for(const c of semanticChains(source,target,roles,targetRoles))chains.push({...c,id:view+':'+c.id});}return chains;}
 return semanticChains(source,target,a.roles,b.roles);
}
