import {contentChunks} from './content-chunks.ts';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import {sha256} from './hash.ts';
import {addResourceManifest,verifyResourceManifest} from './resource-manifest.ts';
import {readProjectHistory,type ProjectHistory} from './project-history.ts';
const limit=128*1024*1024;
const unpack=async(blob:Blob)=>{if(blob.size>limit)throw Error('Historiaprojekti ylittää 128 Mt.');let size=0;const files=unzipSync(new Uint8Array(await blob.arrayBuffer()),{filter:e=>{size+=e.originalSize;if(size>limit)throw Error('Purettu historiaprojekti ylittää 128 Mt.');return true;}});await verifyResourceManifest(files);return files;};
export async function attachHistory(blob:Blob,history:ProjectHistory,read:(r:ProjectHistory['past'][number])=>Promise<{bytes:Uint8Array;stateHash?:string;archiveHash?:string}>):Promise<Blob>{
 readProjectHistory(history);if([...history.past,...history.future].reduce((n,r)=>n+r.size,0)>384*1024*1024)throw Error('Historian rekonstruoitu koko ylittää 384 Mt.');
 const files=await unpack(blob),entries:{size:number;hash:string;chunks:{hash:string;size:number}[]}[]=[];
 for(const r of [...history.past,...history.future]){const state=await read(r),bytes=state.bytes,digest=await sha256(bytes);if(bytes.length!==r.size||(state.stateHash?state.stateHash!==r.hash||digest!==state.archiveHash:digest!==r.hash))throw Error('Siirrettävän historian tarkistussumma ei täsmää.');const chunks:{hash:string;size:number}[]=[];for(const part of contentChunks(bytes)){const hash=await sha256(part),path='history/pool/'+hash;files[path]??=new Uint8Array(part);chunks.push({hash,size:part.length});}entries.push({size:bytes.length,hash:digest,chunks});}
 files['history.json']=strToU8(JSON.stringify({version:2,past:history.past.length,entries}));await addResourceManifest(files);
 if(Object.values(files).reduce((n,b)=>n+b.length,0)>limit)throw Error('Projekti historian kanssa ylittää 128 Mt. Historiaa ei katkaistu; tallenna pienempi projekti.');
 return new Blob([new Uint8Array(zipSync(files,{level:0}))]);
}
export async function extractHistory(blob:Blob){const files=await unpack(blob);if(!files['history.json'])return null;if(files['history.json'].length>4*1024*1024)throw Error('Historian hakemisto on liian suuri.');const h=JSON.parse(strFromU8(files['history.json']));if(![1,2].includes(h.version)||!Array.isArray(h.entries)||h.entries.length>16||!Number.isInteger(h.past)||h.past<0||h.past>h.entries.length)throw Error('Siirrettävä historia on virheellinen.');const entries:Uint8Array[]=[];let expanded=0;for(const [i,e] of h.entries.entries()){let bytes:Uint8Array;if(h.version===1){if(e.path!=='history/'+i+'.hahmo'||!files[e.path])throw Error('Historian vedos puuttuu.');bytes=files[e.path];}else{if(!Number.isSafeInteger(e.size)||e.size<1||e.size>limit||!Array.isArray(e.chunks)||e.chunks.length>8192)throw Error('Historian palaluettelo on virheellinen.');if((expanded+=e.size)>384*1024*1024)throw Error('Historian rekonstruoitu koko ylittää 384 Mt.');bytes=new Uint8Array(e.size);let offset=0;for(const c of e.chunks){if(!/^[a-f0-9]{64}$/.test(c.hash)||!Number.isInteger(c.size)||c.size<1||c.size>65536)throw Error('Historian palaviite on virheellinen.');const part=files['history/pool/'+c.hash];if(!part||part.length!==c.size||await sha256(part)!==c.hash||offset+part.length>bytes.length)throw Error('Historian pala on vioittunut.');bytes.set(part,offset);offset+=part.length;}if(offset!==bytes.length)throw Error('Historian pituus ei täsmää.');}if(await sha256(bytes)!==e.hash)throw Error('Historian vedos on vioittunut.');const inner=await unpack(new Blob([new Uint8Array(bytes)]));if(inner['history.json'])throw Error('Sisäkkäistä kumoamishistoriaa ei tueta.');entries.push(bytes);}return{past:entries.slice(0,h.past),future:entries.slice(h.past)};}
