import {ProjectChunks} from './project-chunks.mjs';
import {mkdir,open,readFile,readdir,rename,rm,stat} from 'node:fs/promises';
import {join} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
import {applySemanticDelta} from './semantic-delta.mjs';
import {metadataRope,ropeBytes} from './metadata-rope.mjs';
import {storedZip,readZip,zipSize,validPath} from './stored-zip.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex'),limit=128*1024*1024,recordLimit=192*1024*1024;
const reference=r=>r&&/^snapshot-[a-f0-9-]{36}\.hahmo$/.test(r.file)&&/^[a-f0-9]{64}$/.test(r.hash)&&Number.isSafeInteger(r.size)&&r.size>0&&r.size<=limit;
function readHistory(h){if(!h)return{past:[],future:[]};if(!Array.isArray(h.past)||!Array.isArray(h.future)||h.past.length+h.future.length>16||[...h.past,...h.future].some(r=>!reference(r)))throw Error('Deltajournalin historia on virheellinen.');return{past:h.past.map(r=>({file:r.file,hash:r.hash,size:r.size})),future:h.future.map(r=>({file:r.file,hash:r.hash,size:r.size}))};}
const jsonValidation=new WeakMap();
function safeJson(value){let count=0;const visit=(v,depth)=>{if(depth>80)throw Error('Projektin metadata on liian suuri.');if(v&&typeof v==='object'){if(!Array.isArray(v)&&Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null)throw Error('Projektin metadata ei ole JSON-dataa.');const known=jsonValidation.get(v);if(known){count+=known.nodes;if(count>1000000||depth+known.height>80)throw Error('Projektin metadata on liian suuri.');return known;}let nodes=1,height=0;if(++count>1000000)throw Error('Projektin metadata on liian suuri.');for(const key of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(key))throw Error('Projektin metadata-avain on estetty.');const child=visit(v[key],depth+1);nodes+=child.nodes;height=Math.max(height,1+child.height);}const result={nodes,height};jsonValidation.set(v,result);return result;}if(++count>1000000)throw Error('Projektin metadata on liian suuri.');if(v===null||v===undefined||typeof v==='boolean')return{nodes:1,height:0};if(typeof v==='number'){if(!Number.isFinite(v))throw Error('Projektin numero on virheellinen.');return{nodes:1,height:0};}if(typeof v==='string'){if(v.length>4*1024*1024)throw Error('Projektin teksti on liian suuri.');return{nodes:1,height:0};}throw Error('Projektin metadata on virheellinen.');};visit(value,0);}

function validateMetadata(m){safeJson(m);if(m?.format!=='hahmostudio-project'||![1,2,3,4,5].includes(m.version)||!m.document||!Number.isInteger(m.document.width)||!Number.isInteger(m.document.height)||m.document.width<1||m.document.height<1||m.document.width*m.document.height>16000000||!Array.isArray(m.document.layers)||m.animation?.format!=='hahmostudio-animation')throw Error('Deltaprojektin rakenne on virheellinen.');if(metadataRope(m).size>10*1024*1024)throw Error('Projektin metadata ylittää 10 Mt.');}
const resourcePath=p=>validPath(p)&&!['project.json','resource-manifest.json','history.json','command-delta.json'].includes(p)&&!p.startsWith('history/');
function patchResources(base,patch){if(!patch||!Array.isArray(patch.set)||!Array.isArray(patch.remove)||patch.set.length+patch.remove.length>2010)throw Error('Resurssidelta on virheellinen.');const result={...base},seen=new Set();for(const p of patch.remove){if(!resourcePath(p)||seen.has(p)||!Object.hasOwn(result,p))throw Error('Poistettavan resurssin viite on virheellinen.');seen.add(p);delete result[p];}for(const r of patch.set){if(!r||!resourcePath(r.path)||seen.has(r.path)||!/^[a-f0-9]{64}$/.test(r.hash)||!Number.isSafeInteger(r.size)||r.size<0||r.size>limit)throw Error('Resurssiviite on virheellinen.');seen.add(r.path);if(r.chunks!==undefined&&(!Array.isArray(r.chunks)||!r.chunks.length||r.chunks.length>8192||r.chunks.some(c=>!c||!/^[a-f0-9]{64}$/.test(c.hash)||!Number.isInteger(c.size)||c.size<0||c.size>65536)||r.chunks.reduce((n,c)=>n+c.size,0)!==r.size))throw Error('Resurssin palaviite on virheellinen.');result[r.path]={hash:r.hash,size:r.size,...(r.chunks?{chunks:r.chunks.map(c=>({hash:c.hash,size:c.size}))}:{})};}if(Object.keys(result).length>1005||Object.values(result).reduce((n,r)=>n+r.size,0)>limit)throw Error('Projektin resurssiraja ylittyy.');return result;}
export function transactionDigest(request){return hash(Buffer.from(JSON.stringify({version:1,name:request.name,base:request.base??null,delta:request.delta,resources:request.resources,command:request.command})));}
function stateInfo(metadata,resources){const rope=metadataRope(metadata),entries=Object.entries(resources).sort(([a],[b])=>a<b?-1:a>b?1:0),stateHash=hash(Buffer.from(JSON.stringify([rope.hash,entries]))),manifest={schemaVersion:1,assets:[...entries.map(([path,r])=>({path,size:r.size,sha256:r.hash})),{path:'project.json',size:rope.size,sha256:'0'.repeat(64)}].sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0)},size=zipSize([...entries.map(([p,r])=>[p,r.size]),['project.json',rope.size],['resource-manifest.json',Buffer.byteLength(JSON.stringify(manifest))]]);if(size>limit)throw Error('Projektin koko ylittää 128 Mt.');return{hash:stateHash,size,rope};}
/** One baseline per imported/new project. Ordinary commits contain JSON paths + resource references only. */
export class DeltaJournal{
 constructor(root,{externalRead,failpoint}={}){this.dir=join(root,'delta');this.pool=join(this.dir,'resources');this.externalRead=externalRead;this.failpoint=failpoint;this.queue=Promise.resolve();this.states=new Map();this.commands=new Map();this.loaded=false;this.head=null;this.sequence=0;this.invalid=0;this.verifiedResources=new Map();this.verifiedDescriptors=new WeakSet();this.diskBytes=0;}
 enqueue(fn){const next=this.queue.then(async()=>{this.activeUploads=new Set();try{return await fn();}catch(error){if(this.activeUploads.size)try{await this.load(true);const referenced=new Set([...this.states.values()].flatMap(s=>Object.values(s.resources).flatMap(r=>r.chunks?r.chunks.map(c=>c.hash):[r.hash])));for(const hash of this.activeUploads)if(!referenced.has(hash)){await rm(join(this.pool,hash+'.bin'),{force:true});this.verifiedResources.delete(hash);}await this.syncDir(this.pool);this.loaded=false;}catch{/* Preserve staged bytes when committed references cannot be verified. */}throw error;}finally{this.activeUploads=undefined;}});this.queue=next.catch(()=>{});return next;}
 async syncDir(path){const d=await open(path,'r');try{await d.sync();}finally{await d.close();}}
 async load(force=false){if(this.loaded&&!force)return;this.diskBytes=0;for(const dir of [this.dir,this.pool])for(const name of await readdir(dir).catch(e=>{if(e.code==='ENOENT')return[];throw e;}))if(/^(commit-[a-f0-9-]{36}\.json|[a-f0-9]{64}\.bin)$/.test(name))this.diskBytes+=(await stat(join(dir,name))).size;this.states=new Map();this.commands=new Map();this.head=null;this.sequence=0;this.invalid=0;const records=[];for(const filename of await readdir(this.dir).catch(e=>{if(e.code==='ENOENT')return[];throw e;})){if(!/^commit-[a-f0-9-]{36}\.json$/.test(filename))continue;try{const bytes=await readFile(join(this.dir,filename));if(bytes.length>recordLimit)throw Error('record limit');const envelope=JSON.parse(bytes.toString()),r=envelope.record;if(r?.version!==1||!Number.isSafeInteger(r.sequence)||r.sequence<1||hash(Buffer.from(JSON.stringify(r)))!==envelope.hash||!Array.isArray(r.states)||r.states.length>17)throw Error('record checksum');records.push(r);}catch{this.invalid++;}}records.sort((a,b)=>a.sequence-b.sequence);for(const r of records){this.sequence=Math.max(this.sequence,r.sequence);try{const staged=new Map(this.states);for(const e of r.states){if(!reference(e.entry)||typeof e.entry.name!=='string'||e.entry.name.length>256||!Number.isFinite(Date.parse(e.entry.createdAt)))throw Error('entry');const base=e.base?staged.get(e.base.file):null;if(e.base&&(!base||base.entry.hash!==e.base.hash||base.entry.size!==e.base.size))throw Error('base');const metadata=applySemanticDelta(base?.metadata??null,e.delta),resources=patchResources(base?.resources??{},e.resources);validateMetadata(metadata);const info=stateInfo(metadata,resources);if(info.hash!==e.entry.hash||info.size!==e.entry.size)throw Error('state hash');readHistory(e.entry.command?.history);staged.set(e.entry.file,{metadata,resources,entry:e.entry});}if(!staged.has(r.head))throw Error('head');this.states=staged;this.head=r.head;this.sequence=Math.max(this.sequence,r.sequence);if(r.requestHash&&r.commandId)this.commands.set(r.commandId,{requestHash:r.requestHash,entry:staged.get(r.head).entry});}catch{this.invalid++;}}this.loaded=true;}
 async upload(uploads,importing=false,reserve=0){
  if(!Array.isArray(uploads)||uploads.length>(importing?50000:10000))throw Error('Resurssilähetys on virheellinen.');let total=0,newBytes=0;const pending=new Map();await mkdir(this.pool,{recursive:true,mode:0o700});
  for(const u of uploads){if(!u||!/^[a-f0-9]{64}$/.test(u.hash)||!(u.bytes instanceof Uint8Array)||(total+=u.bytes.length)>(importing?512*1024*1024:limit)||hash(u.bytes)!==u.hash)throw Error('Uuden resurssin tarkistussumma ei täsmää.');if(pending.has(u.hash))continue;const path=join(this.pool,u.hash+'.bin'),existing=await readFile(path).catch(e=>{if(e.code==='ENOENT')return null;throw e;});if(existing){if(existing.length!==u.bytes.length||hash(existing)!==u.hash)throw Error('Resurssivarasto on vioittunut.');this.verifiedResources.set(u.hash,u.bytes.length);continue;}pending.set(u.hash,u);newBytes+=u.bytes.length;}
  if(this.diskBytes+newBytes+reserve>512*1024*1024)throw Error('Deltajournalin 512 Mt levykiintiö täyttyi. Tallenna projekti historia mukaan lukien ennen palautusvaraston tyhjentämistä.');
  for(const u of pending.values()){const file=await open(join(this.pool,u.hash+'.bin'),'wx',0o600);this.activeUploads?.add(u.hash);try{await file.writeFile(u.bytes);await file.sync();this.diskBytes+=u.bytes.length;this.verifiedResources.set(u.hash,u.bytes.length);}finally{await file.close();}}await this.syncDir(this.pool);
 }

 async resourceBytes(r){const parts=[];for(const c of r.chunks??[{hash:r.hash,size:r.size}]){const bytes=await readFile(join(this.pool,c.hash+'.bin'));if(bytes.length!==c.size||hash(bytes)!==c.hash)throw Error('Projektin resurssipala puuttuu tai on vioittunut.');parts.push(bytes);}const result=Buffer.concat(parts,r.size);if(hash(result)!==r.hash)throw Error('Projektin resurssi puuttuu tai on vioittunut.');return result;}
 async verifyResources(resources,force=false){for(const r of Object.values(resources)){if(!force&&this.verifiedDescriptors.has(r))continue;await this.resourceBytes(r);this.verifiedDescriptors.add(r);}}

 async verifyHistory(h,staged=this.states){for(const r of [...h.past,...h.future]){const state=staged.get(r.file);if(state){if(state.entry.hash!==r.hash||state.entry.size!==r.size)throw Error('Historiaviite ei täsmää.');}else if(this.externalRead)await this.externalRead(r);else throw Error('Historian kohde puuttuu.');}}
 async commit(record){await this.failpoint?.('before-commit');const bytes=Buffer.from(JSON.stringify({record,hash:hash(Buffer.from(JSON.stringify(record)))}));if(bytes.length>recordLimit)throw Error('Journal-transaktio on liian suuri.');if(this.diskBytes+bytes.length>512*1024*1024)throw Error('Deltajournalin 512 Mt levykiintiö täyttyi. Tallenna projekti historia mukaan lukien ennen palautusvaraston tyhjentämistä.');const id=randomUUID(),temp=join(this.dir,'.pending-'+id),target=join(this.dir,'commit-'+id+'.json');const f=await open(temp,'wx',0o600);try{await f.writeFile(bytes);await f.sync();}finally{await f.close();}try{await this.failpoint?.('after-write');await rename(temp,target);this.diskBytes+=bytes.length;await this.syncDir(this.dir);await this.failpoint?.('after-commit');}catch(e){await rm(temp,{force:true});throw e;}for(const e of record.states){const base=e.base?this.states.get(e.base.file):null;this.states.set(e.entry.file,{metadata:applySemanticDelta(base?.metadata??null,e.delta),resources:patchResources(base?.resources??{},e.resources),entry:e.entry});}this.head=record.head;this.sequence=record.sequence;if(record.commandId)this.commands.set(record.commandId,{requestHash:record.requestHash,entry:this.states.get(record.head).entry});this.loaded=true;}
 transaction(request){return this.enqueue(async()=>{await this.load();if(request?.version!==1||typeof request.name!=='string'||request.name.length>256||/[\x00-\x1f]/.test(request.name)||!request.command||!/^[a-f0-9-]{36}$/.test(request.command.id)||!/^[-a-z]{1,80}$/.test(request.command.kind))throw Error('Deltakomento on virheellinen.');const requestHash=transactionDigest(request),previous=this.commands.get(request.command.id);if(previous){if(previous.requestHash!==requestHash)throw Error('Komento-ID:n sisältö muuttui.');return{...previous.entry,requestHash,delta:true};}const base=request.base?this.states.get(request.base.file):null;if(request.base&&(!reference(request.base)||!base||base.entry.hash!==request.base.hash||base.entry.size!==request.base.size||this.head!==base.entry.file))throw Error('Deltakomennon lähtötila on vanhentunut.');safeJson(request.delta);const metadata=applySemanticDelta(base?.metadata??null,request.delta),resources=patchResources(base?.resources??{},request.resources);validateMetadata(metadata);const info=stateInfo(metadata,resources),h=readHistory(request.command.history);await this.verifyHistory(h);const entry={file:'snapshot-'+randomUUID()+'.hahmo',name:request.name,hash:info.hash,size:info.size,createdAt:new Date().toISOString(),command:{id:request.command.id,kind:request.command.kind,history:h},delta:true};const record={version:1,sequence:this.sequence+1,states:[{entry,base:request.base??null,delta:request.delta,resources:request.resources}],head:entry.file,requestHash,commandId:request.command.id};const reserve=Buffer.byteLength(JSON.stringify({record,hash:'0'.repeat(64)}));await this.upload(request.uploads,false,reserve);await this.verifyResources(resources);await this.commit(record);return{...entry,requestHash};});}
 async materialize(state){const files=Object.create(null);for(const [path,r] of Object.entries(state.resources))files[path]=await this.resourceBytes(r);files['project.json']=ropeBytes(metadataRope(state.metadata));files['resource-manifest.json']=Buffer.from(JSON.stringify({schemaVersion:1,assets:Object.keys(files).sort().map(path=>({path,size:files[path].length,sha256:hash(files[path])}))}));const bytes=new Uint8Array(storedZip(files));if(bytes.length!==state.entry.size)throw Error('Palautuspaketin koko ei täsmää.');return{name:state.entry.name,bytes,createdAt:state.entry.createdAt,stateHash:state.entry.hash,archiveHash:hash(bytes),reference:{file:state.entry.file,hash:state.entry.hash,size:state.entry.size},history:state.entry.command?.history,delta:true};}
 read(ref){return this.enqueue(async()=>{await this.load();const state=this.states.get(ref?.file);if(!state||state.entry.hash!==ref.hash||state.entry.size!==ref.size)throw Error('Deltahistorian kohde puuttuu.');return this.materialize(state);});}
 latest(){return this.enqueue(async()=>{await this.load(true);const candidates=[...(this.head?[this.states.get(this.head)]:[]),...[...this.states.values()].reverse().filter(s=>s.entry.file!==this.head)];for(const [i,state] of candidates.entries())try{return{...await this.materialize(state),previous:i>0||this.invalid>0,replayed:true};}catch{/* try earlier committed state */}if(candidates.length)throw Error('Deltajournalista ei löytynyt ehjää palautuskohdetta.');return null;});}
 missing(references){return this.enqueue(async()=>{if(!Array.isArray(references)||references.length>10000)throw Error('Resurssikysely on virheellinen.');const missing=[];for(const r of references){if(!/^[a-f0-9]{64}$/.test(r.hash)||!Number.isSafeInteger(r.size)||r.size<0||r.size>limit)throw Error('Resurssikyselyn viite on virheellinen.');if(this.verifiedResources.get(r.hash)===r.size)continue;const bytes=await readFile(join(this.pool,r.hash+'.bin')).catch(e=>{if(e.code==='ENOENT')return null;throw e;});if(!bytes){missing.push(r.hash);continue;}if(bytes.length!==r.size||hash(bytes)!==r.hash)throw Error('Resurssivaraston tarkistussumma ei täsmää.');this.verifiedResources.set(r.hash,r.size);}return missing;});}
 owns(ref){return this.enqueue(async()=>{await this.load();return this.states.has(ref?.file);});}
 importBatch({name,past,future,current}){return this.enqueue(async()=>{await this.load();if(typeof name!=='string'||name.length>256||!Array.isArray(past)||!Array.isArray(future)||past.length+future.length>16)throw Error('Historiatuonti on virheellinen.');const states=[],uploads=new Map();let total=0;for(const bytes of [...past,...future,current]){if(!(bytes instanceof Uint8Array)||bytes.length>limit||(total+=bytes.length)>512*1024*1024)throw Error('Historiatuonti ylittää kokorajan.');const files=readZip(bytes);if(files['history.json'])throw Error('Sisäkkäinen historia on estetty.');if(files['resource-manifest.json']){const m=JSON.parse(files['resource-manifest.json'].toString());if(m.schemaVersion!==1||!Array.isArray(m.assets)||m.assets.length>1005)throw Error('Resurssimanifesti on virheellinen.');const seen=new Set();for(const a of m.assets){if(!a||seen.has(a.path)||!files[a.path]||files[a.path].length!==a.size||hash(files[a.path])!==a.sha256)throw Error('Tuontiresurssin tarkistussumma ei täsmää.');seen.add(a.path);}if(Object.keys(files).some(p=>p!=='resource-manifest.json'&&!seen.has(p)))throw Error('Manifestista puuttuva tuontiresurssi.');}const metadata=JSON.parse(files['project.json']?.toString()??'null');validateMetadata(metadata);const set=[];for(const [path,data] of Object.entries(files)){if(['project.json','resource-manifest.json','command-delta.json'].includes(path))continue;if(!resourcePath(path))throw Error('Tuontiresurssin polku on virheellinen.');const digest=hash(data),parts=data.length?new ProjectChunks(this.dir).split(data):[data],chunks=parts.map(part=>({hash:hash(part),size:part.length}));parts.forEach((part,i)=>uploads.set(chunks[i].hash,{hash:chunks[i].hash,bytes:new Uint8Array(part)}));set.push({path,hash:digest,size:data.length,chunks});}const resources=patchResources({},{set,remove:[]}),info=stateInfo(metadata,resources),entry={file:'snapshot-'+randomUUID()+'.hahmo',name,hash:info.hash,size:info.size,createdAt:new Date().toISOString(),delta:true};states.push({entry,base:null,delta:{version:1,changes:[{path:[],before:null,after:metadata}]},resources:{set,remove:[]}});}
 const history={past:states.slice(0,past.length).map(s=>({file:s.entry.file,hash:s.entry.hash,size:s.entry.size})),future:states.slice(past.length,-1).map(s=>({file:s.entry.file,hash:s.entry.hash,size:s.entry.size}))},last=states.at(-1);last.entry.command={id:randomUUID(),kind:'history-import-current',history};const record={version:1,sequence:this.sequence+1,states,head:last.entry.file},reserve=Buffer.byteLength(JSON.stringify({record,hash:'0'.repeat(64)}));await this.upload([...uploads.values()],true,reserve);for(const s of states)await this.verifyResources(patchResources({},s.resources));await this.failpoint?.('import-validated');await this.commit(record);return{history,reference:{file:last.entry.file,hash:last.entry.hash,size:last.entry.size}};});}
}
