import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,readdir,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {DeltaJournal} from './delta-journal.mjs';import {readZip,storedZip} from './stored-zip.mjs';import {semanticDelta,applySemanticDelta} from './semantic-delta.mjs';import {metadataRope,ropeBytes} from './metadata-rope.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const metadata=text=>({format:'hahmostudio-project',version:1,document:{name:'Test',width:100,height:100,layers:[]},animation:{format:'hahmostudio-animation',version:1,fps:24,duration:120,rig:{format:'hahmostudio-rig',version:1,source:{name:'Test',width:100,height:100},parts:[]},tracks:[]},scene:{presentationSource:text}});
function req(before,after,base,extra={}){return{version:1,name:'Test',...(base?{base:{file:base.file,hash:base.hash,size:base.size}}:{}),delta:semanticDelta(before,after),resources:{set:[],remove:[]},uploads:[],command:{id:randomUUID(),kind:'test-edit',history:{past:base?[{file:base.file,hash:base.hash,size:base.size}]:[],future:[]}},...extra};}
async function context(t){const dir=await mkdtemp(join(tmpdir(),'kilsat-delta-'));t.after(()=>rm(dir,{recursive:true,force:true}));return{dir,store:new DeltaJournal(dir)};}
test('delta journal persists only changed fields, replays after restart and exports valid ZIP',async t=>{const {dir,store}=await context(t),a=metadata('before'),b=metadata('after'),bytes=Buffer.alloc(1024*1024,7),hash=sha(bytes);const first=await store.transaction(req(null,a,null,{resources:{set:[{path:'images/sample.bin',hash,size:bytes.length}],remove:[]},uploads:[{hash,bytes}]}));const secondRequest=req(a,b,first),second=await store.transaction(secondRequest);assert.equal(second.delta,true);const files=await readdir(join(dir,'delta'));assert.equal(files.some(p=>p.endsWith('.hahmo')),false);const commits=await Promise.all(files.filter(p=>p.startsWith('commit-')).map(p=>readFile(join(dir,'delta',p),'utf8')));assert.ok(commits.some(s=>s.length<2500&&!s.includes('"layers"')));assert.equal((await readdir(join(dir,'delta','resources'))).length,1);const restarted=new DeltaJournal(dir),restored=await restarted.latest();assert.equal(restored.reference.file,second.file);assert.equal(restored.stateHash,second.hash);assert.equal(restored.bytes.length,second.size);assert.equal(JSON.parse(readZip(restored.bytes)['project.json'].toString()).scene.presentationSource,'after');assert.deepEqual(readZip(restored.bytes)['images/sample.bin'],bytes);assert.equal((await restarted.read(first)).stateHash,first.hash);assert.deepEqual(await store.transaction(secondRequest),second);await assert.rejects(store.transaction(req(a,metadata('stale'),first)),/vanhentunut/);});
test('one atomic history import exposes all states or none under injected failure',async t=>{const {dir,store}=await context(t),first=await store.transaction(req(null,metadata('existing'))),zip=s=>new Uint8Array(storedZip({'project.json':Buffer.from(JSON.stringify(metadata(s)))}));const failing=new DeltaJournal(dir,{failpoint:phase=>{if(phase==='after-write')throw Error('simulated disk interruption');}});await assert.rejects(failing.importBatch({name:'Import',past:[zip('old')],future:[zip('redo')],current:zip('current')}),/interruption/);const after=new DeltaJournal(dir);assert.equal((await after.latest()).reference.file,first.file);assert.equal(after.states.size,1);const imported=await after.importBatch({name:'Import',past:[zip('old')],future:[zip('redo')],current:zip('current')});const restarted=new DeltaJournal(dir),latest=await restarted.latest();assert.equal(latest.reference.file,imported.reference.file);assert.equal(latest.history.past.length,1);assert.equal(latest.history.future.length,1);assert.equal(JSON.parse(readZip((await restarted.read(imported.history.future[0])).bytes)['project.json'].toString()).scene.presentationSource,'redo');});
test('corrupt resource and incomplete commit are never accepted as current state',async t=>{const {dir,store}=await context(t),data=Buffer.from('resource'),hash=sha(data),first=await store.transaction(req(null,metadata('safe')));const next=await store.transaction(req(metadata('safe'),metadata('resource'),first,{resources:{set:[{path:'resource.bin',hash,size:data.length}],remove:[]},uploads:[{hash,bytes:data}]}));await writeFile(join(dir,'delta','resources',hash+'.bin'),'corrupt');const restarted=new DeltaJournal(dir),latest=await restarted.latest();assert.equal(latest.reference.file,first.file);assert.equal(latest.previous,true);await assert.rejects(restarted.read(next),/vioittunut/);await writeFile(join(dir,'delta','commit-'+randomUUID()+'.json'),'half written');assert.equal((await new DeltaJournal(dir).latest()).reference.file,first.file);});
test('array splice delta is small and immutable, metadata rope reuses unchanged branches',()=>{const keys=Array.from({length:10000},(_,frame)=>({frame,x:0})),before={tracks:[{keys}]},after={tracks:[{keys:[...keys,{frame:10000,x:3}]}]},delta=semanticDelta(before,after);assert.ok(JSON.stringify(delta).length<250);const result=applySemanticDelta(before,delta);assert.deepEqual(result,after);assert.equal(result.tracks[0].keys[0],keys[0]);assert.equal(before.tracks[0].keys.length,10000);const a=metadataRope(before),b=metadataRope(result);assert.equal(ropeBytes(a).toString(),JSON.stringify(before));assert.equal(ropeBytes(b).toString(),JSON.stringify(after));assert.throws(()=>applySemanticDelta({tracks:[{keys:[]}]},delta),/lähtötila/);});

test('real writer process SIGKILL before commit leaves old project; after durable commit restores new project',async t=>{const {fork}=await import('node:child_process');for(const phase of ['after-write','after-commit']){const {dir,store}=await context(t),before=await store.transaction(req(null,metadata('before-kill'))),child=fork(new URL('./test-fixtures/delta-crash.mjs',import.meta.url),[dir,phase],{stdio:['ignore','ignore','pipe','ipc']});let stderr='';child.stderr.on('data',b=>stderr+=b);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('Crash fixture timed out: '+stderr));},10000);child.once('message',()=>{clearTimeout(timer);resolve();});child.once('exit',code=>{clearTimeout(timer);reject(Error('Crash fixture exited: '+code+' '+stderr));});});await new Promise(resolve=>{child.once('exit',resolve);child.kill('SIGKILL');});const recovered=await new DeltaJournal(dir).latest();assert.equal(JSON.parse(readZip(recovered.bytes)['project.json'].toString()).scene.presentationSource,phase==='after-write'?'before-kill':'child');if(phase==='after-write')assert.equal(recovered.reference.file,before.file);}});

test('prototype resource paths are rejected before persistence',async t=>{const {store}=await context(t),bytes=Buffer.from('bad'),hash=sha(bytes);await assert.rejects(store.transaction(req(null,metadata('bad'),null,{resources:{set:[{path:'__proto__',hash,size:bytes.length}],remove:[]},uploads:[{hash,bytes}]})),/Resurssiviite/);assert.equal(await store.latest(),null);});

test('quota rejects all staged resource writes before a transaction starts',async t=>{const {dir,store}=await context(t);await store.load();store.diskBytes=512*1024*1024-2;const bytes=Buffer.from('too large'),hash=sha(bytes);await assert.rejects(store.transaction(req(null,metadata('quota'),null,{resources:{set:[{path:'resource.bin',hash,size:bytes.length}],remove:[]},uploads:[{hash,bytes}]})),/kiintiö/);assert.deepEqual(await readdir(join(dir,'delta','resources')),[]);assert.equal(await new DeltaJournal(dir).latest(),null);});

test('failed atomic import removes only its uncommitted CAS uploads and preserves old resources',async t=>{const {dir,store}=await context(t),oldBytes=Buffer.from('old'),oldHash=sha(oldBytes);await store.transaction(req(null,metadata('old'),null,{resources:{set:[{path:'old.bin',hash:oldHash,size:oldBytes.length}],remove:[]},uploads:[{hash:oldHash,bytes:oldBytes}]}));const zip=new Uint8Array(storedZip({'project.json':Buffer.from(JSON.stringify(metadata('new'))),'new.bin':Buffer.from('new resource')})),failing=new DeltaJournal(dir,{failpoint:phase=>{if(phase==='after-write')throw Error('write failure');}});await assert.rejects(failing.importBatch({name:'Import',past:[zip],future:[],current:zip}),/failure/);assert.deepEqual(await readdir(join(dir,'delta','resources')),[oldHash+'.bin']);assert.equal(JSON.parse(readZip((await new DeltaJournal(dir).latest()).bytes)['project.json'].toString()).scene.presentationSource,'old');});

test('changed nested archive transmits only new content chunks and restores byte-exact resource',async t=>{const {dir,store}=await context(t),{ProjectChunks}=await import('./project-chunks.mjs'),{randomBytes}=await import('node:crypto'),split=new ProjectChunks(dir),original=randomBytes(2*1024*1024),changed=Buffer.concat([original.subarray(0,800000),Buffer.from('changed animation metadata'),original.subarray(800000)]),build=async bytes=>{const parts=split.split(bytes),chunks=parts.map(p=>({hash:sha(p),size:p.length})),missing=new Set(await store.missing(chunks));return{set:[{path:'cast/actor.hahmo',hash:sha(bytes),size:bytes.length,chunks}],uploads:parts.flatMap((p,i)=>missing.has(chunks[i].hash)?[{hash:chunks[i].hash,bytes:p}]:[])};};const a=await build(original),first=await store.transaction(req(null,metadata('a'),null,{resources:{set:a.set,remove:[]},uploads:a.uploads})),b=await build(changed);assert.ok(b.uploads.reduce((n,u)=>n+u.bytes.length,0)<300000);const last=await store.transaction(req(metadata('a'),metadata('b'),first,{resources:{set:b.set,remove:[]},uploads:b.uploads}));assert.deepEqual(readZip((await new DeltaJournal(dir).read(last)).bytes)['cast/actor.hahmo'],changed);});
