import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm,readdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {DesktopFiles} from './files.mjs';
async function fixture(run){const root=await mkdtemp(join(tmpdir(),'hahmostudio-files-test-'));const source=join(root,'Old.hahmo'),target=join(root,'New.hahmo');await writeFile(source,'original');let open={canceled:false,filePaths:[source]},save={canceled:false,filePath:target};const f=new DesktopFiles({dialog:{showOpenDialog:async()=>open,showSaveDialog:async()=>save},window:()=>null,dataDir:join(root,'settings')});try{await f.initialize();await run({f,root,source,target,cancelOpen:()=>open={canceled:true},cancelSave:()=>save={canceled:true},saveTo:p=>save={canceled:false,filePath:p}});}finally{await rm(root,{recursive:true,force:true});}}
test('selected project path is adopted only after renderer validation; recents expose opaque IDs',async()=>fixture(async({f,source})=>{const file=await f.choose('project');assert.equal(f.currentPath,null);assert.equal(file.name,'Old.hahmo');await f.adopt(file.id);assert.equal(f.currentPath,source);const recent=f.getPreferences().recent;assert.equal(recent[0].name,'Old.hahmo');assert.equal(recent[0].path,undefined);assert.equal((await f.recent(recent[0].id)).name,'Old.hahmo');await assert.rejects(f.recent('/etc/passwd'));await assert.rejects(f.adopt('unknown'));}));
test('Save As keeps original bytes; later Save overwrites only the selected project atomically',async()=>fixture(async({f,source,target,root})=>{await f.adopt((await f.choose('project')).id);await f.save({name:'New.hahmo',bytes:new Uint8Array([7,8]),kind:'project',saveAs:true});assert.equal(await readFile(source,'utf8'),'original');assert.deepEqual([...await readFile(target)],[7,8]);await f.save({name:'New.hahmo',bytes:new Uint8Array([9]),kind:'project',saveAs:false});assert.deepEqual([...await readFile(target)],[9]);assert.equal((await readdir(root)).some(n=>n.endsWith('.tmp')),false);}));
test('canceled native dialogs preserve path, contents and recents without falsely reporting saved',async()=>fixture(async({f,source,cancelOpen,cancelSave})=>{await f.adopt((await f.choose('project')).id);cancelOpen();assert.equal(await f.choose('project'),null);cancelSave();assert.deepEqual(await f.save({name:'New.hahmo',bytes:new Uint8Array([9]),kind:'project',saveAs:true}),{saved:false});assert.equal(f.currentPath,source);assert.equal(await readFile(source,'utf8'),'original');}));
test('failed disk write preserves original and settings survive app replacement',async()=>fixture(async({f,root,source,saveTo})=>{await f.adopt((await f.choose('project')).id);await f.setTheme('dark');saveTo(join(root,'missing-directory','New.hahmo'));await assert.rejects(f.save({name:'New.hahmo',bytes:new Uint8Array([9]),kind:'project',saveAs:true}));assert.equal(await readFile(source,'utf8'),'original');const replacement=new DesktopFiles({dialog:{},window:()=>null,dataDir:join(root,'settings')});await replacement.initialize();assert.equal(replacement.getPreferences().theme,'dark');assert.equal(replacement.getPreferences().recent[0].name,'Old.hahmo');}));
test('export destination does not change current project and native open rejects mismatched types',async()=>fixture(async({f,source})=>{await f.adopt((await f.choose('project')).id);await f.save({name:'video.mp4',bytes:new Uint8Array([1]),kind:'export',saveAs:false});assert.equal(f.currentPath,source);await assert.rejects(f.choose('audio'));await f.adopt(null);assert.equal(f.currentPath,null);}));


test('CSV export uses the existing atomic file writer without adopting or overwriting the active project',()=>fixture(async({f,root,source,saveTo,cancelSave})=>{const opened=await f.readSelected(source,'project');await f.adopt(opened.id);const csv=join(root,'Työjono.csv'),bytes=new TextEncoder().encode('\uFEFF"Kuva";"Vastuuhenkilö"\r\n"001";"Aleksi"\r\n');saveTo(csv);const result=await f.save({name:'Työjono.csv',kind:'export',saveAs:true,bytes});assert.equal(result.saved,true);assert.deepEqual(new Uint8Array(await readFile(csv)),bytes);assert.equal(f.currentPath,source);assert.equal(await readFile(source,'utf8'),'original');cancelSave();assert.equal((await f.save({name:'Työjono.csv',kind:'export',saveAs:true,bytes})).saved,false);assert.equal(f.currentPath,source);}));
