import {layoutDiagnostic} from './layout-diagnostic.mjs';
import {screenplayDiagnostic} from './screenplay-diagnostic.mjs';
import {exportE2eDiagnostic} from './export-e2e-diagnostic.mjs';
import {playbackRafDiagnostic} from './playback-raf-diagnostic.mjs';
import {RevisionStore} from './revisions.mjs';
import {KokoroModelStore,KokoroService,MODEL_LICENSE as KOKORO_LICENSE} from './kokoro.mjs';
import {createProcessEngineFactory} from './kokoro-engine.mjs';
import {DesktopExports} from './export-service.mjs';
import {app,BrowserWindow,Menu,dialog,ipcMain,session,systemPreferences,utilityProcess,nativeTheme,screen} from 'electron';
import {join,dirname} from 'node:path';import {randomBytes,randomUUID} from 'node:crypto';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';
import {DesktopFiles} from './files.mjs';import {validSender,allowedMedia,allowedMediaCheck} from './policy.mjs';
import {RecoveryStore} from './recovery.mjs';
import {mayClose} from './close-workflow.mjs';
const legacyData=app.getPath('userData');app.setName('KOETA');app.setPath('userData',legacyData);
const root=dirname(dirname(fileURLToPath(import.meta.url))),layoutTesting=process.argv.includes('--layout-screenshots'),screenplayTesting=process.argv.includes('--screenplay-gui-test'),playbackRafTesting=process.argv.includes('--playback-raf-profile'),exportE2eTesting=process.argv.includes('--export-e2e-test'),testing=process.argv.includes('--self-test')||layoutTesting||screenplayTesting||playbackRafTesting||exportE2eTesting;
if(testing||process.argv.includes('--diagnostic-workspace')){if(!process.env.HAHMOSTUDIO_TEST_DATA_DIR)throw new Error('Self-test requires isolated data directory');app.setPath('userData',process.env.HAHMOSTUDIO_TEST_DATA_DIR);}
let window,service,files,origin,serviceOrigin,dirty=false,ready=false,closing=false,closeBusy=false,pendingClose,speech,exports,recovery,revisions,kokoro,kokoroDownload;
const token=randomBytes(32).toString('hex');
if(!testing&&!app.requestSingleInstanceLock()){app.quit();}else{
 app.on('second-instance',()=>{window?.show();window?.focus();});
 app.on('before-quit',event=>{if(window&&!closing){event.preventDefault();void closeWindow();}});
 app.on('window-all-closed',async()=>{await stopService();app.quit();});
 // Electron emits ready only after the ESM entry module has finished loading.
 // Register the callback without awaiting it at module scope.
 app.whenReady().then(async()=>{
 try{
  await mkdir(app.getPath('userData'),{recursive:true});await startupStatus('local-service');
  service=utilityProcess.fork(join(root,'desktop/service.mjs'),[],{stdio:'ignore',serviceName:'KOETA · paikallinen puhepalvelu'});
  const port=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{service.kill();reject(new Error('Paikallisen palvelun käynnistys aikakatkaistiin.'));},15000);service.once('message',message=>{clearTimeout(timeout);message.type==='ready'?resolve(message.port):reject(new Error(message.message??'Palvelun käynnistys epäonnistui.'));});service.once('exit',()=>{clearTimeout(timeout);reject(new Error('Paikallinen palvelu sulkeutui käynnistyksessä.'));});service.postMessage({type:'start',token,distDir:join(root,'dist-desktop'),transcriber:{binary:join(app.isPackaged?process.resourcesPath:join(root,'.private-runtime'),'native/bin/whisper-cli'),model:join(app.isPackaged?process.resourcesPath:join(root,'.private-runtime'),'native/models/ggml-base.bin'),downloadPath:join(app.getPath('userData'),'models/ggml-base.bin')},rhubarb:app.isPackaged?join(process.resourcesPath,'rhubarb/rhubarb'):join(root,'.private-runtime/rhubarb/rhubarb')});});
  serviceOrigin=`http://127.0.0.1:${port}`;
  origin=process.env.HAHMOSTUDIO_DEV_URL??serviceOrigin;
  if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin))throw new Error('Kehitysosoitteen on oltava paikallinen.');
  const ses=session.fromPartition('persist:hahmostudio-desktop');
  await ses.cookies.set({url:origin,name:'hahmostudio_desktop',value:token,httpOnly:true,sameSite:'strict'});
  window=new BrowserWindow({width:1440,height:900,minWidth:1200,minHeight:700,show:false,title:'KOETA',backgroundColor:'#202328',webPreferences:{preload:join(root,'desktop/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true,session:ses}});
  recovery=new RecoveryStore(app.getPath('userData'));revisions=new RevisionStore(app.getPath('userData'));kokoro=new KokoroService({store:new KokoroModelStore(app.getPath('userData')),createEngine:createProcessEngineFactory({fork:(path,args,options)=>utilityProcess.fork(path,args,options),workerPath:join(root,'desktop','kokoro-worker.mjs'),runtimeDir:app.isPackaged?join(process.resourcesPath,'kokoro'):join(root,'.private-runtime','kokoro')})});
  files=new DesktopFiles({dialog,window:()=>window,dataDir:app.getPath('userData'),onProject:path=>{window?.setRepresentedFilename(path??'');},onTheme:theme=>{nativeTheme.themeSource=theme;}});
  const preferences=await files.initialize();nativeTheme.themeSource=preferences.theme;if(preferences.ui?.window){const saved=preferences.ui.window,area=screen.getDisplayMatching(saved).workArea,b={...saved,width:Math.min(saved.width,Math.max(1200,area.width)),height:Math.min(saved.height,Math.max(700,area.height))};b.x=Math.max(area.x,Math.min(b.x,area.x+area.width-b.width));b.y=Math.max(area.y,Math.min(b.y,area.y+area.height-b.height));window.setBounds(b);}let boundsTimer;const saveBounds=()=>{clearTimeout(boundsTimer);boundsTimer=setTimeout(()=>void files.setUi({window:window.getBounds()}).catch(()=>{}),300);};window.on('resize',saveBounds);window.on('move',saveBounds);
  ses.setPermissionCheckHandler((contents,permission,requestingOrigin,details)=>contents===window?.webContents&&allowedMediaCheck(permission,details,requestingOrigin,origin));
  ses.setPermissionRequestHandler(async(contents,permission,callback,details)=>{if(contents!==window?.webContents||!allowedMedia(permission,details,details.requestingUrl??contents.getURL(),origin)){callback(false);return;}try{let granted=true;for(const type of details.mediaTypes){const device=type==='audio'?'microphone':'camera';const status=systemPreferences.getMediaAccessStatus(device);granted=granted&&(status==='granted'||status==='not-determined'&&await systemPreferences.askForMediaAccess(device));}callback(granted);}catch{callback(false);}});
  window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith(origin+'/'))event.preventDefault();});window.webContents.on('will-attach-webview',event=>event.preventDefault());
  window.webContents.session.on('will-download',(event)=>{event.preventDefault();dialog.showErrorBox('Tallenna tiedosto sovelluksen kautta','Käytä Tallenna projekti- tai Vie tiedosto -painiketta.');});
  window.on('close',event=>{if(!closing){event.preventDefault();void closeWindow();}});
  window.on('closed',()=>{window=null;void stopService();});
  service.on('exit',()=>{if(!closing&&window){dialog.showErrorBox('Paikallinen palvelu päättyi','Tallenna projekti ja käynnistä KOETA uudelleen. Puheentunnistus ei ole käytettävissä.');}});
  exports=new DesktopExports({window:()=>window,origin,session:ses,root,binary:join(app.isPackaged?process.resourcesPath:join(root,'.private-runtime'),'native/bin/ffmpeg'),trusted,dataDir:app.getPath('userData'),testing});registerIPC();makeMenu();await startupStatus('interface-loading');await window.loadURL(origin+'/');await startupStatus('ready');
  if(testing){if(layoutTesting)await layoutDiagnostic(window,process.env.HAHMOSTUDIO_LAYOUT_OUTPUT??join(app.getPath('userData'),'screenshots'));else if(screenplayTesting)await screenplayDiagnostic(window,{undo:()=>action('undo'),reportPath:join(app.getPath('userData'),'screenplay-gui.json')});else if(playbackRafTesting)await playbackRafDiagnostic(window,{reportPath:join(app.getPath('userData'),'playback-raf.json')});else if(exportE2eTesting)await exportE2eDiagnostic(window,{reportPath:join(app.getPath('userData'),'export-e2e.json'),destination:join(app.getPath('userData'),'export-out','vienti.mp4'),binary:join(app.isPackaged?process.resourcesPath:join(root,'.private-runtime'),'native/bin/ffmpeg')});else await selfTest();closing=true;window.destroy();await stopService();app.quit();}else{window.show();}
 }catch(e){await startupStatus('failed',e.message);if(testing){const fail={ok:false,error:e.message,gui:true,devices:false};if(screenplayTesting)await writeFile(join(app.getPath('userData'),'screenplay-gui.json'),JSON.stringify(fail,null,2));else if(playbackRafTesting)await writeFile(join(app.getPath('userData'),'playback-raf.json'),JSON.stringify(fail,null,2));else if(exportE2eTesting)await writeFile(join(app.getPath('userData'),'export-e2e.json'),JSON.stringify(fail,null,2));else await testReport({ok:false,error:e.message});}else dialog.showErrorBox('KOETA ei käynnistynyt',e.message+'\nSulje sovellus ja yritä uudelleen.');closing=true;window?.destroy();await stopService();app.exit(1);}
 }).catch(error=>{closing=true;dialog.showErrorBox('KOETA ei käynnistynyt',error.message);app.exit(1);});
}
function trusted(event){if(!validSender(event,window,origin))throw new Error('Pyyntö ei tullut KOETA-sovelluksen omasta ikkunasta.');}
function registerIPC(){
 const handle=(name,fn)=>ipcMain.handle(name,async(event,...args)=>{trusted(event);return fn(...args);});
 handle('studio:revisions-list',id=>revisions.list(id));handle('studio:revisions-save',data=>revisions.save(data));handle('studio:revisions-read',(project,id)=>revisions.read(project,id));handle('studio:revisions-remove',(project,id)=>revisions.remove(project,id));
 handle('studio:recovery-resources',refs=>recovery.delta.missing(refs));handle('studio:recovery-transaction',request=>recovery.transaction(request));handle('studio:recovery-import',request=>recovery.importBatch(request));handle('studio:recovery-read',reference=>recovery.read(reference));handle('studio:recovery-save',data=>recovery.save(data));handle('studio:recovery-latest',()=>recovery.latest());handle('studio:recovery-clear',()=>recovery.clear());
 handle('studio:confirm-replace',async()=>{const choice=await dialog.showMessageBox(window,{type:'question',message:'Nykyisessä työssä on tallentamattomia muutoksia.',buttons:['Tallenna ensin','Jatka tallentamatta','Peruuta'],defaultId:0,cancelId:2});return ['save','discard','cancel'][choice.response];});
 handle('studio:open',kind=>files.choose(kind));handle('studio:recent',id=>files.recent(id));handle('studio:adopt',id=>files.adopt(id));handle('studio:save',request=>files.save(request));handle('studio:preferences',()=>files.getPreferences());handle('studio:ui-settings',value=>files.setUi(value));handle('studio:context-menu',scope=>{if(!['stage','timeline'].includes(scope))throw Error('Kontekstivalikko on virheellinen.');Menu.buildFromTemplate(scope==='stage'?[{label:'Sovita näyttämö',click:()=>action('fit')},{label:'Keskitä hahmo',click:()=>action('center')},{label:'Turva-alueen kehys',click:()=>action('guides')}]:[{label:'Toista / tauko',click:()=>action('play')},{label:'Kumoa',click:()=>action('undo')},{label:'Tee uudelleen',click:()=>action('redo')}]).popup({window});});handle('studio:theme',theme=>files.setTheme(theme));handle('studio:accessibility',value=>files.setAccessibility(value));
 handle('studio:edit',action=>{if(!['undo','redo'].includes(action))throw new Error('Tuntematon muokkaustoiminto.');window.webContents[action]();});
 handle('studio:speech',async(bytes,language)=>{if(!(bytes instanceof Uint8Array)||bytes.length>1920044||!['fi','en'].includes(language))throw new Error('Virheellinen puheaineisto.');if(speech)throw new Error('Edellinen tunnistus on kesken.');const controller=new AbortController();speech=controller;try{const response=await fetch(serviceOrigin+'/api/speech/recognize?language='+language,{method:'POST',headers:{Origin:serviceOrigin,'Content-Type':'audio/wav',Cookie:'hahmostudio_desktop='+token},body:bytes,signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);return data.mouthCues;}finally{if(speech===controller)speech=null;}});
 handle('studio:audio-model',async()=>{const r=await fetch(serviceOrigin+'/api/audio/model',{headers:{Cookie:'hahmostudio_desktop='+token}});return r.json();});
 handle('studio:audio-download',async()=>{if(speech)throw Error('Edellinen puhetoiminto on kesken.');const c=new AbortController();speech=c;try{const r=await fetch(serviceOrigin+'/api/audio/model',{method:'POST',headers:{Origin:serviceOrigin,Cookie:'hahmostudio_desktop='+token},signal:c.signal});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}finally{if(speech===c)speech=null;}});
 handle('studio:transcribe',async(bytes,language)=>{if(!(bytes instanceof Uint8Array)||bytes.length>1920044||!['fi','en'].includes(language))throw Error('Virheellinen puheaineisto.');if(speech)throw Error('Edellinen tunnistus on kesken.');const c=new AbortController();speech=c;try{const r=await fetch(serviceOrigin+'/api/audio/transcribe?language='+language,{method:'POST',headers:{Origin:serviceOrigin,'Content-Type':'audio/wav',Cookie:'hahmostudio_desktop='+token},body:bytes,signal:c.signal});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}finally{if(speech===c)speech=null;}});
 handle('studio:cancel-speech',()=>speech?.abort());
 handle('studio:kokoro-status',()=>kokoro.status());
 handle('studio:kokoro-download',async()=>{if(kokoroDownload)throw Error('Mallin lataus on jo käynnissä.');const choice=await dialog.showMessageBox(window,{type:'question',buttons:['Lataa malli','Peruuta'],defaultId:1,cancelId:1,title:'Kokoro-puhemalli',message:'Ladataanko Kokoro-puhemalli tälle koneelle?',detail:'Lähde: huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX ('+KOKORO_LICENSE+'). Noin 100 Mt. Malli tallennetaan sovelluksen tietokansioon, ei projektiin eikä sovelluspakettiin. Tämä on ainoa verkkoyhteys; puhe tuotetaan paikallisesti.'});if(choice.response!==0)return {cancelled:true};const controller=new AbortController();kokoroDownload=controller;try{return await kokoro.store.download({signal:controller.signal,onProgress:p=>{if(window&&!window.isDestroyed())window.webContents.send('studio:kokoro-progress',p);}});}finally{kokoroDownload=null;}});
 handle('studio:kokoro-remove',async()=>{await kokoro.release();return kokoro.store.remove();});
 handle('studio:kokoro-synthesize',async request=>{const audio=await kokoro.synthesize(request);return {samples:audio.samples,sampleRate:audio.sampleRate,modelVersion:audio.modelVersion};});
 handle('studio:kokoro-cancel',()=>{kokoroDownload?.abort();kokoro.cancel();});
 ipcMain.on('studio:state',(event,state)=>{if(!validSender(event,window,origin))return;if(typeof state?.dirty!=='boolean'||typeof state?.ready!=='boolean')return;dirty=state.dirty;window?.setTitle((typeof state.name==='string'?state.name.slice(0,160):'KOETA')+(dirty?' ●':'')+' — KOETA');ready=state.ready;window.setDocumentEdited(dirty);});
 ipcMain.on('studio:close-result',(event,id,saved)=>{if(!validSender(event,window,origin))return;if(pendingClose&&pendingClose.id===id&&typeof saved==='boolean'){pendingClose.resolve(saved);pendingClose=null;}});
}
function action(name){if(window&&ready)window.webContents.send('studio:action',{action:name});}
function makeMenu(){Menu.setApplicationMenu(Menu.buildFromTemplate([
 {label:'KOETA',submenu:[{role:'about',label:'Tietoja KOETA-sovelluksesta'},{label:'Asetukset…',accelerator:'CmdOrCtrl+,',click:()=>action('settings')},{type:'separator'},{role:'hide',label:'Kätke KOETA'},{role:'hideOthers',label:'Kätke muut'},{role:'unhide',label:'Näytä kaikki'},{type:'separator'},{role:'quit',label:'Lopeta KOETA'}]},
 {label:'Tiedosto',submenu:[{label:'Avaa projekti…',accelerator:'CmdOrCtrl+O',click:()=>action('open')},{label:'Tuo kuva / PSD…',click:()=>action('import')},{label:'Lisää ääni…',click:()=>action('audio')},{type:'separator'},{label:'Tallenna projekti',accelerator:'CmdOrCtrl+S',click:()=>action('save')},{label:'Tallenna nimellä…',accelerator:'CmdOrCtrl+Shift+S',click:()=>action('saveAs')},{label:'Vie animaatio…',click:()=>action('export')},{type:'separator'},{label:'Lisätiedostot ja projektiversiot…',click:()=>action('advanced')},{label:'Sulje',accelerator:'CmdOrCtrl+W',click:()=>void closeWindow()}]},
 {label:'Muokkaa',submenu:[{label:'Kumoa',accelerator:'CmdOrCtrl+Z',click:()=>action('undo')},{label:'Tee uudelleen',accelerator:'CmdOrCtrl+Shift+Z',click:()=>action('redo')},{type:'separator'},{role:'cut',label:'Leikkaa'},{role:'copy',label:'Kopioi'},{role:'paste',label:'Liitä'},{role:'selectAll',label:'Valitse kaikki'}]},
 {label:'Näytä',submenu:[{label:'Kirjasto',click:()=>action('library')},{label:'Ominaisuudet',click:()=>action('inspector')},{label:'Aikajana',click:()=>action('timeline')},{type:'separator'},{label:'Sovita koko näyttämö',accelerator:'CmdOrCtrl+0',click:()=>action('fit')},{label:'Lähennä',accelerator:'CmdOrCtrl+=',click:()=>action('zoom-in')},{label:'Loitonna',accelerator:'CmdOrCtrl+-',click:()=>action('zoom-out')},{label:'Turva-alueen kehys',click:()=>action('guides')},{label:'Sivupaneelit',click:()=>action('panels')},{label:'Keskity näyttämöön',click:()=>action('focus-stage')},{label:'Palauta työtila ja paneelien koot',click:()=>action('reset-layout')},{type:'separator'},{label:'Tekoäly…',click:()=>action('ai')}]},
 {label:'Ohje',submenu:[{label:'Käyttöohje',click:()=>action('help')}]},
 {label:'Ikkuna',submenu:[{role:'minimize',label:'Pienennä'},{role:'zoom',label:'Zoomaa'}]},
 ...(app.isPackaged?[]:[{label:'Kehitys',submenu:[{role:'toggleDevTools',label:'Kehittäjätyökalut'}]}])
 ]));}
async function closeWindow(){
 if(closeBusy||closing||!window)return;closeBusy=true;
 try{if(exports?.queue.pending()){const choice=await dialog.showMessageBox(window,{type:'question',message:'Animaation vienti on kesken.',detail:'Vienti jatkuu, kun pienennät ikkunan. Kokonaan suljettu sovellus ei jatka vientiä.',buttons:['Jatka vientiä ja pidä sovellus auki','Peruuta viennit ja sulje'],defaultId:0,cancelId:0});if(choice.response===0)return;exports.queue.cancelAll();while(exports.queue.active)await new Promise(r=>setTimeout(r,50));}
 const allowed=await mayClose({dirty,choose:async()=>{const choice=await dialog.showMessageBox(window,{type:'question',message:'Tallennetaanko keskeneräinen työ?',detail:'Tallentamattomat muutokset häviävät, jos suljet tallentamatta.',buttons:['Tallenna','Sulje tallentamatta','Peruuta'],defaultId:0,cancelId:2});return ['save','discard','cancel'][choice.response];},save:()=>new Promise(resolve=>{const id=randomUUID();const timer=setTimeout(()=>{pendingClose=null;resolve(false);},120000);pendingClose={id,resolve:value=>{clearTimeout(timer);resolve(value);}};window.webContents.send('studio:action',{action:'save-for-close',id});})});if(!allowed)return;
  closing=true;ready=false;speech?.abort();kokoroDownload?.abort();kokoro?.cancel();void kokoro?.release();await stopService();window.destroy();app.quit();
 }catch(error){dialog.showErrorBox("Sulkeminen keskeytettiin",error.message);}finally{closeBusy=false;}
}
async function stopService(){speech?.abort();if(!service)return;const child=service;service=null;await new Promise(resolve=>{const timer=setTimeout(()=>{child.kill();resolve();},2500);child.once('exit',()=>{clearTimeout(timer);resolve();});child.postMessage({type:'stop'});});}
async function startupStatus(phase,error){await writeFile(join(app.getPath('userData'),'startup-status.json'),JSON.stringify({version:app.getVersion(),phase,time:new Date().toISOString(),...(error?{error}:{})},null,2),{mode:0o600}).catch(()=>{});}
async function testReport(report){await writeFile(join(app.getPath('userData'),'self-test.json'),JSON.stringify(report,null,2));}
async function selfTest(){
 // Native-runtime startup smoke test: no device access and no visual/browser UI test.
 const resources=['/library/Pipsa.hahmo','/library/Pipsa.psd','/vision/face_landmarker.task','/microphone-recorder.worklet.js'];for(const path of resources){const response=await fetch(serviceOrigin+path,{headers:{Cookie:'hahmostudio_desktop='+token}});if(response.status!==200)throw new Error('Packaged resource missing: '+path);}
 const denied=await fetch(serviceOrigin+'/library/Pipsa.hahmo',{redirect:'manual'});if(denied.status!==302)throw new Error('Unprotected desktop service');
 const wav=Buffer.alloc(44+32000);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
 for(const language of ['fi','en']){const response=await fetch(serviceOrigin+'/api/speech/recognize?language='+language,{method:'POST',headers:{Origin:serviceOrigin,'Content-Type':'audio/wav',Cookie:'hahmostudio_desktop='+token},body:wav});const data=await response.json();if(!response.ok||!Array.isArray(data.mouthCues))throw new Error('Packaged Rhubarb failed: '+language+' '+JSON.stringify(data));}
 const preferences=window.webContents.getLastWebPreferences();if(!preferences.contextIsolation||!preferences.sandbox||preferences.nodeIntegration)throw new Error('Renderer isolation failed');
 const content=await window.webContents.executeJavaScript('({title:document.title,bridge:typeof window.hahmostudio,require:typeof window.require})');if(content.bridge!=='object'||content.require!=='undefined')throw new Error('Preload bridge failed');
 const exported=[];const fixture=await (await fetch(serviceOrigin+'/library/Taru-3D.hahmo',{headers:{Cookie:'hahmostudio_desktop='+token}})).arrayBuffer();
 for(const format of ['mp4','gif','png']){const destination=join(app.getPath('userData'),'test-export.'+(format==='png'?'frames':format));const id=exports.queue.enqueue({name:'Native export test',destination,preset:{id:'test',name:'Test',format,width:160,height:284,fps:24,start:0,end:2/24,quality:1,transparent:format==='png',audio:false,loop:0},bytes:new Uint8Array(fixture)});const timeout=Date.now()+120000;while(exports.queue.jobs.find(j=>j.id===id).state!=='done'){const j=exports.queue.jobs.find(j=>j.id===id);if(['error','canceled'].includes(j.state))throw Error(format+': '+j.error);if(Date.now()>timeout)throw Error('Native export test timed out');await new Promise(r=>setTimeout(r,50));}exported.push({format,encoder:exports.queue.jobs.find(j=>j.id===id).encoder});}
 await testReport({ok:true,packaged:app.isPackaged,arch:process.arch,electron:process.versions.electron,node:process.versions.node,resources,preload:content,isolated:true,deviceTests:false,exported,layerPixels:true,rhubarbSilentWav:['fi','en']});
}
