import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {RecoveryStore} from './recovery.mjs';
test('immutable recovery snapshots survive restart and serialized saves retain newest and previous',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-recovery-'));try{const store=new RecoveryStore(dir);await Promise.all([store.save({name:'first',bytes:new Uint8Array([1])}),store.save({name:'second',bytes:new Uint8Array([2])}),store.save({name:'third',bytes:new Uint8Array([3])})]);const restored=await new RecoveryStore(dir).latest();assert.equal(restored.name,'third');assert.deepEqual([...restored.bytes],[3]);const journal=JSON.parse(await readFile(join(dir,'recovery/journal.json'),'utf8'));assert.equal(journal.entries.length,2);assert.equal(journal.entries[1].name,'second');}finally{await rm(dir,{recursive:true,force:true});}});
test('corrupt newest recovery falls back to checksum-verified previous snapshot',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-recovery-'));try{const store=new RecoveryStore(dir);await store.save({name:'old',bytes:new Uint8Array([1])});const entry=await store.save({name:'new',bytes:new Uint8Array([2])});await writeFile(join(dir,'recovery',entry.file),new Uint8Array([9]));const restored=await new RecoveryStore(dir).latest();assert.equal(restored.name,'old');assert.equal(restored.previous,true);await store.clear();assert.equal(await store.latest(),null);}finally{await rm(dir,{recursive:true,force:true});}});
test('recovery rejects path traversal, invalid archives and corrupt journal without touching unrelated files',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-recovery-'));try{const store=new RecoveryStore(dir);await assert.rejects(store.save({name:'x',bytes:new Uint8Array()}));await store.save({name:'x',bytes:new Uint8Array([1])});await writeFile(join(dir,'unrelated.txt'),'keep');await writeFile(join(dir,'recovery/journal.json'),JSON.stringify({schemaVersion:1,entries:[{file:'../../unrelated.txt'}]}));const recovered=await store.latest();assert.equal(recovered.name,'x');assert.equal(recovered.replayed,true);assert.equal(await readFile(join(dir,'unrelated.txt'),'utf8'),'keep');}finally{await rm(dir,{recursive:true,force:true});}});

test('durable recovery commits reconstruct lost index and ignore uncommitted or corrupted snapshots',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-replay-'));try{const store=new RecoveryStore(dir);await store.save({name:'base',bytes:new Uint8Array([1])});await store.save({name:'next',bytes:new Uint8Array([2])});await rm(join(dir,'recovery/journal.json'));const replay=await new RecoveryStore(dir).latest();assert.equal(replay.name,'next');assert.equal(replay.replayed,true);await writeFile(join(dir,'recovery/snapshot-00000000-0000-0000-0000-000000000000.hahmo'),new Uint8Array([9]));assert.equal((await store.latest()).name,'next');const records=await store.replayRecords();await writeFile(join(dir,'recovery',records[0].entry.file),new Uint8Array([0]));const fallback=await store.latest();assert.equal(fallback.name,'base');assert.equal(fallback.previous,true);}finally{await rm(dir,{recursive:true,force:true});}});

test('recovery replay log is bounded and corrupt newest commit cannot be promoted',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-replay-limit-'));try{const store=new RecoveryStore(dir);for(let i=0;i<23;i++)await store.save({name:'state-'+i,bytes:new Uint8Array([i])});const records=await store.replayRecords();assert.equal(records.length,20);await writeFile(join(dir,'recovery',records[0].file),'broken');await rm(join(dir,'recovery/journal.json'));const restored=await new RecoveryStore(dir).latest();assert.equal(restored.name,'state-21');assert.equal(restored.replayed,true);}finally{await rm(dir,{recursive:true,force:true});}});

test('each command gets its own acknowledged journal record even when project bytes are identical',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-command-journal-'));try{const store=new RecoveryStore(dir),bytes=new Uint8Array([1,2]),first={id:'11111111-1111-4111-8111-111111111111',kind:'editor-edit'},second={id:'22222222-2222-4222-8222-222222222222',kind:'editor-undo'};const a=await store.save({name:'same',bytes,command:first}),b=await store.save({name:'same',bytes,command:second});assert.notEqual(a.file,b.file);assert.deepEqual(a.command,first);assert.deepEqual(b.command,second);const records=await store.replayRecords();assert.equal(records.length,2);assert.deepEqual(records[0].entry.command,second);await assert.rejects(store.save({name:'same',bytes,command:{id:'bad',kind:'edit'}}));assert.equal((await store.replayRecords()).length,2);}finally{await rm(dir,{recursive:true,force:true});}});

test('project undo and redo references survive restart and retain their snapshots through journal pruning',async()=>{const dir=await mkdtemp(join(tmpdir(),'studio-project-history-'));try{let store=new RecoveryStore(dir);const a=await store.save({name:'A',bytes:new Uint8Array([1])});const reference=e=>({file:e.file,hash:e.hash,size:e.size});const command=(i,kind,history)=>({id:String(i).padStart(8,'0')+'-0000-4000-8000-000000000000',kind,history});const b=await store.save({name:'B',bytes:new Uint8Array([2]),command:command(1,'editor-edit',{past:[reference(a)],future:[]})});const c=await store.save({name:'C',bytes:new Uint8Array([3]),command:command(2,'production-edit',{past:[reference(a),reference(b)],future:[]})});const u=await store.save({name:'B undo',bytes:new Uint8Array([2]),command:command(3,'project-undo',{past:[reference(a)],future:[reference(c)]})});store=new RecoveryStore(dir);const latest=await store.latest();assert.equal(latest.name,'B undo');assert.deepEqual(latest.history.future,[reference(c)]);assert.deepEqual([...(await store.read(latest.history.future[0])).bytes],[3]);for(let i=4;i<30;i++)await store.save({name:'current',bytes:new Uint8Array([i]),command:command(i,'script-source',{past:[reference(a),reference(b),reference(u)],future:[reference(c)]})});assert.deepEqual([...(await store.read(reference(a))).bytes],[1]);assert.equal((await store.replayRecords()).length,20);await assert.rejects(store.read({...reference(a),hash:'b'.repeat(64)}));await assert.rejects(store.save({name:'invalid',bytes:new Uint8Array([8]),command:command(31,'editor-edit',{past:[{...reference(a),file:'snapshot-ffffffff-0000-4000-8000-000000000000.hahmo'}],future:[]})}));assert.equal((await store.latest()).name,'current');}finally{await rm(dir,{recursive:true,force:true});}});
