import {readZip} from './stored-zip.mjs';
import {RevisionStore} from './revisions.mjs';
import {ExportQueueStore} from './export-queue-store.mjs';
import {DurableExportQueue} from './durable-export-queue.mjs';
import {RecoveryStore} from './recovery.mjs';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';
// Runs with the packaged Electron's Node runtime, without GUI or real devices.
import assert from 'node:assert/strict';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';import {createPrivateServer} from '../server/private-server.mjs';import {createSpeechRecognizer} from '../server/speech-recognizer.mjs';import {randomBytes} from 'node:crypto';
const root=dirname(dirname(fileURLToPath(import.meta.url))),resources=dirname(root),token=randomBytes(32).toString('hex');
const server=await createPrivateServer({distDir:join(root,'dist-desktop'),desktopToken:token,speechRecognizer:createSpeechRecognizer(join(resources,'rhubarb/rhubarb'))});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const origin='http://127.0.0.1:'+server.address().port;
try{
 const paths=['/library/Pipsa.hahmo','/library/Ville.hahmo','/library/Pipsa.psd','/library/Ville.psd','/library/Taru-3D.hahmo','/library/Ukko-3D.psd','/library/cutout-studio-v1.svg','/library/cutout-street-v1.png','/library/cutout-car-v1.svg','/schemas/cutout-animation-package.schema.json','/','/library/KILSAT-S01E01.md','/library/Aamu-autossa.md','/library/Studio.png','/library/Taru.hahmo','/library/Pipsa-3D.hahmo','/library/Ville-3D.psd','/library/Ukko.hahmo','/library/Hahmopohja.hahmo','/library/Suupaketti-Pehmea.psd','/library/car-passenger-v1.svg','/vision/face_landmarker.task','/vision/vision_wasm_internal.wasm','/microphone-recorder.worklet.js','/library/office-scene-v1.svg','/library/book-prop-v1.svg'];
 for(const path of paths){const response=await fetch(origin+path,{headers:{Cookie:'hahmostudio_desktop='+token}});assert.equal(response.status,200,path);assert.ok((await response.arrayBuffer()).byteLength>0,path);}
 assert.equal((await fetch(origin+'/',{redirect:'manual'})).status,302);
 const wav=Buffer.alloc(32044);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
 for(const language of ['fi','en']){const response=await fetch(origin+'/api/speech/recognize?language='+language,{method:'POST',headers:{Origin:origin,'Content-Type':'audio/wav',Cookie:'hahmostudio_desktop='+token},body:wav});const data=await response.json();assert.equal(response.status,200,JSON.stringify(data));assert.ok(Array.isArray(data.mouthCues));}
 const recoveryDir=await mkdtemp(join(tmpdir(),'kilsat-packaged-recovery-'));try{const bytes=new Uint8Array(await(await fetch(origin+'/library/Pipsa.hahmo',{headers:{Cookie:'hahmostudio_desktop='+token}})).arrayBuffer());const recovery=new RecoveryStore(recoveryDir),base=await recovery.save({name:'Runtime smoke',bytes});const reference={file:base.file,hash:base.hash,size:base.size};const large=randomBytes(256*1024);await recovery.save({name:'Chunk history smoke',bytes:large,command:{id:'00000000-0000-4000-8000-000000000009',kind:'editor-edit',history:{past:[reference],future:[]}}});const restored=await new RecoveryStore(recoveryDir).latest();assert.deepEqual(restored.bytes,new Uint8Array(large));assert.deepEqual(restored.history.past,[reference]);assert.deepEqual((await new RecoveryStore(recoveryDir).read(reference)).bytes,bytes);
 const sourceFiles=readZip(bytes),metadata=JSON.parse(sourceFiles['project.json'].toString()),set=[],uploads=[];const {createHash}=await import('node:crypto');for(const [path,data] of Object.entries(sourceFiles)){if(['project.json','resource-manifest.json','command-delta.json'].includes(path))continue;const hash=createHash('sha256').update(data).digest('hex');set.push({path,hash,size:data.length});uploads.push({hash,bytes:new Uint8Array(data)});}const deltaBase=await recovery.transaction({version:1,name:'Delta smoke',delta:{version:1,changes:[{path:[],before:null,after:metadata}]},resources:{set,remove:[]},uploads,command:{id:'00000000-0000-4000-8000-000000000010',kind:'delta-baseline',history:{past:[],future:[]}}});const deltaNext=await recovery.transaction({version:1,name:'Delta smoke',base:{file:deltaBase.file,hash:deltaBase.hash,size:deltaBase.size},delta:{version:1,changes:[{path:['document','name'],before:metadata.document.name,after:'Delta changed'}]},resources:{set:[],remove:[]},uploads:[],command:{id:'00000000-0000-4000-8000-000000000011',kind:'delta-edit',history:{past:[{file:deltaBase.file,hash:deltaBase.hash,size:deltaBase.size}],future:[]}}});const deltaRestored=await new RecoveryStore(recoveryDir).latest();assert.equal(deltaRestored.stateHash,deltaNext.hash);assert.equal(JSON.parse(readZip(deltaRestored.bytes)['project.json'].toString()).document.name,'Delta changed');const imported=await recovery.importBatch({name:'Atomic import',past:[bytes],future:[],current:bytes});assert.equal((await new RecoveryStore(recoveryDir).latest()).reference.file,imported.reference.file);
 const revisions=new RevisionStore(recoveryDir),entry=await revisions.save({projectId:'runtime-smoke',name:'Runtime smoke',label:'Verified',bytes});assert.deepEqual((await new RevisionStore(recoveryDir).read('runtime-smoke',entry.id)).bytes,bytes);
 const queueStore=new ExportQueueStore(recoveryDir,()=>{}),hash=await queueStore.put(bytes),id='00000000-0000-4000-8000-000000000001';await queueStore.write([{id,name:'Runtime smoke',destination:join(recoveryDir,'output'),preset:{format:'png'},state:'rendering',progress:.5,snapshotHash:hash,snapshotSize:bytes.length}]);let ran=false;const queue=new DurableExportQueue({store:new ExportQueueStore(recoveryDir,()=>{}),notify:()=>{},run:async()=>{ran=true;}});await queue.ready;assert.equal(queue.list()[0].state,'interrupted');assert.equal(ran,false);queue.forget(id);await queue.flush();}finally{await rm(recoveryDir,{recursive:true,force:true});}
 console.log(JSON.stringify({packagedDeltaJournal:true,packagedAtomicImport:true,packagedRecovery:true,packagedProjectHistory:true,packagedChunks:true,packagedRevisions:true,packagedQueueRecovery:true,ok:true,electron:process.versions.electron,node:process.versions.node,arch:process.arch,resources:paths,rhubarbSilentWav:['fi','en'],gui:false,deviceTests:false},null,2));
}finally{await new Promise(resolve=>server.close(resolve));}
