// Runs with the packaged Electron's Node runtime, without GUI or real devices.
import assert from 'node:assert/strict';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';import {createPrivateServer} from '../server/private-server.mjs';import {createSpeechRecognizer} from '../server/speech-recognizer.mjs';import {randomBytes} from 'node:crypto';
const root=dirname(dirname(fileURLToPath(import.meta.url))),resources=dirname(root),token=randomBytes(32).toString('hex');
const server=await createPrivateServer({distDir:join(root,'dist-desktop'),desktopToken:token,speechRecognizer:createSpeechRecognizer(join(resources,'rhubarb/rhubarb'))});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const origin='http://127.0.0.1:'+server.address().port;
try{
 const paths=['/','/library/KILSAT-S01E01.md','/library/Aamu-autossa.md','/library/Otto.hahmo','/library/Otto.psd','/library/Studio.png','/library/Aino.hahmo','/library/Roni-Monikulma.hahmo','/library/Salla-Monikulma.psd','/library/Aino-Monikulma.hahmo','/library/Otto-Monikulma.psd','/library/Leo.psd','/library/Hahmopohja.hahmo','/library/Suupaketti-Pehmea.psd','/library/car-passenger-v1.svg','/vision/face_landmarker.task','/vision/vision_wasm_internal.wasm','/microphone-recorder.worklet.js','/library/roni-toon.json','/library/salla-toon.json','/library/office-scene-v1.svg','/library/book-prop-v1.svg'];
 for(const path of paths){const response=await fetch(origin+path,{headers:{Cookie:'hahmostudio_desktop='+token}});assert.equal(response.status,200,path);assert.ok((await response.arrayBuffer()).byteLength>0,path);}
 assert.equal((await fetch(origin+'/',{redirect:'manual'})).status,302);
 const wav=Buffer.alloc(32044);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
 for(const language of ['fi','en']){const response=await fetch(origin+'/api/speech/recognize?language='+language,{method:'POST',headers:{Origin:origin,'Content-Type':'audio/wav',Cookie:'hahmostudio_desktop='+token},body:wav});const data=await response.json();assert.equal(response.status,200,JSON.stringify(data));assert.ok(Array.isArray(data.mouthCues));}
 console.log(JSON.stringify({ok:true,electron:process.versions.electron,node:process.versions.node,arch:process.arch,resources:paths,rhubarbSilentWav:['fi','en'],gui:false,deviceTests:false},null,2));
}finally{await new Promise(resolve=>server.close(resolve));}
